// $Id$

#ifndef DDS_RFT2_DCPS_IDL_I
#define DDS_RFT2_DCPS_IDL_I

#pragma ciao lem "connectors/dds4ccm/idl/dds_rtf2_dcps_i_handleE.idl"

#if (CIAO_DDS4CCM_NDDS==1)

module DDS {
    struct NativeInstanceHandle_t {
        octet value[16];
        unsigned long length;
        unsigned long isValid;
    };
    typedef NativeInstanceHandle_t InstanceHandle_t;
    typedef sequence<InstanceHandle_t> InstanceHandleSeq;
};

#endif

#endif
