
/**
 * @file Kokyu_qos.idl
 *
 * $Id$
 *
 */

#ifndef _KOKYU_DSRT_QOS_PIDL_
#define _KOKYU_DSRT_QOS_PIDL_

#include "tao/TimeBase.pidl"
#include "tao/RTCORBA/RTCORBA_include.pidl"

#pragma prefix "omg.org"

module Kokyu
{
  typedef sequence<octet> GuidType;

  struct Svc_Ctxt_DSRT_QoS
  {
    GuidType guid;
    long importance;
    long criticality;
    RTCORBA::Priority desired_priority;
    TimeBase::TimeT deadline;
    TimeBase::TimeT estimated_initial_execution_time;
  };
};

#endif /* KOKYU_DSRT_QOS_PIDL */
