// $Id$

//
// Simplified logger and Logger factory interfaces for 
// testing of the Name Service implementation.


interface Logger;

interface Logger_Factory
{
  Logger make_logger (in string name);
};




interface Logger
{
  // Transmit a Log_Record to the logging server.
  oneway void log (in string message);
};

