// $Id: Bug_2577_Regression.idl 73398 2006-07-03 15:11:32Z parsons $

// Test Bug 2616

struct AA
{
  long x;
};
struct BB
{
  AA data;
};
interface Interface1
{
  typedef BB Type;
  void do_it(in Type value);
};
interface Interface2
{
  typedef AA Type;
  void do_it(in Type value);
};

