// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    old_array.idl
//
// = DESCRIPTION
//    Tests of array IDL constructs
//
// = AUTHORS
//    Andy Gokhale <gokhale@dre.vanderbilt.edu>
//
// ============================================================================

#include "simple.idl"

module OldArray
{
  typedef char str22[22][2];
  typedef boolean boolarray[3][40];


  struct A
  {
    long a1;
    char a2[17];
    char a3[10][2];
  };

  struct B
  {
    long b1;
    A b2;
  };

  struct C
  {
    long c1;
    long c2;
  };

  typedef A A_matrix[2][3][4];
  typedef B B_matrix[2][3][4];
  typedef C C_matrix[2][3][4];

  typedef A_matrix A_rmatrix[2][3][4][5];

  interface A_i
  {
    A op (in A a1,
          inout A a2,
          out A a3);

    str22 op2 (in str22 a1,
               inout str22 a2,
               out str22 a3);

    A_matrix op4 (in A a1,
                  inout A a2,
                  out A a3);

    attribute str22 attribute_array;
  };
};

