// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    typedef.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has 
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================


// Must keep unaliasing until all levels of typedef
// are removed.

typedef char A5[5];

typedef A5 C5;

typedef C5 G5;

typedef G5 J5;

typedef J5 M5[5];

typedef M5 R5;

typedef R5 V5;

// Not yet - creates an array of more than 2 dimensions
// typedef V5 Z5[5];


