// $Id$

interface Test
{
  // = TITLE
  //    Interface for testing this example.
  //
  // = DESCRIPTION
  //    This interface defines a simple object
  //    which has a method which can be 'smartified'
  //    to provide extra functionality.

  exception Oops
    {
      string reason;
    };

  short method (in short boo) raises (Oops);

  oneway void shutdown ();
};
