// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef DDS_SL_ONEBYONE_SENDER_IDL
#define DDS_SL_ONEBYONE_SENDER_IDL

#include "Connector/SL_OneByOne_Connector.idl"

module SL_OneByOne
{
  component Sender
  {
     port SL_OneByOneConnector::DDS_Update test_topic_update;
  };
};

#endif
