// -*- IDL -*-

//=============================================================================
/**
 *  @file    ReplicatedApplication.idl
 *
 *  $Id$
 *
 *  @author  Friedhelm Wolf (fwolf@dre.vanderbilt.edu)
 */
//=============================================================================

#ifndef _REPLICATED_APPLICATION_IDL_
#define _REPLICATED_APPLICATION_IDL_

interface ReplicatedApplication 
{
  /// setter method for the interal state
  /// @param state_value represents the internal state encapsulated
  ///        into an any value
  void set_state (in any state_value);

  /// getter method the the internal state
  /// remark: it's not clear if this is necessary
  any get_state ();
};

#endif /* _REPLICATED_APPLICATION_IDL_ */
