// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/orbsvcs/tests/Interoperable_Naming/
//
// = FILENAME
//    Web_Server.idl
//
// = DESCRIPTION
//     IDL schema definition for Web server interface.
//
// = AUTHORS
//     Priyanka Gontla <pgontla@ece.uci.edu>
//
//
// ============================================================================

module Web_Server
{
  interface Iterator_Factory
  {
  };

};
