// $Id$

// Just implements a nice little Nestea server
interface Nestea_Bookshelf
{
  void drink (in long cans);
  // Add a number of cans to the bookshelf.

  void crush (in long cans);
  // Crush some of those cans.

  long bookshelf_size ();
  // How many cans are in the collection?

  string get_praise ();
  // What does the server think of your collection?

  oneway void shutdown();
};
