// $Id$

module CallMe
  {
    enum Colors { Red, Green, Blue };

    union YourColorBaby switch (enum ColorMe { Red, Blue })
      {
        case Red: enum Val { one, two } c_1;
        case Blue: long c_2;
      };

    union YourCar switch (enum ColorMe { Green, Pink })
      {
        case Green: short c_1;
        case Pink: short c_2;
      };
  };
