// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    keywords.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

// All these identifiers should be accepted, but
// prepended with _cxx_.

// 'private' and 'public' have been commented out because they are now, in
// addition to being C++ keywords, IDL keywords, and thus are illegal
// except when used as such.

struct Keywords
{
  unsigned short or;
  char or_eq;
//  octet private;
  boolean protected;
//  float public;
  double int;
};

interface Testing
{
  void foo (in string namespace);
};

