// -*- IDL -*-

// $Id$

module ImplementationRepository
{
  struct StartupInfo {
    string name;
    string partial_ior;
    string ior;
  };

  interface AsyncStartupWaiter
  {
    StartupInfo wait_for_startup(in string name);
  };
};

