// -*- IDL -*-

// $Id$

#include "tao/PortableServer/ImplRepo.idl"

module ImplementationRepository
{
  interface Activator
  {
    // Tells the activator to launch the specified server using the given
    // startup information. If the activator is already in the process of
    // launching the server, then the StartupOptions are ignored and the
    // call just waits for the server to start. Before, this call returns
    // to the locator, the activator can verify that the server is indeed
    // started by calling ServerObject::ping(). (Option)
    // If the server is already running, then this will just verify that it
    // is started by pinging it. (if enabled) Also, the ping() will only be
    // called if it's been at least X ms since the last ping.
    void start_server(in string name, in string cmdline, in string dir, in EnvironmentList env) raises(CannotActivate);

    // The Locator will call the activator if it receives notification that
    // the server is running. This will allow the activator to return from
    // start_server, for any calls that may have been blocked waiting for this.
    // This will also be called if the server is shutdown, or if the locator
    // receives notice that the server is stopping.
    void server_status_changed(in string name);
  };
};

