/* -*- C++ -*- */
// $Id$

// IDL
enum TCKind
  {
    // = Kinds of typecodes.

    // Do not change these enum values, or duplicate them if you need
    // to add values.  They are used to index tables, and if you
    // change the values you'll need to find and update all of those
    // tables.  The values are also part of the Common Data
    // Representation, and hence are part of IIOP and other ORB
    // protocols.

    tk_null,
    tk_void,
    tk_short,
    tk_long,
    tk_ushort,
    tk_ulong,
    tk_float,
    tk_double,
    tk_boolean,
    tk_char,
    tk_octet,
    tk_any,
    tk_TypeCode,
    tk_Principal,
    tk_objref,
    tk_struct,
    tk_union,
    tk_enum,
    tk_string,
    tk_sequence,
    tk_array,
    tk_alias,               // 94-11-7
    tk_except,              // 94-11-7

    // = These five are OMG-IDL data type extensions.
    tk_longlong,            // 94-9-32 Appendix A (+ 2)
    tk_ulonglong,           // 94-9-32 Appendix A (+ 2)
    tk_longdouble,          // 94-9-32 Appendix A (+ 2)
    tk_wchar,               // 94-9-32 Appendix A (+ 2)
    tk_wstring,             // 94-9-32 Appendix A (+ 2)

    // This symbol is not defined by CORBA 2.0.  It's used to speed up
    // dispatch based on TCKind values, and lets many important ones
    // just be table lookups.  It must always be the last enum value!!

    TC_KIND_COUNT
  };

