// $Id$

/**
 * @file CFTLS_Test_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef CONTENTFILTEREDTOPIC_LISTEN_STATE_TEST_BASE_IDL
#define CONTENTFILTEREDTOPIC_LISTEN_STATE_TEST_BASE_IDL

#pragma ndds typesupport "Base/CFTLS_Test_BaseSupport.h"
#pragma opendds typesupport "Base/CFTLS_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "ContentFilteredTopicListenStateTest"
#pragma DCPS_DATA_KEY "ContentFilteredTopicListenStateTest key"

struct ContentFilteredTopicListenStateTest {
  string key; //@key
  long iteration;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<ContentFilteredTopicListenStateTest> ContentFilteredTopicListenStateTestSeq;
#endif

#endif
