//$Id$
#ifndef RACE_OUTPUT_ADAPTER_IDL
#define RACE_OUTPUT_ADAPTER_IDL

#include <Components.idl>
#include "../Interface/PlanEgress.idl"

module CIAO
{
  module RACE
  {
    component Output_Adapter
    {
      provides PlanEgress plan_egress;
    };
  };
};

#endif /* RACE_OUTPUT_ADAPTER_IDL */
