// file      : RolyPoly/RolyPoly.idl
// author    : Boris Kolpackov <boris@dre.vanderbilt.edu>
interface RolyPoly
{
  exception E
  {
    string s;
  };

  short number (inout string m) raises (E);

  oneway void shutdown ();
};
