// $Id$

/**
 * @file Writer_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef WRITER_BASE_IDL
#define WRITER_BASE_IDL

struct WriterTest {
  string key; //@key
};

typedef sequence<WriterTest> WriterTest_Seq;

#endif
