// $Id$

/**
 * @file   CSL_QoSTest_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef CSL_QOSTEST_BASE_IDL
#define CSL_QOSTEST_BASE_IDL

#pragma ndds typesupport "Base/CSL_QoSTest_BaseSupport.h"
#pragma opendds typesupport "Base/CSL_QoSTest_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "TestTopic"
#pragma DCPS_DATA_KEY "TestTopic key"

struct TestTopic {
  string key; //@key
  long x;
};

typedef sequence<TestTopic> TestTopicSeq;

#endif
