//$Id$

#ifndef CIAO_SENDER_IDL
#define CIAO_SENDER_IDL


#include "../Minimum_Base/Minimum_Base.idl"

module Minimum
{
  /* This is a Sender specific interface which will be used to get the
   * process start.
   */

  interface trigger
  {
    void bar ();
  };

  component Sender supports trigger
  {
  };

  home SenderHome manages Sender
  {
  };
};
#endif /*CIAO_SENDER_IDL*/
