// $Id$

#include "Hello_Sender_Base.idl"
#include <Components.idl>

module Hello_DDS
{
  component Sender
  {
    uses CCM_DDS::string_Writer push_data_data;
    uses DDS::DataWriter push_data_dds_entity;

    attribute unsigned long iterations;
    attribute string message;
  };

  home SenderHome manages Sender
  {
  };
};
