// $Id$
/**
 * @file raw_include.idl
 * @author Jeff Parsons <j.parsons@vanderbilt.edu>
 *
 * Tests tool's 'excluded file' feature, which allows the user
 * to specifcy the generation of an #include for this file, in
 * an IDL2 file corresponding to the IDL3 file this one is
 * included in unchanged, without the '_IDL2' suffix.
 */

#ifndef RAW_INCLUDE_IDL
#define RAW_INCLUDE_IDL

module carnsarn
{
  typedef boolean t_or_f;

  struct one
  {
    short shortshort;
    string along;
    wstring<3> trinity;
  };
};

#endif /* RAW_INCLUDE_IDL */
