// $Id$

/**
 * @file   PSL_SampleLost_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef PSL_SAMPLELOST_BASE_IDL
#define PSL_SAMPLELOST_BASE_IDL

#pragma ndds typesupport "Base/PSL_SampleLost_BaseSupport.h"
#pragma opendds typesupport "Base/PSL_SampleLost_BaseSupportImpl.h"

#pragma DCPS_DATA_TYPE "TestTopic"
#pragma DCPS_DATA_KEY "TestTopic key"

struct TestTopic {
  string key; //@key
  long x;
};

typedef sequence<TestTopic> TestTopicSeq;

#endif
