// $Id$
/**
 * @file Abstract.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests the compilation of abstract events.
 */

#include <Components.idl>

module AbstractEvents
{
  abstract eventtype foo_event
    {
    };

  abstract eventtype InhFoo_event : foo_event
    {
    };

  abstract eventtype bar_event
    {
    };

  abstract eventtype foobar_event : foo_event, bar_event
    {
    };

  // test event multiple inheritance

  eventtype concrete_foo
  {
  };

  eventtype concrete_foobar : concrete_foo, foo_event
  {
  };
};
