// $Id$

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "Hello_Base/Hello_Base.idl"
#include "Hello_Base/Hello_BaseE.idl"
#include "Hello_Base/HelloE.idl"

module Hello_AMI
{
  component Receiver
  {
    //provides 
    provides CCM_AMI::MyFoo do_my_foo;
    provides CCM_AMI::MyInterface do_my_interface;
  };

  home ReceiverHome manages Receiver
  {
  };
};
#endif
