// $Id$

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "Hello_Base/Hello_Base.idl"
#include "Hello_Base/Hello_BaseE.idl"
#include "Hello_Base/HelloE.idl"

module Hello
{
  component Receiver
  {
    // provides
    provides Hello::MyFoo do_my_foo;
  };
};
#endif
