
//=============================================================================
/**
 *  $Id$
 */
//=============================================================================

#include "Parent.idl"

#pragma prefix "child.pragma.prefix"

interface ChildInterface : ParentInterface {};

module ChildModule
  {
    interface ChildInterface : ParentModule::ParentInterface {};
  };
