// $Id$

/**
 * @file MultipleTemp_Connector.idl
 * @author Marijke Hengstmengel
 */

#ifndef MULTIPLE_TEMP_CONNECTOR_IDL_
#define MULTIPLE_TEMP_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/MultipleTemp_Base.idl"

#pragma ciao lem "Connector/MultipleTemp_ConnectorE.idl"

module CCM_DDS
{
  module Duplex_Typed <typename T, sequence<T> TSeq, typename Y, sequence <Y> YSeq> {
    alias Typed <T, TSeq> T_Typed;
    alias Typed <Y, YSeq> Y_Typed;
    local interface Foo {
      void op ();
    };
    connector FooConnector : CCM_DDS::DDS_Base
    {
      mirrorport T_Typed::DDS_Listen t_listen;
      mirrorport Y_Typed::DDS_Listen y_listen;
    };
  };
};

module MultipleTemp
{
  module ::CCM_DDS::Duplex_Typed < ::TestTopicOne, ::TestTopicOneSeq, ::TestTopicTwo, ::TestTopicTwoSeq> MultipleTempConnector;
};

#endif /* MULTIPLE_TEMP_CONNECTOR_IDL_ */
