// $Id$

#if !defined (CCM_COMPONENT_IDL)
#define CCM_COMPONENT_IDL

#include "ccm/CCM_Events.idl"
#include "ccm/CCM_Home.idl"
#include "ccm/CCM_Object.idl"
#include "ccm/CCM_Enumeration.idl"

#endif /* CCM_COMPONENT_IDL */
