// $Id$

/**
 * @file
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/CSL_SRTest_Connector.idl"

module CSL_SRTest
{
  component Receiver
  {
    port CSL_SR_Connector::DDS_Listen info_out;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
    attribute unsigned long rate;
    attribute boolean read_data;//if true, read_all is invoked.
    attribute boolean raw_listen; //if true, raw listen port is enabled.
   };
};

#endif
