
#
# Makefile for building the ORB_destroy test
# 

NAME = ORB_destroy
  
OBJFILES = \
	$(OBJDIR)\ORB_destroy.obj 

CFLAGS = \
	$(ACE_CFLAGS) \
	$(TAO_CFLAGS) \
	$(TAO_PORTABLESERVER_CFLAGS)

LIBFILES = \
	$(ACE_LIB) \
	$(TAO_LIB) \
	$(TAO_PORTABLESERVER_LIB)
  
CPPDIR = .

!include <$(ACE_ROOT)\include\makeinclude\build_exe.bor>
