// -*- IDL -*-
//
// $Id$


#ifndef _SECURITY_LEVEL_1_IDL_
#define _SECURITY_LEVEL_1_IDL_

#include <Security.idl>

#pragma prefix "omg.org"

module SecurityLevel1 {

# pragma version SecurityLevel1 1.8

  local interface Current : CORBA::Current {	// Locality Constrained
#   pragma version Current 1.8

    // thread specific operations

    Security::AttributeList get_attributes (
       in    Security::AttributeTypeList  attributes
    );

  };
};

#pragma prefix ""

#endif /* _SECURITY_LEVEL_1_IDL_ */
