// $Id$

#if !defined (CCM_CONTAINERSTUBREQUESTINFO_IDL)
#define CCM_CONTAINERSTUBREQUESTINFO_IDL

#include "ciao/CCM_ContainerRequestInfo.idl"
#include "tao/AnyTypeCode/Dynamic.pidl"

module Components
{
  module ContainerPortableInterceptor
  {
    local interface ContainerStubRequestInfo : ContainerRequestInfo
    {
      attribute Dynamic::ParameterList arguments;
      readonly attribute string operation;
      attribute any result;
      attribute Object target;
      attribute any the_exception;
    };
  };
};

#endif /* CCM_CONTAINERSTUBREQUESTINFO_IDL */
