
//=============================================================================
/**
 *  @file    repo_id_mod.idl
 *
 *  $Id$
 *
 *  This file contains examples of IDL code that has
 *  caused problems in the past for the TAO IDL
 *  compiler. This test is to make sure the problems
 *  stay fixed.
 *
 *
 *  @author Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
 */
//=============================================================================


module gleep
{
  local interface schmooze {};
};

module gleep
{
  local interface schmeer {};
};

module gleep
{
  local interface schlemiel {};

  // This should propagate to all previous and subsequent
  // openings of this module.
  typeprefix gleep "gleep_prefix";
};

module gleep
{
  local interface spilkis {};

  module floop
  {
    local interface schmuck {};
    local interface schmendrick;

// Tests the handling of extra whitespace as well as the version setting.
#    pragma version     gleep::floop::schmendrick    524.23

    local interface schmendrick {};

    module verklempt
    {
      local interface schlemazel {};

    // This will override the prefix directive for module floop at the end
    // of the file.
      typeprefix floop::verklempt "verklempt_prefix";
    };
  };

  local interface schmegegging {};
};

// This should override any existing prefix and disable any subsequent
// attempts to set it, such as in the directive below.
typeid gleep::floop::schmuck "ABRA:cadabra/hocus/pocus:1.23";

// This will affect everything in floop's scope recursively, except items
// which have a prefix that was applied to a narrower scope.
typeprefix ::gleep::floop "floop_prefix";

