
//=============================================================================
/**
 *  @file    typecode.idl
 *
 *  $Id$
 *
 *  Test a sequence of typecodes
 *
 *
 *  @author Johnny Willemsen  <jwillemsen@remedy.nl>
 */
//=============================================================================


#include "orb.idl"

module MyModule
{
  typedef sequence<CORBA::TypeCode> TypeCodeList;
};

