#
# Makefile for building the Chat example
# 

!ifdef DEBUG
DEBUG_FLAG = -DDEBUG
!endif

!ifdef STATIC
STATIC_FLAG = -DSTATIC
!endif  

!ifdef PASCAL
PASCAL_FLAG = -DPASCAL
!endif

FLAGS = $(DEBUG_FLAG) $(STATIC_FLAG) $(PASCAL_FLAG)

all:
	$(MAKE) -f Chat_Client.bor $(FLAGS)
	$(MAKE) -f Chat_Server.bor $(FLAGS)

