// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef TE_RESETTOPIC_SENDER_IDL
#define TE_RESETTOPIC_SENDER_IDL

#include "Connector/TE_ResetTopic_Connector.idl"

module TE_ResetTopic
{
  interface ChangeTopicInterface
  {
    void set_new_topic (in string topic_name);
  };

  component Sender supports ChangeTopicInterface
  {
    port TE_ResetTopicTestConnector::DDS_Write  info_write;
    port TE_ResetTopicTestConnector::DDS_Update info_update;

    attribute unsigned short iterations;
    attribute unsigned short keys;
  };
};

#endif
