#
# Makefile for building the TAO Portable_Interceptors tests
#

DIRS = \
        Benchmark \
        Dynamic \
        Service_Context_Manipulation

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
