// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef DDS_LATENCYTT_TEST_SENDER_IDL
#define DDS_LATENCYTT_TEST_SENDER_IDL

#include "Connector/LatencyTT_Test_Connector.idl"

module LatencyTT_Test
{
  component Sender
  {
    port CCM_DDS::LatencyTTTest::DDS_Write info_write;
    attribute unsigned long iterations;
    attribute unsigned short sleep; 
    attribute unsigned short number_of_sub; //number of subscribers
    provides CCM_DDS::ConnectorStatusListener connector_status;
    port CCM_DDS::LatencyTTTest::DDS_Listen ping_listen;
  };
};

#endif
