// $Id

module CCM_AMI
{
  native UserExceptionBase;

  local interface ExceptionHolder
  {
    void raise_exception() raises (UserExceptionBase);
  };

  /// Base interface for the Callback model
  interface ReplyHandler { };
};

