// -*- IDL -*-

//=============================================================================
/**
 * @file SLevel1_Test.idl
 *
 * $Id$
 *
 * IDL fot the Security Level 1 test.
 *
 * @author Priyanka Gontla <pgontla@doc.ece.uci.edu>
 */
//=============================================================================


interface SLevel1_Server
{
  /// Exception that indicates that no security attributes were
  /// available during the upcall.  If this exception is thrown,
  /// then is most likely a problem with the underlying security
  /// mechanism(s).
  exception NoSecurityAttributes {};

  /// Test method to authorize access to a client.
  boolean authorize_level1 ();

  /// Shutdown the server.
  oneway void shutdown ();

};
