// $Id$

/**
 * @file Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef BASE_IDL
#define BASE_IDL

#pragma ndds typesupport "Base/BaseSupport.h"
#pragma opendds typesupport "Base/BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "SharedDPTest"
#pragma DCPS_DATA_KEY "SharedDPTest key"

struct SharedDPTest {
  string key;
  long iteration;
};
#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<SharedDPTest> SharedDPTestSeq;
#endif

#endif
