// $Id$

#ifndef FOO_IDL_
#define FOO_IDL_

#include <Components.idl>

typedef sequence<short>  short_sequence;
typedef sequence<long>   long_sequence;
typedef sequence<float>  float_sequence;
typedef sequence<double> double_sequence;

struct Bar
{
  short  s;
  long   l;
  float  f;
  double d;
};

typedef sequence<Bar, 5> BarSeq;

struct Baz
{
  string name;
  BarSeq my_bar_sequence;
};

component Foo
{
  attribute short  my_short;
  attribute long   my_long;
  attribute float  my_float;
  attribute double my_double;

  attribute short_sequence  my_short_sequence;
  attribute long_sequence   my_long_sequence;
  attribute float_sequence  my_float_sequence;
  attribute double_sequence my_double_sequence;

  attribute Bar my_bar_struct;
  attribute Baz my_baz_struct;
};

#endif /* FOO_IDL_ */
