
//=============================================================================
/**
 *  @file    generic_object.idl
 *
 *  $Id$
 *
 *  This file contains examples of IDL code that has
 *  caused problems in the past for the TAO IDL
 *  compiler. This test is to make sure the problems
 *  stay fixed.
 *
 *
 *  @author Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
 */
//=============================================================================


// The IDL compiler deals with these in a completely different way
// that it deals with a derived object, i.e., an interface.

enum ObjectType
{
  OT_THIS,
  OT_THAT
};

union Selecter switch (ObjectType)
{
  case OT_THIS: Object this_object;
  case OT_THAT: Object that_object;
};

// Test stub code for generic object parameters.
interface generic
{
  Object op (in Object inarg,
             inout Object inoutarg,
             out Object outarg);
};

