/* -*- C++ -*- */
// @(#)Notification_Receiver.idl	1.1	10/18/96


// ============================================================================
//
// = LIBRARY
//    EventComm
// 
// = FILENAME
//    Notification_Receiver.idl
//
// = DESCRIPTION 
//    The CORBA IDL interface for the Event Communication 
//    <Notification_Receiver> component.
//
// = AUTHOR
//    Douglas C. Schmidt (schmidt@cs.wustl.edu)
// 
// ============================================================================

#include "Notification.idl"

#ifndef _Notification_Receiver_iDL
#define _Notification_Receiver_iDL

interface Notification_Receiver
  // = TITLE
  //   Defines the interface for a <Notification_Receiver> of events.
  //   Note that all operations are <oneway> to avoid blocking.
  //
  // = DESCRIPTION
{
  oneway void receive_notification (in Notification notification);
  // Inform the <Notification_Receiver> that <event> has occurred.

  oneway void disconnect (in string reason);
  // Disconnect the <Notification_Receiver> from the <Notifier>,
  // giving it the <reason>.
};

#endif /* _Notification_Receiver_iDL */
