// $Id$
// Compliant with OMG 06-04-01 Section 9.3.4.1

#if !defined (CCM_ENTITYCONTEXT_IDL)
#define CCM_ENTITYCONTEXT_IDL

#include "ccm/CCM_Context.idl"
#include "ccm/CCM_Object.idl"

#if !defined (CCM_LW)

module Components
{
  typeprefix Components "omg.org";

  local interface EntityContext : CCMContext
  {
    Object get_CCM_object ()
      raises (IllegalState);

    PrimaryKeyBase get_primary_key ()
      raises (IllegalState);
  };
};

#endif

#endif /* CCM_ENTITYCONTEXT_IDL */
