// $Id$
//===========================================================
/**
 * @file BMDisplayEI.idl
 *
 * Definition of the BMDisplay (navigation display) component
 * implementation.
 *
 * @author Balachandran Natarajan <bala@dre.vanderbilt.edu>
 */
//===========================================================
#ifndef CIAO_BMDISPLAYEI_IDL
#define CIAO_BMDISPLAYEI_IDL

#include "BMDisplayE.idl"

module BasicSP
{
  /**
   * @interface BMDisplay_Exec
   *
   * The actually BMDisplay executor inherits from both CCM_BMDisplay
   * and session_component interfaces as a monolithic implementation.
   */
  local interface BMDisplay_Exec :
    CCM_BMDisplay,
    Components::SessionComponent
  {
  };

};

#endif /* CIAO_BMDISPLAYEI_IDL */
