// $Id$

#if !defined (CCM_CONTAINER_EX_IDL)
#define CCM_CONTAINER_EX_IDL

#include "ccm/CCM_Container.idl"
#include "ccm/CCM_Session2Context.idl"
#include "ccm/CCM_EntityContext.idl"

#endif /* CCM_CONTAINER_EX_IDL */
