// $Id$
/// Compliant with OMG 06-04-01 Section 6.10.1.1

#if !defined (CCM_CONFIGURATOR_IDL)
#define CCM_CONFIGURATOR_IDL

#if !defined (CCM_LW)

module Components
{
  typeprefix Components "omg.org";

  exception WrongComponentType {};

  interface CCMObject;

  interface Configurator
  {
    void configure (in CCMObject comp)
      raises (WrongComponentType);
  };
};

#endif

#endif /* CCM_CONFIGURATOR_IDL */
