// $Id$

/**
 * @@ This is just a temporary file.  Since TAO does not have
 *    CosPersistentState at all, we use this file to define
 *    types necessary to get ComponentBase.idl to compile.
 */

#if !defined (CIAO_COSPERSISTENTSTATE_PIDL)
#define CIAO_COSPERSISTENTSTATE_PIDL

#if !defined (CCM_LW)

module CosPersistentState {

  local interface CatalogBase
  {
  };

  typedef sequence<octet> _TypeId;
  typedef string Pid;
};

#endif
#endif /* CIAO_COSPERSISTENTSTATE_PIDL */
