//$Id$:

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "../Minimum_Base/Minimum_Base.idl"

module Minimum
{
  component Receiver
  {
  };

  home ReceiverHome manages Receiver
  {
  };
};
#endif /*RECEIVER_IDL*/
