//$Id$
#ifndef RACE_PLAN_EGRESS_IDL
#define RACE_PLAN_EGRESS_IDL

#ifndef INCLUDED_DEPLOYMENT_DATA
#define INCLUDED_DEPLOYMENT_DATA
#include "DAnCE/Deployment/Deployment_DeploymentPlan.idl"
#endif

module CIAO
{

  module RACE
  {
    interface PlanEgress
    {
      boolean output_plan (in Deployment::DeploymentPlan plan);
    };
  };
};

#endif /* RACE_PLAN_EGRESS_IDL */
