// $Id$

/**
 * @file HomeRegistrar.idl
 *
 * This file define the interface supported by CIAO's HomeFinder
 * service.  It is basically an extension of Components::HomeFinder
 * interface by supporting CIAO specific home
 */

#include "CCM_Component.idl"

module CIAO
{
  exception AlreadyBound
  {
    // Equivalent to CosNaming::NamingContext::AlreadyBound exception.
  };

  exception InvalidName
  {
    // Equivalent to CosNaming::NamingContext::InvalidName exception.
  };

  exception HomeRegisterFailure
  {
    // Equivalent to CosNaming::NamingContext::InvalidName exception.
  };

  interface HomeRegistrar : Components::HomeFinder
  {
    void register_home (in CORBA::RepositoryId home_repo_id,
                        in CORBA::RepositoryId comp_repo_id,
                        in string home_name,
                        in Object objref)
      raises (AlreadyBound, InvalidName, HomeRegisterFailure);
  };
};
