// $Id$

#include <Components.idl>
#include "../common/Protocols.idl"

#pragma ciao lem "ReceiverE.idl"

module Protocols
{
  interface Receiver_Controller
  {
    void shutdown ();
  };

  component Receiver supports Receiver_Controller
  {
    provides test writer;
  };

  home ReceiverHome manages Receiver
  {
  };
};
