// $Id$

/**
 * @file VT_Array_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VT_ARRAY_CONNECTOR_IDL_
#define VT_ARRAY_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/VTopic_Base.idl"

#pragma ciao lem "Conn_Array/VT_Array_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/VTopic_BaseTypeSupport.idl"
#endif

module VTopic
{
  module ::CCM_DDS::Typed < ::TopicArray, ::TopicArraySeq> TopicArrayConnector;
};

#endif /* VT_ARRAY_CONNECTOR_IDL_ */
