// $Id$

/**
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef DDS_LATENCYTT_TEST_SENDER_IDL
#define DDS_LATENCYTT_TEST_SENDER_IDL

#include "Connector/LatencyTT_Test_Connector.idl"

module LatencyTT_Test
{
  component Sender
  {
    port LatencyTTTestConn::DDS_Write info_write;
    port LatencyTTTestConn::DDS_Listen ping_listen;

    provides CCM_DDS::ConnectorStatusListener connector_status;

    attribute unsigned long iterations;
    attribute unsigned short sleep;
    attribute unsigned short number_of_sub; //number of subscribers
  };
};

#endif
