// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    anonymous.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has 
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

// Normal typedef'd sequence
module Not_Anon
{
  typedef sequence<short > short_seq;
};

// Array is typedef'd, but sequence is not
module Half_Anon
{
  typedef sequence<char> char_seq_array[14];
  typedef sequence<unsigned long, 18> bd_ulong_seq_array[17];
  typedef sequence<unsigned short> ushort_seq_array[12];
  typedef sequence<unsigned short, 7> bd_ushort_seq_array[11];
};

// Neither array nor sequence are typedef'd.
module All_Anon
{
  exception Nested_Anon 
  {
    sequence<float> float_seq_array[6];
  };
};
