// $Id$

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  /// A very simple interface
  interface Hello
  {
    /// Return a simple string
    string get_string ();

    /// A method to shutdown the ORB
    oneway void shutdown ();
  };

  // A derived interface
  interface HelloAgain : Hello
  {
    string get_string_again ();
  };
};
