//$Id$
//=============================================================================
/**
 * @file Satellite.idl
 *
 * Definition of the Satellite component
 *
 * @author Gan Deng <gan.deng@vanderbilt.edu>
 */
//=============================================================================
#ifndef CIAO_SATELLITE_IDL
#define CIAO_SATELLITE_IDL

#include "../BBN_UAV.idl"

module BBN_UAV
{
  interface trigger
    {
      void alert ();
    };

  component Satellite supports trigger
    {
      publishes TargetLocated target_located;
      consumes UAVReady uav_ready;
      consumes UCAVReady ucav_ready;
      consumes BattleReady battle_ready;
    };

  home SatelliteHome manages Satellite
    {
    };
};

#endif /* CIAO_SATELLITE_IDL */
