// $Id$

/**
 * @@ This is just a temporary file.  Since TAO does not have
 *    CosPersistentState at all, we use this file to define
 *    types necessary to get ComponentBase.idl to compile.
 */

module CosPersistentState {
        local interface CatalogBase
          {
          };

        typedef sequence<octet> TypeId;
        typedef string Pid;
};
