/* -*- C++ -*- */
// $Id$

// ============================================================================
//
// = LIBRARY
//    EventComm
// 
// = FILENAME
//    Notifier.idl
//
// = DESCRIPTION 
//    This is the CORBA IDL interface for the Event Communication <Notifier>.
//
// = AUTHOR
//    Douglas C. Schmidt (schmidt@cs.wustl.edu)
// 
// ============================================================================

#if !defined (_Notifier_iDL)
#define _Notifier_iDL

#include "Notification.idl"
#include "Notification_Receiver.idl"

interface Notifier
{
  // = TITLE
  //   Defines the interface for a <Notifier> of events.

  void send_disconnect (in string reason);
  // Disconnect all the receivers, giving them the <reason>.

  void send_notification (in Notification notification);
  // Send the <Notification> to all the consumers who
  // have subscribed and who match the filtering criteria.

  void subscribe (in Notification_Receiver notification_receiver,
                  in string filtering_criteria);
  // Subscribe the <Notification_Receiver> to receive events that
  // match <filtering_criteria> applied by the <Notifier>.

  void unsubscribe (in Notification_Receiver notification_receiver);
  // Unsubscribe the <Notification_Receiver>.
};

#endif /* _Notifier_iDL */
