
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl NodeApplicationManager
// ------------------------------
#ifndef NODEAPPLICATIONMANAGER_EXPORT_H
#define NODEAPPLICATIONMANAGER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (NODEAPPLICATIONMANAGER_HAS_DLL)
#  define NODEAPPLICATIONMANAGER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && NODEAPPLICATIONMANAGER_HAS_DLL */

#if !defined (NODEAPPLICATIONMANAGER_HAS_DLL)
#  define NODEAPPLICATIONMANAGER_HAS_DLL 1
#endif /* ! NODEAPPLICATIONMANAGER_HAS_DLL */

#if defined (NODEAPPLICATIONMANAGER_HAS_DLL) && (NODEAPPLICATIONMANAGER_HAS_DLL == 1)
#  if defined (NODEAPPLICATIONMANAGER_BUILD_DLL)
#    define NodeApplicationManager_Export ACE_Proper_Export_Flag
#    define NODEAPPLICATIONMANAGER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define NODEAPPLICATIONMANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* NODEAPPLICATIONMANAGER_BUILD_DLL */
#    define NodeApplicationManager_Export ACE_Proper_Import_Flag
#    define NODEAPPLICATIONMANAGER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define NODEAPPLICATIONMANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* NODEAPPLICATIONMANAGER_BUILD_DLL */
#else /* NODEAPPLICATIONMANAGER_HAS_DLL == 1 */
#  define NodeApplicationManager_Export
#  define NODEAPPLICATIONMANAGER_SINGLETON_DECLARATION(T)
#  define NODEAPPLICATIONMANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* NODEAPPLICATIONMANAGER_HAS_DLL == 1 */

// Set NODEAPPLICATIONMANAGER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (NODEAPPLICATIONMANAGER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define NODEAPPLICATIONMANAGER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define NODEAPPLICATIONMANAGER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !NODEAPPLICATIONMANAGER_NTRACE */

#if (NODEAPPLICATIONMANAGER_NTRACE == 1)
#  define NODEAPPLICATIONMANAGER_TRACE(X)
#else /* (NODEAPPLICATIONMANAGER_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define NODEAPPLICATIONMANAGER_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (NODEAPPLICATIONMANAGER_NTRACE == 1) */

#endif /* NODEAPPLICATIONMANAGER_EXPORT_H */

// End of auto generated file.
