#
# $Id$
# Makefile for building the orbsvcs basic notify tests
#

NAMES = \
        AdminProperties \
        ConnectDisconnect \
        Events \
        IdAssignment \
        LifeCycle \
        Simple \
        Updates \
	MultiTypes \
	Filter \
	Sequence

OBJFILES = $(OBJDIR)\$(NAME).obj

CFLAGS = \
        $(ACE_CFLAGS) \
        $(TAO_CFLAGS) \
        $(TAO_EVENT_CFLAGS) \
        $(TAO_NAMING_CFLAGS) \
        $(TAO_SVC_UTILS_CFLAGS) \
        $(TAO_IORTABLE_CFLAGS) \
        $(TAO_PORTABLESERVER_CFLAGS) \
        $(TAO_NOTIFYTESTS_CFLAGS) \
        $(TAO_NOTIFY_CFLAGS) \
        $(TAO_MESSAGING_CFLAGS)

CPPDIR = .

LIBFILES = \
        $(ACE_LIB) \
        $(TAO_LIB) \
        $(TAO_EVENT_LIB) \
        $(TAO_NAMING_LIB) \
        $(TAO_SVC_UTILS_LIB) \
        $(TAO_IORTABLE_LIB) \
        $(TAO_PORTABLESERVER_LIB) \
        $(TAO_NOTIFYTESTS_LIB) \
        $(TAO_NOTIFY_LIB) \
        $(TAO_MESSAGING_LIB)

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
!include <$(ACE_ROOT)\include\makeinclude\build_exe.bor>
