// $Id$

interface Test_Object
{
  // = TITLE
  //   This is a simple interface that tests the Naming Service.

  attribute short id;
  // This provides an easy way to differentiate objects if each
  // objects is served by a separate servant.
};
