// -*- IDL -*-

//=============================================================================
/**
 * @file   test.idl
 *
 * $Id$
 *
 * Simple IDL file to test PortableInterceptor::Current
 * support.
 *
 * @author  Ossama Othman <ossama@uci.edu>
 */
//=============================================================================

module PICurrentTest
{

  interface test
  {
    void invoke_me ();

    void invoke_you ();

    oneway void shutdown ();
  };

};
