// $Id$

#if !defined (CCM_INVALIDREGISTRATION_IDL)
#define CCM_INVALIDREGISTRATION_IDL

module Components
{
  module ContainerPortableInterceptor
  {
    exception InvalidRegistration { };
  };
};

#endif /* CCM_INVALIDREGISTRATION_IDL */
