// $Id$

/**
 * @file
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Writer_Connector.idl"

module Writer
{
  component Receiver
  {
    port WriterTestConnector::DDS_Listen info_out;
  };
};

#endif
