// $Id$

/**
 * @file Perf_Keyed_Test_Connector.idl
 * @author Marcel Smit (msmit@remedy.nl)
 *
 * by-hand translation of the idl3p.
 */

#ifndef PERF_KEYED_TEST_CONNECTOR_IDL_
#define PERF_KEYED_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/Perf_Keyed_Test_Base.idl"

#pragma ciao lem "Connector/Perf_Keyed_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/Perf_Keyed_Test_BaseTypeSupport.idl"
#endif

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::PerfKeyedTest, ::PerfKeyedTestSeq> PerfKeyedTest;
};

#endif /* Perf_Keyed_Test_CONNECTOR_IDL_ */
