// $Id$

#ifndef DDS_RFT2_DCPS_IDL
#define DDS_RFT2_DCPS_IDL

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "dds/DdsDcps.idl"
#endif

#if (CIAO_DDS4CCM_NDDS==1)
# include "connectors/dds4ccm/idl/ndds/ndds_dcps.idl"
#endif

#endif
