// $Id$

#ifndef HELLO_SENDER_BASE_IDL_
#define HELLO_SENDER_BASE_IDL_

#include "dds4ccm/idl/dds4ccm_Base.idl3"
module CCM_DDS
{
  interface string_Writer
  {
    typedef sequence<string> stringSeq;
    
    void write (in string an_instance)
      raises (InternalError);
  };
};

#endif