// $Id$

#include <Components.idl>

#include "Hello_Sender_Base.idl"
#include "Hello_Sender_BaseE.idl"
#include "dds4ccm/idl/dds_rtf2_dcpsE.idl"

module Hello_DDS
{
  component Hello_sender_Connector
  {
    provides CCM_DDS::string_Writer sender_data;
#ifndef AVOID_E_IDL
    provides DDS::DataWriter sender_dds_entity;
#endif
  };

  home SenderConnectorHome manages Hello_sender_Connector
  {
  };
};
