// $Id$

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "../Hello_Base/Hello_Base.idl"

module Hello_AMI
{
  component Sender
  {
    // for asynch invocation.
    uses CCM_AMI::AMI_MyFoo       run_asynch_my_foo;
    uses CCM_AMI::AMI_MyInterface run_asynch_my_interface;

    // for synchronous invocation
    uses CCM_AMI::MyFoo         run_my_foo;
    uses CCM_AMI::MyInterface   run_my_interface;

    //provides the callback function/exception for the AMI component.
    provides CCM_AMI::AMI_MyFoo_callback        the_my_foo_callback;
    provides CCM_AMI::AMI_MyInterface_callback  the_my_interface_callback;
  };

  home SenderHome manages Sender
  {
  };
};

#endif