// $Id$

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "../Hello_Base/Hello_Base.idl"

module Hello_AMI
{
  component Sender
  {
    //uses the ami component.
    uses CCM_AMI::AMI_ami_foo          run_asynch_foo;

    //provides the callback function/exception for the AMI component.
    provides CCM_AMI::AMI_foo_callback the_foo_callback;
  };

  home SenderHome manages Sender
  {
  };
};

#endif