
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl ExecutionManager_svnt
// ------------------------------
#ifndef EXECUTIONMANAGER_SVNT_EXPORT_H
#define EXECUTIONMANAGER_SVNT_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (EXECUTIONMANAGER_SVNT_HAS_DLL)
#  define EXECUTIONMANAGER_SVNT_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && EXECUTIONMANAGER_SVNT_HAS_DLL */

#if !defined (EXECUTIONMANAGER_SVNT_HAS_DLL)
#  define EXECUTIONMANAGER_SVNT_HAS_DLL 1
#endif /* ! EXECUTIONMANAGER_SVNT_HAS_DLL */

#if defined (EXECUTIONMANAGER_SVNT_HAS_DLL) && (EXECUTIONMANAGER_SVNT_HAS_DLL == 1)
#  if defined (EXECUTIONMANAGER_SVNT_BUILD_DLL)
#    define ExecutionManager_svnt_Export ACE_Proper_Export_Flag
#    define EXECUTIONMANAGER_SVNT_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define EXECUTIONMANAGER_SVNT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* EXECUTIONMANAGER_SVNT_BUILD_DLL */
#    define ExecutionManager_svnt_Export ACE_Proper_Import_Flag
#    define EXECUTIONMANAGER_SVNT_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define EXECUTIONMANAGER_SVNT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* EXECUTIONMANAGER_SVNT_BUILD_DLL */
#else /* EXECUTIONMANAGER_SVNT_HAS_DLL == 1 */
#  define ExecutionManager_svnt_Export
#  define EXECUTIONMANAGER_SVNT_SINGLETON_DECLARATION(T)
#  define EXECUTIONMANAGER_SVNT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* EXECUTIONMANAGER_SVNT_HAS_DLL == 1 */

// Set EXECUTIONMANAGER_SVNT_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (EXECUTIONMANAGER_SVNT_NTRACE)
#  if (ACE_NTRACE == 1)
#    define EXECUTIONMANAGER_SVNT_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define EXECUTIONMANAGER_SVNT_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !EXECUTIONMANAGER_SVNT_NTRACE */

#if (EXECUTIONMANAGER_SVNT_NTRACE == 1)
#  define EXECUTIONMANAGER_SVNT_TRACE(X)
#else /* (EXECUTIONMANAGER_SVNT_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define EXECUTIONMANAGER_SVNT_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (EXECUTIONMANAGER_SVNT_NTRACE == 1) */

#endif /* EXECUTIONMANAGER_SVNT_EXPORT_H */

// End of auto generated file.
