// $Id$

#ifndef FAULTCORRELATIONMANAGER_IDL
#define FAULTCORRELATIONMANAGER_IDL

#include "orbsvcs/orbsvcs/LWFT/FaultNotification.idl"
#include "ExecutionManagerDaemon.idl"

module DAnCE 
{
  interface FaultCorrelationManager : FLARE::FaultNotification, DAnCE::ExecutionManagerDaemon {
    void stop_failover_unit (in string fou_id);
  };
};

#endif /* FAULTCORRELATIONMANAGER_IDL */
