
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl FaultCorrelationManager_stub
// ------------------------------
#ifndef FAULTCORRELATIONMANAGER_STUB_EXPORT_H
#define FAULTCORRELATIONMANAGER_STUB_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (FAULTCORRELATIONMANAGER_STUB_HAS_DLL)
#  define FAULTCORRELATIONMANAGER_STUB_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && FAULTCORRELATIONMANAGER_STUB_HAS_DLL */

#if !defined (FAULTCORRELATIONMANAGER_STUB_HAS_DLL)
#  define FAULTCORRELATIONMANAGER_STUB_HAS_DLL 1
#endif /* ! FAULTCORRELATIONMANAGER_STUB_HAS_DLL */

#if defined (FAULTCORRELATIONMANAGER_STUB_HAS_DLL) && (FAULTCORRELATIONMANAGER_STUB_HAS_DLL == 1)
#  if defined (FAULTCORRELATIONMANAGER_STUB_BUILD_DLL)
#    define FaultCorrelationManager_stub_Export ACE_Proper_Export_Flag
#    define FAULTCORRELATIONMANAGER_STUB_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define FAULTCORRELATIONMANAGER_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* FAULTCORRELATIONMANAGER_STUB_BUILD_DLL */
#    define FaultCorrelationManager_stub_Export ACE_Proper_Import_Flag
#    define FAULTCORRELATIONMANAGER_STUB_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define FAULTCORRELATIONMANAGER_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* FAULTCORRELATIONMANAGER_STUB_BUILD_DLL */
#else /* FAULTCORRELATIONMANAGER_STUB_HAS_DLL == 1 */
#  define FaultCorrelationManager_stub_Export
#  define FAULTCORRELATIONMANAGER_STUB_SINGLETON_DECLARATION(T)
#  define FAULTCORRELATIONMANAGER_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* FAULTCORRELATIONMANAGER_STUB_HAS_DLL == 1 */

// Set FAULTCORRELATIONMANAGER_STUB_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (FAULTCORRELATIONMANAGER_STUB_NTRACE)
#  if (ACE_NTRACE == 1)
#    define FAULTCORRELATIONMANAGER_STUB_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define FAULTCORRELATIONMANAGER_STUB_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !FAULTCORRELATIONMANAGER_STUB_NTRACE */

#if (FAULTCORRELATIONMANAGER_STUB_NTRACE == 1)
#  define FAULTCORRELATIONMANAGER_STUB_TRACE(X)
#else /* (FAULTCORRELATIONMANAGER_STUB_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define FAULTCORRELATIONMANAGER_STUB_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (FAULTCORRELATIONMANAGER_STUB_NTRACE == 1) */

#endif /* FAULTCORRELATIONMANAGER_STUB_EXPORT_H */

// End of auto generated file.
