// $Id$

/**
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef DDS_SL_DISABLED_SENDER_IDL
#define DDS_SL_DISABLED_SENDER_IDL

#include "Connector/SL_Disabled_Connector.idl"

module SL_Disabled
{
  component Sender
  {
     port SL_DisabledConnector::DDS_Update test_topic_update;
  };
};

#endif
