/**
 * @file CIAO_Properties.idl
 * @author William R. Otte
 * 
 * Standardizes names of configvalues used by CIAO. 
 */

#ifndef CIAO_PROPERTIES_IDL
#define CIAO_PROPERTIES_IDL

module CIAO
{
  module Deployment
  {
    const string SVNT_ENTRYPT = "edu.vanderbilt.dre.ServantEntrypoint";
    const string SVNT_ARTIFACT = "edu.vanderbilt.dre.ServantArtifact";
    const string EXEC_ARTIFACT = "edu.vanderbilt.dre.ExecutorArtifact";
    const string SERVER_RESOURCES = "edu.vanderbilt.dre.ServerResources";
    const string SERVER_UUID = "edu.vanderbilt.dre.ServerUUID";
    const string SERVER_EXECUTABLE = "edu.vanderbilt.dre.ComponentServerExecutable";
    const string SERVER_TIMEOUT = "edu.vanderbilt.dre.ServerTimeout";
    const string SERVER_MULTITHREAD = "edu.vanderbilt.dre.Multithreaded";
  };
};
#endif /* CIAO_PROPERTIES_IDL */