// $Id$

/**
 *  @file Receiver.idl
 *
 *  @author Don Busch <busch_d@ociweb.com>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include <Components.idl>
#include "Message.idl"
#include "History.idl"

component Receiver {
  consumes Message message_consumer;
  uses History message_history;
};

home ReceiverHome manages Receiver {};

#endif
