// $Id$

/**
 * @file   CSL_USTest_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef CSL_USTEST_BASE_IDL
#define CSL_USTEST_BASE_IDL

#pragma ndds typesupport "Base/CSL_USTest_BaseSupport.h"
#pragma opendds typesupport "Base/CSL_USTest_BaseTypeSupportImpl.h"

struct TestTopic {
  string key; //@key
  long x;
};
typedef sequence<TestTopic> TestTopicSeq;

#endif
