// $Id$

/**
 * @file   CSL_USTest_Base.idl 
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef CSL_USTEST_BASE_IDL
#define CSL_USTEST_BASE_IDL


struct TestTopic {
  string key; //@key
  long x;
};

typedef sequence<TestTopic> TestTopic_Seq;

#endif
