// $Id$

#ifndef DANCE_DEPLOYMENTINTERCEPTOR_IDL
#define DANCE_DEPLOYMENTINTERCEPTOR_IDL

#include "Deployment/Deployment_DeploymentPlan.idl"
#include "Deployment/Deployment_PlanError.idl"
#include "Deployment/Deployment_InvalidProperty.idl"
#include "Deployment/Deployment_InvalidNodeExecParameter.idl"
#include "Deployment/Deployment_InvalidComponentExecParameter.idl"
#include "Deployment/Deployment_InvalidConnection.idl"
#include "Deployment/Deployment_StartError.idl"
#include "Deployment/Deployment_StopError.idl"

module DAnCE
{
  local interface DeploymentInterceptor
  {
    void configure (in ::Deployment::Properties config);

    void preprocess_plan (inout ::Deployment::DeploymentPlan plan)
      raises (::Deployment::PlanError);

    void instance_pre_install (inout ::Deployment::DeploymentPlan plan,
                               in unsigned long instanceRef)
      raises (::Deployment::PlanError,
              ::Deployment::InvalidProperty,
              ::Deployment::InvalidNodeExecParameter,
              ::Deployment::InvalidComponentExecParameter);

    void instance_post_install (in ::Deployment::DeploymentPlan plan,
                                in unsigned long instance_index,
                                in any instance_reference,
                                in any exception_thrown)
      raises (::Deployment::PlanError,
              ::Deployment::InvalidProperty,
              ::Deployment::InvalidNodeExecParameter,
              ::Deployment::InvalidComponentExecParameter);
    
    void post_endpoint_reference (in ::Deployment::DeploymentPlan plan,
                                  in unsigned long connectionRef,
                                  in any endpoint_reference,
                                  in any exception_thrown)
      raises (::Deployment::InvalidConnection);
    
    void instance_pre_connect (inout ::Deployment::DeploymentPlan plan,
                               in unsigned long connection_index,
                               inout any provided_reference)
      raises (::Deployment::InvalidConnection);

    void instance_post_connect (in Deployment::DeploymentPlan plan,
                                in unsigned long connectionRef,
                                in any exceptionThrown)
      raises (::Deployment::InvalidConnection);
    
    void instance_post_configured (in ::Deployment::DeploymentPlan plan,
                                   in unsigned long instanceRef,
                                   in any exception_thrown)
      raises (::Deployment::StartError);

    void instance_post_activate (in ::Deployment::DeploymentPlan plan,
                                 in unsigned long instanceRef,
                                 in any exception_thrown)
      raises (::Deployment::StartError);

    void instance_post_passivate (in ::Deployment::DeploymentPlan plan,
                                  in unsigned long instanceRef,
                                  in any exception_thrown)
      raises (::Deployment::StopError);
    void instance_post_remove (in ::Deployment::DeploymentPlan plan,
                               in unsigned long instanceRef,
                               in any exception_thrown)
      raises (::Deployment::StopError);
  };
};

#endif
