
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl DomainApplication
// ------------------------------
#ifndef DOMAINAPPLICATION_EXPORT_H
#define DOMAINAPPLICATION_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (DOMAINAPPLICATION_HAS_DLL)
#  define DOMAINAPPLICATION_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && DOMAINAPPLICATION_HAS_DLL */

#if !defined (DOMAINAPPLICATION_HAS_DLL)
#  define DOMAINAPPLICATION_HAS_DLL 1
#endif /* ! DOMAINAPPLICATION_HAS_DLL */

#if defined (DOMAINAPPLICATION_HAS_DLL) && (DOMAINAPPLICATION_HAS_DLL == 1)
#  if defined (DOMAINAPPLICATION_BUILD_DLL)
#    define DomainApplication_Export ACE_Proper_Export_Flag
#    define DOMAINAPPLICATION_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define DOMAINAPPLICATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* DOMAINAPPLICATION_BUILD_DLL */
#    define DomainApplication_Export ACE_Proper_Import_Flag
#    define DOMAINAPPLICATION_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define DOMAINAPPLICATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* DOMAINAPPLICATION_BUILD_DLL */
#else /* DOMAINAPPLICATION_HAS_DLL == 1 */
#  define DomainApplication_Export
#  define DOMAINAPPLICATION_SINGLETON_DECLARATION(T)
#  define DOMAINAPPLICATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* DOMAINAPPLICATION_HAS_DLL == 1 */

// Set DOMAINAPPLICATION_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (DOMAINAPPLICATION_NTRACE)
#  if (ACE_NTRACE == 1)
#    define DOMAINAPPLICATION_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define DOMAINAPPLICATION_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !DOMAINAPPLICATION_NTRACE */

#if (DOMAINAPPLICATION_NTRACE == 1)
#  define DOMAINAPPLICATION_TRACE(X)
#else /* (DOMAINAPPLICATION_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define DOMAINAPPLICATION_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (DOMAINAPPLICATION_NTRACE == 1) */

#endif /* DOMAINAPPLICATION_EXPORT_H */

// End of auto generated file.
