// $Id$

/**
 * @file CFTLE_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef CONTENTFILTEREDTOPIC_LISTEN_EVENT_TEST_BASE_IDL
#define CONTENTFILTEREDTOPIC_LISTEN_EVENT_TEST_BASE_IDL

#pragma ndds typesupport "Base/CFTLE_Test_BaseSupport.h"
#pragma opendds typesupport "Base/CFTLE_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "ContentFilteredTopicListenEventTest"
#pragma DCPS_DATA_KEY "ContentFilteredTopicListenEventTest key"

struct ContentFilteredTopicListenEventTest {
  string key; //@key
  long iteration;
};

typedef sequence<ContentFilteredTopicListenEventTest> ContentFilteredTopicListenEventTestSeq;

#endif
