# file      : Test/IDL2/Makefile.alt
# author    : Boris Kolpackov <boris@dre.vanderbilt.edu>
# cvs-id    : $Id$

root := ../..

include $(root)/Bootstrap.rules

$(call include, $(root)/Config.rules)

$(call include, $(UTILITY_BUILD_RULES)/Recursion.pre.rules)

target_makefile_list  :=
target_directory_list := Compiler        \
                         SemanticGraph   \
                         Traversal

default_makefile_name := Makefile.alt

Traversal : SemanticGraph
Compiler : Traversal

$(call include, $(UTILITY_BUILD_RULES)/Recursion.post.rules)

