// $Id$

/**
 * @file OneFile_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef ONEFILE_BASE_IDL_
#define ONEFILE_BASE_IDL_

#pragma ndds typesupport "OneFile_BaseSupport.h"

struct OneFileTopic {
  string hello; //@key
  long iteration;
};
typedef sequence<OneFileTopic> OneFileTopicSeq;

#endif /* ONEFILE_BASE_IDL_ */
