branches:
  only:
    - master

os: Visual Studio 2017

clone_depth: 15

install:
  - mkdir ext && cd ext
  - git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - cd ..
  - set MPC_ROOT=%CD%\ext\MPC
  - set ACE_ROOT=%CD%\ACE
  - set TAO_ROOT=%CD%\TAO
  - set PATH=%ACE_ROOT%\lib:%PATH%
  - ps: $CONTENT='#include "ace/config-win32.h"'
  - ps: $CONTENT > ACE\ace\config.h
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - perl %CD%\ACE\bin\mwc.pl -type vs2017 %CD%\TAO\TAO_ACE.mwc

platform:
  - x64

configuration:
  - Debug

build:
  parallel: true
  project: TAO\TAO_ACE.sln

test: off
