variables:
   ACE_ROOT: $(Build.SourcesDirectory)/ACE
   TAO_ROOT: $(Build.SourcesDirectory)/TAO
   MPC_ROOT: $(Build.SourcesDirectory)/ACE/MPC
   system.prefergit: true

schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

resources:
- repo: self
  fetchDepth: 1

jobs:
- job: VisualStudio2019
  timeoutInMinutes: 180
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Qt5:
        BuildPlatform: x64
        BuildConfiguration: Debug
        vcpkgarch: x64-windows
        vcpkglibdir: debug\lib
        vcpkgpackages: 'openssl xerces-c qt5-base'
        OptionalFeatures: qt5=1
  variables:
    VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
    XERCESC_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    XERCESC_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
    SSL_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    SSL_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
    QT5_BINDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\tools\qt5\bin
    QT5_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    QT5_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
  steps:
  - powershell: |
      git clone -q --depth 1 git://github.com/Microsoft/vcpkg.git $(VCPKG_ROOT)
      $(VCPKG_ROOT)\bootstrap-vcpkg.bat
      $(VCPKG_ROOT)\vcpkg install --recurse --triplet $(vcpkgarch) $(vcpkgpackages)
    displayName: Install additional packages using vcpkg
  - powershell: |
      '#include "ace/config-win32.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      echo "xerces3=1" | out-file -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "ssl=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "versioned_namespace=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Create default.features file
  - powershell: |
      echo $(OptionalFeatures) | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Add optional features ($(OptionalFeatures))
    condition: and(succeeded(), ne(variables['OptionalFeatures'], ''))
  - powershell: git clone -q --depth 1 git://github.com/DOCGroup/MPC.git $(MPC_ROOT)
    displayName: git clone MPC
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vs2019 $(TAO_ROOT)/TAO_ACE.mwc -workers 4 -expand_vars -use_env
    displayName: Run script mwc.pl on $(TAO_ROOT)/TAO_ACE.mwc
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vs2019 $(ACE_ROOT)/tests/tests.mwc -workers 4 -expand_vars -use_env
    displayName: Run script mwc.pl on $(ACE_ROOT)/tests/tests.mwc
  - task: VSBuild@1
    displayName: Build solution TAO/TAO_ACE.sln
    inputs:
      solution: TAO/TAO_ACE.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true
  - task: VSBuild@1
    displayName: Build solution ACE/tests/tests.sln
    inputs:
      solution: ACE/tests/tests.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      GCC4:
        CC: gcc
        CXX: g++
        platform_file: include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
  steps:
  - script: |
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ $(Repo) main"
    displayName: Add repository ($(Repo))
    condition: and(succeeded(), ne(variables['Repo'], ''))
  - script: |
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo apt-get --yes update
      sudo apt-get --yes install libxerces-c-dev libssl-dev qtbase5-dev qt5-qmake qt5-default $(PackageDeps)
    displayName: install system package dependencies
  - powershell: |
      '#include "ace/config-linux.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      'xerces3=1' > $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'ssl=1' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'qt5=1' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'versioned_namespace=1' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
    displayName: Create default.features file
  - powershell: |
      'xerces3=1' > $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      'ssl=1' >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      'qt5=1' >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      "$(platform_file)" >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
    displayName: Create platform_macros file
  - powershell: git clone --depth 1 git://github.com/DOCGroup/MPC.git $(MPC_ROOT)
    displayName: git clone MPC
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(TAO_ROOT)/TAO_ACE.mwc -workers 4 -expand_vars -relative QTDIR=/usr
    displayName: Run mwc.pl on $(TAO_ROOT)/TAO_ACE.mwc
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(ACE_ROOT)/tests/tests.mwc -workers 4 -expand_vars -relative QTDIR=/usr
    displayName: Run mwc.pl on $(ACE_ROOT)/tests/tests.mwc
  - bash: make -j 6 -C TAO
    displayName: Build TAO project
  - bash: make -j 6 -C ACE/tests
    displayName: Build tests project

- job: MacOSX
  timeoutInMinutes: 90
  pool:
    vmImage: macOS-10.14
  steps:
  - powershell: |
      '#include "ace/config-macosx.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      'include $(ACE_ROOT)/include/makeinclude/platform_macosx.GNU' > $(ACE_ROOT)/include/makeinclude/platform_macros.GNU;
    displayName: Create platform_macros file
  - powershell: git clone --depth 1 git://github.com/DOCGroup/MPC.git $(MPC_ROOT)
    displayName: git clone MPC
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(TAO_ROOT)/TAO_ACE.mwc -workers 4
    displayName: Run mwc.pl on $(TAO_ROOT)/TAO_ACE.mwc
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(ACE_ROOT)/tests/tests.mwc -workers 4
    displayName: Run mwc.pl on $(ACE_ROOT)/tests/tests.mwc
  - bash: make -j 6 -C TAO
    displayName: Build TAO project
  - bash: make -j 6 -C ACE/tests
    displayName: Build tests project
