// $Id$
// Compliant to OMG 06-04-01, section 9.3.2.1

#if !defined (CCM_CONTEXT_IDL)
#define CCM_CONTEXT_IDL

#include "ccm/Security.idl"
#include "ccm/CCM_Transaction.idl"
#include "ccm/CCM_Home.idl"
#include "ccm/CCM_CCMException.idl"

// *************** Basic Container interfaces ***************

module Components
{
  typeprefix Components "omg.org";

#if !defined (CCM_LW)
  typedef SecurityLevel2::Credentials Principal;
#endif

  exception IllegalState {};

  local interface CCMContext
  {
#if !defined (CCM_LW)
    Principal get_caller_principal();
#endif

    CCMHome get_CCM_home();

#if !defined (CCM_LW)
    boolean get_rollback_only()
      raises (IllegalState);
#endif

#if !defined (CCM_LW)
    Transaction::UserTransaction get_user_transaction()
      raises (IllegalState);
#endif

#if !defined (CCM_LW)
    boolean is_caller_in_role (in string role);
#endif

#if !defined (CCM_LW)
    void set_rollback_only()
      raises (IllegalState);
#endif

    Object resolve_service_reference(in string service_id)
      raises (CCMException);

    void
    install_service_component_reference (in string service_id,
                                         in Object objref);

    Object
    uninstall_service_component_reference (in string service_id);


  };
};
#endif /* CCM_CONTEXT_IDL */
