// $Id$

/**
 * @file Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef SHARED_DP_CONNECTOR_IDL_
#define SHARED_DP_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/Base.idl"

#pragma ciao lem "Connector/ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/BaseTypeSupport.idl"
#endif

module SharedDP
{
  module ::CCM_DDS::Typed < ::SharedDPTest, ::SharedDPTestSeq> SharedDPTestConnector;
};

#endif /* SHARED_DP_CONNECTOR_IDL_ */
