// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    fwd.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has 
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

// This file, along with its companion full.idl, test the
// handling of forward interface declarations that are
// not defined in the same IDL file. The two files have
// mutually dependent interfaces. It is no longer necessary
// for such ILD files to include each other, as long as 
// they are part of the same build.

module mod2
{
  interface fwd;

  interface full
  {
    fwd op (in fwd inarg,
            inout fwd inoutarg,
            out fwd outarg);
  };

  typedef sequence<full, 5> full_seq2;

  interface fwd;
};

