// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    typedef.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has 
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================


// Must keep unaliasing until all levels of typedef
// are removed.

// This is also a test of arrays of arrays. Once 
// upon a time, the generated CDR operators of such 
// animals wouldn't compile on all platforms.

typedef char TAO_A5[5];

typedef TAO_A5 TAO_C5;

typedef TAO_C5 TAO_G5;

typedef TAO_G5 TAO_J5;

typedef TAO_J5 TAO_M5[5];

typedef TAO_M5 TAO_R5;

typedef TAO_R5 TAO_V5;

typedef TAO_V5 TAO_Z5[5];



