// $Id$

//=========================================================================
// Valuebox of basic types
//=========================================================================

// Valuebox of all basic types defined at outermost scope:

enum Color { red, orange, yellow, green, blue, indigo, violet };

valuetype VBshort      short;
valuetype VBlong       long;
valuetype VBlonglong   long long;
valuetype VBushort     unsigned short;
valuetype VBulong      unsigned long;
valuetype VBulonglong  unsigned long long;
valuetype VBchar       char;
valuetype VBwchar      wchar;
valuetype VBboolean    boolean;
valuetype VBoctet      octet;
valuetype VBfloat      float;
valuetype VBdouble     double;
valuetype VBlongdouble long double;
valuetype VBenum       Color;

// Typedefs of basic types
typedef short              TDshort;
typedef long               TDlong;
typedef long long          TDlonglong;
typedef unsigned short     TDushort;
typedef unsigned long      TDulong;
typedef unsigned long long TDulonglong;
typedef char               TDchar;
typedef wchar              TDwchar;
typedef boolean            TDboolean;
typedef octet              TDoctet;
typedef float              TDfloat;
typedef double             TDdouble;
typedef long double        TDlongdouble;
typedef Color              TDenum;

// Value box of typedef of basic types
valuetype VBTDshort      TDshort;
valuetype VBTDlong       TDlong;
valuetype VBTDlonglong   TDlonglong;
valuetype VBTDushort     TDushort;
valuetype VBTDulong      TDulong;
valuetype VBTDulonglong  TDulonglong;
valuetype VBTDchar       TDchar;
valuetype VBTDwchar      TDwchar;
valuetype VBTDboolean    TDboolean;
valuetype VBTDoctet      TDoctet;
valuetype VBTDfloat      TDfloat;
valuetype VBTDdouble     TDdouble;
valuetype VBTDlongdouble TDlongdouble;
valuetype VBTDenum       TDenum;

// Any and typedef of any
valuetype VBany  any;
typedef any TDany;
valuetype VBTDany TDany;

module vb_basic
{
    // Valuebox defined within a module scope
    valuetype M_VBlong long;

    interface Test
    {
        M_VBlong basic_op1(in M_VBlong  p1, inout M_VBlong  p2,
                           out M_VBlong  p3);
    };
};

// Valuebox of an interface
valuetype VBinterface    vb_basic::Test;
