//
// $Id$
//
// ================================================================
//
// = LIBRARY
//   TAO_PortableGroup
//
// = FILENAME
//   mgm.pidl
//
// = DESCRIPTION
//
//   This file was used to generate the code in mgmC.{h,i,cpp}
//
//   The command used to generate code from this file is:
//
//     tao_idl.exe \
//          -Ge 1 \
//          -Wb,export_macro=TAO_PortableGroup_Export \
//          -Wb,export_include="tao/corbafwd.h" \
//          -Wb,pre_include="ace/pre.h" \
//          -Wb,post_include="ace/post.h" \
//          -I../../orbsvcs/orbsvcs \
//          mgm.pidl
//
//   After the file is generated a patch from the diffs directory must
//   be applied.  The patch:
//
//   - Disables parts of the code under certain configurations.
//
//   - Eliminates cycles in the include dependencies.
//
//   - Adds non-idl components of PortableGroup to the namespace.
//     This includes (a) Servant (b) ServantBase (c) RefCountServantBase
//     (d) Cookie (e) ObjectId_to_string (f) string_to_ObjectId (g)
//     ObjectId_to_wstring (h) wstring_to_ObjectId (i) ServantBase_var
//     (j) DynamicImplementation (k) LocalServantBase
//
//   Apply patches using the following commands:
//
//   patch < diffs\mgmC.h.diff
//   patch < diffs\mgmC.i.diff
//   patch < diffs\mgmC.cpp.diff
//
//   Note: The diffs were generated with these commands:
//
//   diff -wub mgmC.h mgmC.h.mod > diffs\mgmC.h.diff
//   diff -wub mgmC.i mgmC.i.mod > diffs\mgmC.i.diff
//   diff -wub mgmC.cpp mgmC.cpp.mod > diffs\mgmC.cpp.diff
//
// ================================================================


#ifdef _MGM_idl
#define _MGM_idl

#include "PortableGroup.idl"

module MGM {
  // Property values
  typedef long GroupCreationMode

  const GroupCreationMode CREATE_ADDRESS_DEFERED = 0;
  const GroupCreationMode CREATE_ADDRESS_GENERATED = 1;
  const GroupCreationMode CREATE_ADDRESS_SUPPLIED = 2;

  interface ObjectGroupFactory :
    PortableGroup::GenericFactory,
    PortableGroup::PropertyManager,
    PortableGroup::ObjectGroupManager {}
};

#endif // _MGM_idl
