#
# Makefile for building the TAO tests
#

!include <$(ACE_ROOT)\include\makeinclude\make_flags.bor>

tests:
	cd $(ACE_ROOT)\TAO\tests\CDR
	$(MAKE) -f Makefile.bor $(MAKE_FLAGS)
	cd $(ACE_ROOT)\TAO\tests\Connection_Purging
	$(MAKE) -f Makefile.bor $(MAKE_FLAGS)
	cd $(ACE_ROOT)\TAO\tests\DynAny_Test
	$(MAKE) -f Makefile.bor $(MAKE_FLAGS)
	cd $(ACE_ROOT)\TAO\tests\IDL_Test
	$(MAKE) -f Makefile.bor $(MAKE_FLAGS)
	cd $(ACE_ROOT)\TAO\tests\Param_Test
	$(MAKE) -f Makefile.bor $(MAKE_FLAGS)
