/// $Id$
/// Compliant with OMG 06-04-01 Section 6.4.3.3

#if !defined (CCM_NAVIGATION_IDL)
#define CCM_NAVIGATION_IDL

#include "tao/orb_types.pidl"
#include "tao/StringSeq.pidl"

module Components
{
  typeprefix Components "omg.org";

  typedef string FeatureName;
  typedef sequence<FeatureName> NameList;

#if !defined (CCM_LW)
  valuetype PortDescription
  {
    public FeatureName name;
    public CORBA::RepositoryId type_id;
  };
#endif

#if !defined (CCM_LW)
  valuetype FacetDescription : PortDescription
  {
    public Object facet_ref;
  };

  typedef sequence<FacetDescription> FacetDescriptions;
#endif

  exception InvalidName {};
  interface Navigation
  {
    Object provide_facet (in FeatureName name)
      raises (InvalidName);
#if !defined (CCM_LW)
    FacetDescriptions get_all_facets();
#endif

#if !defined (CCM_LW)
    FacetDescriptions get_named_facets (in NameList names)
      raises (InvalidName);
#endif

#if !defined (CCM_LW)
    boolean same_component (in Object object_ref);
#endif
  };
};
#endif /* CCM_NAVIGATION_IDL */
