// $Id$

/**
 * @file TwoTopics_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef TWOTOPICS_CONNECTOR_IDL_
#define TWOTOPICS_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/TwoTopics_Base.idl"

#pragma ciao lem "Connector/TwoTopics_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/TwoTopics_BaseTypeSupport.idl"
#endif

module TT_Connector
{
  module ::CCM_DDS::Typed < HelloTopic, HelloTopicSeq> HelloConnector;
  module ::CCM_DDS::Typed < GoodbyeTopic, GoodbyeTopicSeq> GoodbyeConnector;
};

#endif /* TWOTOPICS_CONNECTOR_IDL_ */
