// $Id$
/**
 * @file EventAny.idl
 * @author Jeff Parsons <j.parsons@vanderbilt.edu>
 *
 * Tests Any insertion/extraction of event types,
 * and (de)marshaling of such Anys.
 */

#include <Components.idl>

eventtype StringMsg
{
  public string str_msg;
};

