// $Id$

/**
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef DDS_WRITER_ENTITY_SENDER_IDL
#define DDS_WRITER_ENTITY_SENDER_IDL

#include "Connector/Writer_Connector.idl"

module Writer
{
  component Sender
  {
    port WriterTestConnector::DDS_Write info_write;
    attribute unsigned short rate;
    attribute unsigned short iterations;
    attribute unsigned short keys;
  };
};

#endif /* DDS_WRITER_ENTITY_SENDER_IDL */
