// $Id$

#ifndef FDP_BAR_IDL
#define FDP_BAR_IDL

#include <Components.idl>

#include "FDP_Foo.idl"

module One
{
  interface Bar_Port
  {
    void bar ();
  };
  
  interface Foo_Port;
};

module Two
{
  component Bar
  {
    provides One::Bar_Port bar;
    uses One::Foo_Port foo;
  };
};

#endif