
//=============================================================================
/**
 *  @file    test.idl
 *
 *  $Id$
 *
 * Simple IDL file to test portable interceptor support.
 *
 *
 *  @author Nanbor Wang <nanbor@cs.wustl.edu>
 */
//=============================================================================


module Test_Interceptors
{
  exception Silly
    {};

  interface Visual
  {
    // = TITLE
    //   A test idl for checking interceptor visually.
    //
    // = DESCRIPTION
    //

    void normal (in long arg);
    // Normal operation.

    void nothing ();
    // Normal operation without return.

    void user ()
      raises (Silly);
    // throws a user exception.

    void system ();
    // thows a system exception.

   oneway void shutdown ();
    // shutdown the ORB
  };
};
