// $Id$
/**
 * @file Homes.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests equivalent IDL semantics for Homes
 */

#include <Components.idl>

module ImplicitHomes
{
  component Foo
    {
    };

  home FooHome manages Foo
    {
    };
  /*
  interface test
    {
      FooHomeExplicit test_op ();
      FooHomeImplicit test_op_1 ();
      FooHome test_op_2 ();
    };
  */
};
