// $Id$

/**
 * @file NavDisplay.idl
 *
 * Definition of the navigation display component.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */

#ifndef NAVDISPLAY_IDL
#define NAVDISPLAY_IDL

#include "../Display_Base/Display_Base.idl"

module HUDisplay
{
  component NavDisplay
    {
      consumes tick Refresh;
      uses multiple position GPSLocation;
      /// The attribute can be configured via deploymentplan
      // This number must indicate the number of GPS devices
      // which are also defined in the deploymentplan.
      attribute long number_of_GPS;
    };

  home NavDisplayHome manages NavDisplay
  {
  };
};

#endif /* NAVDISPLAY_IDL */
