// $Id$
/**
 * @file include.idl
 * @author Jeff Parsons <j.parsons@vanderbilt.edu>
 *
 * Tests tool's regeneration of IDL2 constructs, which
 * should be basically unchanged.
 */

#ifndef INCLUDE_IDL
#define INCLUDE_IDL

module pre_mod
{
  typedef long longarray[3][14][7];

  exception wrong
  {
    sequence<sequence<long> > longseqseq;
    string reasons[4][2];
    wstring<3> why;
  };

  enum which
  {
    ZERO,
    ONE,
    TWO
  };
};

const pre_mod::which which_one = pre_mod::ONE;

#endif /* INCLUDE_IDL */

