// $Id$

/**
 * @file Quoter_Base.idl
 * @author William R. Otte <wotte@dre.vanderbilt.edu>
 */

#ifndef QUOTER_BASE_IDL
#define QUOTER_BASE_IDL

#pragma ndds typesupport "Base/Quoter_BaseSupport.h"
#pragma opendds typesupport "Base/Quoter_BaseTypeSupportC.h"
#pragma coredx typesupport "Base/Quoter_BaseTypeSupport.hh"

#pragma DCPS_DATA_TYPE "Quoter::Stock_Info"
#pragma DCPS_DATA_KEY "Quoter::Stock_Info symbol"

module Quoter
{
  struct Stock_Info
  {
    unsigned long low;
    unsigned long high;
    unsigned long current;
    string symbol; //@key
  };
  typedef sequence<Stock_Info> Stock_InfoSeq;
};

#endif
