// $Id$

/**
 * @file VTopic_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VTOPIC_CONNECTOR_IDL_
#define VTOPIC_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/VTopic_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/VTopic_ConnectorE.idl"

module VTopic
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopic_Seq> TestTopicConn;
  connector VTopic_Connector : TestTopicConn::DDS_Event
  {
  };
};

#endif /* VTopic_CONNECTOR_IDL_ */
