// $Id:$

#include "DAnCE/Deployment/Deployment_TargetData.idl"

module CIAO
{
  module TM_Daemon
  {

    interface Daemon
    {

      ::Deployment::Domain get_snapshot ();

      oneway void shutdown ();

    };
  };
};
