// $Id$

//==============================================================================
/// @file Hello_defn.idl
//==============================================================================

#ifndef HELLO_DEFN_IDL
#define HELLO_DEFN_IDL

module Hello
{
  exception InternalError
    {
      long id;
      string error_string;
    };
};

#endif
