// $Id$

//==============================================================================
/// @file Hello_obj.idl
//==============================================================================

#ifndef HELLO_OBJ_IDL
#define HELLO_OBJ_IDL

//#include "Hello_defn.idl"

#pragma ciao lem "Hello_objE.idl"
#pragma ciao ami4ccm interface "Hello::MyFoo"
#pragma ciao lem "Hello_objAE.idl"

module Hello
{
  exception InternalError
    {
      long id;
      string error_string;
    };

  // Sender/Receiver interface
  interface MyFoo
    {
      long foo (in string in_str, out string answer)
        raises (InternalError);
      void hello (out long answer)
        raises (InternalError);

      attribute short rw_attrib
        getraises (InternalError)
        setraises (InternalError);

      readonly attribute short ro_attrib
        raises (InternalError);
    };
};

#endif

