// $Id$

/**
 * @file HelloGoodbye.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef GOODBYE_IDL_
#define GOODBYE_IDL_

module Goodbye
{
  struct HelloGoodbye {
    string goodbye;  //@key
    long iteration;
  };
  typedef sequence<HelloGoodbye> HelloGoodbyeSeq;
};

#endif /* GOODBYE_IDL_ */
