// $Id$

/**
 * @file
 * @author Marcel Smit (msmit@remedy.nl)
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef DDS_STATE_CONNECTION_TEST_SENDER_IDL
#define DDS_STATE_CONNECTION_TEST_SENDER_IDL

#include "Connector/State_Connection_Test_Connector.idl"

module State_Connection_Test
{
  component Sender
  {
    port State_ConnectionTestConnector::DDS_Update info_update;
  };
};

#endif
