/* -*- C++ -*- */
// @(#)ttcp.idl	1.1	10/18/96


interface ttcp_sequence {

typedef sequence<char> my_sequence;

  oneway void send (in my_sequence ttcp_rec);
  oneway void send_hack (in string ttcp_string);
  oneway void start_timer ();
  oneway void stop_timer ();
};

interface ttcp_string {

  oneway void send (in string ttcp_string);
  oneway void send_hack (in string ttcp_string);
  oneway void start_timer ();
  oneway void stop_timer ();
};


