//$Id$

#ifndef RACE_SIMPLE_BIN_PACKER_IDL
#define RACE_SIMPLE_BIN_PACKER_IDL

#include <Components.idl>
#include "../Base/Planner.idl"

module CIAO
{
  module RACE
  {
    component SimpleBinPacker : Planner
    {
    };
    
    home SimpleBinPacker_Home manages SimpleBinPacker
    {
    };
  };
};

#endif /* RACE_SIMPLE_BIN_PACKER_IDL */
