// $Id$

/**
 * @file State_Connection_Test_Connector.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef KEYED_TEST_CONNECTOR_IDL_
#define KEYED_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/State_Connection_Test_Base.idl"

#pragma ciao lem "Connector/State_Connection_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/State_Connection_Test_BaseTypeSupport.idl"
#endif

module State_Connection_Test
{
  module ::CCM_DDS::Typed < ::State_ConnectionTest, ::State_ConnectionTestSeq> State_ConnectionTestConnector;
};

#endif /* State_Connection_Test_CONNECTOR_IDL_ */
