// $Id$
/// Compliant with OMG 06-04-01 Section 9.4.3.1

#if !defined (CCM_STATEIDFACTORY)
#define CCM_STATEIDFACTORY

#include <CosPersistentState.idl>

#if !defined (CCM_LW)
module Components
{
  typeprefix Components "omg.org";

  typedef short SegmentId;
  const SegmentId COMPONENT_SEGMENT = 0;

  typedef short FacetId;
  const FacetId COMPONENT_FACET = 0;

  typedef sequence<octet> IdData;
  typedef CosPersistentState::Pid PersistentId;

  exception InvalidStateIdData {};

  typedef short StateIdType;
  const StateIdType PERSISTENT_ID = 0;

  abstract valuetype StateIdValue
  {
    StateIdType get_sid_type();
    IdData get_sid_data();
  };

  local interface StateIdFactory
  {
    StateIdValue create (in IdData data)
      raises (InvalidStateIdData);
  };

  valuetype PersistentIdValue : StateIdValue
  {
    private PersistentId pid;
    PersistentId get_pid();
    factory init (in PersistentId pid);
  };

  valuetype SegmentDescr
  {
    private StateIdValue sid;
    private SegmentId seg;

    StateIdValue get_sid();
    SegmentId get_seg_id();
    factory init (in StateIdValue sid,
                  in SegmentId seg);
  };

  typedef sequence<SegmentDescr> SegmentDescrSeq;

};
#endif

#endif /* CCM_STATEIDFACTORY */
