// -*- IDL -*-
//
// $Id$

#ifndef HTIOP_IDL
#define HTIOP_IDL

// This is a OMG specified IDL. When HTIOP modules start getting
// complicated we may want to have them here.
#pragma prefix "omg.org"


module HTIOP
{
  struct ListenPoint
  {
    string host;
    unsigned short _port;
    string htid;
  };

  typedef sequence<ListenPoint> ListenPointList;

  struct BiDirHTIOPServiceContext
  {
    ListenPointList listen_points;
  };
};

#endif  /* TAO_IIOP_PIDL */
