// $Id$

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "Hello_MyFoo_obj.idl"

module Hello
{
  component Receiver_comp
  {
    /// Provides
    provides MyFoo_obj do_my_foo;
  };
};
#endif
