// $Id$

#ifndef HELLO_IDL
#define HELLO_IDL

#pragma ciao lem "HelloE.idl"
#pragma ciao ami4ccm interface "Hello::MyFoo"
#pragma ciao ami4ccm interface "Hello::MyDerived"
#pragma ciao ami4ccm interface "Hello::MyBar"
#pragma ciao ami4ccm interface "Foo::MyFoo"
#pragma ciao ami4ccm interface "Foo::MyBar"

module Hello
{
  exception InternalError
    {
      long id;
      string error_string;
    };

  interface MyFoo
    {
      long foo_return (in string in_str, out string answer)
        raises (InternalError);
      void foo_no_return (in string in_str, out string answer)
        raises (InternalError);
      void hello (out long answer)
        raises (InternalError);
      void no_answer (in string in_str)
        raises (InternalError);
      attribute short rw_attrib
        getraises (InternalError)
        setraises (InternalError);

      readonly attribute short ro_attrib
        raises (InternalError);
    };

  interface MyDerived : MyFoo
    {
      long do_someting (in string str);
      attribute long my_attribute;
    };

  interface MyBar : MyDerived
    {
      double bar_return (in string in_str, in string answer)
        raises (InternalError);
      void bye (out long answer, out double db)
        raises (InternalError);
      attribute short rw_bar_attrib
        getraises (InternalError)
        setraises (InternalError);
      readonly attribute short ro_bar_attrib
        raises (InternalError);
    };
};

module Foo
{
  struct TestTopic 
    {
      string key;
      long x;
    };

  interface MyFoo
    {
      long myop (in TestTopic topic);
    };

  interface MyBar : MyFoo
    {
      TestTopic mybarop (in string str, in long lg, out double db);
    };
};

#endif
