// $Id$

#ifndef SHAPES_CONN_IDL_
#define SHAPES_CONN_IDL_

#include  <Components.idl>
#include "Shapes_msg.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Shapes_connE.idl"

module Shapes
{
  typedef sequence<ShapeType> ShapeTypeSeq;
  module ::CCM_DDS::Typed < ::ShapeType, ShapeTypeSeq> ShapesConnector;
};

#endif /* SHAPES_CONN_IDL_ */


