//$Id$

#ifndef SENDER_IDL
#define SENDER_IDL


#include "../Hello_Base/Hello_Base.idl"
#include "tao/StringSeq.pidl"

module Hello
{
  /* This is a Sender specific interface which will be used to get the
   * process start.
   */

  interface trigger
  {
    void start ();
  };

  enum COLOR_SELECTION
    {
      empty,
      white,
      red,
      yellow
    };
    
  typedef sequence<COLOR_SELECTION> COLORS;

  component Sender supports trigger
  {
    provides ReadMessage push_message;
    publishes TimeOut click_out;

    attribute string local_message;
    
    // A test attribute to test setting attributes through XML
    attribute COLOR_SELECTION color;
    
    // Testing attributes of sequence type.
    attribute COLORS the_colors;
    attribute CORBA::StringSeq str_seq;
  };

  home SenderHome manages Sender
  {
  };
};
#endif /*SENDER_IDL*/
