// $Id$

/**
 * @file VT_String_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VT_STRING_CONNECTOR_IDL_
#define VT_STRING_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/VTopic_Base.idl"

#pragma ciao lem "Conn_String/VT_String_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/VTopic_BaseTypeSupport.idl"
#endif

module VTopic
{
  module ::CCM_DDS::Typed < ::TopicString, ::TopicStringSeq> TopicStringConnector;
};

#endif /* VTopic_CONNECTOR_IDL_ */
