//
// $Id$
//

interface test
{
  typedef sequence<octet> data;
  oneway void method (in unsigned long request_number,
                      in data d,
                      in unsigned long work);

  oneway void shutdown ();
};
