// $Id$

#ifndef DIFFDIR_CONNECTOR_IDL
#define DIFFDIR_CONNECTOR_IDL

#include <Components.idl>
#include <ccm_dds.idl>

#include "DiffDir.idl"

#pragma ciao lem "DiffDir_ConnectorE.idl"

module ::CCM_DDS::Typed < ::DiffDirType, ::DiffDirTypeSeq> DiffDirConnector;

#endif
