// $Id$

#ifndef DIFFDIR_IDL
#define DIFFDIR_IDL

#pragma ndds typesupport "DiffDirSupport.h"
#pragma opendds typesupport "DiffDirTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "DiffDirType"
#pragma DCPS_DATA_KEY "DiffDirType value"

struct DiffDirType {
  string value; //@key
};

typedef sequence<DiffDirType> DiffDirTypeSeq;

#endif
