// $Id$

/**
 * @file HomeT_Connector.idl
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef HOMET_CONNECTOR_IDL_
#define HOMET_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/HomeT_Base.idl"

#pragma ciao lem "Connector/HomeT_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/HomeT_BaseTypeSupport.idl"
#endif

module ::CCM_DDS::Typed < ::HomeTest, ::HomeTestSeq> ConnComp;

#endif /* HOMET_CONNECTOR_IDL_ */


