// $Id$

/**
 * @file LatencyTT_Test_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef LATENCYTT_TEST_BASE_IDL
#define LATENCYTT_TEST_BASE_IDL

#pragma ndds typesupport "Base/LatencyTT_Test_BaseSupport.h"
#pragma opendds typesupport "Base/LatencyTT_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "LatencyTTTest"

const short MAX_DATA_SEQUENCE_LENGTH = 8192;

typedef sequence<octet, MAX_DATA_SEQUENCE_LENGTH> BD_oct_seq;

struct LatencyTTTest {
  long seq_num;
  BD_oct_seq data;
 };

typedef sequence<LatencyTTTest> LatencyTTTestSeq;

#endif
