//$Id$
#include "../BasicSP.idl"

module BasicSP
{
  component BMDisplay
    {
      consumes  DataAvailable data_ready;
      uses ReadData comp_data;
    };

  home BMDisplayHome manages BMDisplay
    {
    };
};
