#
# Makefile for building the Policies test
# 

NAME = Manipulation
  
OBJFILES = \
	$(OBJDIR)\testC.obj \
	$(OBJDIR)\testS.obj \
	$(OBJDIR)\Manipulation.obj
  
CPPDIR = .;..

IDLDIR = .
  
!include <$(ACE_ROOT)\include\makeinclude\build_example.bor>
  
# 
# IDL Build rules
# 
  
$(IDLDIR)\testC.cpp $(IDLDIR)\testS.cpp: $(IDLDIR)\test.idl
	$(TAO_IDL) $**



