// $Id$

#ifndef SHAPES_SENDER_COMP_IDL_
#define SHAPES_SENDER_COMP_IDL_

#include "Shapes_ShapeType_conn.idl"
#include "Shapes_Control_obj.idl"

component Sender_comp
{
  port ShapeType_conn::DDS_Write info_write;

  provides Control_obj control;
};

#endif /* SHAPES_SENDER_COMP_IDL_ */
