// $Id$

#include "dance/Deployment/Deployment_RepositoryManager.idl"

module CIAO
{
  interface RepositoryManagerDaemon : Deployment::RepositoryManager
  {
    // Shutdown the daemon process.
    oneway void shutdown ();
  };
};

