// $Id$

/**
 * @file FSS_State_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef FIXED_SIZE_STRUCT_STATE_CONNECTOR_IDL_
#define FIXED_SIZE_STRUCT_STATE_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/FSS_State_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/FSS_State_ConnectorE.idl"
#pragma ndds typesupport "Base/FSS_State_BaseSupport.h"

module FSS_State
{
  module ::CCM_DDS::Typed < ::FixedStructSizeTest, ::FixedStructSizeTestSeq> FixedStructSizeTestConnector;
};

#endif /* FSS_State_CONNECTOR_IDL_ */
