//
// $Id$
//

module ECM_IDLData
{
  // Some simple data types to show how the Events can carry its
  // payload in the octet sequence.

  struct Point {
    double x;
    double y;
  };
  typedef sequence<Point> Vector;

  struct Info {
    string mobile_name;
    double mobile_speed;
    Vector trajectory;
  };
};
