// $Id$

/**
 * @file RG_LateBinding_Connector.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef RG_LATEBINDING_CONNECTOR_IDL_
#define RG_LATEBINDING_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/RG_LateBinding_Base.idl"

#pragma ciao lem "Connector/RG_LateBinding_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/RG_LateBinding_BaseTypeSupport.idl"
#endif

module RG_LateBinding
{
  module ::CCM_DDS::Typed < ::RG_LateBindingTest, ::RG_LateBindingTestSeq> RG_LateBindingTestConnector;
};

#endif /* RG_LateBinding_CONNECTOR_IDL_ */
