// $Id$

/**
 * @file TwoTopics_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef TWOTOPICS_BASE_IDL
#define TWOTOPICS_BASE_IDL

#pragma ndds typesupport "Base/TwoTopics_BaseSupport.h"
#pragma opendds typesupport "Base/TwoTopics_BaseTypeSupportImpl.h"

struct HelloTopic {
  string hello; //@key
  long iteration;
};
typedef sequence<HelloTopic> HelloTopicSeq;

struct GoodbyeTopic {
  string goodbye; //@key
  long iteration;
};
typedef sequence<GoodbyeTopic> GoodbyeTopicSeq;

#endif
