// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 *
 */

#ifndef DDS_SHARED_DP_COMPONENT_IDL
#define DDS_SHARED_DP_COMPONENT_IDL

#include "Connector/Connector.idl"

module SharedDP
{
  component SharedDPComponent
  {
    port CCM_DDS::SharedDPTest::DDS_Write write1;
    port CCM_DDS::SharedDPTest::DDS_Write write2;
    port CCM_DDS::SharedDPTest::DDS_Write write3;
    port CCM_DDS::SharedDPTest::DDS_Write write4;

    attribute boolean perform_test;
  };
};

#endif
