// $Id$

/**
 * @file
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/SL_ManyByMany_Connector.idl"

module SL_ManyByMany
{
  component Receiver
  {
    port SLManyByManyConnector::DDS_StateListen info_out;
  };
};

#endif
