// $Id$

/**
 * @file 
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/SL_ManyByMany_Connector.idl"
#include "Connector/SL_ManyByMany_ConnectorE.idl"


module SL_ManyByMany
{
  component Receiver
  {
    port CCM_DDS::TestTopic::DDS_StateListen info_out; 
  };
};


#endif
