// $Id$

/**
 * @file NonChangeable_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef NONCHANGEABLE_BASE_IDL
#define NONCHANGEABLE_BASE_IDL

#pragma ndds typesupport "Base/NonChangeable_BaseSupport.h"
#pragma opendds typesupport "Base/NonChangeable_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "NonChangeableTest"

struct NonChangeableTest {
  string key;
  long iteration;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<NonChangeableTest> NonChangeableTestSeq;
#endif

#endif
