// $Id$

/**
 * @file Updater_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef UPDATER_CONNECTOR_IDL_
#define UPDATER_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/Updater_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

TYPED_MODULE( ::TestTopic, ::TestTopic_Seq, TestTopic)

module Updater
{
  connector Updater_Connector : ::CCM_DDS::TestTopic::DDS_State
  {
  };
};

#endif /* UPDATER_CONNECTOR_IDL_ */
