//$Id$
#ifndef RACE_PLAN_ANALYZER_IDL
#define RACE_PLAN_ANALYZER_IDL

#include <Components.idl>
#include "../Interface/PlanIngress.idl"
#include "../../Planner_Manager/Interface/Planner_Manager_I.idl"

module CIAO
{
  
  module RACE
  {
    component Plan_Analyzer
    {
      provides PlanIngress plan_ingress;
      uses Planner_Manager_I planner_manager_i;

      readonly attribute RACE_Classifications classes;

      // provides PlannerInfo pinfo;
      // uses multiple Analyzer plugins;
    };

    home Plan_Analyzer_Home manages Plan_Analyzer
    {
    };
  };
};


#endif /* RACE_PLAN_ANALYZER_IDL */
