// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/QueryFilter_Test_Connector.idl"
#include "Base/QueryFilter_Starter.idl"

module QueryFilter_Test
{
  component Receiver
  {
    port QueryConditionTestConnector::DDS_Get get_port;

    provides QueryFilterStarter reader_start;
    uses QueryFilterRestarter writer_restart;
  };
};

#endif
