// $Id$

/**
 * @file Quoter_Connector.idl
 * @author William R. Otte <wotte@dre.vanderbilt.edu>
 */

#ifndef QUOTER_CONNECTOR_IDL_
#define QUOTER_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/Quoter_Base.idl"

#pragma ciao lem "Connector/Quoter_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/Quoter_BaseTypeSupport.idl"
#endif

module ::CCM_DDS::Typed < ::Quoter::Stock_Info, ::Quoter::Stock_InfoSeq> Quoter;

#endif /* QUOTER_CONNECTOR_IDL_ */
