// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    included.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has 
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

#ifndef IDL_TEST_INCLUDED_IDL
#define IDL_TEST_INCLUDED_IDL

// Included in IDL file 'including.idl'.
module Aok 
{
  typedef sequence<double> Seq1Type;
  typedef long Me;
};

enum Agog
{
  Agog1, 
  Agog2, 
  Agog3
};

#endif /* IDL_TEST_INCLUDED_IDL */
