// $Id$

/**
 * @file 
 * @author 
 */

#ifndef CONNECTORSTATUSLISTENER_TEST_BASE_IDL
#define CONNECTORSTATUSLISTENER_TEST_BASE_IDL


  struct TestTopic {
    string key; //@key
    long x;
   };


typedef sequence<TestTopic> TestTopic_Seq;

struct TestSecondTopic {
    string key; //@key
    long x;
    long y;
   };


typedef sequence<TestSecondTopic> TestSecondTopic_Seq;
#endif
