// $Id$

/**
 * @file UL_ResetTopic_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef UL_RESETTOPIC_BASE_IDL
#define UL_RESETTOPIC_BASE_IDL

#pragma ndds typesupport "Base/UL_ResetTopic_BaseSupport.h"
#pragma opendds typesupport "Base/UL_ResetTopic_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "UL_ResetTopicTest"
#pragma DCPS_DATA_KEY "UL_ResetTopicTest key"

struct UL_ResetTopicTest {
  string key; //@key
  long iteration;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<UL_ResetTopicTest> UL_ResetTopicTestSeq;
#endif

#endif
