// $Id$

#ifndef SIMPLE_PUBLISHER_IDL
#define SIMPLE_PUBLISHER_IDL

#include "SimpleCommon.idl"
#include "Components.idl"

module Simple
{
  component SimplePublisher
  {
    publishes Hello hello_;
  };

  home SimplePublisherHome manages SimplePublisher
  {
  };
};

#endif /*SIMPLE_PUBLISHER_IDL*/
