// -*- IDL -*-

// $Id$

// Included for compatibility with the CORBA 2 specification.

#ifndef TAO_ORB_IDL
#define TAO_ORB_IDL

#include <Policy.pidl>
#include <Services.pidl>

#pragma prefix "omg.org"

module CORBA
{
  enum TCKind
  {
    tk_null,
    tk_void,
    tk_short,
    tk_long,
    tk_ushort,
    tk_ulong,
    tk_float,
    tk_double,
    tk_boolean,
    tk_char,
    tk_octet,
    tk_any,
    tk_TypeCode,
    tk_Principal,
    tk_objref,
    tk_struct,
    tk_union,
    tk_enum,
    tk_string,
    tk_sequence,
    tk_array,
    tk_alias,
    tk_except,
    tk_longlong,
    tk_ulonglong,
    tk_longdouble,
    tk_wchar,
    tk_wstring,
    tk_fixed,
    tk_value,
    tk_value_box,
    tk_native,
    tk_abstract_interface,
    tk_local_interface,
    tk_component,
    tk_home
  };

  typedef string  ORBid;
  typedef unsigned long Flags;
  typedef string Identifier;
  typedef string RepositoryId;

  struct NamedValue
  {
    Identifier name;
    any argument;
    long len;
    Flags arg_modes;
  };

  enum exception_type
  {
    NO_EXCEPTION,
    USER_EXCEPTION,
    SYSTEM_EXCEPTION
  };

  enum ParameterMode
  {
    PARAM_IN,
    PARAM_OUT,
    PARAM_INOUT
  };

  typedef short ValueModifier;
  const ValueModifier VM_NONE = 0;
  const ValueModifier VM_CUSTOM = 1;
  const ValueModifier VM_ABSTRACT = 2;
  const ValueModifier VM_TRUNCATABLE = 3;

  typedef short Visibility;
  const Visibility PRIVATE_MEMBER = 0;
  const Visibility PUBLIC_MEMBER = 1;

  typedef string ObjectId;
  typedef sequence <ObjectId> ObjectIdList;

  // Portable Interceptor specification adds these types.
  typedef sequence<string> StringSeq;
  typedef sequence<wstring> WStringSeq;
  typedef sequence<octet> OctetSeq;
};

#endif /* TAO_ORB_IDL */
