// -*- IDL -*-

// Included for compatibility with the CORBA 2 specification.

#ifndef TAO_ORB_IDL
#define TAO_ORB_IDL

///FUZZ: disable check_for_include/
#include "BooleanSeq.pidl"
#include "CharSeq.pidl"
#include "DoubleSeq.pidl"
#include "FloatSeq.pidl"
#include "LongDoubleSeq.pidl"
#include "LongSeq.pidl"
#include "OctetSeq.pidl"
#include "ShortSeq.pidl"
#include "StringSeq.pidl"
#include "ULongSeq.pidl"
#include "UShortSeq.pidl"
#include "WCharSeq.pidl"
#include "WStringSeq.pidl"
#include "LongLongSeq.pidl"
#include "ULongLongSeq.pidl"

#include "Policy.pidl"
#include "Policy_Manager.pidl"
#include "Policy_Current.pidl"
#include "Services.pidl"
#include "ParameterMode.pidl"
#include "orb_types.pidl"
#include "Typecode_types.pidl"
#include "WrongTransaction.pidl"

#pragma prefix "omg.org"

module CORBA
{
  struct NamedValue
  {
    Identifier name;
    any argument;
    long len;
    Flags arg_modes;
  };

  enum exception_type
  {
    NO_EXCEPTION,
    USER_EXCEPTION,
    SYSTEM_EXCEPTION
  };

  native ValueFactory;
};

#endif /* TAO_ORB_IDL */
