// $Id$

/**
 * @file State_Connection_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef STATE_CONNECTION_TEST_BASE_IDL
#define STATE_CONNECTION_TEST_BASE_IDL

#pragma rti typesupport "Base/State_Connection_Test_BaseSupport.h"

struct State_ConnectionTest {
  string key; //@key
  long iteration;
};

typedef sequence<State_ConnectionTest> State_ConnectionTest_Seq;

#endif
