// $Id$

/**
 * @file UCC_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef USERDATA_COPY_COUNT_TEST_CONNECTOR_IDL_
#define USERDATA_COPY_COUNT_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/UCC_Test_Base.idl"

#pragma ciao lem "Connector/UCC_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/UCC_Test_BaseTypeSupport.idl"
#endif

module UCCVariableSizedStruct_Test
{
  module ::CCM_DDS::Typed < ::UCCVariableSizedStructTest, ::UCCVariableSizedStructTestSeq> UCCVariableSizedStructTestConnector;
};

module UCCFixedSizeStruct_Test
{
  module ::CCM_DDS::Typed < ::UCCFixedSizedStructTest, ::UCCFixedSizedStructTestSeq> UCCFixedSizedStructTestConnector;
};

#endif /* USERDATA_COPY_COUNT_TEST_CONNECTOR_IDL_ */
