// $Id$

/**
 * @file QCLE_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef QUERY_CONDITION_LISTEN_EVENT_TEST_CONNECTOR_IDL_
#define QUERY_CONDITION_LISTEN_EVENT_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/QCLE_Test_Base.idl"

#pragma ciao lem "Connector/QCLE_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/QCLE_Test_BaseTypeSupport.idl"
#endif

module QCLE_Test
{
  module ::CCM_DDS::Typed < ::QueryConditionListenEventTest, ::QueryConditionListenEventTestSeq> QueryConditionListenEventTestConnector;
};

#endif /* QCLE_Test_CONNECTOR_IDL_ */
