#
# Makefile for building the NT_Service ace examples
#

NAME = NT_Service

OBJFILES = \
        $(OBJDIR)\main.obj \
        $(OBJDIR)\ntsvc.obj

CFLAGS = \
        $(ACE_CFLAGS)

LIBFILES = \
        $(ACE_LIB)

CPPDIR = .

!include <$(ACE_ROOT)\include\makeinclude\build_exe.bor>
