// $Id$

/**
 * @file GPS.idl
 *
 * Definition of the GPS component.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */
#ifndef GPS_IDL
#define GPS_IDL

#include "../Display_Base/Display_Base.idl"

module HUDisplay
{
  component GPS
    {
      provides position MyLocation;
      publishes tick Ready;
      consumes tick Refresh;
      /// The attribute can be configured via the deploymentplan
      attribute unsigned short id;
    };

  home GPSHome manages GPS
  {
  };
};

#endif /* GPS_IDL */
