// $Id$

#ifndef SIMPLE_CONSUMER_IDL
#define SIMPLE_CONSUMER_IDL

#include "SimpleCommon.idl"
#include <Components.idl>

module Simple
{
  component SimpleConsumer
  {
#if !defined (CCM_NOEVENT)
    consumes Hello hello_;
#endif
  };

  home SimpleConsumerHome manages SimpleConsumer
  {
  };
};

#endif /*SIMPLE_CONSUMER_IDL*/
