// $Id$

#ifndef SIMPLE_PROVIDER_IDL
#define SIMPLE_PROVIDER_IDL

#include "SimpleCommon.idl"
#include "Components.idl"

module Simple
{
  component SimpleLocalProvider
  {
    provides LocalTrigger trig;
  };

  home SimpleLocalProviderHome manages SimpleLocalProvider
  {
  };
};

#endif /*SIMPLE_PROVIDER_IDL*/
