// $Id$

#ifndef SHAPES_CONTROL_COMP_IDL_
#define SHAPES_CONTROL_COMP_IDL_

#include "Shapes_Control_obj.idl"

#include <Components.idl>

component Control_comp
{
  uses Control_obj control;

  attribute unsigned long rate;
  attribute unsigned short max_x;
  attribute unsigned short max_y;
  attribute unsigned short max_size;
  attribute boolean resize_shape;
};

#endif /* SHAPES_CONTROL_COMP_IDL_ */
