// $Id$
/// Compliant with OMG 06-04-01 Section 8.3.2

#if !defined (CCM_EXECUTORLOCATOR_IDL)
#define CCM_EXECUTORLOCATOR_IDL

#include "ccm/CCM_EnterpriseComponent.idl"
#include "ccm/CCM_CCMException.idl"
#include "ccm/CCM_Object.idl"

// *************** Extended Container Interfaces ***************

#if !defined (CCM_LW)

module Components
{
  typeprefix Components "omg.org";

  local interface ExecutorLocator : EnterpriseComponent
  {
    Object obtain_executor (in string name)
      raises (CCMException);

    void release_executor (in Object exc)
      raises (CCMException);

    void configuration_complete()
      raises (InvalidConfiguration);
  };
};
#endif

#endif /* CCM_EXECUTORLOCATOR_IDL */
