// $Id$

/**
 * @file Distributor.idl
 * @author William R. Otte <wotte@dre.vanderbilt.edu>
 *
 * by-hand idl3 translation of distributor components.
 */

#ifndef DDS_DISTRIBUTOR_IDL
#define DDS_DISTRIBUTOR_IDL

#include "Connector/Quoter_Connector.idl"

module Quoter
{
  interface Trigger
  {
    void add_stock (in string stock);
    void del_stock (in string stock);
    void start ();
    void stop ();
  };

  component Distributor supports Trigger
  {
    port Quoter::DDS_Write info_in;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
    attribute unsigned long rate;
  };
};

#endif

