// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef DDS_CONNECTORSTATUSLISTENER_TEST_SENDER_IDL
#define DDS_CONNECTORSTATUSLISTENER_TEST_SENDER_IDL

#include "Connector/ConnectorStatusListener_Test_Connector.idl"
#include "SecConnector/ConnectorStatusListener_TestSec_Connector.idl"

module ConnectorStatusListener_Test
{
  component Sender
  {
    port CCM_DDS::TestSecondTopic::DDS_Write topic_write;
    provides CCM_DDS::ConnectorStatusListener connector_status;
  };
};

#endif
