// $Id$
/// Compliant with OMG 06-04-01 Section 9.4.1.3

#if !defined (CCM_PROXYHOMEREGISTRATION_IDL)
#define CCM_PROXYHOMEREGISTRATION_IDL

#include "ccm/CCM_HomeRegistration.idl"

#if !defined (CCM_LW)

module Components
{
  typeprefix Components "omg.org";

  exception UnknownActualHome {};
  exception ProxyHomeNotSupported {};

  local interface ProxyHomeRegistration : HomeRegistration
  {
    void register_proxy_home (in CCMHome rhome,
                              in CCMHome ahome)
      raises (UnknownActualHome,
              ProxyHomeNotSupported);
  };
};

#endif

#endif /* CCM_PROXYHOMEREGISTRATION_IDL */
