#
# Makefile for building the TAO obsvcs tests
# $Id$
#

DIRS = \
        AVStreams \
        Concurrency \
	FaultTolerance \
	Event \
	EC_Throughput \
	EC_Multiple \
	EC_Mcast \
	EC_Custom_Marshal \
        ior_corbaname \
        IOR_MCast \
        LoadBalancing \
        Miop \
	Property \
        Simple_Naming \
        Time \
	Trading

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
