//$Id$
module dynany_test
{
  typedef sequence<double> DoubleSequence;
  typedef sequence<long> LongSequence;
  typedef sequence<string, 3> StringSequence;

  enum COLOR
    {
      yellow,
      blue,
      black,
      grey,
      red
    };

  typedef sequence<COLOR> ColorSequence;

  struct Foo
  {
    double db;
    LongSequence long_sequence;
    StringSequence string_sequence;
    ColorSequence color_sequence;
  };

  typedef sequence<Foo> FooSequence;
};
