// $Id$

module TAO_Trader_Test
{
  
interface Remote_Output
{
};

interface Plotter : Remote_Output
{
};

interface Printer : Remote_Output
{
};

interface File_System : Remote_Output
{
};

interface PostScript_Printer : Remote_Output
{
};

typedef sequence<short> ShortSeq;
typedef sequence<unsigned short> UShortSeq;
typedef sequence<long> LongSeq;
typedef sequence<unsigned long> ULongSeq;
typedef sequence<boolean> BooleanSeq;
typedef sequence<float> FloatSeq;
typedef sequence<double> DoubleSeq;
typedef sequence<string> StringSeq;

};




