// $Id$
/**
 * @file Finder.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests the compilation of Homes with Factorys.
 */

#include <Components.idl>

module FactoryHomes
{
  exception foo_exception
    {
    };

  interface foo_interface
    {
    };

  component Foo supports foo_interface
    {
    };

  home FooHome manages Foo
    {
      factory FooFinder (in string foo, in short bar) raises (foo_exception);
    };

};
