// $Id$
/**
 * @file ICReceptacles.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests equivalent idl for receptacles.
 */
#include <Components.idl>

module EquivReceptacles
{
  interface foo_interface
    {
    };

  component Foo
    {
      uses multiple foo_interface foo_recep;
    };

  /**
  interface bar
    {
      Foo::foo_recepConnections get_seq ();
      Foo::foo_recepConnection get_struct ();
    };
   */
};
