// $Id$

#include "tao/orbconf.h"
#include "tao/Versioned_Namespace.h"

#if !defined (ETCL_MACROS)
#define ETCL_MACROS

#define ETCL_PREFERENCE_CLASS TAO_ETCL_Preference
#define ETCL_BINARY_EXPR_CLASS TAO_ETCL_Binary_Expr
#define ETCL_UNARY_EXPR_CLASS TAO_ETCL_Unary_Expr
#define ETCL_EXIST_CLASS TAO_ETCL_Exist
#define ETCL_DEFAULT_CLASS TAO_ETCL_Default
#define ETCL_EVAL_CLASS TAO_ETCL_Eval
#define ETCL_DOT_CLASS TAO_ETCL_Dot
#define ETCL_COMPONENT_CLASS TAO_ETCL_Component
#define ETCL_SPECIAL_CLASS TAO_ETCL_Special
#define ETCL_COMPONENT_ARRAY_CLASS TAO_ETCL_Component_Array
#define ETCL_COMPONENT_ASSOC_CLASS TAO_ETCL_Component_Assoc
#define ETCL_COMPONENT_POS_CLASS TAO_ETCL_Component_Pos
#define ETCL_UNION_POS_CLASS TAO_ETCL_Union_Pos
#define ETCL_UNION_VALUE_CLASS TAO_ETCL_Union_Value

#define ETCL_PARSER_EXPORT_MACRO TAO_ETCL_Parser_Export
#define BEGIN_VERSIONED_NAMESPACE_MACRO TAO_BEGIN_VERSIONED_NAMESPACE_DECL
#define END_VERSIONED_NAMESPACE_MACRO TAO_END_VERSIONED_NAMESPACE_DECL

#endif // ETCL_MACROS

