// $Id$

//==============================================================================
/// @file Hello_MyFoo_obj.idl
//==============================================================================

#ifndef HELLO_MYFOO_OBJ_IDL
#define HELLO_MYFOO_OBJ_IDL

#include "Hello_Common_defn.idl"

#pragma ciao lem "Hello_MyFoo_objE.idl"
#pragma ciao ami4ccm interface "Hello::MyFoo_obj"
#pragma ciao lem "Hello_MyFoo_objAE.idl"
//needed for 'uses multiple', not used in this example
#pragma ciao ami4ccm idl "Hello_MyFoo_objA.idl"

module Hello
{
  // Sender/Receiver interface
  interface MyFoo_obj
    {
      long foo (in string in_str, out string answer)
        raises (InternalError);
      void hello (out long answer)
        raises (InternalError);

      attribute short rw_attrib
        getraises (InternalError)
        setraises (InternalError);

      readonly attribute short ro_attrib
        raises (InternalError);
    };
};

#endif
