// $Id$
module taoimrtest
{
  module reconnectserver
  {
    interface Dummy
    {
      string getMessage ();
    };

    interface TimeSrv
    {
      long current_time ();
      oneway void shutdown ();
    };
  };
};
