// $Id$
/**
 * @file ICBasic.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests implied idl functionality of basic components.
 */

#include <Components.idl>

module Basic
{
  component Foo
    {
    };

  interface Bar
    {
      Foo test_op_1 ();
      void test_op_2 (in Foo f);
      void test_op_3 (out Foo f);
    };


};
