// $Id$

/**
 * @file OIT_Test_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef ON_INCONSISTENT_TOPIC_TEST_BASE_IDL
#define ON_INCONSISTENT_TOPIC_TEST_BASE_IDL

#pragma ndds typesupport "Base/OIT_Test_BaseSupport.h"
#pragma opendds typesupport "Base/OIT_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "OIT_Receiver_Topic"
#pragma DCPS_DATA_KEY "OIT_Receiver_Topic symbol"

struct OIT_Receiver_Topic {
  string symbol; //@key
  long x;
  long y;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<OIT_Receiver_Topic> OIT_Receiver_TopicSeq;
#endif

#pragma DCPS_DATA_TYPE "OIT_Sender_Topic"
#pragma DCPS_DATA_KEY "OIT_Sender_Topic symbol"

struct OIT_Sender_Topic {
  string symbol; //@key
  long x;
  long y;
  long z;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<OIT_Sender_Topic> OIT_Sender_TopicSeq;
#endif

#endif
