// $Id$

#ifndef ONEREPLYH_T_IDL
#define ONEREPLYH_T_IDL

#pragma ciao lem "Base/OneReplyHE.idl"
#pragma ciao ami4ccm interface "OneReplyH::MyFoo"
#pragma ciao lem "Base/OneReplyHAE.idl"
#pragma ciao ami4ccm idl "Base/OneReplyHA.idl"

module OneReplyH
{

  const short cmd_synch_foo_ok = 1;
  const short cmd_synch_foo_nok = 2;
  const short cmd_asynch_foo_ok = 3;
  const short cmd_asynch_foo_nok = 4;
  const short cmd_synch_bar_ok = 5;
  const short cmd_synch_bar_nok = 6;
  const short cmd_asynch_bar_ok = 7;
  const short cmd_asynch_bar_nok = 8;

  exception InternalError
    {
      long id;
      string error_string;
    };

  // Sender/Receiver interface
  interface MyFoo
    {
      long foo (in string in_str, in long cmd, out string answer)
        raises (InternalError);
      void bar (in string in_str, in long cmd, out string answer, out long l_cmd)
        raises (InternalError);
    };
};

#endif
