//
// $Id$
//

/// A simple module to avoid namespace pollution
module Test
{

  exception InvalidTimestamp {};
  exception ServerOverload {};

  /// Use a timestamp to measure the roundtrip delay
  typedef unsigned long long Timestamp;

  valuetype Red_Herring
  {
    Timestamp test_method (in Timestamp send_time)
      raises (InvalidTimestamp, ServerOverload);
  };

  /// Measure roundtrip Delay
  interface Roundtrip
  {
    Timestamp test_method (in Timestamp send_time)
      raises (InvalidTimestamp, ServerOverload);

    oneway void shutdown ();
  };

};
