module M1 {

  struct S1 {
    octet o;
  };

  local interface LI {
    void op(in S1 s);
  };

  struct X {
    string valString;
    S1 valStruct;
    LI valLocalIface;
  };

  valuetype V {
    public string valString;
    public S1 valStruct;
    public LI valLocalIface;
  };
};

module M2 {
  module M3 {
    struct S2 {
      octet o;
    };

    local interface L2 {
      void op(in S2 s);
    };

    exception E1 {};

    local interface L3 {
      void op(in S2 s) raises (E1);
    };

    valuetype V2 {
      public string valString;
      public S2 valStruct;
      public L2 valLocalIface;
      public L3 valLocalIface3;
    };
    valuetype V3 {
      public string valString;
      public M1::S1 valStruct;
      public M1::LI valLocalIface;
    };
  };
};
