/* -*- C++ -*- */
// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/orbsvcs/examples/PSS
//
// = AUTHOR
//     Priyanka Gontla <gontla_p@ociweb.com>
//
// ============================================================================

#ifndef TAO_SERVER_IDL
#define TAO_SERVER_IDL

#pragma prefix "omg.org"

module Simple_Server
{
  interface Server
  {
    string get_status ();
  };

};

#endif /* TAO_SERVER_IDL */
