// $Id$

/**
 * @file GPSEI.idl
 *
 * Definition of the GPS component implementation.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */

#ifndef GPSEI_IDL
#define GPSEI_IDL

#include "GPSE.idl"

module HUDisplay
{
  /**
   * @interface GPS_Exec
   *
   * The actually GPS executor inherits from both CCM_GPS and
   * CCM_position interfaces as a monolithic implementation.
   */
  local interface GPS_Exec :
    CCM_GPS,
    CCM_position,
    Components::SessionComponent
  {
  };

};

#endif /* GPSEI_IDL */
