// -*- IDL -*-
//$Id$
#include "tao/PortableInterceptor.pidl"

module ForwardRequestTest
{

  interface test
  {
    /// Return the number assigned to the current object.  For
    /// example, object one will return "1," and object two will
    /// return "2."
    short number ();

    oneway void shutdown ();
  };

  local interface ServerRequestInterceptor
    : PortableInterceptor::ServerRequestInterceptor
  {

    /// Set the references to which requests will be forwarded.
    void forward_references (in Object obj1,
                             in Object obj2);

  };

};
