// $Id$

#include <Components.idl>
#include "../common/Protocols.idl"

module Protocols
{
  interface Sender_Controller
  {
    enum Test_Type
      {
        PACED,
        THROUGHPUT,
        LATENCY
      };

    void start (in unsigned long iterations,
                in unsigned long invocation_rate,
                in boolean count_missed_end_deadlines,
                in boolean do_dump_history,
                in boolean print_missed_invocations,
                in unsigned long message_size,
                in unsigned long test_protocol_tag,
                in boolean print_statistics,
                in unsigned long number_of_connection_attempts,
                in boolean enable_diffserv_code_points,
                in short priority,
                in Test_Type testtype);

    void shutdown ();
  };

  component Sender supports Sender_Controller
  {
    uses test reader;
  };

  home SenderHome manages Sender
  {
  };
};
