//LocationUpdater.idl,v 1.1 spaunov Exp
//Author: Stoyan Paunov
//$Id$

#ifndef RACE_LOCATION_UPDATING_INPUT_ADAPTER_IDL
#define RACE_LOCATION_UPDATING_INPUT_ADAPTER_IDL

#include <Components.idl>
#include "Input_Adapters/Base/Input_Adapter.idl"
#include "common/RACE_common.idl"

module CIAO
{
  module RACE
  {
    eventtype Deploy_Input
    {
      public string plan_uri;
      public string package_uri;
      public Action command;
    };

    component LocationUpdater : Input_Adapter
    {
      consumes Deploy_Input deployment;
    };

    home LocationUpdater_Home manages LocationUpdater
    {
    };
  };
};

#endif /* RACE_LOCATION_UPDATING_INPUT_ADAPTER_IDL */
