// $Id$

/**
 * @file ReadGet_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef QUERY_CONDITION_TEST_CONNECTOR_IDL_
#define QUERY_CONDITION_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/ReadGet_Test_Base.idl"

#pragma ciao lem "Connector/ReadGet_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/ReadGet_Test_BaseTypeSupport.idl"
#endif

module ReadGet_Test
{
  module ::CCM_DDS::Typed < ::QueryConditionTest, ::QueryConditionTestSeq> QueryConditionTestConnector;
};

#endif /* QUERY_CONDITION_TEST_CONNECTOR_IDL_ */
