../../ACE_wrappers/bin/m[p,w]c.pl          usr/lib/ace/bin
../../ACE_wrappers/bin/MakeProjectCreator  usr/lib/ace/bin
../../ACE_wrappers/MPC/config              usr/lib/ace/MPC
../../ACE_wrappers/MPC/modules             usr/lib/ace/MPC
../../ACE_wrappers/MPC/templates           usr/lib/ace/MPC
../../ACE_wrappers/MPC/*.pl                usr/lib/ace/MPC
../../ACE_wrappers/MPC/ChangeLog           usr/lib/ace/MPC
../../ACE_wrappers/bin/PerlACE/*.pm        usr/lib/ace/bin/PerlACE
