// -*- C++ -*-
// $Id$

// Definition for Win32 Export directives
// ---------------------------------------------

#ifndef _EFFECTOR_MAIN_STUB_EXPORT_H_
#define _EFFECTOR_MAIN_STUB_EXPORT_H_

#include "ace/config-all.h"

#if !defined (EFFECTOR_MAIN_STUB_HAS_DLL)
#  define EFFECTOR_MAIN_STUB_HAS_DLL 1
#endif /* !EFFECTOR_MAIN_STUB_HAS_DLL */

#if defined (EFFECTOR_MAIN_STUB_HAS_DLL) && (EFFECTOR_MAIN_STUB_HAS_DLL == 1)
#  if defined (EFFECTOR_MAIN_STUB_BUILD_DLL)
#    define EFFECTOR_MAIN_STUB_Export ACE_Proper_Export_Flag
#    define EFFECTOR_MAIN_STUB_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define EFFECTOR_MAIN_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else  /* EFFECTOR_MAIN_STUB_BUILD_DLL */
#    define EFFECTOR_MAIN_STUB_Export ACE_Proper_Import_Flag
#    define EFFECTOR_MAIN_STUB_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define EFFECTOR_MAIN_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* EFFECTOR_MAIN_STUB_BUILD_DLL */
#else  /* EFFECTOR_MAIN_STUB_HAS_DLL == 1 */
#  define EFFECTOR_MAIN_STUB_Export
#  define EFFECTOR_MAIN_STUB_SINGLETON_DECLARATION(T)
#  define EFFECTOR_MAIN_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* EFFECTOR_MAIN_STUB_HAS_DLL == 1 */

// Set EFFECTOR_MAIN_STUB_NTRACE = 0 to turn on library specific 
// tracing even if tracing is turned off for ACE.

#if !defined (EFFECTOR_MAIN_STUB_NTRACE)
#  if (ACE_NTRACE == 1)
#    define EFFECTOR_MAIN_STUB_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define EFFECTOR_MAIN_STUB_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !EFFECTOR_MAIN_STUB_NTRACE */

#if (EFFECTOR_MAIN_STUB_NTRACE == 1)
#  define EFFECTOR_MAIN_STUB_TRACE(X)
#else /* (EFFECTOR_MAIN_STUB_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define EFFECTOR_MAIN_STUB_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (EFFECTOR_MAIN_STUB_NTRACE == 1) */

#endif /* EFFECTOR_MAIN_STUB_EXPORT_H_ */
