// $Id$

/**
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef DDS_PSL_DEADLINETEST_SENDER_IDL
#define DDS_PSL_DEADLINETEST_SENDER_IDL

#include "Connector/PSL_DeadlineTest_Connector.idl"

module PSL_DeadlineTest
{
  component Sender
  {
     port PSLDeadlineConnector::DDS_Write test_topic_write;
     provides CCM_DDS::ConnectorStatusListener test_topic_connector_status;

  };
};

#endif
