// $Id$

/**
 * @file NonChangeable_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef NONCHANGEABLE_BASE_IDL
#define NONCHANGEABLE_BASE_IDL

struct NonChangeableTest {
  string key;
  long iteration;
};

typedef sequence<NonChangeableTest> NonChangeableTest_Seq;

#endif
