// $Id$

/**
 * @file Worker.idl
 *
 * Definition of a Worker component that does some work.  This work
 * can be either compute-bound or I/O-bound.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */

#ifndef WORKER_IDL
#define WORKER_IDL

#include "../Priority_Test.idl"

module Priority_Test
{
  component Worker
    {
      provides Common_Ops some_device;
    };

  home WorkerHome manages Worker
  {
  };
};

#endif /* WORKER_IDL */
