// $Id$

#ifndef PACKAGING_DATA_IDL
#define PACKAGING_DATA_IDL

#include "ciao/Deployment_Data.idl"

module Deployment
{
  struct ComponentPackageImport {
    ::CORBA::StringSeq location;
  };

  typedef sequence < ComponentPackageImport > ComponentPackageImports;

  struct SubcomponentPropertyReference {
    string propertyName;
    unsigned long instanceRef;
  };

  struct SubcomponentPortEndpoint {
    string portName;
    unsigned long instanceRef;
  };

  typedef sequence < SubcomponentPortEndpoint > SubcomponentPortEndpoints;

  typedef sequence < SubcomponentPropertyReference > SubcomponentPropertyReferences;

  struct AssemblyPropertyMapping {
    string name;
    string externalName;
    SubcomponentPropertyReferences delegatesTo;
  };

  typedef sequence < AssemblyPropertyMapping > AssemblyPropertyMappings;

#ifndef AVOID_IFR_CRASH
  struct NamedImplementationArtifact;

  typedef sequence < NamedImplementationArtifact > NamedImplementationArtifacts;
#endif /* AVOID_IFR_CRASH */

  struct ImplementationArtifactDescription {
    string label;
    string UUID;
    ::CORBA::StringSeq location;
    Properties execParameter;
    Requirements deployRequirement;
#ifndef AVOID_IFR_CRASH
    NamedImplementationArtifacts dependsOn;
#endif /* AVOID_IFR_CRASH */
    Properties infoProperty;
  };

  struct NamedImplementationArtifact {
    string name;
    ImplementationArtifactDescription referencedArtifact;
  };

  struct MonolithicImplementationDescription {
    Properties nodeExecParameter;
    Properties componentExecParameter;
#ifndef AVOID_IFR_CRASH
    NamedImplementationArtifacts primaryArtifact;
#endif /* AVOID_IFR_CRASH */
    ImplementationRequirements deployRequirement;
  };

  typedef sequence < MonolithicImplementationDescription > MonolithicImplementationDescriptions;

#ifndef AVOID_IFR_CRASH
  struct PackageConfiguration;

  typedef sequence < PackageConfiguration > PackageConfigurations;

  struct ComponentPackageDescription;

  typedef sequence < ComponentPackageDescription > ComponentPackageDescriptions;
#endif /* AVOID_IFR_CRASH */

  struct SubcomponentInstantiationDescription {
    string name;
#ifndef AVOID_IFR_CRASH
    ComponentPackageDescriptions basePackage;
    PackageConfigurations specializedConfig;
#endif /* AVOID_IFR_CRASH */
    Requirements selectRequirement;
    Properties configProperty;
    ComponentPackageReferences referencedPackage;
    ComponentPackageImports importedPackage;
  };

  typedef sequence < SubcomponentInstantiationDescription > SubcomponentInstantiationDescriptions;

  struct AssemblyConnectionDescription {
    string name;
    Requirements deployRequirement;
    ComponentExternalPortEndpoints externalEndpoint;
    SubcomponentPortEndpoints internalEndpoint;
    ExternalReferenceEndpoints externalReference;
  };

  typedef sequence < AssemblyConnectionDescription > AssemblyConnectionDescriptions;

  struct ComponentAssemblyDescription {
    SubcomponentInstantiationDescriptions instance;
    AssemblyConnectionDescriptions connection;
    AssemblyPropertyMappings externalProperty;
  };

  typedef sequence < ComponentAssemblyDescription > ComponentAssemblyDescriptions;

  struct ComponentImplementationDescription {
    string label;
    string UUID;
    ComponentInterfaceDescription implements;
    ComponentAssemblyDescriptions assemblyImpl;
    MonolithicImplementationDescriptions monolithicImpl;
    Properties configProperty;
    Capabilities capability;
    ImplementationDependencies dependsOn;
    Properties infoProperty;
  };


  struct PackagedComponentImplementation {
    string name;
    ComponentImplementationDescription referencedImplementation;
  };


  typedef sequence < PackagedComponentImplementation > PackagedComponentImplementations;

  struct ComponentPackageDescription {
    string label;
    string UUID;
    ComponentInterfaceDescription realizes;
    Properties configProperty;
    PackagedComponentImplementations implementation;
    Properties infoProperty;
  };


  struct PackageConfiguration {
    string label;
    string UUID;
#ifndef AVOID_IFR_CRASH
    PackageConfigurations specializedConfig;
    ComponentPackageDescriptions basePackage;
#endif /* AVOID_IFR_CRASH */
    ComponentPackageReferences reference;
    Requirements selectRequirement;
    Properties configProperty;
  };


};

#endif /* PACKAGING_DATA_IDL */
