// $Id$
//===========================================================
/**
 * @file RTEventServiceEI.idl
 *
 * Definition of the RTEventService component implementation.
 *
 * @author George Edwards <g.edwards@vanderbilt.edu>
 */
//===========================================================
#ifndef CIAO_RTEVENTSERVICEEI_IDL
#define CIAO_RTEVENTSERVICEEI_IDL

#include "RTEventServiceE.idl"

module BasicSP
{
  /**
   * @interface RTEventService_Exec
   */
  local interface RTEventService_Exec :
    CCM_RTEventService,
    RtecEventChannelAdmin::CCM_EventChannel,
    Components::SessionComponent
  {
  };

};

#endif /* CIAO_RTEVENTSERVICEEI_IDL */
