// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/CoherentUpdate_Test_Connector.idl"
#include "Base/Reader_Starter.idl"

module CoherentUpdate_Test
{
  component Receiver
  {
    port CoherentUpdateTestConn::DDS_Read info_out;

    provides CoherentUpdateStarter reader_start;
    uses CoherentUpdateRestarter updater_restart;

    attribute unsigned short nr_runs;
  };
};

#endif
