// $Id$

/**
 * @file
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Throughput_Connector.idl"
#include "SecConnector/Throughput_Sec_Connector.idl"

module Throughput
{
  component Receiver
  {
    port ThroughputTestConn::DDS_Listen info_listen;
    port ThroughputCommandConn::DDS_Listen command_listen;
  };
};

#endif
