//
// $Id$

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  /// A very simple interface
  interface Simple
  {
    /// Return a simple string
    string get_string ();

  };
};

