// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Listen_Test_Connector.idl"
#include "Connector/Listen_Test_ConnectorE.idl"

#include "Base/Listen_Invoker.idl"
#include "Base/Listen_InvokerE.idl"

module Listen_Test
{
  component Receiver
  {
    port CCM_DDS::ListenTest::DDS_Listen info_listen;

    provides ListenInvoker listen_invoke;
  };
};

#endif
