// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/VTopics_Connector.idl"

module VTopics
{
  component Receiver
  {
    port TestTopicConnector::DDS_Listen info_out;
    provides CCM_DDS::ConnectorStatusListener connector_status;
   };
};

#endif
