// $Id$

/**
 *  @file Messenger.idl
 *
 *  @author Don Busch <busch_d@ociweb.com>
 */

#ifndef MESSENGER_IDL
#define MESSENGER_IDL

#include <Components.idl>
#include "Runnable.idl"
#include "Publication.idl"
#include "Message.idl"
#include "History.idl"

component Messenger { 
  attribute string subject;

  provides Runnable control;
  provides Publication content;

  publishes Message message_publisher;
  provides History message_history;
};

home MessengerHome manages Messenger {};

#endif
