// -*- IDL -*-

//=============================================================================
/**
 *  @file    StateSynchronizationAgent.idl
 *
 *  $Id$
 *
 *  @author  Friedhelm Wolf (fwolf@dre.vanderbilt.edu)
 */
//=============================================================================

#ifndef _STATE_SYNCHRONIZATION_AGENT_IDL_
#define _STATE_SYNCHRONIZATION_AGENT_IDL_

#include "ReplicatedApplication.idl"
#include "LWFTDataStructures.idl"

interface StateSynchronizationAgent 
{
  /// Triggers an serial update of the state information 
  /// to all registered replicas.
  void state_changed (in string object_id);

  /// Transfer the state of the give object_id to the agents in the replicas.
  /// Invoked by primary SSA to SSA in replica servers.
  void transfer_state (in string object_id, in any state_value);

  /// Send the state of the object_id to the other Agents.
  /// Commit it only when ReplicationManager says commit.
  /// Should be invoked only on the primary agents by the ReplicationManager.
  boolean precommit_state (in string object_id);

  /// Commit the state with the replica object_id by calling set_stae.
  /// Invoked by the ReplicationManager on the SSA in the replicas.
  void commit_state (in string object_id);

  /// Used by the ReplicationManager to update information about
  /// active replicas.
  void update_rank_list (in RankList replicas);

  /// Informs the replication manager about applications for which
  /// it is responsible for replication. 
  void register_application (in string object_id,
                             in ReplicatedApplication app);
};

#endif /* _STATE_SYNCHRONIZATION_AGENT_IDL_ */
