// $Id$

#if !defined (CCM_HOMEREGISTRATION_IDL)
#define CCM_HOMEREGISTRATION_IDL

#include "ccm/CCM_Home.idl"

#if !defined (CCM_LW)

module Components
{
  typeprefix Components "omg.org";

  local interface HomeRegistration
  {
    void register_home (in CCMHome home_ref,
                        in string home_name);

    void unregister_home (in CCMHome home_ref);
  };
};

#endif

#endif /* CCM_HOMEREGISTRATION_IDL */
