// $Id$

/**
 * @file SL_Disabled_Connector.idl
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef SL_DISABLED_CONNECTOR_IDL_
#define SL_DISABLED_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/SL_Disabled_Base.idl"

#pragma ciao lem "Connector/SL_Disabled_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/SL_Disabled_BaseTypeSupport.idl"
#endif

module SL_Disabled
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> SL_DisabledConnector;
};

#endif /* SL_Disabled_CONNECTOR_IDL_ */
