
//=============================================================================
/**
 *  $Id$
 */
//=============================================================================

#pragma prefix "parent.pragma.prefix"

interface ParentInterface {};

module ParentModule
  {
    interface ParentInterface {};
  };
