// $Id$

//IDL

#ifndef TAO_COUNTRY_IDL
#define TAO_COUNTRY_IDL

#include "orbsvcs/CosTypedEventComm.idl"

interface Country : ::CosTypedEventComm::TypedPushConsumer
{
  void update_population (in string country,
                          in long population);
};

#endif /* TAO_COUNTRY_IDL */
