// $Id$

#ifndef ONEREPLYH_T_RECEIVER_IDL
#define ONEREPLYH_T_RECEIVER_IDL

#include <Components.idl>

#include "Base/OneReplyH.idl"

module OneReplyH
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
