// $Id$

#ifndef DEPLOYMENT_APPLICATION_IDL
#define DEPLOYMENT_APPLICATION_IDL

#include "DAnCE/Deployment/Deployment_Connection.idl"
#include "DAnCE/Deployment/Deployment_StartError.idl"
#include "DAnCE/Deployment/Deployment_StopError.idl"
#include "DAnCE/Deployment/Deployment_InvalidConnection.idl"

module Deployment
{
  interface Application {
    void finishLaunch (in Connections providedReference, in boolean start)
      raises (StartError, InvalidConnection);

    void start ()
      raises (StartError);
  };

  typedef sequence < Application > Applications;
};

#endif /* DEPLOYMENT_APPLICATION_IDL */
