// $Id$
// Compliant with OMG 06-04-01 section 15

#ifndef DEPLOYMENT_APPLICATIONMANAGER_IDL
#define DEPLOYMENT_APPLICATIONMANAGER_IDL

#include "DAnCE/Deployment/Deployment.idl"
#include "DAnCE/Deployment/Deployment_InvalidProperty.idl"
#include "DAnCE/Deployment/Deployment_Application.idl"
#include "DAnCE/Deployment/Deployment_Connection.idl"
#include "DAnCE/Deployment/Deployment_ResourceNotAvailable.idl"
#include "DAnCE/Deployment/Deployment_InvalidNodeExecParameter.idl"
#include "DAnCE/Deployment/Deployment_InvalidComponentExecParameter.idl"

module Deployment {

  interface ApplicationManager {
    Application startLaunch (in Properties configProperty,
                             out Connections providedReference)
      raises (ResourceNotAvailable,
              StartError,
              InvalidProperty,
              InvalidNodeExecParameter,
              InvalidComponentExecParameter);

    void destroyApplication (in Application app)
      raises (StopError);
  };
};

#endif /* DEPLOYMENT_APPLICATIONMANAGER_IDL */
