// $Id$

#ifndef DOMAINAPPLICATIONMANAGER_IDL
#define DOMAINAPPLICATIONMANAGER_IDL

#include "Deployment/Deployment_DeploymentPlan.idl"
#include "Deployment/Deployment_ApplicationManager.idl"

module Deployment {
  interface DomainApplicationManager : ApplicationManager
   {
     Applications getApplications ();
     DeploymentPlan getPlan ();
   };

   typedef sequence < DomainApplicationManager > DomainApplicationManagers;
};

#endif /* DOMAINAPPLICATIONMANAGER_IDL */
