// $Id$

/**
 * @file CoherentUpdate_Test_Connector.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef COHERENT_UPDATE_TEST_CONNECTOR_IDL_
#define COHERENT_UPDATE_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/CoherentUpdate_Test_Base.idl"

#pragma ciao lem "Connector/CoherentUpdate_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/CoherentUpdate_Test_BaseTypeSupport.idl"
#endif

module ::CCM_DDS::Typed < ::CoherentUpdateTest, ::CoherentUpdateTestSeq> CoherentUpdate_Test;

#endif /* COHERENT_UPDATE_TEST_CONNECTOR_IDL_ */
