// $Id$

/**
 * @file Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef BASE_IDL_
#define BASE_IDL_

struct QueryConditionTest {
  string symbol; //@key
  long iteration;
};

typedef sequence<QueryConditionTest> QueryConditionTestSeq;

#endif
