// $Id$

/**
 * @file
 * @author
 */

#ifndef NONTOPIC_TEST_IDL
#define NONTOPIC_TEST_IDL

#include <Components.idl>

#pragma dds4ccm impl "NonTopic_Connector_T.h"

module Typed_NonTopic_Test_1<typename T,typename U,typename V,
                           sequence<T> TSeq, sequence<U> USeq, sequence<V> VSeq>
   {
     local interface TestControl
       {
         void create(out T dat_T, out U dat_u, out V dat_v);
       };
     connector NT
       {
         uses TestControl foo;
       };
    };

module Typed_NonTopic_Test_2<typename T,typename U,
                           sequence<T> TSeq, sequence<U> USeq>
   {
     local interface TestControl
       {
         void create(out T dat_T, out U dat_u);
       };
     connector NT_2
       {
         uses TestControl bar;
       };
    };

#endif
