// $Id$
/**
 * @file Basic.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests the compileability of basic Home types.
 */

#include <Components.idl>

module BasicHomes
{

  interface foo_interface {};

  component Foo supports foo_interface {};

  home FooHome manages Foo
    {
    };


  interface bar_interface {};

  component Bar supports bar_interface {};

  home BarHome supports foo_interface manages Bar
    {
    };

};

home SecondFooHome manages BasicHomes::Foo
{
};