// $Id$

/**
 * @file VT_Array_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VT_ARRAY_CONNECTOR_IDL_
#define VT_ARRAY_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/VTopic_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "VT_Array_ConnectorE.idl"

TYPED_MODULE( ::TopicArray, ::TopicArray_Seq, TopicArray)

module VTopic
{
  connector VT_Array_Connector : ::CCM_DDS::TopicArray::DDS_Event
  {
  };
};

#endif /* VT_ARRAY_CONNECTOR_IDL_ */
