// $Id$

/**
 * @file
 * @author Marcel Smit (msmit@remedy.nl)
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef DDS_READER_TEST_SENDER_IDL
#define DDS_READER_TEST_SENDER_IDL

#include "Connector/Reader_Test_Connector.idl"
#include "Base/Reader_Starter.idl"

module Reader_Test
{
  component Sender
  {
    port ReaderTestConnector::DDS_Write info_write;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;

    uses ReaderStarter start_reader;

    attribute unsigned short keys;
    attribute unsigned short iterations;
  };
};

#endif
