//
// $Id$
//

module Test
{
  /**
   * Callback interface used to test the behavior of the ORB under
   * crashes.
   */
  interface Crashed_Callback
  {
    /// Make sure the callback object is still in good shape
    /**
     * The server needs to verify that at least some requests worked
     * before trying to test the behavior of the ORB after a crash.
     */
    boolean are_you_there ();

    /// Force an abort() on the process implementing the callback
    /// interface
    oneway void crash_now_please ();

    /// Receive the first callback
    oneway void test_oneway ();
  };

  /**
   * Clients connect to this interface passing in a Crashed_Callback
   * object.
   * The service will then invoke all the methods on the
   * Crashed_Callback, and verify that only exceptions are raised
   * after invoking @c crash_now_please()
   *
   */
  interface Service
  {
    /// Invoke the callback object from the server
    oneway void run_test (in Crashed_Callback the_callback);
  };

};
