// $Id$

/**
 * @file VTS_Seq_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VTS_SEQ_CONNECTOR_IDL_
#define VTS_SEQ_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/VTopics_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "ConnSeq/VTS_Seq_ConnectorE.idl"

module VTopics
{
  module ::CCM_DDS::Typed < ::TopicSeq, ::TopicSeqSeq> TopicSeqConn;
  connector VTSSeq_Connector : TopicSeqConn::DDS_State
  {
  };
};

#endif /* VTS_SEQ_CONNECTOR_IDL_ */
