// $Id$

/**
 * @file VTS_Seq_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef VTS_SEQ_CONNECTOR_IDL_
#define VTS_SEQ_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/VTopics_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

TYPED_MODULE( ::TopicSeq, ::TopicSeq_Seq, TopicSeq)

module VTopics
{
  connector VTS_Seq_Connector : ::CCM_DDS::TopicSeq::DDS_Event
  {
  };
 
};



#endif /* VTS_SEQ_CONNECTOR_IDL_ */
