// $Id$

/**
 * @file VTS_Seq_Connector.idl
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef VTS_SEQ_CONNECTOR_IDL_
#define VTS_SEQ_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/VTopics_Base.idl"

#pragma ciao lem "Conn_Seq/VTS_Seq_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/VTopics_BaseTypeSupport.idl"
#endif

module VTopics
{
  module ::CCM_DDS::Typed < ::TopicSeq, ::TopicSeqSeq> TopicSeqConnector;
};

#endif /* VTS_SEQ_CONNECTOR_IDL_ */
