// $Id$

#ifndef CCM_DDS_MLT_IDL
#define CCM_DDS_MLT_IDL

#include <Components.idl>

#pragma dds4ccm impl "MultipleTemp_Connector_T.h"

#include <ccm_dds.idl>

module CCM_DDS
{
  module Duplex_Typed <typename T, sequence<T> TSeq, typename Y,  sequence <Y> YSeq> {
    alias Typed <T, TSeq> T_Typed;
    alias Typed <Y, YSeq> Y_Typed;

    connector FooConnector : CCM_DDS::DDS_Base
    {
      mirrorport T_Typed::DDS_Listen push_consumer_t;
      mirrorport Y_Typed::DDS_Listen push_consumer_y;
      mirrorport T_Typed::DDS_Update observable_t;
      mirrorport Y_Typed::DDS_Update observable_y;

      attribute string topic_name_t;
      attribute string topic_name_y;

    };
  };
};

#endif // CCM_DDS_MLT_IDL
