// $Id$

#if !defined (CCM_NAVIGATION_IDL)
#define CCM_NAVIGATION_IDL

#include "tao/orb_types.pidl"
#include "tao/StringSeq.pidl"

module Components
{
  typeprefix Components "omg.org";

  typedef string FeatureName;
  typedef sequence<FeatureName> NameList;

  valuetype PortDescription
  {
    public FeatureName name;
    public CORBA::RepositoryId type_id;
  };

  valuetype FacetDescription : PortDescription
  {
    public Object facet_ref;
  };

  typedef sequence<FacetDescription> FacetDescriptions;

  exception InvalidName {};
  interface Navigation
  {
    Object provide_facet (in FeatureName name)
      raises (InvalidName);
    FacetDescriptions get_all_facets();
    FacetDescriptions get_named_facets (in NameList names)
      raises (InvalidName);
    boolean same_component (in Object object_ref);
  };
};
#endif /* CCM_NAVIGATION_IDL */
