// $Id$

/**
 * @file
 * @author Marcel Smit (msmit@remedy.nl)
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef DDS_KEYED_TEST_SENDER_IDL
#define DDS_KEYED_TEST_SENDER_IDL

#include "Connector/Writer_Connector.idl"

module Writer
{
  component Sender
  {
    port WriterTestConnector::DDS_Write info_write;
    attribute unsigned short rate;
    attribute unsigned short iterations;
    attribute unsigned short keys;
  };
};

#endif
