// $Id$

interface Test
{
  // = TITLE
  //    A simple test interface
  //
  // = DESCRIPTION
  //    This test demostrates the smart proxy feature in TAO
  //    Note that though the interface has two methods just one
  //    of them can be "smartified" if necessary, the other one
  //    simply performs the same way as would the default proxy.

  exception Oops
    {
      string reason;
    };

  short method (in short boo) raises (Oops);

  oneway void shutdown ();
};

