// $Id$

/**
 * @file CIAO_Servers.idl
 *
 * @brief Some CIAO helper interfaces for implementing various server
 * tools.
 */

#include "CCM_Deployment.idl"

module CIAO
{
  interface Activator_Callback
  {
    ::Components::Deployment::ServerActivator
    register_component_server (in ::Components::Deployment::ComponentServer svr);
  };
};
