// $Id$

#ifndef DEPLOYMENT_IDL
#define DEPLOYMENT_IDL

#include "Deployment_Data.idl"
#include "Packaging_Data.idl"
#include "Target_Data.idl"
#include "ServerResources.idl"

module Deployment {

  exception InvalidProperty {
    string name;
    string reason;
  };

  exception NoSuchName {
  };

  exception LastConfiguration {
  };

  exception InvalidReference {
  };

  // Below exception types are CIAO specific
  exception PlanNotExist {
  };

  // CIAO specific struct type used for shared component management
  // mapping the name of component to its plan_uuid
  struct ComponentPlan
  {
    string name;
    string plan_uuid;
  };
  /**
   * @struct Sched_Params
   * @brief Carries Scheduling Params
   * @description  CIAO specific structure to carry the scheduling params
   *  to set the process, required by RACE
   */

  struct Sched_Params
  {
    long policy_;
    long priority_;
    long scope_;
    long msec_;
  };

  typedef sequence < ComponentPlan > ComponentPlans;

  typedef sequence < Application > Applications;

  interface Logger {
  };
};

#endif /* DEPLOYMENT_IDL */
