#!/bin/csh -x
#
# Usage: server <switches>
# -u : use IOR 
# -f m : output results in Mbps
# -b <sock Q size> ** not implemented **
# -OAhost <host name>  ************* must provide this for this version
# -OAthread : use threaded version as opposed to reactive
#

server -d 1 -f m -ORBhost `hostname` -ORBobjrefstyle url #-OAthread
