/*
 * $Id$
 */

typedef sequence<char> Char_Seq;
typedef sequence<octet> Octet_Seq;

interface Simple_Server
{
  oneway void sendCharSeq (in Char_Seq charSeq);
  oneway void sendOctetSeq (in Octet_Seq charSeq);

  long get_number (in long num);

  oneway void shutdown ();
};
