// $Id$

module Hello
{
  exception InternalErrorA
    {
    };
  exception InternalErrorB
    {
    };

  // Sender/Receiver interface
  interface MyFoo
    {
      attribute short rw_attrib
        getraises (InternalErrorA)
        setraises (InternalErrorB);

      attribute short rw_attribB
        getraises (InternalErrorB);

      // This should work
//      readonly attribute short ro_attrib
//        getraises (InternalErrorB);

      // Illegal, so commented out
//      readonly attribute short ro_attrib
//        setraises (InternalErrorB);
    };
};

