// $Id$

module CallMe
  {
    union YourColorBaby switch (enum ColorMe { Red, Blue })
      {
        case Red: long c_1;
        case Blue: long c_2;
      };
// Disabled, see bug_3312
/*    union YourCar switch (enum ColorMe { Green, Pink })
      {
        case Green: short c_1;
        case Pink: short c_2;
      };
*/
  };
