
//=============================================================================
/**
 *  @file    full.idl
 *
 *  $Id$
 *
 *  This file contains examples of IDL code that has
 *  caused problems in the past for the TAO IDL
 *  compiler. This test is to make sure the problems
 *  stay fixed.
 *
 *
 *  @author Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
 */
//=============================================================================


// This file, along with its companion fwd.idl, test the
// handling of forward interface declarations that are
// not defined in the same IDL file. The two files have
// mutually dependent interfaces. It is no longer necessary
// for such ILD files to include each other, as long as
// they are part of the same build.

module scope_test
{
  interface i_scope_test {};
};

module mod2
{
  interface fwd;
  interface full;

  interface fwd
  {
    attribute string attr;

    union un switch (short)
    {
      case 0: full full_mem;
    };

    typedef sequence<full> full_seq;

    exception bar {};

    full op (inout full full_arg,
             inout un un_arg,
             inout full_seq full_seq_arg)
      raises (bar);
  };

  interface full;
  interface fwd;
};

