
//=============================================================================
/**
 *  @file    gperf.idl
 *
 *  $Id$
 *
 *  This file contains examples of IDL code that has
 *  caused problems in the past for the TAO IDL
 *  compiler. This test is to make sure the problems
 *  stay fixed.
 *
 *
 *  @author Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
 */
//=============================================================================


// The examples below uncovered some bugs in gperf,
// in the form of runtime errors when clients made
// requests on some of the methods, for example

//       TAO_Perfect_Hash_Table:find failed
//       Bad operation <ackConfArchData>


enum TestEnum
{
  first,
  second,
  third
};

interface testlistitem
{
  readonly attribute string name;
};


interface test
{
  attribute string stest;
#ifndef WITHOUT_CORBA_WSTRING
  attribute wstring wstest;
#else
  attribute string wstest;
#endif
#ifndef WITHOUT_CORBA_LONGLONG
  attribute long long ltest;
#else
  attribute long ltest;
#endif
#ifndef WITHOUT_CORBA_LONGDOUBLE
  attribute long double ldtest;
#else
  attribute double ldtest;
#endif
  attribute TestEnum etest;
#ifndef WITHOUT_CORBA_WSTRING
  attribute wstring setest;
#else
  attribute string setest;
#endif
  attribute testlistitem tltest;

  testlistitem new_testlistitem (in string name);
};

interface Simple_Server
{
 oneway void ackConfBasData ();

 oneway void ackConfMosData ();
 oneway void ackConfTwmData ();
 oneway void ackConfArchData ();
 oneway void ackConfVonData ();
 oneway void ackConfFftData ();
 oneway void ackConfSosData ();
 oneway void ackConfSscData ();
 oneway void ackConfCsData ();

 oneway void ackConfR10Data ();
 oneway void ackConfR11Data ();
 oneway void ackConfR12Data ();
 oneway void ackConfR13Data ();
 oneway void ackConfR14Data ();
 oneway void ackConfR15Data ();

 oneway void shutdown ();

 oneway void transferTriggerDb ();
 oneway void transferTriggerTdc ();
};


