// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    nested_scope.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has 
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

// Tests all the problem datatypes for repeating a scope
// name after skipping one nesting level.

module skip
{
  module hump
  {
    struct skip {short s;};      
  };
};

module u_skip
{
  module u_hump
  {
    union u_skip switch (short)
    {
      case 0: short s;
    };
  };
};

module e_skip
{
  module e_hump
  {
    exception e_skip {};
  };
};

module i_skip
{
  module i_hump
  {
    interface i_skip {};
  };
};

module pre_u_skip
{
  module pre_u_hump
  {
    typedef sequence<long> pre_u_skip;
  };
};

module pre_b_skip
{
  module pre_b_hump
  {
    typedef sequence<long, 3> pre_b_skip;
  };
};

module str_u_skip
{
  module str_u_hump
  {
    typedef sequence<string> str_u_skip;
  };
};

module str_b_skip
{
  module str_b_hump
  {
    typedef sequence<string, 3> str_b_skip;
  };
};

module wstr_u_skip
{
  module wstr_u_hump
  {
    typedef sequence<wstring> wstr_u_skip;
  };
};

module wstr_b_skip
{
  module wstr_b_hump
  {
    typedef sequence<wstring, 3> wstr_b_skip;
  };
};

interface bloo {};

module obj_u_skip
{
  module obj_u_hump
  {
    typedef sequence<bloo> obj_u_skip;
  };
};

module obj_b_skip
{
  module obj_b_hump
  {
    typedef sequence<bloo> obj_b_skip;
  };
};

// This one caused several problems - in the stub declaration of
// the operation, in the skeleton body's allocation of return type,
// and in the generated code for the ancestor in _tao_QueryInterface().
module Negotiator
{ 
  interface UAV_Negotiator {};

  interface UAV_Negotiator_Factory : ::Negotiator::UAV_Negotiator
  { 
    ::Negotiator::UAV_Negotiator make_negotiator (in string bitrate_sc);
  };
};


