// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    params.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has 
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

// Compiling the generated code for the parameters of
// getDate taught us to use the ACE_NESTED_CLASS macro
// more judiciously in the header file. This file was
// also initially a problem for lookups as well.

module foo 
{
  struct date 
    {
      short year;
      short month;
      short day;
    };
  
  module bar 
    {
      struct date 
        {
          short x;
        };
              
      interface fooBar 
        {
          foo::date getDate (in foo::date a,
                             inout foo::date b,
                             out foo::date c);
        };
    };
};

