// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    params.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

// Compiling the generated code for the parameters of
// getDate taught us to use the ACE_NESTED_CLASS macro
// more judiciously in the header file. This file was
// also initially a problem for lookups as well.

module foo
{
  struct theDate
    {
      short year;
      short month;
      short day;
    };

  module bar
    {
      struct theDate
        {
          short x;
        };

      interface fooBar
        {
          foo::theDate getDate (in foo::theDate a,
                                inout foo::theDate b,
                                out foo::theDate c);
        };
    };
};

