// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    valuetype.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has 
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Gary Duzan <gduzan@bbn.com>
//
// ============================================================================

// A valuetype factory can have exceptions, so the declaration must pull in
// an #include of SystemException.h.
valuetype MyValueType 
{
  public string my_string_value;
  factory make_one ();
};
