// $Id$

/**
 * @file Priority_Test.idl
 *
 * Definition of events, and common interfaces used in Priority_Test module.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */

#ifndef CIAO_PRIORITY_TEST_IDL
#define CIAO_PRIORITY_TEST_IDL

#include <Components.idl>

module Priority_Test
{
  /**
   * @brief interface Op_Mode defines the "operation mode" interface.
   */
  interface Op_Mode
  {
    void start ();

    void stop ();

    boolean active ();
  };

  /**
   * @brief interface Common_Ops defines some "common" operations.  It
   * is intended to be used as the interface type of a facet or a
   * receptacle.  All operations in the interface are rather generic
   * and the actualy component implmenetion should decide what they
   * actually do.
   *
   * @param work the amount of work to be done
   * @param aux auxiliary parameter
   */
  interface Common_Ops
  {
    long do_work (in long work,
                  in long aux);
  };
};

#endif /* CIAO_PRIORITY_TEST_IDL */
