// $Id$

/**
 * @file Latency_Test_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef LATENCY_TEST_BASE_IDL
#define LATENCY_TEST_BASE_IDL

#pragma ndds typesupport "Base/Latency_Test_BaseSupport.h"

const short MAX_DATA_SEQUENCE_LENGTH = 8192;
typedef sequence<octet, MAX_DATA_SEQUENCE_LENGTH> OctetSeq;

#pragma DCPS_DATA_TYPE "LatencyTest"

struct LatencyTest {
  long seq_num;
  long ping;
  OctetSeq data;
 };

typedef sequence<LatencyTest> LatencyTestSeq;

#endif
