// $Id$

/**
 * @file QCLS_Test_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef QUERY_CONDITION_LISTEN_STATE_TEST_BASE_IDL
#define QUERY_CONDITION_LISTEN_STATE_TEST_BASE_IDL

#pragma ndds typesupport "Base/QCLS_Test_BaseSupport.h"
#pragma opendds typesupport "Base/QCLS_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "QueryConditionListenStateTest"
#pragma DCPS_DATA_KEY "QueryConditionListenStateTest key"

struct QueryConditionListenStateTest {
  string key; //@key
  long iteration;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<QueryConditionListenStateTest> QueryConditionListenStateTestSeq;
#endif

#endif
