// $Id$

/**
 * @file PSL_DeadlineTest_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef PSL_DeadlineTest_CONNECTOR_IDL_
#define PSL_DeadlineTest_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/PSL_DeadlineTest_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/PSL_DeadlineTest_ConnectorE.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> TestTopic;
};

module PSL_DeadlineTest
{
  connector PSL_DeadlineTest_Connector : ::CCM_DDS::TestTopic::DDS_Event
  {
  };
};

#endif /* PSL_DeadlineTest_CONNECTOR_IDL_ */
