// $Id$

/**
 * @file 
 * @author >
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/ConnectorStatusListener_Test_Connector.idl"
#include "Connector/ConnectorStatusListener_Test_ConnectorE.idl"

module ConnectorStatusListener_Test
{
  component Receiver
  {
    port CCM_DDS::TestTopic::DDS_Listen info_out; 
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
   };
};


#endif
