// $Id$
/// Compliant with OMG 06-04-01 Section 6.10.1.2

#if !defined (CCM_STANDARDCONFIGURATOR_IDL)
#define CCM_STANDARDCONFIGURATOR_IDL

#include "ccm/CCM_Configurator.idl"
#include "ccm/CCM_Navigation.idl"

module Components
{
  typeprefix Components "omg.org";

  valuetype ConfigValue
  {
    public FeatureName name;
    public any value;
  };

  typedef sequence<ConfigValue> ConfigValues;

#if !defined (CCM_LW)
  interface StandardConfigurator : Configurator
  {
    void set_configuration (in ConfigValues descr);
  };
#endif

};
#endif /* CCM_STANDARDCONFIGURATOR_IDL */
