//$Id$

interface Counter
{
  void increment ();
  void decrement ();
  long get_count ();
  void reset ();
  // @@ Angelo, please don't use more code than you need to.  For this
  // test you only need one method, if that much.
};

// @@ Angelo, please add README file.
