// $Id$

/**
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef DDS_KEYED_TEST_SENDER_IDL
#define DDS_KEYED_TEST_SENDER_IDL

#include "Connector/Unkeyed_Test_Connector.idl"

module Unkeyed_Test
{
  component Sender
  {
    port UnkeyedTestConnector::DDS_Write info_write;
    attribute unsigned short rate;
    attribute unsigned short iterations;
    attribute unsigned short keys;
  };
};

#endif
