//$Id$

// This test is to ensure if the destruction process
// and the _non_existent() function in the smart proxy
// is working properly.


interface Test
{
  void hello (in long howmany);
  oneway void shutdown ();
};
