
#ifndef RESOURCE_COMMITMENT_MANAGER_IDL
#define RESOURCE_COMMITMENT_MANAGER_IDL
#include "Deployment_Base.idl"
module Deployment {

  exception ResourceCommitmentFailure {
    string reason;
    short index;
    string propertyName;
    any propertyValue;
  };
  /**
   * @struct ResourceAllocation
   * @brief Identifies a resource within a domain that is 
   *  allocated from and the amount it is allocated
   */
  struct ResourceAllocation
  {
    string elementName;
    string resourceName;
    Properties property;
  };

  /// The Resource Allocation Sequence
  typedef sequence <ResourceAllocation> ResourceAllocationSeq;

  interface ResourceCommitmentManager {
    void commitResources (in ResourceAllocationSeq resources)
      raises (ResourceCommitmentFailure);
    void releaseResources (in ResourceAllocationSeq resources)
      raises (ResourceCommitmentFailure);
  };
};


#endif
