// $Id$

#ifndef TARGETMANAGER_IDL
#define TARGETMANAGER_IDL

#include "ciao/Deployment_Target_Data.idl"
#include "ciao/Deployment_TargetData.idl"
#include "ciao/Deployment_DeploymentPlan.idl"
#include "ciao/Deployment_ResourceCommitmentManager.idl"

module Deployment {

  enum DomainUpdateKind {
    Add,
    Delete,
    UpdateAll,
    UpdateAvailable
  };

  /**
   * @todo The ResourceCommitmentManager is part of 06-04-01 and this is not
   * part of the Target Manager yet
   */
  interface TargetManager {
    Domain getAllResources ();
    Domain getAvailableResources ();
    ResourceCommitmentManager createResourceCommitment (in ResourceAllocationSeq manager);
    void destroyResourceCommitment (in ResourceCommitmentManager resources);
    void updateDomain (in ::CORBA::StringSeq elements,
                       in Domain domainSubset,
                       in DomainUpdateKind updateKind);
  };
};

#endif /* TARGETMANAGER_IDL */
