// $Id$
//=============================================================================
/**
 * @file RTEventService.idl
 *
 * Definition of component and home that will provide event channels.
 *
 * @author George Edwards <g.edwards@vanderbilt.edu>
 */
//=============================================================================

#include "../BasicSP.idl"

#ifndef CIAO_RTEVENTSERVICE_IDL
#define CIAO_RTEVENTSERVICE_IDL


module BasicSP
{

  component RTEventService
    {
      provides RtecEventChannelAdmin::EventChannel rt_event_channel;
    };

  home RTEventServiceHome manages RTEventService
    {
    };

};

#endif /* CIAO_RTEVENTSERVICE_IDL*/
