
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl ETCL_Notify_Filtering
// ------------------------------
#ifndef ETCL_NOTIFY_FILTERING_EXPORT_H
#define ETCL_NOTIFY_FILTERING_EXPORT_H

#include "ace/config-all.h"

#if !defined (ETCL_NOTIFY_FILTERING_HAS_DLL)
#  define ETCL_NOTIFY_FILTERING_HAS_DLL 1
#endif /* ! ETCL_NOTIFY_FILTERING_HAS_DLL */

#if defined (ETCL_NOTIFY_FILTERING_HAS_DLL) && (ETCL_NOTIFY_FILTERING_HAS_DLL == 1)
#  if defined (ETCL_NOTIFY_FILTERING_BUILD_DLL)
#    define ETCL_Notify_Filtering_Export ACE_Proper_Export_Flag
#    define ETCL_NOTIFY_FILTERING_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define ETCL_NOTIFY_FILTERING_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* ETCL_NOTIFY_FILTERING_BUILD_DLL */
#    define ETCL_Notify_Filtering_Export ACE_Proper_Import_Flag
#    define ETCL_NOTIFY_FILTERING_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define ETCL_NOTIFY_FILTERING_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* ETCL_NOTIFY_FILTERING_BUILD_DLL */
#else /* ETCL_NOTIFY_FILTERING_HAS_DLL == 1 */
#  define ETCL_Notify_Filtering_Export
#  define ETCL_NOTIFY_FILTERING_SINGLETON_DECLARATION(T)
#  define ETCL_NOTIFY_FILTERING_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* ETCL_NOTIFY_FILTERING_HAS_DLL == 1 */

// Set ETCL_NOTIFY_FILTERING_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (ETCL_NOTIFY_FILTERING_NTRACE)
#  if (ACE_NTRACE == 1)
#    define ETCL_NOTIFY_FILTERING_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define ETCL_NOTIFY_FILTERING_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !ETCL_NOTIFY_FILTERING_NTRACE */

#if (ETCL_NOTIFY_FILTERING_NTRACE == 1)
#  define ETCL_NOTIFY_FILTERING_TRACE(X)
#else /* (ETCL_NOTIFY_FILTERING_NTRACE == 1) */
#  define ETCL_NOTIFY_FILTERING_TRACE(X) ACE_TRACE_IMPL(X)
#endif /* (ETCL_NOTIFY_FILTERING_NTRACE == 1) */

#endif /* ETCL_NOTIFY_FILTERING_EXPORT_H */

// End of auto generated file.
