#ifndef RACE_PATH_IDL
#define RACE_PATH_IDL


module CIAO
{
  module RACE
  {

    struct Path_Element
    {
      /// UUID of the component.
      string node;

      /// Name of the source port.
      string src;

      /// Name of the destination port.
      string dst;
    };

    /// Type definition for a path sequence.
    typedef sequence <Path_Element> Critical_Path;
  };

};

#endif /*RACE_PATH_IDL*/
