// $Id$

//=============================================================================
/**
 * @file ECEI.idl
 *
 *
 * @author Balachandran Natarajan <bala@dre.vanderbilt.edu>
 */
//=============================================================================
#ifndef CIAO_ECEI_IDL
#define CIAO_ECEI_IDL

#include "ECE.idl"

module BasicSP
{
  /**
   * @interface EC_Exec
   *
   * The actually EC executor need to support
   * Components::SessionComponent interface.  Therefore, we need to
   * define the component executor interface explicitly here.
   */
  local interface EC_Exec : CCM_EC,
    Components::SessionComponent
  {
  };

};

#endif /* RATEGENEI_IDL */
