// -*- IDL -*-

// $Id$

#include "ImplRepo.idl"

module ImplementationRepository
{
  interface Activator
  {
    /// Tells the activator to launch a server with the given information.
    void start_server (in string name, in string cmdline,
      in string dir, in EnvironmentList env) raises(CannotActivate);

    oneway void shutdown ();
  };

  interface ActivatorExt : Activator
  {
    /// Tells the activator to send a signal to a child process
    boolean kill_server (in string name, in short signum);
  };
};

