/// This is a simple interface that tests the Naming Service.
interface Test_Object
{
  /// This provides an easy way to differentiate objects if each
  /// objects is served by a separate servant.
  attribute short id;
};
