//$Id$

/**
 * @file MUF_Scheduling.idl
 *
 * $Id$
 *
 */

#include "tao/RTScheduling/RTScheduler_include.pidl"
#include "tao/RTCORBA/RTCORBA_include.pidl"
#include "tao/TimeBase.pidl"

module MUF_Scheduling
{
  struct SchedulingParameter
  {
    TimeBase::TimeT deadline;
    TimeBase::TimeT estimated_initial_execution_time;
    long criticality;
  };

  local interface SchedulingParameterPolicy
  : CORBA::Policy
  {
    attribute SchedulingParameter value;
  };

  local interface Scheduler : RTScheduling::Scheduler
  {
    SchedulingParameterPolicy
      create_scheduling_parameter
        (in SchedulingParameter value);
  };
};
