// $Id$

// A plain vanilla component definition.

interface Hello
{
  // Return the greating string as:
  //   "Greeting from <helloname>.  How are you, <username>?"
  string sayhello (in string username);
};

#if 0
component HelloWorld supports Hello
{
  // The name of this greeting machine.
  attribute string helloname;
};


home HelloHome manages HelloWorld
{
  factory init (in string name);
};
#else

interface HelloWorld :
  ::Components::CCMObject,
  Hello
{
  attribute string helloname;
};

interface HelloHomeExplicit
// : ::Components::CCMHome
{
  HelloWorld init (in string name);
};

interface HelloHomeImplicit
// : ::Components::KeylessCCMHome
{
  HelloWorld create ()
    //    raises (CreateFailure)
    ;
};

interface HelloHome
  : HelloHomeExplicit,
    HelloHomeImplicit
{
};

#endif
