// $Id$

// A plain vanilla component definition.

#include "ciao/CIAO_Component.pidl"

interface Hello
{
  string sayhello (in string username);
};

component HelloWorld supports Hello
{
};


home HelloHome manages HelloWorld
{
};
