// $Id$

/**
 * @file Connector2.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef SHARED_DP_CONNECTOR2_IDL_
#define SHARED_DP_CONNECTOR2_IDL_

#include  <Components.idl>
#include "Base/Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector2/Connector2E.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::SharedDPTest2, ::SharedDPTest2Seq> SharedDPTest2;
};

module SharedDP_Connector2
{
  connector Connector2 : ::CCM_DDS::SharedDPTest2::DDS_Event
  {
  };
};

#endif /* SHARED_DP_CONNECTOR2_IDL_ */
