//$Id$
//=============================================================================
/**
 * @file UCAV_GS.idl
 *
 * Definition of the UCAV_GS component
 *
 * @author Gan Deng <gan.deng@vanderbilt.edu>
 * @author George Edwards <g.edwards@vanderbilt.edu>
 */
//=============================================================================
#ifndef CIAO_UCAV_GS_IDL
#define CIAO_UCAV_GS_IDL

#include "../BBN_UAV.idl"

module BBN_UAV
{
  component UCAV_GS
    {
      publishes StartMove start_move;
      consumes PrepareMove prepare_move;
    };

  home UCAV_GSHome manages UCAV_GS
    {
    };
};

#endif /*CIAO_UCAV_GS_IDL */
