// $Id$

/**
 * @file GCE_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef GET_COMPONENT_EVENT_TEST_BASE_IDL
#define GET_COMPONENT_EVENT_TEST_BASE_IDL

#pragma ndds typesupport "Base/GCE_Test_BaseSupport.h"
#pragma opendds typesupport "Base/GCE_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "GCETest"
#pragma DCPS_DATA_KEY "GCETest symbol"

struct GCETest {
  string symbol; //@key
  long x;
  long y;
};

typedef sequence<GCETest> GCETestSeq;

#endif /* GET_COMPONENT_EVENT_TEST_BASE_IDL */
