// $Id$

/**
 * @file LMBM_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef LISTEN_MANY_BY_MANY_TEST_BASE_IDL
#define LISTEN_MANY_BY_MANY_TEST_BASE_IDL

#pragma ndds typesupport "Base/LMBM_Test_BaseSupport.h"
#pragma opendds typesupport "Base/LMBM_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "ListenManyByManyTest"
#pragma DCPS_DATA_KEY "ListenManyByManyTest key"

struct ListenManyByManyTest {
  string key; //@key
  long iteration;
};

typedef sequence<ListenManyByManyTest> ListenManyByManyTestSeq;

#endif
