//
// $Id$
//

interface test
{
  typedef sequence<octet> data;
  oneway void method (in unsigned long request_number,
                      in long start_time,
                      in data d,
                      in unsigned long work);
  void flush ();
  oneway void shutdown (in long start_time);
};
