// $Id$

/**
 * @file SL_Disabled_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef SL_DISABLED_CONNECTOR_IDL_
#define SL_DISABLED_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/SL_Disabled_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/SL_Disabled_ConnectorE.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> TestTopic;
};

module SL_Disabled
{
  connector SL_Disabled_Connector : ::CCM_DDS::TestTopic::DDS_State
  {
  };
};

#endif /* SL_Disabled_CONNECTOR_IDL_ */
