// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Perf_Keyed_Test_Connector.idl"

module Perf_Keyed_Test
{
  component Receiver
  {
    port CCM_DDS::PerfKeyedTest::DDS_Listen info_listen;
    port CCM_DDS::PerfKeyedTest::DDS_Write write_ping;
  };
};

#endif
