// $Id$

#ifndef NOMODULE_IDL
#define NOMODULE_IDL

#pragma ndds typesupport "DerivedSupport.h"
#pragma opendds typesupport "DerivedTypeSupportImpl.h"

struct DerivedType {
  string value; //@key
};

typedef sequence<DerivedType> DerivedTypeSeq;

#endif
