// $Id$

#ifndef NOMODULE_CONNECTOR_IDL
#define NOMODULE_CONNECTOR_IDL

#include <Components.idl>
#include <ccm_dds.idl>

#include "Derived.idl"

#pragma ciao lem "Derived_ConnectorE.idl"

#pragma dds4ccm impl "DDS_Derived_Connector_T.h"

module ::CCM_DDS::Typed < ::DerivedType, ::DerivedTypeSeq> DerivedTypeConnector;

interface fooA
{
  void send (in long value);
};

interface fooB
{
  void send (in long value);
};

connector MyEvent : DerivedTypeConnector::DDS_Event
{
  provides fooA my_foo;
};

connector MyState : DerivedTypeConnector::DDS_State
{
  provides fooB my_foo;
};

#endif
