/* -*- IDL -*- */
//=============================================================================
/**
 *  @file    FT_ReplicationManager.idl
 *
 *  $Id$
 *
 *  This file is part of Fault Tolerant CORBA.
 *  This was original part of the OMG FT.idl file
 *
 *  @author Curt Hibbs <hibbs_c@ociweb.com>
 */
//=============================================================================

#ifndef _FT_REPLICATION_MANAGER_IDL_
#define _FT_REPLICATION_MANAGER_IDL_

#include "orbsvcs/PortableGroup.idl"
#include "orbsvcs/FT_CORBA.idl"
#include "orbsvcs/FT_Replica.idl"
#include "orbsvcs/FT_Notifier.idl"

#pragma prefix "omg.org"

module FT
{
  exception InterfaceNotFound {};

  // Specification of ReplicationManager Interface
  interface ReplicationManager : PropertyManager,
                                 FTObjectGroupManager,
                                 GenericFactory {

    /**
    * Registers the Fault Notifier with the Replication Manager.
    * @param fault_notifier where to send the fault information.
    */
    void register_fault_notifier(in FaultNotifier fault_notifier);

    /**
    * Returns the reference of the Fault Notifier.
    * @returns the reference of the Fault Notifier.
    */
    FaultNotifier get_fault_notifier()
      raises (InterfaceNotFound);

    /**
    * Creates and returns a dummy IOGR for unit testing
    */
    ObjectGroup create_test_iogr ();
 
    /**
    * TAO-specific shutdown operation.
    */
    void oneway shutdown ();
  };
};


#endif // _FT_REPLICATION_MANAGER_IDL_
