// $Id$

/**
 * @file VT_Union_Connector.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef VT_UNION_CONNECTOR_IDL_
#define VT_UNION_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/VTopic_Base.idl"

#pragma ciao lem "Conn_Union/VT_Union_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/VTopic_BaseTypeSupport.idl"
#endif

module VTopic
{
  module ::CCM_DDS::Typed < ::TopicUnion, ::TopicUnionSeq> TopicUnionConnector;
#if !defined (CIAO_DDS4CCM_OPENDDS)
  module ::CCM_DDS::Typed < ::X_Union, ::X_UnionSeq> X_UnionConnector;
#else
  module ::CCM_DDS::Typed < ::TopicString, ::TopicStringSeq> X_UnionConnector;
#endif
};

#endif /* VT_UNION_CONNECTOR_IDL_ */
