#
# Makefile for building	the IOGRManipulation executable
#

NAME = IOGRTest

OBJFILES = $(OBJDIR)\IOGRTest.obj

CFLAGS = \
	$(ACE_CFLAGS) \
	$(TAO_CFLAGS) \
	$(TAO_PORTABLESERVER_CFLAGS) \
	$(TAO_IORMANIP_CFLAGS) \
	$(TAO_SVC_UTILS_CFLAGS)	\
	$(TAO_NAMING_CFLAGS) \
	$(TAO_EVENT_CFLAGS) \
	$(TAO_NOTIFY_CFLAGS) \
        $(TAO_FTORB_CFLAGS)

LIBFILES = \
	$(ACE_LIB) \
	$(TAO_LIB) \
	$(TAO_PORTABLESERVER_LIB) \
	$(TAO_IORMANIP_LIB) \
	$(TAO_SVC_UTILS_LIB) \
	$(TAO_NAMING_LIB) \
	$(TAO_EVENT_LIB) \
	$(TAO_NOTIFY_LIB) \
        $(TAO_FTORB_LIB)

CPPDIR = .

!include <$(ACE_ROOT)\include\makeinclude\build_exe.bor>
