// $Id$

/**
 * @file navDisplay.idl
 *
 * Definition of the navigation display component.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */

#include "../HUDisplay.idl"

module HUDisplay
{
  component navDisplay
    {
      consumes tick Refresh;
      uses position GPSLocation;
    };

  home NavDisplayHome manages NavDisplay
  {
  };
};
