// $Id$

/**
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef COMPONENT_IDL
#define COMPONENT_IDL

#include "Connector/Exception_Test_Connector.idl"

module CFT_Exception_Test
{
  component CFTTestComponent
  {
    port CFTExceptionTestConn::DDS_Get getter;
  };
};

#endif
