$Id$:
/**
 * @file ReceiverEI.idl
 *
 * @author Tao Lu <lu@dre.vanderbilt.edu>
 */

#ifndef RECEIVEREI_IDL
#define RECEIVERET_IDL


#include "ReceiverE.idl"

module Hello
{
  //Note since the Receiver only uses the message interface, there won't
  //be any inheritance from CCM_message.
  local interface Receiver_Exec :
    CCM_Receiver,
    Components::SessionComponent
    {
    };

}; 
#endif /*RECEIVEREI_IDL*/
