/**
 * @file Activation_Manager.idl
 *
 * @brief
 *
 * $Id$
 *
 * @author Pradeep Gore <pradeep@oomworks.com>
 */

#ifndef _NOTIFY_TEST_IDL_
#define _NOTIFY_TEST_IDL_

#pragma prefix ""

/**
 * @namespace Activation_Manager
 *
 * @brief Notify Test
 */
module Notify_Test
{
  interface Activation_Manager
  {
    /*
     * Prompts the Activation Manager to start.
     */
    void start ();
  };
};

#endif /* _NOTIFY_TEST_IDL_ */
