// $Id$

/**
 * @file Exception_Test_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef CFT_EXCEPTION_TEST_BASE_IDL
#define CFT_EXCEPTION_TEST_BASE_IDL

#pragma ndds typesupport "Base/Exception_Test_BaseSupport.h"
#pragma opendds typesupport "Base/Exception_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "CFTExceptionTest"
#pragma DCPS_DATA_KEY "CFTExceptionTest symbol"

struct CFTExceptionTest {
  string symbol; //@key
  long x;
  long y;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<CFTExceptionTest> CFTExceptionTestSeq;
#endif

#endif /* CFT_EXCEPTION_TEST_BASE_IDL */
