// $Id$
/// Compliant with OMG 06-04-01 Section 6.7.7

#if !defined (CCM_KEYLESSCCMHOME_IDL)
#define CCM_KEYLESSCCMHOME_IDL

#include "ccm/CCM_Object.idl"

module Components
{
  typeprefix Components "omg.org";

  interface KeylessCCMHome
  {
    CCMObject create_component()
      raises (CreateFailure);
  };
};
#endif /* CCM_KEYLESSCCMHOME_IDL */
