//$Id$

#ifndef STOCKDISTRIBUTOR_IDL
#define STOCKDISTRIBUTOR_IDL

#include "../Stock_Base/Stock_Base.idl"

module Stock
{
  /**
   * @class Trigger
   *
   * @brief supported interface
   */
  interface Trigger {
    /// Start the real-time monitoring service
    void start ();
    /// Stop the real-time monitoring service
    void stop ();
  };

  /**
   * @class StockDistributor
   *
   * @brief component
   */
  component StockDistributor supports Trigger
  {
    publishes StockName notify_out;
    provides StockQuoter push_quoter;
    attribute long rate;
  };

  /**
   * @class StockDistributorHome
   *
   * @brief home for StockDistributor component
   */
  home StockDistributorHome manages StockDistributor
  {
  };
};

#endif /* STOCKDISTRIBUTOR_IDL */
