// $Id$

/**
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef DDS_PERF_KEYED_TEST_SENDER_IDL
#define DDS_PERF_KEYED_TEST_SENDER_IDL

#include "Connector/Perf_Keyed_Test_Connector.idl"


module Perf_Keyed_Test
{
  component Sender
  {
    port CCM_DDS::PerfKeyedTest::DDS_Write info_write;
    attribute unsigned short keys;
    attribute unsigned long iterations;
    attribute unsigned short latency_count; //number of samples sent before a latency ping packet is sent. default 100000, < sample_count
    attribute unsigned short sleep; //time in ms to sleep between each send
    attribute unsigned short spin;
    attribute unsigned short datalen; //minimal 32
    attribute unsigned short number_of_sub; //number of subscribers
    provides CCM_DDS::ConnectorStatusListener connector_status;
    port CCM_DDS::PerfKeyedTest::DDS_Listen ping_listen;
  };
};

#endif
