// $Id$

module corbaname
{

  interface Status
  {
    // = TITLE
    //     A simple interface to check the status of
    //     connection between the client and the server.
    //
    // = DESCRIPTION
    //     Prints out the status.

    boolean print_status ();
    // Return <true> if the server received the
    // request from the client.

  };
};
