// $Id$

// A plain vanilla component definition.

component HelloWorld
{
  // The name of this greeting machine.
  //  attribute string helloname;

  // Return the greating string as:
  //   "Greeting from <helloname>.  How are you, <username>?"
  //  string hello (in string username);
};


home HelloHome manages HelloWorld
{
  // No explicit home operation.
};
