//$Id$
//=============================================================================
/**
 * @file Battle.idl
 *
 * Definition of the Battle component
 *
 * @author Gan Deng <gan.deng@vanderbilt.edu> 
 * @author George Edwards <g.edwards@vanderbilt.edu>
 */
//=============================================================================
#ifndef CIAO_BATTLE_IDL
#define CIAO_BATTLE_IDL

#include "../BBN_UAV.idl"

module BBN_UAV
{
  component Battle
    {
      publishes BattleReady battle_ready;
      consumes StartEngage start_engage;
    };

  home BattleHome manages Battle
    {
    };
};

#endif /*CIAO_BATTLE_IDL */
