# makefile.b32 (for wxNamingViewer)

WXDIR = $(WXWIN)

EXTRACPPFLAGS = $(EXTRADEFINES) $(EXTRAINCLUDES) $(EXTRAFLAGS)
EXTRADEFINES = -DACE_HAS_DLL=1 -DTAO_HAS_DLL=1 -DTAO_ORBSVCS_HAS_DLL=1 -DACE_USE_RCSID=0 -D__ACE_INLINE__=1
EXTRAINCLUDES = -I$(ACE_ROOT) -I$(ACE_ROOT)\tao -I$(ACE_ROOT)\tao\orbsvcs
EXTRAFLAGS = -w-rvl -w-par -w-rch -H=wxNamingViewer.csm -Hh=pch.h

EXTRALINKFLAGS = -L$(ACE_ROOT)\bin\Dynamic\Release 
EXTRALIBS = ace_b.lib tao_b.lib TAO_CosNaming_b.lib

TARGET = wxNamingViewer

OBJECTS = wxAddNameServerDlg.obj \
	  wxBindDialog.obj\
	  wxBindNewContext.obj \
	  wxNamingObject.obj \
	  wxNamingTree.obj \
	  wxNamingViewer.obj \
	  wxNamingViewerFrame.obj \
	  wxSelectNSDialog.obj \
	  wxViewIORDialog.obj  

!include $(WXDIR)\src\makeprog.b32

