// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    old_struct.idl
//
// = DESCRIPTION
//    Tests of struct IDL constructs
//
// = AUTHORS
//    Andy Gokhale <gokhale@dre.vanderbilt.edu>
//
// ============================================================================

typedef string string_20[20];

struct bar1
{
  long b1;
  long b2;
  string_20 b3;
};

struct bar2
{
  long b3;
  bar1  b4;
};

struct bar3
{
  long b1;
  long b2;
  long b3;
};

struct bar4
{
  long b1;
  bar2 b2;
  long b3;
  bar3 b4;
  long b5;
};


interface foo1
{
  long op (in bar1 a, out bar2 b);
};

interface foo2 : foo1
{
  bar1  op2 (in bar2 a);

  long op3 (in long a, out char b);
};


typedef unsigned short Coord;

struct CellPos
{
  Coord row;
  Coord col;
};

struct CellPos2
{
  unsigned short row;
  unsigned short col;
};

struct CellPos3
{
  Coord row;
  Coord col;
  unsigned short col2;
};
