// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    reopen_include1.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

#ifndef IDL_TEST_REOPEN_INCLUDE1_IDL
#define IDL_TEST_REOPEN_INCLUDE1_IDL

// First opening of a module included by a chain of
// inclusions into reopened_modules.idl
module frag
{
  typedef sequence<double> dub_seq;
};

// These are in each file in the reopened_modules chain,
// and in reopened_modules.idl, test interface parent lookup.
module A
{
  module B
  {
    interface X1
    {
      string getX1 ();
    };
  };
};

#endif /* IDL_TEST_REOPEN_INCLUDE1_IDL */
