// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    reopen_include2.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that has
//    caused problems in the past for the TAO IDL
//    compiler. This test is to make sure the problems
//    stay fixed.
//
// = AUTHORS
//    Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
//
// ============================================================================

#ifndef IDL_TEST_REOPEN_INCLUDE2_IDL
#define IDL_TEST_REOPEN_INCLUDE2_IDL

#include "reopen_include1.idl"

// #included by reopened modules.idl along with
// same module in reopen_include1.idl.
module frag
{
  struct pug {short leash;};
};

// These three are reopened in reopened_modules.idl.
module XX
{
  typedef long whah;
};

module A
{
  module B
  {
    interface X2
    {
      string getX2 ();
    };
  };
};

#endif /* IDL_TEST_REOPEN_INCLUDE2_IDL */
