// $Id$

// ============================================================================
//
// = LIBRARY
//    TAO/tests/IDL_Test
//
// = FILENAME
//    simple.idl
//
// = DESCRIPTION
//    Tests of simple IDL
//
// = AUTHORS
//    Andy Gokhale <gokhale@dre.vanderbilt.edu>
//
// ============================================================================

typedef sequence<long,10> vec10;

exception simple_error
{
  long reason;
};

interface simple
{
  long op (in long a,
           out simple b,
           inout long c)
    raises (simple_error);
};

interface simple2 : simple
{
  exception simple2_error
  {
    long reason2;
  };

  long op2 (in long a,
            in simple b,
            out simple2 c)
    raises (simple2_error);
};
