//
// $Id$
//

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  /// A very simple interface
  interface Hello
  {
    /// Return a simple string
    unsigned long next_prime ();
  };
};
