//$Id$
#ifndef RACE_COMMON_IDL
#define RACE_COMMON_IDL

#include "tao/StringSeq.pidl"

module CIAO
{
  module RACE
    {
      typedef string RACE_Classification;
      typedef sequence <RACE_Classification> RACE_Classifications;
      typedef CORBA::StringSeq PlannerFlow;
    };
};

#endif /* RACE_COMMON_IDL */
