// $Id$

/**
 * @file VT_Seq_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VT_SEQ_CONNECTOR_IDL_
#define VT_SEQ_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/VTopic_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Conn_Seq/VT_Seq_ConnectorE.idl"

module VTopic
{
  module ::CCM_DDS::Typed < ::TopicSeq, ::TopicSeqSeq> TopicSeqConn;
  connector VT_Seq_Connector : TopicSeqConn::DDS_Event
  {
  };
};

#endif /* VTopic_CONNECTOR_IDL_ */
