// $Id$

/**
 * @file FSS_Event_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef FIXED_SIZE_STRUCT_EVENT_BASE_IDL
#define FIXED_SIZE_STRUCT_EVENT_BASE_IDL

#pragma ndds typesupport "Base/FSS_Event_BaseSupport.h"
#pragma opendds typesupport "Base/FSS_Event_BaseTypeSupportImpl.h"

struct FixedStructSizeTest {
  long one;
  long two;
};

typedef sequence<FixedStructSizeTest> FixedStructSizeTestSeq;

#endif
