#!/bin/sh
#
# $Id$
#

./latency.pl -k LOCAL -r 100 EC1.log EC2.log >local.log
tail +3 local.log | sort -n > local.data
./latency.pl -k REMOTE -r 1000 EC1.log EC2.log >remote.log
tail +3 remote.log | sort -n > remote.data

gnuplot <<_EOF_
set grid xtics ytics
set xlabel "Time (usecs)"
set ylabel "Relative frequency"

set terminal postscript eps color
set output "local.eps"
plot 'local.data' w i
set terminal x11
plot 'local.data' w i
pause 2

set terminal postscript eps
set output "remote.eps"
plot 'remote.data' w i
set terminal x11
plot 'remote.data' w i
pause 2

_EOF_

gs -sDEVICE=jpeg -g640x480 -r110x110 -sNOPAUSE -sOutputFile="local.jpg" local.eps quit.ps
gs -sDEVICE=jpeg -g640x480 -r110x110 -sNOPAUSE -sOutputFile="remote.jpg" remote.eps quit.ps
