// $Id$

/**
 * @file Get_Connection_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef GET_CONNECTION_TEST_BASE_IDL
#define GET_CONNECTION_TEST_BASE_IDL

struct Get_ConnectionTest {
  string key; //@key
  long iteration;
};

typedef sequence<Get_ConnectionTest> Get_ConnectionTest_Seq;

#endif
