// $Id$
//
#ifndef RESOURCE_COMMITMENT_MANAGER_IDL
#define RESOURCE_COMMITMENT_MANAGER_IDL

#include "DAnCE/Deployment/Deployment_Base.idl"
#include "tao/AnyTypeCode/AnySeq.pidl"

module Deployment {
  struct ResourceAllocation {
    string elementName;
    string resourceName;
    Properties property;
  };

  typedef sequence < ResourceAllocation > ResourceAllocations;

  exception ResourceCommitmentFailure {
    string reason;
    long index;
    string propertyName;
    ::CORBA::AnySeq propertyValue;
  };

  interface ResourceCommitmentManager {
    void commitResources (in ResourceAllocations resources)
      raises (ResourceCommitmentFailure);
    void releaseResources (in ResourceAllocations resources)
      raises (ResourceCommitmentFailure);
  };
};

#endif //RESOURCE_COMMITMENT_MANAGER_IDL

