// $Id$

#ifndef DEPLOYMENT_CORE_IDL
#define DEPLOYMENT_CORE_IDL

//#include "ciao/CCM_Component.idl"
#include "DAnCE/Deployment/Deployment_TargetData.idl"
#include "DAnCE/Deployment/Deployment_Data.idl"
#include "DAnCE/Deployment/Deployment_Application.idl"

module Deployment {

	//@! in DOCGroup three additional exceptions specified
	exception StopError {
		string name;
		string reason;
	};
};
#endif /* DEPLOYMENT_CORE_IDL */

