// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "ReceiverConnector/OIT_Receiver_Connector.idl"

module OIT_Test
{
  component Receiver
  {
    port OIT_Receiver_TopicConnector::DDS_Listen info_out;
    provides CCM_DDS::ConnectorStatusListener connector_status;
  };
};

#endif
