// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:373


#include "InheritedOpC.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "InheritedOpC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:48

// Traits specializations for Outer::Inner::Base.

Outer::Inner::Base_ptr
TAO::Objref_Traits<Outer::Inner::Base>::duplicate (
    Outer::Inner::Base_ptr p)
{
  return Outer::Inner::Base::_duplicate (p);
}

void
TAO::Objref_Traits<Outer::Inner::Base>::release (
    Outer::Inner::Base_ptr p)
{
  ::CORBA::release (p);
}

Outer::Inner::Base_ptr
TAO::Objref_Traits<Outer::Inner::Base>::nil (void)
{
  return Outer::Inner::Base::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Outer::Inner::Base>::marshal (
    const Outer::Inner::Base_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:88

void
Outer::Inner::Base::BaseOp (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }

  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "BaseOp",
      6,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _tao_call.invoke (0, 0);
}

Outer::Inner::Base::Base (void)
{
}

Outer::Inner::Base::~Base (void)
{
}

Outer::Inner::Base_ptr
Outer::Inner::Base::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Base>::narrow (
        _tao_objref,
        "IDL:Outer/Inner/Base:1.0");
}

Outer::Inner::Base_ptr
Outer::Inner::Base::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Base>::unchecked_narrow (
        _tao_objref);
}

Outer::Inner::Base_ptr
Outer::Inner::Base::_nil (void)
{
  return 0;
}

Outer::Inner::Base_ptr
Outer::Inner::Base::_duplicate (Base_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Outer::Inner::Base::_tao_release (Base_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Outer::Inner::Base::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:Outer/Inner/Base:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Outer::Inner::Base::_interface_repository_id (void) const
{
  return "IDL:Outer/Inner/Base:1.0";
}

::CORBA::Boolean
Outer::Inner::Base::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:48

// Traits specializations for Outer::Derived.

Outer::Derived_ptr
TAO::Objref_Traits<Outer::Derived>::duplicate (
    Outer::Derived_ptr p)
{
  return Outer::Derived::_duplicate (p);
}

void
TAO::Objref_Traits<Outer::Derived>::release (
    Outer::Derived_ptr p)
{
  ::CORBA::release (p);
}

Outer::Derived_ptr
TAO::Objref_Traits<Outer::Derived>::nil (void)
{
  return Outer::Derived::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Outer::Derived>::marshal (
    const Outer::Derived_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:88

void
Outer::Derived::shutdown (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }

  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "shutdown",
      8,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _tao_call.invoke (0, 0);
}

Outer::Derived::Derived (void)
{
}

Outer::Derived::~Derived (void)
{
}

Outer::Derived_ptr
Outer::Derived::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Derived>::narrow (
        _tao_objref,
        "IDL:Outer/Derived:1.0");
}

Outer::Derived_ptr
Outer::Derived::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Derived>::unchecked_narrow (
        _tao_objref);
}

Outer::Derived_ptr
Outer::Derived::_nil (void)
{
  return 0;
}

Outer::Derived_ptr
Outer::Derived::_duplicate (Derived_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Outer::Derived::_tao_release (Derived_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Outer::Derived::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:Outer/Inner/Base:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Outer/Derived:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Outer::Derived::_interface_repository_id (void) const
{
  return "IDL:Outer/Derived:1.0";
}

::CORBA::Boolean
Outer::Derived::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:51

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Outer::Inner::Base_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Outer::Inner::Base_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }

  typedef ::Outer::Inner::Base RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());

  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:51

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Outer::Derived_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Outer::Derived_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }

  typedef ::Outer::Derived RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());

  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



