// $Id$

#if !defined (CCM_CONTAINER_IDL)
#define CCM_CONTAINER_IDL

#include "ccm/CCM_Component.idl"
#include "ccm/CCM_CCMException.idl"
#include "ccm/CCM_HomeExecutorBase.idl"
#include "ccm/CCM_SessionContext.idl"
#include "ccm/CCM_SessionComponent.idl"

#endif /* CCM_CONTAINER_IDL */
