/* -*- C++ -*- */
#include <orb.idl>

module DynAnyTests
{
  struct enclosed_struct
  {
    float f;
    short s;
  };

  struct test_struct
  {
    char c;
    CORBA::ShortSeq ss;
    enclosed_struct es;
  };

  typedef sequence<string<8> > test_seq;
  typedef sequence<short> SeqShort;
  typedef sequence<boolean> SeqBoolean;

  typedef fixed<10, 3> test_fixed;
  typedef fixed<31, 0> test_max_fixed;
  typedef fixed<31, 31> test_max_scale_fixed;
  typedef fixed<3, 3> test_fraction_fixed;
  typedef fixed<3, 0> test_small_fixed;
  typedef sequence<test_fixed> test_fixed_sequence;

  const unsigned long DIM = 2;
  typedef long test_array [DIM];

  enum test_enum
  {
    TE_ZEROTH,
    TE_FIRST,
    TE_SECOND,
    TE_THIRD,
    TE_FOURTH
  };

  typedef test_enum Enumerated_a;
  typedef test_enum Enumerated_b;
  typedef test_enum Enumerated_c;

  struct StructTypedefEnum {
    Enumerated_a    field_1;
    Enumerated_b    field_2;
    Enumerated_c    field_3;
  };

  union test_union switch (test_enum)
  {
    case TE_SECOND: CORBA::TypeCode tc;
    case TE_FOURTH: test_enum te;
    default: short s;
    case TE_THIRD: string str;
    case TE_ZEROTH: octet o;
  };

  typedef test_struct test_struct_alias;
  typedef test_union test_union_alias;

  union test_multi_label_union switch (long) {
    case 1:
    case 2: string value;
    default: long other;
  };

  union test_default_label_union switch (long) {
    case 1:
    default: long value;
    case 2: short other;
  };

  union test_boolean_union switch (boolean) {
    case TRUE: long true_value;
    case FALSE: short false_value;
  };

  union test_char_union switch (char) {
    case 'a':
    case 'b': long value;
    case 'c': short other;
  };

  enum discriminator_enum {
    DE_FIRST,
    DE_SECOND,
    DE_THIRD
  };

  union test_enum_union switch (discriminator_enum) {
    case DE_FIRST:
    case DE_SECOND: long value;
    case DE_THIRD: short other;
  };

  union test_enum_default_union switch (discriminator_enum) {
    case DE_FIRST: long value;
    default: short other;
  };

  union test_implicit_def switch (boolean) {
    case TRUE :
       test_enum tenum;
  } ;

  union test_union_no_active_member switch (long) {
        case 1: long    field_long;
        case 2: string  field_string;
  };

  struct test_struct_with_long_double
  {
    long double field_longdouble;
  };


};
