// $Id$
#include <Components.idl>

interface foo
{
  void do_foo ();
};

interface foo_inherited : Components::Navigation
{
  void do_inherited_foo ();
};

component Navigation
{
  provides foo navigation_foo;
  provides foo_inherited inherited_foo;
};
