// $Id$
#ifndef NODEAPPLICATIONMANAGER_IDL
#define NODEAPPLICATIONMANAGER_IDL

#include "DAnCE/Deployment/Deployment_ApplicationManager.idl"

module Deployment {
  interface NodeApplicationManager :
    ApplicationManager
  {
  };
};

#endif /* NODEAPPLICATIONMANAGER_IDL */
