// $Id$
// Compliant with OMG 06-04-01 section 15

#ifndef DEPLOYMENT_STOPERROR_IDL
#define DEPLOYMENT_STOPERROR_IDL

module Deployment {
  exception StopError {
    string name;
    string reason;
  };
};
#endif /* DEPLOYMENT_STOPERROR_IDL */

