//
// $Id$
//
module Test
{
   enum Selector { STRUCTTYPE, VALTYPE };

   struct Foo { long l; } ;

   valuetype Bar { public short s; } ;

   union MyUnion switch (Selector)
   {
      case STRUCTTYPE: Foo fooData;
      case VALTYPE: Bar barData;
   };
};
