// $Id$

/**
 * @file Exception_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef CFT_EXCEPTION_TEST_CONNECTOR_IDL_
#define CFT_EXCEPTION_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/Exception_Test_Base.idl"

#pragma ciao lem "Connector/Exception_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/Exception_Test_BaseTypeSupport.idl"
#endif

module ::CCM_DDS::Typed < ::CFTExceptionTest, ::CFTExceptionTestSeq> CFTExceptionTestConn;
#endif /* CFT_EXCEPTION_TEST_CONNECTOR_IDL_ */
