// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Keyed_Test_Connector.idl"

module Keyed_Test
{
  component Receiver
  {
    port KeyedTestConnector::DDS_Get info_out;
    attribute unsigned long rate;
    attribute unsigned short iterations;
    attribute unsigned short keys;
  };
};

#endif
