// $Id$
// Compliant to OMG 06-04-01, section 6.6.8

#if !defined (CCM_BASE_IDL)
#define CCM_BASE_IDL

module Components
{
  typeprefix Components "omg.org";

  exception InvalidConnection {};
  exception AlreadyConnected {};
  exception NoConnection {};
};
#endif /* CCM_BASE_IDL */
