// $Id$
// Compliant with OMG 06-04-01 Section 8.3.2

#if !defined (CCM_ENTERPRISECOMPONENT_IDL)
#define CCM_ENTERPRISECOMPONENT_IDL

module Components
{
  typeprefix Components "omg.org";

  local interface EnterpriseComponent {};
};
#endif /* CCM_CONTAINER_IDL */
