/* -*- C++ -*- */
//
// $Id$

#include <orb.idl>

module DynAnyTests
{
  struct enclosed_struct
  {
    float f;
    short s;
  };

  struct test_struct
  {
    char c;
    long l;
    enclosed_struct es;
  };

  typedef sequence<string<8> > test_seq;

  const unsigned long DIM = 2;
  typedef long test_array [DIM];

  enum test_enum
  {
    TE_ZEROTH,
    TE_FIRST,
    TE_SECOND,
    TE_THIRD,
    TE_FOURTH
  };

  union test_union switch (test_enum)
  {
    case TE_SECOND: CORBA::TypeCode tc;
    case TE_FOURTH: test_enum te;
    default: short s;
    case TE_THIRD: string str;
    case TE_ZEROTH: octet o;
  };

  typedef test_struct test_struct_alias;
  typedef test_union test_union_alias;

  union test_implicit_def switch (boolean) {
    case TRUE :
       test_enum tenum;
  } ;
};
