// $Id$

/**
 * @file Shapes_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef SHAPES_BASE_IDL
#define SHAPES_BASE_IDL

#pragma ndds typesupport "Base/Shapes_BaseSupport.h"
#pragma opendds typesupport "Base/Shapes_BaseTypeSupportC.h"
#pragma splice typesupport "Base/Shapes_BaseDscpC.h"

#pragma DCPS_DATA_TYPE "ShapeType"
#pragma DCPS_DATA_KEY "ShapeType color"

struct ShapeType {
  string color; //@key
  long x;
  long y;
  long shapesize;
};
typedef sequence<ShapeType> ShapeTypeSeq;
#pragma keylist ShapeType color

#pragma DCPS_DATA_TYPE "Attributes"
#pragma DCPS_DATA_KEY "Attributes shape"
#pragma DCPS_DATA_KEY "Attributes color"

struct Attributes {
  string shape; //@key
  string color; //@key
  float speed;
};
typedef sequence<Attributes> AttributesSeq;

#pragma keylist Attributes shape color

#endif
