// $Id$
#include <Components.idl>
#include "EC.idl"

module BasicSP
{
  local interface CCM_EC : ::Components::EnterpriseComponent, ::BasicSP::trigger
  {
    attribute long hertz;
  };

  local interface CCM_EC_Context  : ::Components::SessionContext
  {
    void push_timeout (in ::BasicSP::TimeOut ev);
  };

  local interface CCM_ECHomeExplicit : ::Components::HomeExecutorBase
  {
    ::Components::EnterpriseComponent new_EC (in long hertz);
  };

  local interface CCM_ECHomeImplicit
  {
    ::Components::EnterpriseComponent create () raises (::Components::CCMException);
  };

  local interface CCM_ECHome : CCM_ECHomeExplicit, CCM_ECHomeImplicit
  {
  };

};

module EC_Impl
{
  local interface _Context : ::BasicSP::CCM_EC_Context, ::Components::SessionContext
  {
  };

};

