// $Id$

#ifndef FAULTCORRELATIONMANAGER_IDL
#define FAULTCORRELATIONMANAGER_IDL

#include "orbsvcs/orbsvcs/LWFT/FaultNotification.idl"
#include "ExecutionManagerDaemon.idl"

module DAnCE 
{
  interface FaultCorrelationManager : FLARE::FaultNotification, DAnCE::ExecutionManagerDaemon {
    /* This function is not invoked remotely. Instead,
       FLARE::FaultNotification::app_failure is invoked by RM. */
     void stop_failover_unit (in string fou_id); 
     FLARE::ApplicationList FOU_participants(in string app);
  };
};

#endif /* FAULTCORRELATIONMANAGER_IDL */
