// $Id$

/**
 * @file PSL_DeadlineTest_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef PSL_DeadlineTest_CONNECTOR_IDL_
#define PSL_DeadlineTest_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/PSL_DeadlineTest_Base.idl"

#pragma ciao lem "Connector/PSL_DeadlineTest_ConnectorE.idl"

module PSL_DeadlineTest
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> PSLDeadlineConnector;
};

#endif /* PSL_DeadlineTest_CONNECTOR_IDL_ */
