//$Id$
//=============================================================================
/**
 * @file BMDevice.idl
 *
 * Definition of the BMDevice component
 *
 * @author Balachandran Natarajan <bala@dre.vanderbilt.edu>
 */
//=============================================================================
#ifndef CIAO_BMDEVICE_IDL
#define CIAO_BMDEVICE_IDL

#include "BasicSP.idl"

module BasicSP
{
  component BMDevice
  {
    provides ReadData data_read;
    publishes DataAvailable data_available;
    consumes TimeOut timeout_value;
  };

  home BMDeviceHome manages BMDevice
  {
  };
};

#endif /*CIAO_BMDEVICE_IDL */
