
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl RTCORBA_Quoter_Common
// ------------------------------
#ifndef RTCORBA_QUOTER_COMMON_EXPORT_H
#define RTCORBA_QUOTER_COMMON_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (RTCORBA_QUOTER_COMMON_HAS_DLL)
#  define RTCORBA_QUOTER_COMMON_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && RTCORBA_QUOTER_COMMON_HAS_DLL */

#if !defined (RTCORBA_QUOTER_COMMON_HAS_DLL)
#  define RTCORBA_QUOTER_COMMON_HAS_DLL 1
#endif /* ! RTCORBA_QUOTER_COMMON_HAS_DLL */

#if defined (RTCORBA_QUOTER_COMMON_HAS_DLL) && (RTCORBA_QUOTER_COMMON_HAS_DLL == 1)
#  if defined (RTCORBA_QUOTER_COMMON_BUILD_DLL)
#    define RTCORBA_Quoter_Common_Export ACE_Proper_Export_Flag
#    define RTCORBA_QUOTER_COMMON_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define RTCORBA_QUOTER_COMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* RTCORBA_QUOTER_COMMON_BUILD_DLL */
#    define RTCORBA_Quoter_Common_Export ACE_Proper_Import_Flag
#    define RTCORBA_QUOTER_COMMON_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define RTCORBA_QUOTER_COMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* RTCORBA_QUOTER_COMMON_BUILD_DLL */
#else /* RTCORBA_QUOTER_COMMON_HAS_DLL == 1 */
#  define RTCORBA_Quoter_Common_Export
#  define RTCORBA_QUOTER_COMMON_SINGLETON_DECLARATION(T)
#  define RTCORBA_QUOTER_COMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* RTCORBA_QUOTER_COMMON_HAS_DLL == 1 */

// Set RTCORBA_QUOTER_COMMON_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (RTCORBA_QUOTER_COMMON_NTRACE)
#  if (ACE_NTRACE == 1)
#    define RTCORBA_QUOTER_COMMON_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define RTCORBA_QUOTER_COMMON_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !RTCORBA_QUOTER_COMMON_NTRACE */

#if (RTCORBA_QUOTER_COMMON_NTRACE == 1)
#  define RTCORBA_QUOTER_COMMON_TRACE(X)
#else /* (RTCORBA_QUOTER_COMMON_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define RTCORBA_QUOTER_COMMON_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (RTCORBA_QUOTER_COMMON_NTRACE == 1) */

#endif /* RTCORBA_QUOTER_COMMON_EXPORT_H */

// End of auto generated file.
