
//=============================================================================
/**
 *  @file    pragma.idl
 *
 *  $Id$
 *
 *  This file contains examples of IDL code that has
 *  caused problems in the past for the TAO IDL
 *  compiler. This test is to make sure the problems
 *  stay fixed.
 *
 *
 *  @author Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
 */
//=============================================================================


#pragma prefix "anvil.com"

interface hello {};

// These declarations all at one time caused the prefix above
// to be dropped.

typedef string FuBar;

enum ClusterFu
  {
    CHAOS,
    MAYHEM
  };

interface aloha;

const long GangBa = -278;

exception Riot {};

interface goodbye {};

module A
{
  exception my_exception {};
};

module salutation
{
// This prefix applies only in this module
# pragma prefix "hammer.com"

  interface sayonara {};
};

// 'anvil.com' returns
interface ciao {};

interface aloha {};

