// $Id$
//=============================================================================
/**
 * @file BasicSP.idl
 *
 * Definition of events, and common interfaces used in the BasicSP module.
 *
 * @author Balachandran Natarajan <bala@dre.vanderbilt.edu>
 */
//=============================================================================

#ifndef CIAO_BASIC_SP_IDL
#define CIAO_BASIC_SP_IDL

#include <Components.idl>

// @@NOTE: Do we need a pragma prefix. Anyway its broken now in TAO..
// #pragma prefix ""

module BasicSP
{

  /**
   * @NOTE: Not sure whether this is a good abstraction. Just copying
   *  the stuff from Cadena folks.
   */
  /**
   * @interface ReadData
   *
   */

  interface ReadData {
    string get_data ();
  };

  /**
   * @eventtype Events that represent timeouts
   */
  eventtype TimeOut {};

  /**
   * @eventtype Events that represent data availability
   */
  eventtype DataAvailable {};
};

#endif /*CIAO_BASIC_SP_IDL*/
