// $Id$

#include "DAnCE/Deployment/Deployment_TargetData.idl"

module CIAO
{
  module TM_Daemon
  {

    interface Daemon
    {
      ::Deployment::Domain getInitialDomain ();

      ::Deployment::Domain getSnapshot ();

      oneway void shutdown ();

    };
  };
};
