// $Id$

#ifndef DEPLOYMENT_APPLICATION_IDL
#define DEPLOYMENT_APPLICATION_IDL

#include "DAnCE/Deployment/Deployment_Connection.idl"

module Deployment
{
        exception StartError {
                string name;
                string reason;
        };

        exception InvalidConnection {
                string name;
                string reason;
        };

        interface Application {
                //@! in DOCGroup has additional parameter
                void finishLaunch (in Connections providedReference, in boolean start)
                        raises (StartError, InvalidConnection);
                        
                void start ()
                        raises (StartError);
        };
        
        typedef sequence < Application > Applications;
};

#endif /* DEPLOYMENT_APPLICATION_IDL */
