/**
 * @file CCM_ComponentServer_Base.idl
 * $Id$
 * Contains base types for all component server interfaces.
 * These interfaces are not part of the CCM standard.
 */

#ifndef COMPONENTSERVER_BASE_IDL_
#define COMPONENTSERVER_BASE_IDL_

#include "ccm/CCM_Exceptions.idl"
#include "ccm/CCM_Navigation.idl"

module Components
{
  typeprefix Components "omg.org";

  module Deployment
  {
    typedef string UUID;
    typedef string Location;

    typedef FailureReason InvalidConfigurationReason;
    const InvalidConfigurationReason UnknownConfigValueName = 0;
    const InvalidConfigurationReason InvalidConfigValueType = 1;
    const InvalidConfigurationReason ConfigValueRequired = 2;
    const InvalidConfigurationReason ConfigValueNotExpected = 3;

    exception InvalidConfiguration
    {
      InvalidConfigurationReason reason;
      FeatureName name;
    };

    exception UnknownImplId
    {
    };

    exception InvalidLocation
    {
    };

    exception ImplEntryPointNotFound
    {
    };

    exception InstallationFailure
    {
      FailureReason reason;
    };
  };
};

#endif
