/**
 * @file ComponentServer_Client.idl
 * Client side objects hosted by the NodeApplication.
 */

#ifndef COMPONENTSERVER_CLIENT_IDL_
#define COMPONENTSERVER_CLIENT_IDL_

#include "ComponentServer_Base.idl"

module Components
{
  typeprefix Components "omg.org";

  module Deployment
  {
    interface ComponentServer;
    typedef sequence<ComponentServer> ComponentServers;
    
    interface ComponentInstallation
    {
      void install(in UUID implUUID, in Location component_loc)
	raises (InvalidLocation, InstallationFailure);
      
      void replace(in UUID implUUID, in Location component_loc)
	raises (InvalidLocation, InstallationFailure);
      
      void remove(in UUID implUUID)
	raises (UnknownImplId, RemoveFailure);
      
      Location get_implementation(in UUID implUUID)
	raises(UnknownImplId, InstallationFailure);
    };

    interface ServerActivator
    {
      ComponentServer create_component_server(in ConfigValues config)
	raises(::Components::CreateFailure, 
	       ::Components::Deployment::InvalidConfiguration);
      
      void remove_component_server(in ComponentServer server)
	raises(::Components::RemoveFailure);
      
      ComponentServers get_component_servers();
    };
  };
};

#endif
