//  CosLifeCycleContainment Module, p 6-42 CORBAservices,
//  Life Cycle Service V1.0, 3/94

#include <CosContainment.idl>
#include <CosCompoundLifeCycle.idl>

module CosLifeCycleContainment {

        interface Relationship : 
                        CosCompoundLifeCycle::Relationship,
                        CosContainment::Relationship {};

        interface ContainsRole : 
                        CosCompoundLifeCycle::Role,
                        CosContainment::ContainsRole {};

        interface ContainedInRole : 
                        CosCompoundLifeCycle::Role,
                        CosContainment::ContainedInRole {};
};

