// CosObjectIdentity Module, p 9-19 CORBAservices, Relationship
// Service V1.0, 3/94

#ifndef __CosObjectIdentity_IDL
#define __CosObjectIdentity_IDL

#pragma prefix "omg.org"

module CosObjectIdentity 
{
        typedef unsigned long ObjectIdentifier;

        interface IdentifiableObject {
                        readonly attribute ObjectIdentifier constant_random_id;
                        boolean is_identical (
                                in IdentifiableObject other_object);
        };

};

#endif
