// CosReference Module, p 9-50 CORBAservices,
//  Relationship Service V1.0, 3/94

#include <CosGraphs.idl>

#pragma prefix "omg.org"

module CosReference 
{

        interface Relationship : 
                        CosRelationships::Relationship {};

        interface ReferencesRole : CosGraphs::Role {};

        interface ReferencedByRole : CosGraphs::Role {};

};
