// PIDL for CosTSInteroperation Module, p 10-59 
// CORBAservices, Transaction Service V1.0, 3/94

#include <CosTransactions.idl>

#pragma prefix "org.omg"

module CosTSInteroperation 
{ // PIDL
        struct otid_t {
                long formatID; /*format identifier. 0 is OSI TP */
                long bequal_length;
                sequence <octet> tid;
	};
        struct TransIdentity {
                CosTransactions::Coordinator coordinator;
                CosTransactions::Terminator terminator;
                otid_t otid;
	};
        struct PropagationContext {
                unsigned long timeout;
                TransIdentity current;
                sequence <TransIdentity> parents;
                any implementation_specific_data;
        };
};

