/**
 * Definitions of all CORBA System Exceptions defined in the CORBA module.
 * We need the Helper classes generated for these exceptions but we do not
 * want the code for the Exception classes or Holder classes.
 */

#ifndef _SYSEX_IDL
#define _SYSEX_IDLx1


#pragma prefix "omg.org"

module CORBA 
{
    // Note: this used to be 'completion_status' but was renamed to
    // CompletionStatus in the Java mapping

    enum CompletionStatus { COMPLETED_YES, COMPLETED_NO, COMPLETED_MAYBE };

#define ex_body { unsigned long minor; CompletionStatus completed;}
	
    exception UNKNOWN  ex_body;
    exception BAD_PARAM  ex_body;
    exception NO_MEMORY  ex_body;
    exception IMP_LIMIT  ex_body;
    exception COMM_FAILURE  ex_body;
    exception INV_OBJREF  ex_body;
    exception NO_PERMISSION  ex_body;
    exception INTERNAL  ex_body;
    exception MARSHAL  ex_body;
    exception INITIALIZE  ex_body;
    exception NO_IMPLEMENT  ex_body;
    exception BAD_TYPECODE  ex_body;
    exception BAD_OPERATION  ex_body;
    exception NO_RESOURCES  ex_body;
    exception NO_RESPONSE  ex_body;
    exception PERSIST_STORE  ex_body;
    exception BAD_INV_ORDER  ex_body;
    exception TRANSIENT  ex_body;
    exception FREE_MEM  ex_body;
    exception INV_IDENT  ex_body;
    exception INV_FLAG  ex_body;
    exception INTF_REPOS  ex_body;
    exception BAD_CONTEXT  ex_body;
    exception OBJ_ADAPTER  ex_body;
    exception DATA_CONVERSION  ex_body;
    exception OBJECT_NOT_EXIST  ex_body;
    exception TRANSACTION_REQUIRED  ex_body;
    exception TRANSACTION_ROLLEDBACK  ex_body;
    exception INVALID_TRANSACTION ex_body;
    exception INV_POLICY ex_body;
    exception CODESET_INCOMPATIBLE ex_body;
    exception TRANSACTION_MODE ex_body;
    exception TRANSACTION_UNAVAILABLE ex_body;

};

#endif /* _SYSEX_IDL */
