// -*- C++ -*-

//=============================================================================
/**
 *  @file    ParserErrors.h
 *
 *  $Id$
 *
 *  @author Krishnakumar B <kitty@cs.wustl.edu>
 */
//=============================================================================

#ifndef _ACEXML_PARSER_ERRORS_H_
#define _ACEXML_PARSER_ERRORS_H_

#include "ace/pre.h"
#include "ACEXML/parser/parser/Parser_export.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

enum ACEXML_Error {
  ACEXML_INVIP,
  ACEXML_LESS,
  ACEXML_GREAT,
  ACEXML_INVCO,
  ACEXML_DUPDOC,
  ACEXML_EOF,
  ACEXML_INVXMLDECL,
  ACEXML_INVVERSION,
  ACEXML_ENOTSUP,
  ACEXML_ENCMISMATCH,
  ACEXML_EINT,
  ACEXML_INVPI,
  ACEXML_INVDOCKEYWORD,
  ACEXML_INVDOCNAME,
  ACEXML_MISSINGROOT,
  ACEXML_RDATTR,
  ACEXML_DUPPREFIX,
  ACEXML_DUPATTR,
  ACEXML_NSERR,
  ACEXML_ECHAR,
  ACEXML_ETAG,
  ACEXML_ECDATASEC,
  ACEXML_MKDECLKEYWORD,
  ACEXML_MKINVCH,
  ACEXML_MKDECL,
  ACEXML_EELEMENT,
  ACEXML_ERDELENAME,
  ACEXML_EEMPTY,
  ACEXML_EANY,
  ACEXML_ERDELE,
  ACEXML_EENTITY,
  ACEXML_INVREF,
  ACEXML_ENTNAME,
  ACEXML_ENTVALUE,
  ACEXML_DUPENT,
  ACEXML_INVEXTID,
  ACEXML_UNDATA,
  ACEXML_ENDATA,
  ACEXML_EATTLIST,
  ACEXML_EATTNAME,
  ACEXML_ECDATA,
  ACEXML_EID,
  ACEXML_EENTITIES,
  ACEXML_ENMTOKEN,
  ACEXML_ENMTOKENS,
  ACEXML_ENOTATION,
  ACEXML_LPAREN,
  ACEXML_ENOTNAME,
  ACEXML_ENMNAME,
  ACEXML_INVATTRTYPE,
  ACEXML_EREQUIRED,
  ACEXML_EIMPLIED,
  ACEXML_EFIXED,
  ACEXML_EINVFIXED,
  ACEXML_INVNOTNAME,
  ACEXML_ESYSTEM,
  ACEXML_EPUBLIC,
  ACEXML_ELITERAL,
  ACEXML_ESYSPUB,
  ACEXML_EPCDATA,
  ACEXML_EMIXED,
  ACEXML_ERPAREN,
  ACEXML_ESUBELE,
  ACEXML_ECHOICE,
  ACEXML_INVCHAR
};

#include "ace/post.h"

#endif /* _ACEXML_PARSER_ERRORS_H_ */
