//$Id$
//Input_Adapter.idl

#ifndef RACE_INPUT_ADAPTER_IDL
#define RACE_INPUT_ADAPTER_IDL

#include <Components.idl>
#include "../../Plan_Analyzer/Interface/PlanIngress.idl"

module CIAO
{
  module RACE
  {
    component Input_Adapter
    {
      uses PlanIngress ingress;
    };
  };
};

#endif /* RACE_INPUT_ADAPTER_IDL */
