// $Id$

#ifndef GATEWAY_IDL
#define GATEWAY_IDL

module Gateway
{
  interface Object_Factory
  {
    Object create_object (in string interface_repository_id,
			  in Object gatewayed_object);
  };

};

#endif  /* GATEWAY_IDL */
