//
// $Id$

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  /// A very simple interface
  interface Basic
  {
    /// Return a simple string
    string get_string ();

    /// A method to shutdown the ORB
    /**
     * This method is used to simplify the test shutdown process
     */
    oneway void shutdown ();

    /// A method to remove the servant from the LoadManager Object Group.
    oneway void remove_member ();
  };
};

