// $Id$
/**
 * @file ICEventSource.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests implied IDL of event sources.
 */

#include <Components.idl>

module ImpliedSources
{
  eventtype foo_event
    {
    };

  eventtype bar_event
    {
    };

  component Foo
    {
      publishes foo_event p_foo;
    };

  component Bar
    {
      emits bar_event e_bar;
    };
  /*
  interface test
    {
      ImpliedSources::FooEventConsumers::foo_eventConsumer test_op ();
      ImpliedSources::BarEventConsumers::bar_eventConsumer test_op_1 ();
    };
  */
};

