// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Updater_Connector.idl"

module Updater
{
  component Receiver
  {
    //port CCM_DDS::TestTopic::DDS_Get info_get;
    port CCM_DDS::TestTopic::DDS_StateListen info_out;
    //provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
   };
};

#endif
