// $Id$

#ifndef DANCE_ARTIFACT_INSTALLATION_HANDLER_IDL
#define DANCE_ARTIFACT_INSTALLATION_HANDLER_IDL

#include "DAnCE/Deployment/Deployment_PlanError.idl"

module DAnCE
{
  /// Each ArtifactInstallationHandler knows how to handle
  /// a single protocol.
  native ArtifactInstallationHandler;

  // the installation handlers are implemented as native
  // objects rather than CORBA objects
#if 0
  interface ArtifactInstallationHandler
  {
    readonly attribute string protocol_prefix;

    void initialize ()
      raises (::Deployment::PlanError);

    void clear ()
      raises (::Deployment::PlanError);

    // Install should mangle the URI in the location field to specify the
    // URI of the next resolution that need be attempted.
    void install (in string plan_uuid,
                  inout string location,
                  in property_map properties);
      raises (::Deployment::PlanError);

    void remove (in string plan_uuid,
                 in string location);
  };
#endif

};

#endif /* DANCE_ARTIFACT_INSTALLATION_HANDLER_IDL */
