// $Id$

/**
 * @file SL_OneByOne_Connector.idl
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef SL_ONEBYONE_CONNECTOR_IDL_
#define SL_ONEBYONE_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/SL_OneByOne_Base.idl"

#pragma ciao lem "Connector/SL_OneByOne_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/SL_OneByOne_BaseTypeSupport.idl"
#endif

module SL_OneByOne
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> SL_OneByOneConnector;
};

#endif /* SL_OneByOne_CONNECTOR_IDL_ */
