// $Id$

/**
 * @file IDL_Test_Connector.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef IDL_TEST_CONNECTOR_IDL_
#define IDL_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/IDL_Test_Base.idl"

#pragma ciao lem "Connector/IDL_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/IDL_Test_BaseTypeSupport.idl"
#endif

module ::CCM_DDS::Typed < ::IDL_Test, ::IDL_TestSeq> IDL_Connector;

#endif /* IDL_Test_CONNECTOR_IDL_ */
