// $Id$

/**
 * @file Latency_Test_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef LATENCY_TEST_CONNECTOR_IDL_
#define LATENCY_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/Latency_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/Latency_Test_ConnectorE.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::LatencyTest, ::LatencyTestSeq> LatencyTest;
};

module Latency_Test
{
  connector Latency_Test_Connector : ::CCM_DDS::LatencyTest::DDS_Event
  {
  };
};

#endif /* Latency_Test_CONNECTOR_IDL_ */
