// $Id$

/**
 * @file LatencyTT_Test_Connector.idl
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 *
 * by-hand translation of the idl3p.
 */

#ifndef LATENCYTT_TEST_CONNECTOR_IDL_
#define LATENCYTT_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include <ccm_dds.idl>

#include "Base/LatencyTT_Test_Base.idl"

#pragma ciao lem "Connector/LatencyTT_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/LatencyTT_Test_BaseTypeSupport.idl"
#endif

module LatencyTT_Test
{
  module ::CCM_DDS::Typed < ::LatencyTTTest, ::LatencyTTTestSeq> LatencyTTTestConn;
};

#endif /* LatencyTT_Test_CONNECTOR_IDL_ */
