#
# Makefile for building the TAO AVStreams tests
#

DIRS = \
        Asynch_Three_Stage \
        Component_Switching \
        Full_Profile \
        Multicast \
        Multicast_Full_Profile \
        Pluggable \
        Simple_Three_Stage \
        Simple_Two_Stage \
        Simple_Two_Stage_With_QoS

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
