// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/LNE_Test_Connector.idl"

module LNE_Test
{
  component Receiver
  {
    port CCM_DDS::ListenNotEnabledTest::DDS_Listen info_listen;
    provides CCM_DDS::ConnectorStatusListener info_listen_connector_status;
  };
};

#endif
