// $Id$
#ifndef RACE_SA_POP_INPUT_ADAPTER_IDL
#define RACE_SA_POP_INPUT_ADAPTER_IDL

#include <Components.idl>
#include "common/OpString.idl"
#include "common/RACE_common.idl"
#include "Input_Adapters/Base/Input_Adapter_Base.idl"

module CIAO
{
  module RACE
  {
    module Input_Adapter
    {
      interface Admin
      {
        /// "Schedule" a string for future deployment.
        boolean add_string (in OperationalString opstring,
                            out UUID ID);

        /// Remove a string that was scheduled for deployment. Raises
        /// UnknownID.
        boolean delete_string (in UUID ID)
          raises (UnknownID);

        /// Deploy a string right away.
        boolean deploy_string (in OperationalString opstring,
                               out UUID ID);

        /// Deploy a string that was previously scheduled via
        /// add_string. Raises UnknownID.
        boolean deploy_string_with_id (in UUID ID)
          raises (UnknownID);

        /// Modify a previously scheduled/deployed string. Raises UnknownID.
        boolean modify_string (in OperationalString opstring,
                               in UUID ID)
          raises (UnknownID);

        /// Teardown a string. Raises UnknownID.
        boolean tear_down_string (in UUID ID)
          raises (UnknownID);

      };

      component SA_POP_IA_Component : Input_Adapter_Base
      {
        provides Admin admin;
      };

      home SA_POP_IA_Component_Home manages SA_POP_IA_Component
      {
      };
    };
  };

};

#endif /* RACE_SA_POP_INPUT_ADAPTER_IDL */
