// -*- IDL -*-

// $Id$

// Included for compatibility with the CORBA 2 specification.

#ifndef TAO_ORB_IDL
#define TAO_ORB_IDL

#include <Policy.pidl>

#pragma prefix "omg.org"

module CORBA
{
  typedef string  ORBid;
  typedef unsigned long Flags;
  typedef string Identifier;
  typedef string RepositoryId;

  struct NamedValue
  {
    Identifier name;
    any argument;
    long len;
    Flags arg_modes;
  };

  enum exception_type
  {
    NO_EXCEPTION,
    USER_EXCEPTION,
    SYSTEM_EXCEPTION
  };

  enum ParameterMode
  {
    PARAM_IN,
    PARAM_OUT,
    PARAM_INOUT
  };

  typedef string ObjectId;
  typedef sequence <ObjectId> ObjectIdList;

  typedef unsigned short ServiceType;
  typedef unsigned long ServiceOption;
  typedef unsigned long ServiceDetailType;

  struct ServiceDetail
  {
    ServiceDetailType service_detail_type;
    sequence <octet> service_detail;
  };

  struct ServiceInformation
  {
    sequence <ServiceOption> service_options;
    sequence <ServiceDetail> service_details;
  };

  // Portable Interceptor specification adds these types.
  typedef sequence<string> StringSeq;
  typedef sequence<wstring> WStringSeq;
  typedef sequence<octet> OctetSeq;

};

#pragma prefix ""

#endif /* TAO_ORB_IDL */
