// $Id$

/**
 * @@ Compile this file with:
 *
 *     tao_idl -I W:/ACE_wrappers/TAO Component_Base.idl
 *     tao_idl -I ../.. \
 *          -Wb,export_macro=CIAO_Export \
 *          -Wb,export_include=CIAO_export.h \
 *          -Wb,pre_include="ace/pre.h" \
 *          -Wb,post_include="ace/post.h" \
 *          CCM_Navigation.idl
 */

//#define CIAO_HAS_IMPORT_KEYWORD

#if !defined (CCM_NAVIGATION_IDL)
#define CCM_NAVIGATION_IDL

#include "tao/orb_types.pidl"
#include "tao/StringSeq.pidl"

module Components
{
  typeprefix Components "omg.org";

  typedef string FeatureName;
  typedef sequence<FeatureName> NameList;

  valuetype PortDescription
  {
    public FeatureName name;
    public CORBA::RepositoryId type_id;
  };

  valuetype FacetDescription : PortDescription
  {
    public Object facet_ref;
  };

  typedef sequence<FacetDescription> FacetDescriptions;

  exception InvalidName {};
  interface Navigation
  {
    Object provide_facet (in FeatureName name)
      raises (InvalidName);
    FacetDescriptions get_all_facets();
    FacetDescriptions get_named_facets (in NameList names)
      raises (InvalidName);
    boolean same_component (in Object object_ref);
  };
};
#endif /* CCM_NAVIGATION_IDL */
