// $Id$

#if !defined (CCM_BASE_IDL)
#define CCM_BASE_IDL

module Components
{
  typeprefix Components "omg.org";

  exception InvalidConnection {};
  exception AlreadyConnected {};
  exception NoConnection {};
};
#endif /* CCM_BASE_IDL */
