// $Id$
/// NOT Compliant with OMG 06-04-01 Section 6.7.6

#if !defined (CCM_HOMES_IDL)
#define CCM_HOMES_IDL

#include "ccm/CCM_Home.idl"

module Components
{
  typeprefix Components "omg.org";

  /**
   * @@ Added by wotte for continued compatibility with OFCCM
   */
  typedef sequence<CCMHome> CCMHomes;
};

#endif /* CCM_HOMES_IDL */
