//$Id$:

#ifndef CIAO_HELLO_IDL
#define CIAO_HELLO_IDL

#include <Components.idl>

#pragma ciao lem "../Hello_Base/Hello_BaseE.idl"

module Hello
{
  interface ReadMessage
  {
    string get_message();
  };

  eventtype TimeOut
  {
    public string data;
  };
};

#endif /* CIAO_HELLO_IDL */
