// $Id$

/**
 * @file   SL_Disabled_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef SL_DISABLED_BASE_IDL
#define SL_DISABLED_BASE_IDL

#pragma ndds typesupport "Base/SL_Disabled_BaseSupport.h"
#pragma opendds typesupport "Base/SL_Disabled_BaseSupportImpl.h"

#pragma DCPS_DATA_TYPE "TestTopic"
#pragma DCPS_DATA_KEY "TestTopic key"

struct TestTopic {
  string key; //@key
  long x;
};

typedef sequence<TestTopic> TestTopicSeq;

#endif
