// $Id$

/**
 * @file Getter_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef GETTER_TEST_BASE_IDL
#define GETTER_TEST_BASE_IDL

struct GetterTest {
  string key;
  long iteration;
};

typedef sequence<GetterTest> GetterTest_Seq;

#endif
