// $Id$

module MCast
{

  interface Server
  {
    // = TITLE
    //
    // = DESCRIPTION
    //     Prints out the status.

    boolean connect_server ();
    // Return <true> if the server received the
    // request from the client.

  };

};
