/**
 * @file Extension_Container.idl
 * @author Johnny Willemsen
 * $Id$
 * Extends the basic container interface for extension capabilities.
 */

#include "ciao/Containers/Container_Base.idl"
#include "ccm/Extension/CCM_ClientContainerInterceptorRegistration.idl"
#include "ccm/Extension/CCM_ServantContainerInterceptorRegistration.idl"
#include "ccm/Extension/CCM_ServerContainerInterceptorRegistration.idl"
#include "ccm/Extension/CCM_StubContainerInterceptorRegistration.idl"

module CIAO
{
  local interface Extension_Container : Container
  {
    Components::Cookie install_service_reference(in string service_id, in Object objref)
      raises (Components::CCMException);
    Object uninstall_service_reference(in Components::Cookie ck)
      raises (Components::CCMException);

    Components::ContainerPortableInterceptor::ClientContainerInterceptorRegistration
      get_client_interceptor_registration ()
        raises (Components::CCMException);
    Components::ContainerPortableInterceptor::ServerContainerInterceptorRegistration
      get_server_interceptor_registration ()
        raises (Components::CCMException);
    Components::ContainerPortableInterceptor::StubContainerInterceptorRegistration
      get_stub_interceptor_registration()
        raises (Components::CCMException);
    Components::ContainerPortableInterceptor::ServantContainerInterceptorRegistration
      get_servant_interceptor_registration()
        raises (Components::CCMException);
  };
};
