// $Id$

/**
 * @file Broker.idl
 * @author William R. Otte <wotte@dre.vanderbilt.edu>
 */

#ifndef BROKER_IDL
#define BROKER_IDL

#include "Connector/Quoter_Connector.idl"

module Quoter
{
  component Broker
  {
    port ::Quoter::DDS_Listen info_out;
  };
};

#endif
