#if !defined (ACE_CONFIG_GCC_2_7_2_H)
#define ACE_CONFIG_GCC_2_7_2_H

#define ACE_TEMPLATES_REQUIRE_SOURCE
#define ACE_HAS_BROKEN_EXPLICIT_TEMPLATE_DESTRUCTOR
#define ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION
#define ACE_LACKS_STATIC_DATA_MEMBER_TEMPLATES

#define ACE_HAS_GNU_CSTRING_H

#endif /* ACE_CONFIG_GCC_2_7_2_H */
