#----------------------------------------------------------------------------
#       $Id$
#
#       Makefile for building libACE using Visual Age C++ Incremental compiler
#----------------------------------------------------------------------------

all:
	vacbld_r ace.icc -severity=warning

realclean:
	vacbld_r ace.icc -clean
