// $Id$
/**
 * @file include.idl
 * @author Jeff Parsons <j.parsons@vanderbilt.edu>
 *
 * Tests tool's regeneration of IDL2 constructs, which
 * should be basically unchanged.
 */

#ifndef INCLUDE_IDL
#define INCLUDE_IDL

module pre_mod
{
  typedef long longarray[3][14][7];
  typedef string reasonsarray[4][2];
  typedef wstring<3> wstringofthree;
  typedef sequence<sequence<long> > seqoflongseq;

  exception wrong
  {
    seqoflongseq longseqseq;
    reasonsarray reasons;
    wstringofthree why;
  };

  enum which
  {
    ZERO,
    ONE,
    TWO
  };
};

const pre_mod::which which_one = pre_mod::ONE;

#endif /* INCLUDE_IDL */

