// $Id$

/**
 * @file Reader_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef READER_TEST_CONNECTOR_IDL_
#define READER_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/Reader_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

TYPED_MODULE( ::ReaderTest, ::ReaderTest_Seq, ReaderTest)

module Reader_Test
{
  connector Reader_Test_Connector : ::CCM_DDS::ReaderTest::DDS_Event
  {
  };
};

#endif /* Reader_Test_CONNECTOR_IDL_ */
