#if !defined (ACE_CONFIG_FSU_PTHREAD_H)
#define ACE_CONFIG_FSU_PTHREAD_H

#define ACE_LACKS_CONST_TIMESPEC_PTR

// Threads
#define	ACE_HAS_THREADS
#if !defined(ACE_MT_SAFE)
#define ACE_MT_SAFE 1
#endif

#define	ACE_HAS_PTHREADS
#define	ACE_HAS_FSU_PTHREADS
#define	ACE_HAS_THREAD_SPECIFIC_STORAGE
#define	ACE_HAS_PTHREAD_T
#define	ACE_HAS_SIGWAIT
#define	ACE_HAS_ONEARG_SIGWAIT
#define	ACE_HAS_PTHREAD_YIELD_VOID_PTR
#define	ACE_HAS_YIELD_VOID_PTR
#define	ACE_HAS_PTHREAD_ATTR_INIT
#define	ACE_HAS_PTHREAD_ATTR_DESTROY
#define	ACE_HAS_PTHREAD_DSTATE_PTR
#define	ACE_HAS_PTHREAD_EQUAL
#define	ACE_HAS_PTHREAD_GETSPECIFIC_DATAPTR
#define	ACE_LACKS_THREAD_STACK_ADDR
#define	ACE_LACKS_PTHREAD_THR_SIGSETMASK
#define	ACE_LACKS_CONDATTR_PSHARED
#define	ACE_LACKS_RWLOCK_T
#define	ACE_LACKS_SETSCHED

#define	ACE_LACKS_TIMESPEC_T

#include <pthread.h>

#if !defined(PTHREAD_STACK_MIN)
#define PTHREAD_STACK_MIN (1024*10)
#endif

#undef PTHREAD_INHERIT_SCHED

struct sched_param  
{
  int sched_priority;
  int prio;
};

#endif /* ACE_CONFIG_FSU_PTHREAD_H */
