
//=============================================================================
/**
 *  @file    DsEventLogAdmin.idl
 *
 *  $Id$
 *
 *  This module defines the EventLog and
 *  EventLogFactory interfaces.
 *
 *
 *  @author D A Hanvey (d.hanvey@qub.ac.uk)
 */
//=============================================================================


#ifndef DS_EVENT_LOG_ADMIN_IDL
#define DS_EVENT_LOG_ADMIN_IDL

#include "CosEventChannelAdmin.idl"
// CORBA Event Service

#include "DsLogAdmin.idl"

#pragma prefix "omg.org"

module DsEventLogAdmin
{
  interface EventLog : DsLogAdmin::Log,
      CosEventChannelAdmin::EventChannel{};

  interface EventLogFactory : DsLogAdmin::LogMgr,
      CosEventChannelAdmin::ConsumerAdmin
  {
  EventLog create (
    in DsLogAdmin::LogFullActionType  full_action,
    in unsigned long long     max_size,
    in DsLogAdmin::CapacityAlarmThresholdList thresholds,
    out DsLogAdmin::LogId id
  ) raises (DsLogAdmin::InvalidLogFullAction,
                    DsLogAdmin::InvalidThreshold);

  EventLog create_with_id (
    in DsLogAdmin::LogId id,
    in DsLogAdmin::LogFullActionType full_action,
    in unsigned long long max_size,
    in DsLogAdmin::CapacityAlarmThresholdList thresholds
  ) raises (DsLogAdmin::LogIdAlreadyExists,
                    DsLogAdmin::InvalidLogFullAction,
        DsLogAdmin::InvalidThreshold);

  };

};

#endif /* DS_EVENT_LOG_ADMIN_IDL */
