//$Id$
#ifndef _edf_sched_DSUI_FAMILIES_H
#define _edf_sched_DSUI_FAMILIES_H


#define edf_sched_NUM_FAMILIES 1


/* DSUI Family: EDF_SCHED
 * (null)
 */
#define EDF_SCHED_FAM 4
#define NUM_COUNTERS_EDF_SCHED 0
#define NUM_EVENTS_EDF_SCHED 31
#define NUM_HISTOGRAMS_EDF_SCHED 0


#define KOKYU_SCHED_START 0
#define BEGIN_NEW_SCHED_SEGMENT_END 1
#define BEGIN_NEW_SCHED_SEGMENT_START 2
#define CREATE_SCHED_PARAM 3
#define DISPATCHER_SHUTDOWN 4
#define ENTER_CLIENT_SCHED_TIME 5
#define CALL_KOKYU_DISPATCH_UPDATE_SCHEDULE 6
#define LEAVE_KOKYU_DISPATCH_UPDATE_SCHEDULE 7
#define LEAVE_CLIENT_SCHED_TIME 8
#define ENTER_SERVER_SCHED_TIME 9
#define LEAVE_SERVER_SCHED_TIME 10
#define ENTER_SERVER_DISPATCH_SCHEDULE 11
#define LEAVE_SERVER_DISPATCH_SCHEDULE 12
#define BEGIN_NESTED_SCHED_SEGMENT 13
#define BEGIN_UPDATE_SCHED_SEGMENT 14
#define END_UPDATE_SCHED_SEGMENT 15
#define END_SCHED_SEGMENT 16
#define END_NESTED_SCHED_SEGMENT 17
#define SEND_POLL 18
#define ENTER_SEND_REPLY 19
#define EXIT_SEND_REPLY 20
#define SEND_EXCEPTION 21
#define SEND_OTHER 22
#define ENTER_RECEIVE_REPLY 23
#define EXIT_RECEIVE_REPLY 24
#define RECEIVE_EXCEPTION 25
#define RECEIVE_OTHER 26
#define CONSTRUCTOR 27
#define CREATE_SCHED_PARAM_END 28
#define BEGIN_NESTED_SCHED_SEGMENT_END 29
#define END_SCHED_SEGMENT_END 30






#ifdef CONFIG_DSTREAM_EDF_SCHED 
#define DSUI_EVENT_LOG_EDF_SCHED_FAM( event, tag, len, data ) \
	if(dsui_event_enabled(EDF_SCHED_FAM, (event))) \
		dsui_event_log( EDF_SCHED_FAM, (event), (tag), (len), (data) )
#else
#define DSUI_EVENT_LOG_EDF_SCHED_FAM( event, tag, len, data ) 
#endif

#endif
