// -*- IDL -*-
//
// $Id$

#ifndef OBJECT_REFERENCE_FACTORY_IDL
#define OBJECT_REFERENCE_FACTORY_IDL

#include "tao/ObjectReferenceTemplate.pidl"

module ORT
{
  valuetype ObjectReferenceFactory
    : PortableInterceptor::ObjectReferenceFactory {};
};

#endif  /* OBJECT_REFERENCE_FACTORY_IDL */
