// $Id$

/**
 * @file Display_Base.idl
 *
 * Definition of events, and common interfaces used in HUDisplay module.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */

#ifndef HUDISPLAY_IDL
#define HUDISPLAY_IDL

#include <Components.idl>

#pragma ciao lem "../Display_Base/Display_BaseE.idl"

module HUDisplay
{
  struct GPS_position
  {
    long pos_x;
    long pos_y;
  };
  /**
   * @brief interface opmode defines the "operation mode" interface.
   */
  interface opmode
  {
    void start ();
    void stop ();
    boolean active ();
  };

  /**
   * @brief a timed event that happens at some fix rate.
   */
  eventtype tick
    {
      // We could put a timestamp here if desired.
    };

  /**
   * @brief interface position allows querying of a coordination.
   */
  interface position
  {
    GPS_position posxy ();
    unsigned short id ();
    boolean started ();
  };
};

#endif /* HUDISPLAY_IDL */
