//$Id$

#include "Basic.idl"

module Basic
{
  component Base supports Extra::Supernumerary, Extra::Superfluous
  {
    provides  ReadData data_read;
    attribute boolean is_not_necessary;
  };

  component CodeGen : Base
  {
    provides  ReadData data_out;
    uses      ReadData data_in;
#if !defined (CCM_NOEVENT)
    publishes DataAvailable out_avail;
    consumes  DataAvailable in_avail;
    provides  AnalyzeData data_crunch;
#endif
    readonly attribute boolean is_necessary;
  };

  home BaseHome supports Extra::Supernumerary manages Base
  {
    void base_do_nothing ();

    factory create_no_base (in long fake_id)
      raises (Extra::NoRhyme);

    finder find_no_base ();

    readonly attribute boolean is_useful;
  };

  home CodeGenHome : BaseHome manages CodeGen
  {
    factory create_no_derived ();

    finder find_no_derived ();

    attribute boolean is_not_useful;

    string do_nothing ();
  };
};
