// $Id$
#include "../Robot_Base.idl"

module RobotAssembly
{
  component WatchSettingManager
  {
	//Production Interfaces
	publishes DisplayWork Display;
	publishes ProcessPallet ProductionControl;
	publishes MovePalletRequest MovePallet;
	publishes ProductionStatus ProductionReport;
	consumes PalletProcessingStatus ProcessingStatus;
	consumes PalletStatusResponse PalletStatus;

	provides WorkOrderResponses DisplayResponse;
	consumes ProductionWorkOrder recvWorkOrder;

  };
  home WatchSettingManagerHome manages WatchSettingManager {};

};


