// $Id$

#ifndef LARGE_COMMON_IDL
#define LARGE_COMMON_IDL

#pragma ndds typesupport "Common/CommonSupport.h"
#pragma opendds typesupport "Common/CommonTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "LargeType"
#pragma DCPS_DATA_KEY "LargeType value"

struct LargeType {
  string value; //@key
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<LargeType> LargeTypeSeq;
#endif

#endif
