/**
 * @file Null_Component.idl
 *
 * @author Abdul Sowayan <sowayan@gmail.com>
 *
 * $Id$
 */

#ifndef NULL_COMPONENT_IDL
#define NULL_COMPONENT_IDL

#include <Components.idl>
#include "Null_Interface.idl"

#pragma ciao lem "Null_ComponentE.idl"

/**
 * @class Null_Component
 *
 * This component is intentionally left blank. Its purpose
 * is to measure the footprint of a component in CIAO.
 */
component Null_Component
{
  provides Null_Interface null_facet;
};

/**
 * @class Null_Component_Home
 *
 * @brief home for Null_Component
 */
home Null_ComponentHome manages Null_Component
{
};

#endif /* NULL_COMPONENT_IDL */


