// $Id$

// This is the equivalent interface definitions for Hello.idl.
//       tao_idl -I ../../.. -I ../../../.. -Sc helloC.idl

#include "ciao/CIAO_Component.pidl"

interface Hello
{
  // Return the greating string as:
  //   "Greeting from <helloname>.  How are you, <username>?"
  string sayhello (in string username);
};

interface HelloWorld
  : ::Components::CCMObject,
    Hello
{
};

interface HelloHomeExplicit
  : ::Components::CCMHome
{
};

interface HelloHomeImplicit
  : ::Components::KeylessCCMHome
{
  HelloWorld create ()
    raises (::Components::CreateFailure)
    ;
};

interface HelloHome
  : HelloHomeExplicit,
    HelloHomeImplicit
{
};
