// $Id$

/**
 * @file LOBO_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef LISTEN_ONE_BY_ONE_TEST_CONNECTOR_IDL_
#define LISTEN_ONE_BY_ONE_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/LOBO_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/LOBO_Test_ConnectorE.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::ListenOneByOneTest, ::ListenOneByOneTestSeq> ListenOneByOneTest;
};

module LOBO_Test
{
  connector LOBO_Test_Connector : ::CCM_DDS::ListenOneByOneTest::DDS_Event
  {
  };
};

#endif /* LOBO_Test_CONNECTOR_IDL_ */
