// $Id$

/**
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef COMPONENT_IDL
#define COMPONENT_IDL

#include "Connector/TypeRegistration_Test_Connector.idl"

module MLD_TypeRegistration_Test
{
  component CFTTestComponent
  {
    port MLDTypeRegistrationTestConn::DDS_Write   writer;
    port MLDTypeRegistrationTestConn::DDS_Listen  listener;
  };
};

#endif
