// $Id$

interface test
{
  void start_test (in unsigned long iterations);
  void end_test ();

  typedef sequence<octet> octets;
  oneway void method (in unsigned long iteration,
                      in octets payload);

  void shutdown ();
};
