// $Id$

/**
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef DDS_SENDER_IDL
#define DDS_SENDER_IDL

#include "Connector/Hello_Connector.idl"

module Hello
{
  component Sender
  {
    port Hello::DDS_Write info_in;
    attribute unsigned long rate;
    attribute unsigned long iterations;
    attribute string message;
    attribute boolean log_time;
    provides CCM_DDS::ConnectorStatusListener connector_status;
  };
};

#endif
