//$Id$
#ifndef RACE_XML_OUTPUT_ADAPTER_IDL
#define RACE_XML_OUTPUT_ADAPTER_IDL

#include "../Base/Output_Adapter.idl"

module CIAO
{
  module RACE
  {
    component XML_Output_Adapter : Output_Adapter
    {
    };
    
    home XML_Output_Adapter_Home manages XML_Output_Adapter
    {
    };
  };
};

#endif /* RACE_XML_OUTPUT_ADAPTER_IDL */
