// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/QFLS_Test_Connector.idl"

module QFLS_Test
{
  component Receiver
  {
    port QueryFilterListenStateTestConnector::DDS_StateListen info_state;

    attribute unsigned short keys;
    attribute unsigned short iterations;
  };
};

#endif
