// $Id$
/// Compliant with OMG 06-04-01 Section 10.3.1.2

#if !defined (CCM_ENUMERATION_IDL)
#define CCM_ENUMERATION_IDL

#if !defined (CCM_LW)

#include "ccm/CCM_Object.idl"

module Components
{
  typeprefix Components "omg.org";

  abstract valuetype Enumeration
  {
    boolean has_more_elements();
    CCMObject next_element();
  };

  valuetype DefaultEnumeration : Enumeration
  {
    private CCMObjectSeq objects;
  };
};

#endif

#endif /* CCM_ENUMERATION_IDL */
