// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef DDS_SENDER_IDL
#define DDS_SENDER_IDL
#include  <Components.idl>
module connector_test
{
  component A
  {
    attribute string topic_name_a;
  };

  component B : A
  {
    attribute string topic_name_b;
  };

  component C : B
  {
    attribute string topic_name_c;
  };
};
#endif
