// $Id$

#include "tao/StringSeq.pidl"
#include "tao/LongSeq.pidl"
#include "tao/OctetSeq.pidl"

interface Coffee
{
  struct Desc
  {
    string name;
  };

  attribute Desc description;
  /// Provides us the coffee object type.s
};

interface Alt_Mapping
{
  string test_unbounded_string (in string s1,
                                inout string s2,
                                out string s3);

  struct Fixed_Struct
  {
    long l;
    char c;
    short s;
    octet o;
    float f;
    boolean b;
    double d;
  };


  typedef sequence<Fixed_Struct> StructSeq;
  StructSeq test_struct_sequence (in StructSeq s1,
                                  inout StructSeq s2,
                                  out StructSeq s3);

  CORBA::StringSeq test_strseq (in CORBA::StringSeq s1,
                                inout CORBA::StringSeq s2,
                                out CORBA::StringSeq s3);

  CORBA::LongSeq test_long_sequence (in CORBA::LongSeq s1,
                                     inout CORBA::LongSeq s2,
                                     out CORBA::LongSeq s3);

  CORBA::OctetSeq test_octet_sequence (in CORBA::OctetSeq s1,
                                       inout CORBA::OctetSeq s2,
                                       out CORBA::OctetSeq s3);

  typedef string DUMMY;

  // Variable structure.
  struct Var_Struct
  {
    double dbl;
    DUMMY dummy1;
    boolean boole;
    DUMMY dummy2;
    short shrt;
    CORBA::StringSeq seq;
  };

  Var_Struct test_var_struct (in Var_Struct s1,
                              inout Var_Struct s2,
                              out Var_Struct s3);

  // Nested structs (We reuse the var_struct defn above to make a very
  // complicated nested structure).
  struct Nested_Struct
  {
    Var_Struct vs;
  };

  Nested_Struct test_nested_struct (in Nested_Struct s1,
                                    inout Nested_Struct s2,
                                    out Nested_Struct s3);

  void shutdown ();
  // Shutdown the server: this is useful to check for memory leaks,
  // performance results and in general to verify that orderly
  // shutdown is possible.
};
