// $Id$

/**
 * @file LMBM_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef LISTEN_MANY_BY_MANY_TEST_CONNECTOR_IDL_
#define LISTEN_MANY_BY_MANY_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/LMBM_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

TYPED_MODULE( ::ListenManyByManyTest, ::ListenManyByManyTest_Seq, ListenManyByManyTest)

module LMBM_Test
{
  connector LMBM_Test_Connector : ::CCM_DDS::ListenManyByManyTest::DDS_Event
  {
  };
};

#endif /* LMBM_Test_CONNECTOR_IDL_ */
