// $Id$

/**
 * @file VTS_String_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VTS_STRING_CONNECTOR_IDL_
#define VTS_STRING_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/VTopics_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/VTS_String_ConnectorE.idl"

TYPED_MODULE( ::TopicString, ::TopicString_Seq, TopicString)

module VTopics
{
  connector VTS_String_Connector : ::CCM_DDS::TopicString::DDS_Event
  {
  };
};

#endif /* VTS_STRING_CONNECTOR_IDL_ */
