// $Id$

#ifndef PRAGMAT_RECEIVER_IDL
#define PRAGMAT_RECEIVER_IDL

#include <Components.idl>

#include "Base/PragmaT.idl"

module PragmaT
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
