// $Id$

/**
 * @file DNM_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef DOUBLE_NESTED_MODULE_CONNECTOR_IDL_
#define DOUBLE_NESTED_MODULE_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/DNM_Base.idl"

#pragma ciao lem "Connector/DNM_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/DNM_BaseTypeSupport.idl"
#endif

module DNM_Test_Connector
{
  module Nested_Connector
  {
    module ::CCM_DDS::Typed < X::Y::Z::DNM_Test_Struct, X::Y::Z::DNM_Test_StructSeq> DNM_TestConnector;
  };
};

#endif /* DOUBLE_NESTED_MODULE_CONNECTOR_IDL_ */
