// $Id$

/**
 * @file PartialShutdown.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef PARTIALSHUTDOWN_IDL_
#define PARTIALSHUTDOWN_IDL_

#include <Components.idl>

#pragma ciao lem "Base/PartialShutdownE.idl"

module PartialShutdown
{
  local interface Writer {
    void write_line (in string line);
  };

  local interface Reader {
    CORBA::StringSeq read_lines ();
  };
};

#endif /* PARTIALSHUTDOWN_IDL_ */
