// $Id$

/**
 * @file QueryFilter_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef QUERY_FILTER_TEST_CONNECTOR_IDL_
#define QUERY_FILTER_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/QueryFilter_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/QueryFilter_Test_ConnectorE.idl"

module QueryFilter_Test
{
  module ::CCM_DDS::Typed < ::QueryFilterTest, ::QueryFilterTest_Seq> QueryFilterTestConn;
  connector QueryFilter_Test_Connector : QueryFilterTestConn::DDS_Event
  {
  };
};

#endif /* QUERY_FILTER_TEST_CONNECTOR_IDL_ */
