/* -*- IDL -*- */
//=============================================================================
/**
 *  @file    FT_NamingManager.idl
 *
 *  $Id$
 *
 *  This file is part of Fault Tolerant Naming Service.
 *
 *  @author Kevin Stanley <stanleyk@ociweb.com>
 */
//=============================================================================

#ifndef _FT_NAMING_MANAGER_IDL_
#define _FT_NAMING_MANAGER_IDL_

#include "orbsvcs/PortableGroup.idl"

#pragma prefix "omg.org"

module FT
{
  const string TAO_FT_OBJECT_GROUP_NAME = "TAO_FT_GroupName";
  const string TAO_FT_LOAD_BALANCING_STRATEGY = "TAO_FT_LB_Strategy";
  
  typedef long LoadBalancingStrategyValue;
  const LoadBalancingStrategyValue ROUND_ROBIN = 0;
  const LoadBalancingStrategyValue RANDOM = 1;
  const LoadBalancingStrategyValue ACTIVE = 2;

  typedef sequence<string> GroupNames;

  // Specification of NamingManager Interface
  interface NamingManager : PortableGroup::PropertyManager,
                            PortableGroup::ObjectGroupManager,
                            PortableGroup::GenericFactory
  {
    Object create_object_group (in string group_name,
                                in PortableGroup::_TypeId type_id,
                                in PortableGroup::Criteria the_criteria)
      raises (PortableGroup::ObjectNotCreated,
              PortableGroup::InvalidCriteria,
              PortableGroup::InvalidProperty,
              PortableGroup::CannotMeetCriteria);

    void delete_object_group (in string group_name)
      raises (PortableGroup::ObjectGroupNotFound);

    PortableGroup::ObjectGroup get_object_group_ref_from_name (
      in string group_name)
      raises (PortableGroup::ObjectGroupNotFound);

    // Return names of all groups defined in the NamingManager
    GroupNames groups ();

  };
};


#endif // _FT_NAMING_MANAGER_IDL_
