// $Id$

#ifndef CIF_COMPONENT_IDL_
#define CIF_COMPONENT_IDL_

#include <Components.idl>

module CIF
{
  interface foo
  {
    void do_foo ();
  };

  interface derived_foo : foo
  {
    void do_derived_foo ();
  };

  eventtype DoSomething {
    public string tobedone;
  };
  eventtype DoSomethingElse {
    public string tobedone;
  };

  component CIF_Provider
  {
    publishes DoSomething     publish_do_something;
    publishes DoSomethingElse publish_do_something_else;
    emits     DoSomething     emit_do_something;

    provides foo          provide_cif_foo;
    provides derived_foo  provide_cif_derived_foo;

    attribute short provider_id;
  };

  component CIF_User
  {
    consumes DoSomething consume_do_something;

    uses foo             use_cif_foo;
    uses multiple foo    use_multiple_foo;
    uses derived_foo     use_cif_derived_foo;

    attribute short user_id;
  };

  home CIF_UserHome manages CIF_User
  {
  };
};

#endif /* CIF_COMPONENT_IDL_ */
