// $Id$

/**
 * @file FSS_Event_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef FIXED_SIZE_STRUCT_EVENT_CONNECTOR_IDL_
#define FIXED_SIZE_STRUCT_EVENT_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/FSS_Event_Base.idl"

#pragma ciao lem "Connector/FSS_Event_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/FSS_Event_BaseTypeSupport.idl"
#endif

module FSS_Event
{
  module ::CCM_DDS::Typed < ::FixedStructSizeTest, ::FixedStructSizeTestSeq> FixedStructSizeTestConnector;
};

#endif /* FSS_Event_CONNECTOR_IDL_ */
