//
// $Id$
//

interface Test
{
  oneway void test_method (in short arg);

  typedef sequence<long> long_seq;
  oneway void test_long_sequence (in long_seq input);

  // Shut down the ORB.
  oneway void shutdown ();
};
