// $Id$

// ===========================================================
//
// @file BMDeviceE.idl
//
// Handlecrafted "generated" code. :)
//
// @author Balachandran Natarajan <bala@dre.vanderbilt.edu>
//
// ===========================================================

#ifndef CIAO_BMDEVICEE_IDL
#define CIAO_BMDEVICEE_IDL

#include "CCM_Container.idl"
#include "BMDevice.idl"       // Original component IDL definition
#include "../BasicSPE.idl"

module BasicSP
{
  local interface CCM_BMDevice_Executor
  : Components::EnterpriseComponent
  {
  };

  local interface CCM_BMDevice
    : Components::EnterpriseComponent
  {
    CCM_ReadData get_data_out ();
    void push_timeout20 (in TimeOut ev);
  };

  /** Context Interface
   *
   * Notice that we are taking a shortcut here to inherit the
   * component-specific context from SessionContext directly instead
   * of CCMContext.
   */
  local interface CCM_BMDevice_Context
  : Components::SessionContext
  {
    void push_out_data (in DataAvailable ev);
  };

  local interface CCM_BMDeviceHomeExplicit
    : Components::HomeExecutorBase
  {
  };

  local interface CCM_BMDeviceHomeImplicit
  {
    ::Components::EnterpriseComponent create ()
      raises (::Components::CCMException);
  };

  local interface CCM_BMDeviceHome
    : CCM_NavDisplayHomeExplicit,
      CCM_NavDisplayHomeImplicit
  {
  };
};

#endif /* NAVDISPLAYE_IDL */
