/**
 * @file Null_Interface.idl
 *
 * @author Abdul Sowayan <sowayan@gmail.com>
 *
 * $Id$
 */

#ifndef NULL_INTERFACE_IDL
#define NULL_INTERFACE_IDL

#pragma ciao lem "Null_InterfaceE.idl"

/**
 * @interface Null_Interface
 */
interface Null_Interface
{
  void null_operation();
};

#endif /* NULL_INTERFACE_IDL */
