// $Id$

/**
 * @file PSL_SampleLost_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef PSL_SampleLost_CONNECTOR_IDL_
#define PSL_SampleLost_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/PSL_SampleLost_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/PSL_SampleLost_ConnectorE.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> TestTopic;
};

module PSL_SampleLost
{
  connector PSL_SampleLost_Connector : ::CCM_DDS::TestTopic::DDS_Event
  {
  };
};

#endif /* PSL_SampleLost_CONNECTOR_IDL_ */
