// $Id$

#ifndef FAULTNOTIFICATION_IDL
#define FAULTNOTIFICATION_IDL

module FLARE {

  typedef sequence<string> ApplicationList;

  interface FaultNotification {
    void app_failure (in string host,
                      in ApplicationList applications);
  };

  exception NotifyRegistrationError {};

  typedef unsigned long NotificationId;

  interface FaultNotifier {

    NotificationId register_fault_notification (in FaultNotification receiver)
      raises (NotifyRegistrationError);

    void unregister_fault_notification (in NotificationId id);

  };

};

#endif /* FAULTNOTIFICATION_IDL */
