// -*- IDL -*-
// $Id$

#ifndef HOSTMONITOR_IDL
#define HOSTMONITOR_IDL

interface HostMonitor
{
  boolean register_process (in string process_id, 
                            in string hostname, 
                            in long _port);

  boolean unregister_process (in string process_id);

  // returns a different port number every time on which the
  // client shall then listen for heartbeats. This will be passed
  // in by the client in the register_process call.
  short heartbeat_port ();

  void dump ();
};

#endif // HOSTMONITOR_IDL

