// -*- IDL -*-

//=============================================================================
/**
 *  @file    LWFTDataStructures.idl
 *
 *  $Id$
 *
 *  @author  Friedhelm Wolf (fwolf@dre.vanderbilt.edu)
 */
//=============================================================================

#ifndef _LWFT_DATASTRUCTURES_IDL_
#define _LWFT_DATASTRUCTURES_IDL_

typedef sequence<Object> ObjectList;

struct Rank
{
  string object_id;
  boolean now;
  ObjectList ior_list;
};

typedef sequence<Rank> RankList;

#endif /* _LWFT_DATASTRUCTURES_IDL_ */
