// -*- IDL -*-
// $Id$

#ifndef OBJECT_REFERENCE_FACTORY_IDL
#define OBJECT_REFERENCE_FACTORY_IDL

#include "tao/ObjRefTemplate/ObjectReferenceTemplate_include.pidl"

module lwft
{

  valuetype ObjectReferenceFactory
    : PortableInterceptor::ObjectReferenceFactory {};

};

#endif  /* OBJECT_REFERENCE_FACTORY_IDL */
