// -*- IDL -*-

//=============================================================================
/**
 *  @file    ReplicatedApplication.idl
 *
 *  $Id$
 *
 *  @author  Friedhelm Wolf (fwolf@dre.vanderbilt.edu)
 */
//=============================================================================

#ifndef _REPLICATED_APPLICATION_IDL_
#define _REPLICATED_APPLICATION_IDL_

interface StateSynchronizationAgent;

interface ReplicatedApplication 
{
  /// Setter method for the interal state.
  /// @param state_value represents the internal state encapsulated
  ///        into an any value
  void set_state (in any state_value);

  /// Getter method for the internal state.
  /// remark: it's not clear if this is necessary
  any get_state ();
  
  attribute StateSynchronizationAgent agent;
  attribute string object_id;
};

#endif /* _REPLICATED_APPLICATION_IDL_ */
