// -*- IDL -*-

//=============================================================================
/**
 *  @file    StateSynchronizationAgent.idl
 *
 *  $Id$
 *
 *  @author  Friedhelm Wolf (fwolf@dre.vanderbilt.edu)
 */
//=============================================================================

#ifndef _STATE_SYNCHRONIZATION_AGENT_IDL_
#define _STATE_SYNCHRONIZATION_AGENT_IDL_

#include "ReplicatedApplication.idl"
#include "LWFTDataStructures.idl"

interface StateSynchronizationAgent 
{
  /// Triggers an serial update of the state information 
  /// to all registered replicas.
  void state_changed (in string object_id);

  /// Used by the ReplicationManager to update information about
  /// active replicas.
  void update_rank_list (in RankList replicas);

  /// Informs the replication manager about applications for which
  /// it is responsible for replication. 
  void register_application (in string object_id,
			                       in ReplicatedApplication app);
};

#endif /* _STATE_SYNCHRONIZATION_AGENT_IDL_ */
