// $Id$

/**
 * @file MultipleTemp_Connector.idl
 * @author Marijke Hengstmengel
 */

#ifndef MULTIPLE_TEMP_CONNECTOR_IDL_
#define MULTIPLE_TEMP_CONNECTOR_IDL_

#include <Components.idl>
#include <Connector/ccm_dds_mlt.idl>

#include "Base/MultipleTemp_Base.idl"

#pragma ciao lem "Connector/MultipleTemp_ConnectorE.idl"

module MultipleTemp
{
  module ::CCM_DDS::Duplex_Typed < ::TestTopicOne, ::TestTopicOneSeq, ::TestTopicTwo, ::TestTopicTwoSeq> MultipleTempConnector;
};

#endif /* MULTIPLE_TEMP_CONNECTOR_IDL_ */
