// $Id$

/**
 * @file PSL_SampleLost_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef PSL_SampleLost_CONNECTOR_IDL_
#define PSL_SampleLost_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/PSL_SampleLost_Base.idl"

#pragma ciao lem "Connector/PSL_SampleLost_ConnectorE.idl"

module PSL_SampleLost
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> PSL_SampleLostConnector;
};

#endif /* PSL_SampleLost_CONNECTOR_IDL_ */
