// $Id$

/**
 * @file
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include "Connector/Hello_Connector.idl"

module Hello
{
  component Receiver
  {
    port Hello::DDS_Listen info_out;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;

    attribute string name;
    attribute unsigned long expected_samples;
  };
};

#endif
