// $Id$

#include <Components.idl>
#include "Test.idl"

module Simple
{
  component SimpleFT supports test
  {
    attribute Object COMPONENT_REFERENCE;
    attribute string object_id;
    attribute double load;
    attribute short  role;
  };

  home SimpleFTHome manages SimpleFT
  {
  };
};
