// $Id$
//=============================================================================
/**
 * @file BBN_UAV.idl
 *
 * Definition of events, and used in the BBN_UAV module.
 *
 * @author George Edwards <g.edwards@vanderbilt.edu>
 * @author Gan Deng <gan.deng@vanderbilt.edu>
 */
//=============================================================================

#ifndef CIAO_BBN_UAV_IDL
#define CIAO_BBN_UAV_IDL

#include <Components.idl>

// @@NOTE: Do we need a pragma prefix. Anyway its broken now in TAO..
// #pragma prefix ""

module BBN_UAV
{
  /**
   * @eventtype: emitted by Satellite, and consumed by CAOC.
   */
  eventtype TargetLocated {};

  /**
   * @eventtype: emitted by CAOC, and consumed by UAV_GS
   *             (UAV ground station).
   */
  eventtype PrepareCapture {};

  /**
   * @eventtype: published by UAV_GS, and consumed by UAVs.
   */
  eventtype StartCapture {};

  /**
   * @eventtype: emitted by CAOC, and consumed by Engagement.
   */
  eventtype PrepareEngage {};

  /**
   * @eventtype: emitted by Engagement, and consumed by Battle.
   */
  eventtype StartEngage {};
  
  /**
   * @eventtype: emitted by Engagement, and consumed by UCAV_GS.
   */
  eventtype PrepareMove {};
  
  /**
   * @eventtype: published by UCAV_GS, and consumed by UCAVs.
   */
  eventtype StartMove {};

  /**
   * @eventtype: published by UAV, and consumed by Satellite.
   */
  eventtype UAVReady {};

  /**
   * @eventtype: published by UCAV, and consumed by Satellite.
   */
  eventtype UCAVReady {};

  /**
   * @eventtype: published by Battle, and consumed by Satellite.
   */
  eventtype BattleReady {};

};

#endif /*CIAO_BBN_UAV_IDL*/
