// $Id$

/**
 * @file
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/State_Connection_Test_Connector.idl"

module State_Connection_Test
{
  component Receiver
  {
    port State_ConnectionTestConnector::DDS_Read info_read;
    port State_ConnectionTestConnector::DDS_Get info_get;
    port State_ConnectionTestConnector::DDS_Listen info_listen;
    port State_ConnectionTestConnector::DDS_StateListen info_statelisten;
  };
};

#endif
