//
// $Id$
//

interface Simple_Server {

  oneway void set_x_angle (in long x);
  oneway void set_y_angle (in long y);
  // Set the X and Y angles in the view port..

  void shutdown ();
  // Shutdown the ORB
};
