//$Id$:

#ifndef CIAO_HELLO_IDL
#define CIAO_HELLO_IDL

#include <Components.idl>

module Hello
{
  interface ReadMessage
  {
    string get_message();
  };
    
  typedef sequence <octet> OctetStream;
  
  eventtype TimeOut
  {
    //public string data;
    public OctetStream payload;
  };
};

#endif /* CIAO_HELLO_IDL */
