
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl ComponentServer_Configurator
// ------------------------------
#ifndef COMPONENTSERVER_CONFIGURATOR_EXPORT_H
#define COMPONENTSERVER_CONFIGURATOR_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (COMPONENTSERVER_CONFIGURATOR_HAS_DLL)
#  define COMPONENTSERVER_CONFIGURATOR_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && COMPONENTSERVER_CONFIGURATOR_HAS_DLL */

#if !defined (COMPONENTSERVER_CONFIGURATOR_HAS_DLL)
#  define COMPONENTSERVER_CONFIGURATOR_HAS_DLL 1
#endif /* ! COMPONENTSERVER_CONFIGURATOR_HAS_DLL */

#if defined (COMPONENTSERVER_CONFIGURATOR_HAS_DLL) && (COMPONENTSERVER_CONFIGURATOR_HAS_DLL == 1)
#  if defined (COMPONENTSERVER_CONFIGURATOR_BUILD_DLL)
#    define ComponentServer_Configurator_Export ACE_Proper_Export_Flag
#    define COMPONENTSERVER_CONFIGURATOR_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define COMPONENTSERVER_CONFIGURATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* COMPONENTSERVER_CONFIGURATOR_BUILD_DLL */
#    define ComponentServer_Configurator_Export ACE_Proper_Import_Flag
#    define COMPONENTSERVER_CONFIGURATOR_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define COMPONENTSERVER_CONFIGURATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* COMPONENTSERVER_CONFIGURATOR_BUILD_DLL */
#else /* COMPONENTSERVER_CONFIGURATOR_HAS_DLL == 1 */
#  define ComponentServer_Configurator_Export
#  define COMPONENTSERVER_CONFIGURATOR_SINGLETON_DECLARATION(T)
#  define COMPONENTSERVER_CONFIGURATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* COMPONENTSERVER_CONFIGURATOR_HAS_DLL == 1 */

// Set COMPONENTSERVER_CONFIGURATOR_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (COMPONENTSERVER_CONFIGURATOR_NTRACE)
#  if (ACE_NTRACE == 1)
#    define COMPONENTSERVER_CONFIGURATOR_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define COMPONENTSERVER_CONFIGURATOR_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !COMPONENTSERVER_CONFIGURATOR_NTRACE */

#if (COMPONENTSERVER_CONFIGURATOR_NTRACE == 1)
#  define COMPONENTSERVER_CONFIGURATOR_TRACE(X)
#else /* (COMPONENTSERVER_CONFIGURATOR_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define COMPONENTSERVER_CONFIGURATOR_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (COMPONENTSERVER_CONFIGURATOR_NTRACE == 1) */

#endif /* COMPONENTSERVER_CONFIGURATOR_EXPORT_H */

// End of auto generated file.
