// $Id$

/**
 * @file CFTLS_Test_Connector.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef CONTENTFILTEREDTOPIC_LISTEN_STATE_TEST_CONNECTOR_IDL_
#define CONTENTFILTEREDTOPIC_LISTEN_STATE_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/CFTLS_Test_Base.idl"

#pragma ciao lem "Connector/CFTLS_Test_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/CFTLS_Test_BaseTypeSupport.idl"
#endif

module CFTLS_Test
{
  module ::CCM_DDS::Typed < ::ContentFilteredTopicListenStateTest, ::ContentFilteredTopicListenStateTestSeq> ContentFilteredTopicListenStateTestConnector;
};

#endif /* CONTENTFILTEREDTOPIC_LISTEN_STATE_TEST_CONNECTOR_IDL_ */
