// $Id$

/**
 * @file   CSL_SRTest_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef CSL_SRTEST_BASE_IDL
#define CSL_SRTEST_BASE_IDL

#pragma ndds typesupport "Base/CSL_SRTest_BaseSupport.h"

struct TestTopic {
  string key; //@key
  long x;
};
typedef sequence<TestTopic> TestTopicSeq;

#endif
