// $Id$

/**
 * @file HelloGoodbye.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef HELLO_IDL_
#define HELLO_IDL_

#pragma ndds typesupport "Hello/HelloGoodbyeSupport.h"
#pragma opendds typesupport "Hello/HelloGoodbyeTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "Hello::HelloGoodbye"
#pragma DCPS_DATA_KEY "Hello::HelloGoodbye hello"

module Hello
{
  struct HelloGoodbye {
    string hello;  //@key
    long iteration;
  };
  #if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<HelloGoodbye> HelloGoodbyeSeq;
#endif
};


#endif /* HELLO_IDL_ */
