// $Id$

#ifndef THREECOMP_SENDER_IDL
#define THREECOMP_SENDER_IDL

#include <Components.idl>

#include "Base/ThreeComp.idl"
#include "Base/ThreeComp_no_ami.idl"

#pragma ciao ami4ccm receptacle "ThreeComp::Sender::run_my_foo"

module ThreeComp
{
  component Sender
  {
    /// For synchronous invocation
    uses multiple MyFoo run_my_foo;
    provides State  do_my_state;

    // test for no ami4ccm interface
    provides MyBar  do_my_bar;
  };
};

#endif
