// $Id$

// Forward declaration to make recursive construct.
valuetype BaseNode;

//@@ Dosn't work for now
//typedef sequence<BaseNode> BaseNodeSeq;

// Performance test: One may try to pass
// over the wire a cyclic graph and measure
// how quickly TAO evaporates memory ;-)

valuetype BaseNode
{
  //@@ TODO:
  //public BaseNodeSeq node_seq;

  public BaseNode left;
  public BaseNode right;

};
