// $Id$

/**
 * @file Get_Invoker.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef GETTER_INVOKER_IDL
#define GETTER_INVOKER_IDL

interface GetInvoker
{
  void get_no_data ();
  void start_get_one (in string key, in long iteration);
  void start_get_many (in short keys, in long iterations);
};

#endif /* SAMPLE_INFO_IDL */
