#
# Makefile for building the ACE examples
#

DIRS = \
        Log_Msg \
        Map_Manager \
        Reactor \
        RMCast \
        Service_Configurator \
        Threads

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
