// $Id$
#include <Components.idl>
#include "BMDisplay.idl"

module BasicSP
{
  local interface CCM_BMDisplay : ::Components::EnterpriseComponent
  {
    void push_data_ready (in ::BasicSP::DataAvailable ev);
  };

  local interface CCM_BMDisplay_Context  : ::Components::SessionContext
  {
    ::BasicSP::ReadData get_connection_comp_data ();
  };

  local interface CCM_BMDisplayHomeExplicit : ::Components::HomeExecutorBase
  {
  };

  local interface CCM_BMDisplayHomeImplicit
  {
    ::Components::EnterpriseComponent create () raises (::Components::CCMException);
  };

  local interface CCM_BMDisplayHome : CCM_BMDisplayHomeExplicit, CCM_BMDisplayHomeImplicit
  {
  };

};

module BMDisplay_Impl
{
  local interface _Context : ::BasicSP::CCM_BMDisplay_Context, ::Components::SessionContext
  {
  };

};

