../../ACE_wrappers/bin/generate_export_file.pl       usr/share/ace/bin
../../ACE_wrappers/bin/split-cpp                     usr/share/ace/bin
../../ACE_wrappers/bin/g++dep                        usr/share/ace/bin
../../ACE_wrappers/bin/add_rel_link.sh               usr/share/ace/bin
../../ACE_wrappers/bin/depgen.pl                     usr/share/ace/bin
../../ACE_wrappers/bin/DependencyGenerator           usr/share/ace/bin
../../ACE_wrappers/include                           usr/share/ace
../../objdir/include/makeinclude/platform_macros.GNU usr/share/ace/include/makeinclude
usr/include/ace/*.{h,inl,cpp}
usr/include/ace/os_include
usr/lib/libACE.so
usr/lib/pkgconfig/ACE.pc
