// $Id$
/**
 * @file SimpleComponent.idl
 *
 * Tests simple component declarations.
 */

#include <Components.idl>

module VerySimple
{

  component Foo
    {
    };

  home FooHome manages Foo
    {
    };

};

module SupportsInterface
{
  interface foo_interface
    {
    };

  component Foo supports foo_interface
    {
    };

  home FooHome manages Foo
    {
    };

};


module SupportsMultiple
{
  interface foo_interface
    {
    };

  interface bar_interface
    {
    };

  component FooBar supports foo_interface, bar_interface
    {
    };

  home FooBarHome manages FooBar
    {
    };
};

module Inheritance
{
  interface foo_interface
    {
    };

  interface Bar_interface
    {
    };

  component Foo supports foo_interface
    {
    };

  component Bar : Foo
    {
    };

  home FooHome manages Foo
    {
    };

  home BarHome manages Bar
    {
    };


};

module Bug_2790_Regression
{
  // It is legal for a derived component to support an interface
  interface Wibble {};
  interface Wobble {};
  component Bobble {};
  component Bibble : Bobble supports Wibble, Wobble {};
};

