//
// $Id$
//

typedef sequence<long> LongSeq;

struct Structure
{
  short i;
  sequence<long> seq;
};

interface Simple_Server
{
  long test_method (in long x,
                    in Structure the_in_structure,
                    out Structure the_out_structure,
                    inout string name);

  oneway void shutdown ();
};
