// $Id$

// ============================================================================
//
// = FILENAME
//    DsNotifyLogAdmin.idl
//
// = DESCRIPTION
//    This module defines the NotifyLog and
//    NotifyLogFactory interfaces.
//
// = AUTHOR
//    David Hanvey (d.hanvey@qub.ac.uk)
//
// ============================================================================

#ifndef DS_NOTIFY_LOG_ADMIN_IDL
#define DS_NOTIFY_LOG_ADMIN_IDL

#include "DsEventLogAdmin.idl"
#include "CosNotifyChannelAdmin.idl"
#include "CosNotifyFilter.idl"
#include "CosNotification.idl"
#pragma prefix "omg.org"

module DsNotifyLogAdmin
{
  interface NotifyLog : DsEventLogAdmin::EventLog,
      CosNotifyChannelAdmin::EventChannel
  {
  CosNotifyFilter::Filter get_filter();
  void set_filter(in CosNotifyFilter::Filter filter);
  };

  interface NotifyLogFactory : DsLogAdmin::LogMgr,
      CosNotifyChannelAdmin::ConsumerAdmin
  {
  NotifyLog create (
    in DsLogAdmin::LogFullActionType  full_action,
    in unsigned long long     max_size,
    in DsLogAdmin::CapacityAlarmThresholdList thresholds,
    in CosNotification::QoSProperties initial_qos,
    in CosNotification::AdminProperties initial_admin,
    out DsLogAdmin::LogId id
  ) raises (DsLogAdmin::InvalidLogFullAction,
        DsLogAdmin::InvalidThreshold,
        CosNotification::UnsupportedQoS,
        CosNotification::UnsupportedAdmin);

  NotifyLog create_with_id (
    in DsLogAdmin::LogId id,
    in DsLogAdmin::LogFullActionType full_action,
    in unsigned long long max_size,
    in DsLogAdmin::CapacityAlarmThresholdList thresholds,
    in CosNotification::QoSProperties initial_qos,
    in CosNotification::AdminProperties initial_admin
  ) raises (DsLogAdmin::LogIdAlreadyExists,
        DsLogAdmin::InvalidLogFullAction,
        DsLogAdmin::InvalidThreshold,
        CosNotification::UnsupportedQoS,
        CosNotification::UnsupportedAdmin);
  };

};

#endif /* DS_NOTIFY_LOG_ADMIN_IDL */
