// $Id$
/**
 * @file Events.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests implied IDL for event types.
 */

#include <Components.idl>

module ImpliedEvent
{
  eventtype foo
    {
    };
  /*
  interface test_foo
    {
      fooConsumer test_op ();
    };
  */
};
