//
// $Id$
//

module Test
{
  typedef sequence<octet> Payload;

  interface Payload_Receiver
  {
    /// Send the data using a twoway operat
    oneway void more_data (in Payload the_payload);

    /// Return the number of messages received so far
    long get_message_count ();
  };
};
