// $Id$

#ifndef MY_TEST_IDL
#define MY_TEST_IDL

#include <Components.idl>

module Test
{
   struct Foo
   {
      double myDouble;
      string myStr;
   };
};

exception ExceptType {};

module TemplTest<typename T, exception S>
{
   interface Bar
   {
      // having 2 or more args of the same template param type
      // causes an "illegal redefinition" error
      T myTestOperation(in T inParam, out T outParam) raises(S);
   };

   struct TemplStruct
   {
      T myTemplField;
   };
};

module TemplTest<Test::Foo, ExceptType> TemplatedInst;

component Baz
{
   provides  TemplatedInst::Bar         myBar;
   attribute TemplatedInst::TemplStruct myTemplStruct;
};

#endif
