// $Id$

/**
 * @file UCC_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef USERDATA_COPY_COUNT_TEST_BASE_IDL
#define USERDATA_COPY_COUNT_TEST_BASE_IDL

#pragma ndds typesupport "Base/UCC_Test_BaseSupport.h"
#pragma opendds typesupport "Base/UCC_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "UCCVariableSizedStructTest"
#pragma DCPS_DATA_KEY "UCCVariableSizedStructTest symbol"

struct UCCVariableSizedStructTest {
  string symbol; //@key
  long x;
  long y;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<UCCVariableSizedStructTest> UCCVariableSizedStructTestSeq;
#endif

#pragma DCPS_DATA_TYPE "UCCFixedSizedStructTest"

struct UCCFixedSizedStructTest {
  long x;
  long y;
  long z;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<UCCFixedSizedStructTest> UCCFixedSizedStructTestSeq;
#endif

#endif /* USERDATA_COPY_COUNT_TEST_BASE_IDL */
