// $Id$

/**
 * @file QCLE_Test_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef QUERY_CONDITION_LISTEN_EVENT_TEST_BASE_IDL
#define QUERY_CONDITION_LISTEN_EVENT_TEST_BASE_IDL

#pragma ndds typesupport "Base/QCLE_Test_BaseSupport.h"
#pragma opendds typesupport "Base/QCLE_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "QueryConditionListenEventTest"
#pragma DCPS_DATA_KEY "QueryConditionListenEventTest key"

struct QueryConditionListenEventTest {
  string key; //@key
  long iteration;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<QueryConditionListenEventTest> QueryConditionListenEventTestSeq;
#endif

#endif
