#
# Makefile for building RTCORBA tests
#

DIRS = \
	Banded_Connections \
	Client_Propagated \
	Client_Protocol \
	Server_Declared \
	Server_Protocol \
	MT_Client_Protocol_Priority

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
