/**
 * @file CIAO_Servant_Activator.idl
 * @author William R. Otte <wotte@dre.vanderbilt.edu>
 * $Id$
 * Local interface extensions for the CIAO servant activator.
 */

#ifndef CIAO_SERVANT_ACTIVATOR_IDL
#define CIAO_SERVANT_ACTIVATOR_IDL

#include "tao/PortableServer/ServantActivator.pidl"
#include "ciao/Servants/CIAO_Port_Activator.idl"

module CIAO
{
  local interface Servant_Activator : PortableServer::ServantActivator
  {
    boolean update_port_activator (in PortableServer::ObjectId oid);

    boolean register_port_activator (in Port_Activator pa);
  };
};

#endif
