// $Id$

module CCM_AMI
{
  typedef long Cookie;

  struct InternalException
    {
      long id;
      string error_string;
    };

  exception InternalError
    {
      InternalException ex;
    };

  // Sender/Receiver interface
  interface AMI_foo
    {
      long foo (in string in_str, out string answer)
        raises (InternalError);
    };

  // callback interface from AMI-component to Sender component
  interface AMI_foo_callback
    {
      void foo_callback_handler (in Cookie ck, in long result, in string answer);
      void foo_callback_excep   (in Cookie ck, in InternalException exception_holder);
    };

  // AMI component. Sender calls AMI-component and AMI-component calls Receiver
  // using the AMI_foo interface.
  interface AMI_ami_foo
    {
      Cookie sendc_foo (in string in_str);
    };
};
