// $Id$

/**
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef COMPONENT_IDL
#define COMPONENT_IDL

#include "Connector/QosProfile_Test_Connector.idl"

module QosProfile_Test
{
  component QosProfileComponent
  {
    port QosProfileTestConn::DDS_Write info_write;
  };
};

#endif /* COMPONENT_IDL */
