// $Id$

/**
 * @file VTS_Valuetype_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef VTS_VALUE_TYPE_CONNECTOR_IDL_
#define VTS_VALUE_TYPE_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/VTopics_Base.idl"

#pragma ciao lem "Conn_Valuetype/VTS_Valuetype_ConnectorE.idl"

#if !defined (CIAO_DDS4CCM_OPENDDS)
module VTopics
{
  module ::CCM_DDS::Typed < ::TopicValuetype, ::TopicValuetypeSeq> TopicValuetypeConnector;
  //module ::CCM_DDS::Typed < ::X_Valuetype, ::X_ValuetypeSeq> X_ValuetypeConnector;
};
#endif

#endif /* VTS_VALUE_TYPE_CONNECTOR_IDL_ */
