// $Id$

/**
 * @file Updater_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef UPDATER_CONNECTOR_IDL_
#define UPDATER_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/Updater_Base.idl"

#pragma ciao lem "Connector/Updater_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/Updater_BaseTypeSupport.idl"
#endif

module Updater
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> UpdaterConnector;
};

#endif /* UPDATER_CONNECTOR_IDL_ */
