//
// $Id$
//

interface Callback
{
  oneway void shutdown ();
  // A safe way to shutdown the client, using either clean shutdowns
  // or "catastrophic failures".

  void callback_method ();
  // A simple remote call

};

interface Simple_Server
{
  long test_method (in boolean do_callback);
  // Just call a method on the server,

  void callback_object (in Callback cb);
  // send the callback object to the server

  oneway void shutdown ();
  // A safe way to shutdown the server, it is a oneway function so we
  // will never get a COMM_FAILURE error
};
