// $Id$
// Compliant with OMG 06-04-01 section 15

#ifndef DEPLOYMENT_STARTERROR_IDL
#define DEPLOYMENT_STARTERROR_IDL

module Deployment {
  exception StartError {
    string name;
    string reason;
 };
};
#endif /* DEPLOYMENT_STARTERROR_IDL */

