// $Id$
/**
 * @file ICEventSink.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests implied idl features of event sinks
 */

#include <Components.idl>

module ImpliedEventSink
{
  eventtype foo_event
    {
    };

  component Foo
    {
      consumes foo_event c_foo;
    };
  /*
  interface test
    {
      ImpliedEventSink::FooEventConsumers::foo_eventConsumer test_a ();
    };
  */
};
