// $Id$

#ifndef TAO_RTEC_BASE_IDL
#define TAO_RTEC_BASE_IDL

module RtecBase
{
  // Define the basic types shared between the scheduling service and
  // the event service.
  // They are on a separate file to decouple the real-time event
  // service from the scheduling service implementation.

  enum Dependency_Type_t
  // Specify one-way or two-way call.
  {
    ONE_WAY_CALL,
    TWO_WAY_CALL
  };

  typedef long handle_t;
  // RT_Info's are assigned per-application
  // unique identifiers.

  struct Dependency_Info
  {
    Dependency_Type_t dependency_type;
    long number_of_calls;
    handle_t rt_info;
    // Notice the reference to the RT_Info we
    // depend on.
  };
  
  typedef long OS_Priority;
  typedef long Preemption_Subpriority_t;
  typedef long Preemption_Priority_t;
};

#endif /* TAO_RTEC_BASE_IDL */
