//
// $Id$
//

module Test
{
  typedef sequence<octet> Payload;

  interface Receiver {
    /// Receive a big payload
    void receive_data (in Payload the_payload);

    /// Return the number of messages received so far
    long get_event_count ();
  };
};
