// $Id$

#ifndef AMI_IDL
#define AMI_IDL

#include <Components.idl>

#include "Base/HelloE.idl"

#define connector component

module Hello
{
  connector AMI_Sender
  {
    /// Provides the interface for Sender
    provides AMI_MyFoo sendc_run_my_foo;

    /// Uses the interface of the Receiver ('server')
    uses MyFoo run_my_foo;
  };
};


#endif
