package edu.vanderbilt.isis.meta;



public class WSML_udm_xml_0 {
	private static String str = new String();

	public static String getString()
	{
		if (str.length() == 0)
		{
			str +="<Diagram name=\"WSML\" version=\"1.00\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"Uml.xsd\">\n";
			str +="	<Association _id=\"idcc\" name=\"HeaderBinding\" assocClass=\"idb\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idcd\" max=\"-1\" min=\"0\" name=\"srcHeaderBinding\" target=\"id6\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idce\" max=\"-1\" min=\"0\" name=\"dstHeaderBinding\" target=\"id24\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idcf\" name=\"BodyBinding\" assocClass=\"idc\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idd0\" max=\"-1\" min=\"0\" name=\"srcBodyBinding\" target=\"id6\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idd1\" max=\"1\" min=\"1\" name=\"dstBodyBinding\" target=\"id26\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idd2\" max=\"-1\" min=\"0\" name=\"referedbyBindingRef\" target=\"id1c\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idd3\" max=\"1\" min=\"0\" name=\"ref\" target=\"id1e\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idd4\" name=\"BindingPortType\" assocClass=\"id30\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idd5\" max=\"-1\" min=\"0\" name=\"srcBindingPortType\" target=\"id1e\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idd6\" max=\"1\" min=\"1\" name=\"dstBindingPortType\" target=\"id2b\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idd7\" name=\"BindsOperation\" assocClass=\"id1f\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idd8\" max=\"-1\" min=\"0\" name=\"srcBindsOperation\" target=\"id21\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idd9\" max=\"1\" min=\"0\" name=\"dstBindsOperation\" target=\"id29\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idda\" name=\"PortBinding\" assocClass=\"id20\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"iddb\" max=\"-1\" min=\"0\" name=\"srcPortBinding\" target=\"id22\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"iddc\" max=\"1\" min=\"1\" name=\"dstPortBinding\" target=\"id1c\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"iddd\" max=\"-1\" min=\"0\" name=\"referedbyOperationRef\" target=\"id29\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idde\" max=\"1\" min=\"0\" name=\"ref\" target=\"id15\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"iddf\" max=\"-1\" min=\"0\" name=\"referedbyPart\" target=\"id2c\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"ide0\" max=\"1\" min=\"0\" name=\"ref\" target=\"id14\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"ide1\" max=\"-1\" min=\"0\" name=\"referedbyPartRef\" target=\"id2d\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"ide2\" max=\"1\" min=\"0\" name=\"ref\" target=\"id2c\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"ide3\" max=\"-1\" min=\"0\" name=\"referedbyInputRef\" target=\"id8\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"ide4\" max=\"1\" min=\"0\" name=\"ref\" target=\"id38\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"ide5\" max=\"-1\" min=\"0\" name=\"referedbyMessageRef\" target=\"id32\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"ide6\" max=\"1\" min=\"0\" name=\"ref\" target=\"id1d\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"ide7\" max=\"-1\" min=\"0\" name=\"referedbyFaultRef\" target=\"id33\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"ide8\" max=\"1\" min=\"0\" name=\"ref\" target=\"id36\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"ide9\" name=\"SOAPFaultExtension\" assocClass=\"ida\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idea\" max=\"-1\" min=\"0\" name=\"srcSOAPFaultExtension\" target=\"id33\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"ideb\" max=\"1\" min=\"1\" name=\"dstSOAPFaultExtension\" target=\"id25\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idec\" name=\"FaultMessage\" assocClass=\"id34\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"ided\" max=\"-1\" min=\"0\" name=\"srcFaultMessage\" target=\"id36\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idee\" max=\"1\" min=\"1\" name=\"dstFaultMessage\" target=\"id32\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idef\" name=\"OutputMessage\" assocClass=\"id35\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idf0\" max=\"-1\" min=\"0\" name=\"srcOutputMessage\" target=\"id37\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idf1\" max=\"1\" min=\"1\" name=\"dstOutputMessage\" target=\"id32\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idf2\" name=\"InputMessage\" assocClass=\"id39\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idf3\" max=\"-1\" min=\"0\" name=\"srcInputMessage\" target=\"id38\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idf4\" max=\"1\" min=\"1\" name=\"dstInputMessage\" target=\"id32\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idf5\" max=\"-1\" min=\"0\" name=\"referedbyOutputRef\" target=\"id7\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idf6\" max=\"1\" min=\"0\" name=\"ref\" target=\"id37\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idf7\" name=\"HeaderPart\" assocClass=\"id3\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idf8\" max=\"-1\" min=\"0\" name=\"srcHeaderPart\" target=\"id24\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idf9\" max=\"1\" min=\"1\" name=\"dstHeaderPart\" target=\"id2d\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idfa\" name=\"HeaderMessage\" assocClass=\"id5\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idfb\" max=\"-1\" min=\"0\" name=\"srcHeaderMessage\" target=\"id24\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idfc\" max=\"1\" min=\"0\" name=\"dstHeaderMessage\" target=\"id32\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Association _id=\"idfd\" name=\"BodyParts\" assocClass=\"id9\" nonpersistent=\"false\">\n";
			str +="		<AssociationRole _id=\"idfe\" max=\"-1\" min=\"0\" name=\"srcBodyParts\" target=\"id26\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="		<AssociationRole _id=\"idff\" max=\"-1\" min=\"0\" name=\"dstBodyParts\" target=\"id2d\" isPrimary=\"false\" isNavigable=\"true\"/>\n";
			str +="	</Association>\n";
			str +="	<Class _id=\"id3\" name=\"HeaderPart\" baseTypes=\"id4\" childRoles=\"id6f\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idf7\"/>\n";
			str +="	<Class _id=\"id5\" name=\"HeaderMessage\" baseTypes=\"id4\" childRoles=\"id6d\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idfa\"/>\n";
			str +="	<Class _id=\"id6\" name=\"IORef\" subTypes=\"id7 id8\" baseTypes=\"id4\" childRoles=\"id5f\" isAbstract=\"true\" stereotype=\"FCO\" associationRoles=\"idcd idd0\"/>\n";
			str +="	<Class _id=\"id9\" name=\"BodyParts\" baseTypes=\"id4\" childRoles=\"id6b\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idfd\"/>\n";
			str +="	<Class _id=\"ida\" name=\"SOAPFaultExtension\" baseTypes=\"id4\" childRoles=\"id63\" isAbstract=\"false\" stereotype=\"Connection\" association=\"ide9\"/>\n";
			str +="	<Class _id=\"idb\" name=\"HeaderBinding\" baseTypes=\"id4\" childRoles=\"id5d\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idcc\"/>\n";
			str +="	<Class _id=\"idc\" name=\"BodyBinding\" baseTypes=\"id4\" childRoles=\"id67\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idcf\"/>\n";
			str +="	<Class _id=\"idd\" name=\"ExtensibilityElement\" subTypes=\"ide idf id10 id11\" baseTypes=\"id4\" isAbstract=\"true\" stereotype=\"FCO\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"required\" type=\"Boolean\" ordered=\"false\" defvalue=\"false;\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id12\" name=\"SchemaBuiltins\" baseTypes=\"id4\" childRoles=\"idc3\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id42\"/>\n";
			str +="	<Class _id=\"id13\" name=\"AtomicType\" baseTypes=\"id14\" childRoles=\"id41\" isAbstract=\"false\" stereotype=\"Atom\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"typeCode\" type=\"String\" ordered=\"false\" defvalue=\"string;\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id15\" name=\"Operation\" subTypes=\"id16 id17 id18 id19\" baseTypes=\"id4\" childRoles=\"id95\" isAbstract=\"true\" stereotype=\"Model\" parentRoles=\"id44 id46 id48 id4a id4c\" associationRoles=\"idde\"/>\n";
			str +="	<Class _id=\"id11\" name=\"ExtensibleBinding\" subTypes=\"id1a\" baseTypes=\"idd\" childRoles=\"id51\" isAbstract=\"true\" stereotype=\"FCO\"/>\n";
			str +="	<Class _id=\"idf\" name=\"ExtensiblePort\" subTypes=\"id1b\" baseTypes=\"idd\" childRoles=\"id73\" isAbstract=\"true\" stereotype=\"FCO\"/>\n";
			str +="	<Class _id=\"id1c\" name=\"BindingRef\" baseTypes=\"id4\" childRoles=\"id7d\" isAbstract=\"false\" stereotype=\"Reference\" associationRoles=\"idd2 iddc\"/>\n";
			str +="	<Class _id=\"id1d\" name=\"Message\" baseTypes=\"id4\" childRoles=\"id93\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id4e\" associationRoles=\"ide6\"/>\n";
			str +="	<Class _id=\"id1e\" name=\"Binding\" baseTypes=\"id4\" childRoles=\"id8b\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id50 id52 id54 id56 id58\" associationRoles=\"idd3 idd5\"/>\n";
			str +="	<Class _id=\"id1f\" name=\"BindsOperation\" baseTypes=\"id4\" childRoles=\"id53\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idd7\"/>\n";
			str +="	<Class _id=\"id20\" name=\"PortBinding\" baseTypes=\"id4\" childRoles=\"id7f\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idda\"/>\n";
			str +="	<Class _id=\"id21\" name=\"BindingOperation\" baseTypes=\"id4\" childRoles=\"id4f\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id5a id5c id5e id60 id62 id64 id66 id68 id6a id6c id6e id70 id72\" associationRoles=\"idd8\"/>\n";
			str +="	<Class _id=\"id22\" name=\"Port\" baseTypes=\"id4\" childRoles=\"id7b\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id74 id76\" associationRoles=\"iddb\"/>\n";
			str +="	<Class _id=\"id23\" name=\"Types\" baseTypes=\"id4\" childRoles=\"id91\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id78 id7a\"/>\n";
			str +="	<Class _id=\"id10\" name=\"ExtensibleMessage\" subTypes=\"id24 id25 id26\" baseTypes=\"idd\" childRoles=\"id5b\" isAbstract=\"true\" stereotype=\"FCO\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"encodingStyle\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"use\" type=\"String\" ordered=\"false\" defvalue=\"literal;\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"namespace\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id27\" name=\"Service\" baseTypes=\"id4\" childRoles=\"id8d\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id7c id7e id80\"/>\n";
			str +="	<Class _id=\"id28\" name=\"Definitions\" baseTypes=\"id4\" childRoles=\"id99 idc6\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id82 id84 id86 id88 id8a id8c id8e id90 id92\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"targetNamespace\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id29\" name=\"OperationRef\" baseTypes=\"id4\" childRoles=\"id55\" isAbstract=\"false\" stereotype=\"Reference\" associationRoles=\"idd9 iddd\"/>\n";
			str +="	<Class _id=\"id2a\" name=\"Messages\" baseTypes=\"id4\" childRoles=\"id89\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id94\"/>\n";
			str +="	<Class _id=\"id2b\" name=\"PortType\" baseTypes=\"id4\" childRoles=\"id87\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id96 id98\" associationRoles=\"idd6\"/>\n";
			str +="	<Class _id=\"id2c\" name=\"Part\" baseTypes=\"id4\" childRoles=\"id4d\" isAbstract=\"false\" stereotype=\"Reference\" associationRoles=\"iddf ide2\"/>\n";
			str +="	<Class _id=\"id2d\" name=\"PartRef\" baseTypes=\"id4\" childRoles=\"id65\" isAbstract=\"false\" stereotype=\"Reference\" associationRoles=\"ide1 idf9 idff\"/>\n";
			str +="	<Class _id=\"ide\" name=\"ExtensibleOperation\" subTypes=\"id2e\" baseTypes=\"idd\" childRoles=\"id59\" isAbstract=\"true\" stereotype=\"FCO\"/>\n";
			str +="	<Class _id=\"id2f\" name=\"Import\" baseTypes=\"id4\" childRoles=\"id83\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id9a id9c\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"location\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"namespace\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id30\" name=\"BindingPortType\" baseTypes=\"id4\" childRoles=\"id8f\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idd4\"/>\n";
			str +="	<Class _id=\"id31\" name=\"Documentation\" baseTypes=\"id4\" childRoles=\"id4b id57 id71 id75 id79 id85 id97 id9b ida7 ida9 idb1\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"id9e\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"DocText\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"Mixed\" type=\"Boolean\" ordered=\"false\" defvalue=\"false;\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id8\" name=\"InputRef\" baseTypes=\"id6\" isAbstract=\"false\" stereotype=\"Reference\" associationRoles=\"ide3\"/>\n";
			str +="	<Class _id=\"id19\" name=\"OneWayOperation\" baseTypes=\"id15\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"ida0\"/>\n";
			str +="	<Class _id=\"id32\" name=\"MessageRef\" baseTypes=\"id4\" childRoles=\"id43 id61\" isAbstract=\"false\" stereotype=\"Reference\" associationRoles=\"ide5 idee idf1 idf4 idfc\"/>\n";
			str +="	<Class _id=\"id18\" name=\"RequestResponseOperation\" baseTypes=\"id15\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"ida2 ida4 ida6\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"parameterOrder\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id33\" name=\"FaultRef\" baseTypes=\"id4\" childRoles=\"id69\" isAbstract=\"false\" stereotype=\"Reference\" associationRoles=\"ide7 idea\"/>\n";
			str +="	<Class _id=\"id34\" name=\"FaultMessage\" baseTypes=\"id4\" childRoles=\"id45\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idec\"/>\n";
			str +="	<Class _id=\"id35\" name=\"OutputMessage\" baseTypes=\"id4\" childRoles=\"id47\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idef\"/>\n";
			str +="	<Class _id=\"id36\" name=\"Fault\" baseTypes=\"id4\" childRoles=\"ida5 idad\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"ida8\" associationRoles=\"ide8 ided\"/>\n";
			str +="	<Class _id=\"id37\" name=\"Output\" baseTypes=\"id4\" childRoles=\"ida3 idaf idb3\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"idaa\" associationRoles=\"idf0 idf6\"/>\n";
			str +="	<Class _id=\"id17\" name=\"SolicitResponseOperation\" baseTypes=\"id15\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"idac idae idb0\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"parameterOrder\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id38\" name=\"Input\" baseTypes=\"id4\" childRoles=\"id9f ida1 idab\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"idb2\" associationRoles=\"ide4 idf3\"/>\n";
			str +="	<Class _id=\"id39\" name=\"InputMessage\" baseTypes=\"id4\" childRoles=\"id49\" isAbstract=\"false\" stereotype=\"Connection\" association=\"idf2\"/>\n";
			str +="	<Class _id=\"id16\" name=\"NotificationOperation\" baseTypes=\"id15\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"idb4\"/>\n";
			str +="	<Class _id=\"id7\" name=\"OutputRef\" baseTypes=\"id6\" isAbstract=\"false\" stereotype=\"Reference\" associationRoles=\"idf5\"/>\n";
			str +="	<Class _id=\"id3a\" name=\"SchemaReference\" subTypes=\"id3b\" baseTypes=\"id4\" childRoles=\"idbf\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"idb6\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"id\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"schemaLocation\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id3c\" name=\"Attribute\" baseTypes=\"id4\" childRoles=\"id81 idb9 idbd\" isAbstract=\"false\" stereotype=\"Atom\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"Value\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id3d\" name=\"Element\" baseTypes=\"id14\" childRoles=\"id9d idb7 idbb\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"idb8 idba\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"schemaType\" type=\"String\" ordered=\"false\" defvalue=\"local;\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"Order\" type=\"Integer\" ordered=\"false\" defvalue=\"0;\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id14\" name=\"Referrable\" subTypes=\"id13 id3d\" baseTypes=\"id4\" isAbstract=\"true\" stereotype=\"FCO\" associationRoles=\"ide0\"/>\n";
			str +="	<Class _id=\"id3e\" name=\"Schema\" baseTypes=\"id4\" childRoles=\"id77 idb5 idc8\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"idbc idbe idc0\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"targetNamespace\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id3b\" name=\"SchemaImport\" baseTypes=\"id3a\" isAbstract=\"false\" stereotype=\"Model\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"namespace\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id2e\" name=\"SOAPOperation\" baseTypes=\"ide\" isAbstract=\"false\" stereotype=\"Atom\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"soapAction\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"style\" type=\"String\" ordered=\"false\" defvalue=\"document;\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id24\" name=\"SOAPHeaders\" subTypes=\"id3f id40\" baseTypes=\"id10\" isAbstract=\"true\" stereotype=\"FCO\" associationRoles=\"idce idf8 idfb\"/>\n";
			str +="	<Class _id=\"id40\" name=\"SOAPHeader\" baseTypes=\"id24\" isAbstract=\"false\" stereotype=\"Model\" parentRoles=\"idc2\"/>\n";
			str +="	<Class _id=\"id3f\" name=\"SOAPHeaderFault\" baseTypes=\"id24\" childRoles=\"idc1\" isAbstract=\"false\" stereotype=\"Atom\"/>\n";
			str +="	<Class _id=\"id25\" name=\"SOAPFault\" baseTypes=\"id10\" isAbstract=\"false\" stereotype=\"Atom\" associationRoles=\"ideb\"/>\n";
			str +="	<Class _id=\"id26\" name=\"SOAPBody\" baseTypes=\"id10\" isAbstract=\"false\" stereotype=\"Atom\" associationRoles=\"idd1 idfe\"/>\n";
			str +="	<Class _id=\"id1a\" name=\"SOAPBinding\" baseTypes=\"id11\" isAbstract=\"false\" stereotype=\"Atom\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"transport\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"style\" type=\"String\" ordered=\"false\" defvalue=\"document;\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id1b\" name=\"SOAPAddress\" baseTypes=\"idf\" isAbstract=\"false\" stereotype=\"Atom\">\n";
			str +="		<Attribute max=\"1\" min=\"1\" name=\"location\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"idc4\" name=\"RootFolder\" childRoles=\"idca\" isAbstract=\"false\" stereotype=\"Folder\" parentRoles=\"idc5 idc7 idc9 idcb\">\n";
			str +="		<Attribute max=\"1\" min=\"0\" name=\"name\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Class _id=\"id4\" name=\"MgaObject\" subTypes=\"id3 id5 id6 id9 ida idb idc idd id12 id15 id1c id1d id1e id1f id20 id21 id22 id23 id27 id28 id29 id2a id2b id2c id2d id2f id30 id31 id32 id33 id34 id35 id36 id37 id38 id39 id3a id3c id14 id3e\" isAbstract=\"true\">\n";
			str +="		<Attribute max=\"1\" min=\"0\" name=\"name\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="		<Attribute max=\"1\" min=\"0\" name=\"position\" type=\"String\" ordered=\"false\" registry=\"false\" visibility=\"public\" nonpersistent=\"false\"/>\n";
			str +="	</Class>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id41\" max=\"-1\" min=\"0\" target=\"id13\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id42\" target=\"id12\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id43\" max=\"-1\" min=\"0\" target=\"id32\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id44\" target=\"id15\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id45\" max=\"-1\" min=\"0\" target=\"id34\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id46\" target=\"id15\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id47\" max=\"-1\" min=\"0\" target=\"id35\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id48\" target=\"id15\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id49\" max=\"-1\" min=\"0\" target=\"id39\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id4a\" target=\"id15\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id4b\" max=\"1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id4c\" target=\"id15\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id4d\" max=\"-1\" min=\"0\" target=\"id2c\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id4e\" target=\"id1d\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id4f\" max=\"-1\" min=\"0\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id50\" target=\"id1e\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id51\" max=\"1\" min=\"1\" target=\"id11\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id52\" target=\"id1e\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id53\" max=\"-1\" min=\"0\" target=\"id1f\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id54\" target=\"id1e\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id55\" max=\"-1\" min=\"0\" target=\"id29\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id56\" target=\"id1e\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id57\" max=\"1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id58\" target=\"id1e\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id59\" max=\"1\" min=\"0\" target=\"ide\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id5a\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id5b\" max=\"-1\" min=\"1\" target=\"id10\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id5c\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id5d\" max=\"-1\" min=\"0\" target=\"idb\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id5e\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id5f\" max=\"-1\" min=\"0\" target=\"id6\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id60\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id61\" max=\"-1\" min=\"0\" target=\"id32\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id62\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id63\" max=\"-1\" min=\"0\" target=\"ida\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id64\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id65\" max=\"-1\" min=\"0\" target=\"id2d\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id66\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id67\" max=\"-1\" min=\"0\" target=\"idc\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id68\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id69\" max=\"-1\" min=\"0\" target=\"id33\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id6a\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id6b\" max=\"-1\" min=\"0\" target=\"id9\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id6c\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id6d\" max=\"-1\" min=\"0\" target=\"id5\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id6e\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id6f\" max=\"-1\" min=\"0\" target=\"id3\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id70\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id71\" max=\"1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id72\" target=\"id21\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id73\" max=\"1\" min=\"1\" target=\"idf\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id74\" target=\"id22\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id75\" max=\"1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id76\" target=\"id22\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id77\" max=\"-1\" min=\"0\" target=\"id3e\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id78\" target=\"id23\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id79\" max=\"1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id7a\" target=\"id23\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id7b\" max=\"-1\" min=\"0\" target=\"id22\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id7c\" target=\"id27\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id7d\" max=\"-1\" min=\"0\" target=\"id1c\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id7e\" target=\"id27\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id7f\" max=\"-1\" min=\"0\" target=\"id20\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id80\" target=\"id27\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id81\" max=\"-1\" min=\"0\" target=\"id3c\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id82\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id83\" max=\"-1\" min=\"0\" target=\"id2f\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id84\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id85\" max=\"1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id86\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id87\" max=\"-1\" min=\"0\" target=\"id2b\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id88\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id89\" max=\"1\" min=\"0\" target=\"id2a\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id8a\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id8b\" max=\"-1\" min=\"0\" target=\"id1e\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id8c\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id8d\" max=\"-1\" min=\"0\" target=\"id27\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id8e\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id8f\" max=\"-1\" min=\"0\" target=\"id30\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id90\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id91\" max=\"1\" min=\"0\" target=\"id23\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id92\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id93\" max=\"-1\" min=\"0\" target=\"id1d\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id94\" target=\"id2a\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id95\" max=\"-1\" min=\"0\" target=\"id15\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id96\" target=\"id2b\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id97\" max=\"1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id98\" target=\"id2b\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id99\" max=\"1\" min=\"1\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id9a\" target=\"id2f\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id9b\" max=\"-1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id9c\" target=\"id2f\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id9d\" max=\"-1\" min=\"0\" target=\"id3d\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"id9e\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"id9f\" max=\"1\" min=\"1\" target=\"id38\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"ida0\" target=\"id19\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"ida1\" max=\"1\" min=\"1\" target=\"id38\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"ida2\" target=\"id18\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"ida3\" max=\"1\" min=\"1\" target=\"id37\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"ida4\" target=\"id18\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"ida5\" max=\"-1\" min=\"0\" target=\"id36\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"ida6\" target=\"id18\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"ida7\" max=\"-1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"ida8\" target=\"id36\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"ida9\" max=\"-1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idaa\" target=\"id37\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idab\" max=\"1\" min=\"1\" target=\"id38\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idac\" target=\"id17\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idad\" max=\"-1\" min=\"0\" target=\"id36\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idae\" target=\"id17\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idaf\" max=\"1\" min=\"1\" target=\"id37\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idb0\" target=\"id17\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idb1\" max=\"-1\" min=\"0\" target=\"id31\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idb2\" target=\"id38\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idb3\" max=\"1\" min=\"1\" target=\"id37\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idb4\" target=\"id16\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idb5\" max=\"1\" min=\"1\" target=\"id3e\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idb6\" target=\"id3a\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idb7\" max=\"-1\" min=\"0\" target=\"id3d\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idb8\" target=\"id3d\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idb9\" max=\"-1\" min=\"0\" target=\"id3c\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idba\" target=\"id3d\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idbb\" max=\"-1\" min=\"0\" target=\"id3d\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idbc\" target=\"id3e\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idbd\" max=\"-1\" min=\"0\" target=\"id3c\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idbe\" target=\"id3e\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idbf\" max=\"-1\" min=\"0\" target=\"id3a\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idc0\" target=\"id3e\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idc1\" max=\"-1\" min=\"0\" target=\"id3f\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idc2\" target=\"id40\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idc3\" max=\"-1\" min=\"0\" target=\"id12\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idc5\" target=\"idc4\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idc6\" max=\"-1\" min=\"0\" target=\"id28\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idc7\" target=\"idc4\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idc8\" max=\"-1\" min=\"0\" target=\"id3e\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idc9\" target=\"idc4\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="	<Composition nonpersistent=\"false\">\n";
			str +="		<CompositionChildRole _id=\"idca\" max=\"-1\" min=\"0\" target=\"idc4\" isNavigable=\"true\"/>\n";
			str +="		<CompositionParentRole _id=\"idcb\" target=\"idc4\" isNavigable=\"true\"/>\n";
			str +="	</Composition>\n";
			str +="</Diagram>\n";
			str +="\n";
			str +="\n";
			str +="\n";
		}
		return str;
	}
}
