// $Id$

#if !defined (CCM_CLIENTCONTAINERINTERCEPTOR_IDL)
#define CCM_CLIENTCONTAINERINTERCEPTOR_IDL

#include "ciao/CCM_ContainerInterceptor.idl"
#include "ciao/CCM_ContainerClientRequestInfo.idl"
#include "tao/PI/PIForwardRequest.pidl"

module Components
{
  module ContainerPortableInterceptor
  {
    local interface ClientContainerInterceptor : ContainerInterceptor
    {
      void send_request (in ContainerClientRequestInfo info)
        raises (PortableInterceptor::ForwardRequest);
      void send_poll (in ContainerClientRequestInfo info);
      void receive_reply (in ContainerClientRequestInfo info);
      void receive_exception (in ContainerClientRequestInfo info)
        raises (PortableInterceptor::ForwardRequest);
      void receive_other (in ContainerClientRequestInfo info)
        raises (PortableInterceptor::ForwardRequest);
    };
  };
};
#endif /* CCM_CLIENTCONTAINERINTERCEPTOR_IDL */
