// $Id$

/**
 * @file Getter_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef GETTER_TEST_CONNECTOR_IDL_
#define GETTER_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/Getter_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

TYPED_MODULE( ::GetterTest, ::GetterTest_Seq, GetterTest)

module Getter_Test
{
  connector Getter_Test_Connector : ::CCM_DDS::GetterTest::DDS_Event
  {
  };
};

#endif /* Getter_Test_CONNECTOR_IDL_ */
