// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/QueryFilter_Test_Connector.idl"
#include "Connector/QueryFilter_Test_ConnectorE.idl"

#include "Base/QueryFilter_Starter.idl"
#include "Base/QueryFilter_StarterE.idl"

module QueryFilter_Test
{
  component Receiver
  {
    port CCM_DDS::QueryFilterTest::DDS_Read info_out;

    provides QueryFilterStarter reader_start;
    uses QueryFilterRestarter writer_restart;
  };
};

#endif
