// $Id$

#ifndef DIFFDIR_IDL
#define DIFFDIR_IDL

#pragma ndds typesupport "DiffDirSupport.h"
#pragma opendds typesupport "DiffDirTypeSupportImpl.h"

struct DiffDirType {
  string value; //@key
};

typedef sequence<DiffDirType> DiffDirTypeSeq;

#endif
