#
# Makefile for building the TAO Notify tests
# $Id$
#

DIRS = \
        lib \
        Basic \
        Blocking \
        Ordering \
        performance-tests

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
