/* -*- IDL -*- */

//=============================================================================
/**
 * @file      Node_Daemon.idl
 *
 * $Id$
 *
 * @author    James H. Hill
 */
//=============================================================================

#ifndef _CUTS_NODE_DAEMON_IDL_
#define _CUTS_NODE_DAEMON_IDL_

module CUTS
{
  struct Node_Binding
  {
    boolean localhost;

    unsigned short port;
  };

  typedef sequence <Node_Binding> Node_Bindings;

  struct Spawn_Detail
  {
    string params;

    Node_Bindings bindings;
  };

  interface Node_Daemon
  {
    unsigned long spawn (in Spawn_Detail detail);

    unsigned long kill (in Node_Bindings nodes);

    Node_Bindings details ();

    void shutdown ();
  };
};

#endif  /* !defined _CUTS_NODE_DAEMON_IDL_ */
