// $Id$

#if !defined (CCM_SERVANTCONTAINERINTERCEPTORREGISTRATION_IDL)
#define CCM_SERVANTCONTAINERINTERCEPTORREGISTRATION_IDL

#include "ccm/Extension/CCM_Cookie.idl"
#include "ccm/Extension/CCM_InvalidRegistration.idl"

module Components
{
  module ContainerPortableInterceptor
  {
    local interface ServantContainerInterceptor;

    local interface ServantContainerInterceptorRegistration
    {
      Components::Cookie register_servant_interceptor (in ServantContainerInterceptor ci);
      ServantContainerInterceptor unregister_servant_interceptor (in Components::Cookie cookie)
        raises(InvalidRegistration);
    };
  };
};

#endif /* CCM_SERVANTCONTAINERINTERCEPTORREGISTRATION_IDL */
