//
// $Id$
//

typedef sequence<long> DSI_LongSeq;

struct Structure
{
  short i;
  sequence<long> seq;
};

exception test_exception
{
  short error_code;
  string error_message;
  string status_message;
};

interface Simple_Server
{
  long test_method (in long x,
                    in Structure the_in_structure,
                    out Structure the_out_structure,
                    inout string name);

  void raise_user_exception () raises (test_exception);

  void raise_system_exception ();

  oneway void shutdown ();
};
