#ifndef RACE_DANCE_OUTPUT_ADAPTER_IDL
#define RACE_DANCE_OUTPUT_ADAPTER_IDL

#include <Components.idl>
#include "common/OpString.idl"
#include "common/RACE_common.idl"
#include "DAnCE/Deployment/Deployment_DeploymentPlan.idl"

module CIAO
{
  module RACE
  {
    module DAnCE_OA
    {
      interface Admin
      {
        /// Deploy the given plan.
        //boolean deploy_plan (in ::Deployment::DeploymentPlan plan);

        /// Re_deploy the given plan.
        //boolean redeploy_plan (in ::Deployment::DeploymentPlan plan);

        /// Convert the given operational string to a DeploymentPlan and
        /// deploy it.
        boolean deploy_string (in OperationalString opstring);

        /// Convert the given operational string to a DeploymentPlan and
        /// redeploy it.
        boolean redeploy_string (in OperationalString opstring);

        /// Teardown a string. Raises UnknownID.
        boolean tear_down_string (in UUID ID)
          raises (UnknownID);
      };

      component DAnCE_OA_Component
      {
        attribute string repoman_id;

        provides Admin admin;
      };

      home DAnCE_OA_Component_Home manages DAnCE_OA_Component
      {
      };
    };
  };
};
#endif /* RACE_DANCE_OUTPUT_ADAPTER_IDL */
