// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Get_Connection_Test_Connector.idl"
#include "Connector/Get_Connection_Test_ConnectorE.idl"

module Get_Connection_Test
{
  component Receiver
  {
    port CCM_DDS::Get_ConnectionTest::DDS_Listen  info_listen;
    port CCM_DDS::Get_ConnectionTest::DDS_Get     info_get;
    //port CCM_DDS::Get_ConnectionTest::DDS_StateListen
  };
};

#endif
