
#
# Makefile for building the POA Single_Threaded_POA test
#

NAME = Single_Threaded_POA

OBJFILES = \
	$(OBJDIR)\testC.obj \
	$(OBJDIR)\testS.obj \
	$(OBJDIR)\Single_Threaded_POA.obj

IDLFILES = \
        $(IDLDIR)\test.idl

CPPDIR = .;..

IDLDIR = .

!include <$(ACE_ROOT)\include\makeinclude\build_example.bor>

#
# IDL Build rules
#

$(IDLDIR)\testC.cpp $(IDLDIR)\testS.cpp: $(IDLDIR)\test.idl
	$(TAO_IDL) $**
