// $Id$

/**
 * @file CSL_SRTest_Connector.idl
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef CSL_SRTEST_CONNECTOR_IDL_
#define CSL_SRTEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/CSL_SRTest_Base.idl"

#pragma ciao lem "Connector/CSL_SRTest_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/CSL_SRTest_BaseTypeSupport.idl"
#endif

module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> CSL_SR_Connector;

#endif /* CSL_SRTEST_CONNECTOR_IDL_ */
