// $Id$

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "Hello_MyFoo_obj.idl"

#pragma ciao ami4ccm receptacle "Hello::Sender_comp::run_my_foo"

module Hello
{
  component Sender_comp
  {
    /// For synchronous invocation
    uses MyFoo_obj run_my_foo;
  };
};

#endif
