// -*- C++ -*-
// $Id$

// @@ Ossama: we should call this class just 'Hasher' it shouldn't be
// so obvious that the service must be designed to be load balanced.
interface Hash_Replica
{
  // = DESCRIPTION
  //    This Replica interface provides a simple hashing function.

  unsigned long do_hash (in string str);
  // Perform a simple hashing operation on the input string <str> and
  // return the hash value.
};
