
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl SIMPLEALLOCATIONANALYZER_EXEC
// ------------------------------
#ifndef SIMPLEALLOCATIONANALYZER_EXEC_EXPORT_H
#define SIMPLEALLOCATIONANALYZER_EXEC_EXPORT_H

#include "ace/config-all.h"

#if !defined (SIMPLEALLOCATIONANALYZER_EXEC_HAS_DLL)
#  define SIMPLEALLOCATIONANALYZER_EXEC_HAS_DLL 1
#endif /* ! SIMPLEALLOCATIONANALYZER_EXEC_HAS_DLL */

#if defined (SIMPLEALLOCATIONANALYZER_EXEC_HAS_DLL) && (SIMPLEALLOCATIONANALYZER_EXEC_HAS_DLL == 1)
#  if defined (SIMPLEALLOCATIONANALYZER_EXEC_BUILD_DLL)
#    define SIMPLEALLOCATIONANALYZER_EXEC_Export ACE_Proper_Export_Flag
#    define SIMPLEALLOCATIONANALYZER_EXEC_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define SIMPLEALLOCATIONANALYZER_EXEC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* SIMPLEALLOCATIONANALYZER_EXEC_BUILD_DLL */
#    define SIMPLEALLOCATIONANALYZER_EXEC_Export ACE_Proper_Import_Flag
#    define SIMPLEALLOCATIONANALYZER_EXEC_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define SIMPLEALLOCATIONANALYZER_EXEC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* SIMPLEALLOCATIONANALYZER_EXEC_BUILD_DLL */
#else /* SIMPLEALLOCATIONANALYZER_EXEC_HAS_DLL == 1 */
#  define SIMPLEALLOCATIONANALYZER_EXEC_Export
#  define SIMPLEALLOCATIONANALYZER_EXEC_SINGLETON_DECLARATION(T)
#  define SIMPLEALLOCATIONANALYZER_EXEC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* SIMPLEALLOCATIONANALYZER_EXEC_HAS_DLL == 1 */

// Set SIMPLEALLOCATIONANALYZER_EXEC_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (SIMPLEALLOCATIONANALYZER_EXEC_NTRACE)
#  if (ACE_NTRACE == 1)
#    define SIMPLEALLOCATIONANALYZER_EXEC_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define SIMPLEALLOCATIONANALYZER_EXEC_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !SIMPLEALLOCATIONANALYZER_EXEC_NTRACE */

#if (SIMPLEALLOCATIONANALYZER_EXEC_NTRACE == 1)
#  define SIMPLEALLOCATIONANALYZER_EXEC_TRACE(X)
#else /* (SIMPLEALLOCATIONANALYZER_EXEC_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define SIMPLEALLOCATIONANALYZER_EXEC_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (SIMPLEALLOCATIONANALYZER_EXEC_NTRACE == 1) */

#endif /* SIMPLEALLOCATIONANALYZER_EXEC_EXPORT_H */

// End of auto generated file.
