// $Id$

/**
 * This IDL file is used to combine the NodeApplication
 * interface with the NodeApplicationManager interface.
 *
 * NodeApplicationManager will be spawn NodeApplication.
 * The call back object will be used to get the objectref of
 * NodeApplication.
 */

#include "DAnCE/Deployment/Deployment_NodeApplication.idl"
#include "DAnCE/Deployment/Deployment_NodeApplicationManager.idl"

module CIAO
{
  interface NodeApplication_Callback
  {
    Deployment::NodeApplicationManager
      register_node_application (in Deployment::NodeApplication na,
                                 out Deployment::Properties properties);
  };
};
