// $Id$

#if !defined (CCM_CONTEXT_IDL)
#define CCM_CONTEXT_IDL

#include "ciao/Security.idl"
#include "ciao/CCM_Transaction.idl"
#include "ciao/CCM_Home.idl"
#include "ciao/CCM_CCMException.idl"

// *************** Basic Container interfaces ***************

module Components
{
  typeprefix Components "omg.org";

  typedef SecurityLevel2::Credentials Principal;

  exception IllegalState {};

  local interface CCMContext
  {
    Principal get_caller_principal();

    CCMHome get_CCM_home();

    boolean get_rollback_only()
      raises (IllegalState);

    Transaction::UserTransaction get_user_transaction()
      raises (IllegalState);

    boolean is_caller_in_role (in string role);

    void set_rollback_only()
      raises (IllegalState);

    /**
     * Added for QoS4CCM
     */
    Object resolve_service_reference(in string service_id)
      raises (CCMException);
  };
};
#endif /* CCM_CONTEXT_IDL */
