// $Id$

/**
 * @file Perf_Keyed_Test_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef PERF_KEYED_TEST_BASE_IDL
#define PERF_KEYED_TEST_BASE_IDL


struct PerfKeyedTest {
  string key; //@key
  long entity_id;  //id of subscriber/publisher
  unsigned long seq_num;
  long latency_ping;
  string bin_data;
  unsigned long data_len;
  unsigned long long nanotime;
};

typedef sequence<PerfKeyedTest> PerfKeyedTest_Seq;

#endif
