// $Id$

/**
 * @file QFLS_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef QUERY_CONDITION_LISTEN_STATE_TEST_CONNECTOR_IDL_
#define QUERY_CONDITION_LISTEN_STATE_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/QFLS_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/QFLS_Test_ConnectorE.idl"

module QFLS_Test
{
  module ::CCM_DDS::Typed < ::QueryConditionListenStateTest, ::QueryConditionListenStateTestSeq> QueryConditionListenStateTestConnector;
};

#endif /* QFLS_Test_CONNECTOR_IDL_ */
