// $Id$
/**
 * @file Facets.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * This IDL file tests Facets within components.
 */

#include <Components.idl>

module Facets
{
  interface foo_interface
    {
    };

  interface bar_interface
    {
    };

  component Foo
    {
      provides foo_interface p_foo;
    };

  component Bar : Foo
    {
      provides bar_interface p_bar;
    };

  component FooFoo : Foo
    {
      provides foo_interface p_foofoo;
    };

  component FooBar
    {
      provides foo_interface foo;
      provides bar_interface bar;
    };

  component ObjectProvider
    {
      provides Object foo_object;
    };
};
