// $Id$

/**
 * @file
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/RG_ResetTopic_Connector.idl"
#include "Base/Reader_Starter.idl"

module RG_ResetTopic
{
  component Receiver
  {
    port RG_ResetTopicSampleConnector::DDS_Get info_get;
    port RG_ResetTopicSampleConnector::DDS_Read info_read;

    provides ReaderStarter start_reading;
  };
};

#endif
