// $Id$

/**
 * @file   SL_OneByOne_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef SL_ONEBYONE_BASE_IDL
#define SL_ONEBYONE_BASE_IDL

#pragma ndds typesupport "Base/SL_OneByOne_BaseSupport.h"

#pragma DCPS_DATA_TYPE "TestTopic"
#pragma DCPS_DATA_KEY "TestTopic key"

struct TestTopic {
  string key; //@key
  long x;
};

typedef sequence<TestTopic> TestTopicSeq;

#endif
