// $Id$

/**
 * @file   VTopic_Base.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VTOPIC_BASE_IDL
#define VTOPIC_BASE_IDL

#pragma ndds typesupport "Base/VTopic_BaseSupport.h"
#pragma opendds typesupport "Base/VTopic_BaseTypeSupportImpl.h"

typedef octet octet_array[5];

#pragma DCPS_DATA_TYPE "TestTopic"
#pragma DCPS_DATA_KEY "TestTopic key"

// Plain topic
struct TestTopic {
  string key; //@key
  long x;
};

#pragma DCPS_DATA_TYPE "TopicString"
#pragma DCPS_DATA_KEY "TopicString key"

// String
struct TopicString {
  string key; //@key
  string x_str;
};

#pragma DCPS_DATA_TYPE "TopicArray"
#pragma DCPS_DATA_KEY "TopicArray key"

// Arrays
struct TopicArray {
  string key; //@key
  octet_array x_array;
 };

// Unions
union X_Union switch (short) {
    case 0:
      string x_test;
    case 1:
      long   x_long;
};

#pragma DCPS_DATA_TYPE "TopicUnion"
#pragma DCPS_DATA_KEY "TopicUnion key"

struct TopicUnion {
  string key; //@key
  X_Union x_uni;
};

// Sequence
struct test {
  short x_test;
  string x_teststr;
};
typedef sequence<test> testSeq;

#pragma DCPS_DATA_TYPE "TopicSeq"
#pragma DCPS_DATA_KEY "TopicSeq key"

struct TopicSeq {
  string key; //@key
  testSeq x_seq;
};

// ValueType
valuetype X_Valuetype {
  public string type;
  public long x_long;
};

#pragma DCPS_DATA_TYPE "TopicValuetype"
#pragma DCPS_DATA_KEY "TopicValuetype key"

struct TopicValuetype {
  string key; //@key
  X_Valuetype x_vt;
};

// Sequences
typedef sequence<TestTopic> TestTopicSeq;
typedef sequence<TopicString> TopicStringSeq;
typedef sequence<TopicArray> TopicArraySeq;
typedef sequence<TopicUnion> TopicUnionSeq;
typedef sequence<X_Union> X_UnionSeq;
typedef sequence<TopicSeq> TopicSeqSeq;
typedef sequence<TopicValuetype> TopicValuetypeSeq;
typedef sequence<X_Valuetype> X_ValuetypeSeq;

#endif
