/* -*- C++ -*- */
// $Id$

interface Pluggable_Test
{
  // = TITLE
  //    Defines an interface that encapsulates operations designed to
  //    test the TAO Pluggable Protocols implementation.
  //
  // = DESCRIPTION
  //    This interface encapsulates operations that send
  //    octets, voids, and octet sequences.

  oneway void send_oneway ();
  // Test the basic latency of a nil oneway operation.

  void send_void ();
  // Test the basic latency of a nil operation.

  oneway void shutdown ();
  // shutdown the application.

};

interface Pluggable_Test_Factory
{
  // = TITLE
  //    Creates Pluggable_Test objects.

  Pluggable_Test make_pluggable_test ();
};
