// $Id$

/**
 * @file CSL_DeadlineTest_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef CSL_DeadlineTest_CONNECTOR_IDL_
#define CSL_DeadlineTest_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/CSL_DeadlineTest_Base.idl"

#pragma ciao lem "Connector/CSL_DeadlineTest_ConnectorE.idl"

module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> CSLDeadlineConnector;

#endif /* CSL_DeadlineTest_CONNECTOR_IDL_ */
