// $Id$

/**
 * @file CoherentWrite_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef COHERENT_WRITE_TEST_BASE_IDL
#define COHERENT_WRITE_TEST_BASE_IDL

#pragma ndds typesupport "Base/CoherentWrite_Test_BaseSupport.h"
#pragma opendds typesupport "Base/CoherentWrite_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "CoherentWriteTest"
#pragma DCPS_DATA_KEY "CoherentWriteTest symbol"

struct CoherentWriteTest {
  string symbol; //@key
  long iteration;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<CoherentWriteTest> CoherentWriteTestSeq;
#endif

#endif
