// $Id$
/// Compliant with OMG 06-04-01 Section 6.7.6

#if !defined (CCM_EXCEPTIONS_IDL)
#define CCM_EXCEPTIONS_IDL

module Components
{
  typeprefix Components "omg.org";

  typedef unsigned long FailureReason;

  exception CreateFailure {
    FailureReason reason;
  };
  exception FinderFailure
  {
    FailureReason reason;
  };
  exception RemoveFailure
  {
    FailureReason reason;
  };
};

#endif
