#
# Makefile for building the TAO POA tests
#

DIRS = \
        Deactivation \
        Destruction \
        Identity \
        Non_Servant_Upcalls \
        Single_Threaded_POA \
        wait_for_completion \
	Multiple_Deactivations

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
