//=============================================================================
/**
 *  @file    test.idl
 *
 *  $Id$
 *
 *  IDL description of the Test interface
 *
 *  @author Martin Corino <mcorino@remedy.nl>
 */
//=============================================================================

module A
  {
    enum RunMode
    {
        RM_SLAVE,
        RM_MASTER
    };

    enum RequestMode
    {
        RQM_SYNCH,
        RQM_ASYNCH
    };

    enum FollowUp
    {
        FU_TIMER,
        FU_NOTIFICATION
    };

    interface Test
      {
        void request (in RequestMode mode, inout unsigned long counter, out FollowUp follow_up);

        void report (in string msg);

        oneway void shutdown ();
      };
  };
