// $Id$
/**
 * @file Regular.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests the compilation of regular  event types.
 */

#include <Components.idl>

module RegularEvents
{
  eventtype foo
    {
    };

  eventtype bar
    {
    };

  eventtype InhFoo : foo
    {
    };

  /* @@
   * TAO_IDL cannot handle custom yet.
  custom eventtype custom_foo
    {
    };

  custom eventtype custom_InhFoo : foo
    {
    };
  */

  eventtype Baz
  {
    long test_op ();
    void test_op_a (in long foo, out float bar);
    InhFoo test_op_b ();
  };


};
