// $Id$

#include <Components.idl>

module DeCoRAM
{
  component FTClient
  {
    attribute double period;
    attribute double execution_time;
    attribute unsigned long iterations;
    attribute string server_ior;
   };

  home FTClientHome manages FTClient
  {
  };
};
