// $Id$
//===============================================================================
//
// = FILENAME
//     Foo.idl
//
//==================================================================================

// IDL

interface Foo
{
  long doit ();

  oneway void simply_doit ();
};
