// $Id$
//===============================================================================
//
// = FILENAME
//     Foo.idl
//
//==================================================================================

// IDL

interface Foo
{
  long doit();
};
