// $Id$

/**
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef DDS_CSL_SRTEST_SENDER_IDL
#define DDS_CSL_SRTEST_SENDER_IDL

#include "Connector/CSL_SRTest_Connector.idl"

module CSL_SRTest
{
  component Sender
  {
     port CSL_SR_Connector::DDS_Write test_topic_write;
  };
};

#endif
