//
// $Id$
//

interface Test
{
  typedef sequence<octet> data;
  oneway void oneway_payload_test (in data d);

  oneway void oneway_work_test (in unsigned long work);

  void twoway_work_test (in unsigned long work);

  oneway void shutdown ();
};
