// $Id$

/**
 * @file TwoTopics_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef TWOTOPICS_BASE_IDL
#define TWOTOPICS_BASE_IDL

#pragma ndds typesupport "Base/TwoTopics_BaseSupport.h"
#pragma opendds typesupport "Base/TwoTopics_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "HelloTopic"
#pragma DCPS_DATA_KEY "HelloTopic hello"

struct HelloTopic {
  string hello; //@key
  long iteration;
};
#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<HelloTopic> HelloTopicSeq;
#endif

#pragma DCPS_DATA_TYPE "GoodbyeTopic"
#pragma DCPS_DATA_KEY "GoodbyeTopic goodbye"

struct GoodbyeTopic {
  string goodbye; //@key
  long iteration;
};
#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<GoodbyeTopic> GoodbyeTopicSeq;
#endif

#endif
