// $Id$

/**
 * @file
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/PSL_SampleLost_Connector.idl"

module PSL_SampleLost
{
  component Receiver
  {
    port PSL_SampleLostConnector::DDS_Get info_get;
    port PSL_SampleLostConnector::DDS_Listen info_out;
   };
};

#endif
