// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/CSL_QoSTest_Connector.idl"

module CSL_QoSTest
{
  component Receiver
  {
    port CSLQoSConnector::DDS_Listen info_out;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
   };
};

#endif
