// $Id$
/**
 * @file EventSink.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 */

#include <Components.idl>

module EventSink
{
  eventtype foo_event
    {
    };

  eventtype bar_event
    {
    };

  component Foo
    {
      consumes foo_event c_foo;
    };

  component Bar : Foo
    {
      consumes bar_event c_bar;
    };

};
