
//=============================================================================
/**
 *  @file    Multiple.idl
 *
 *  $Id$
 *
 *  IDL definition of a Diamond shaped hierarchy
 *  of IDL interfaces. This Diamond shaped hierarchy
 *  is used for testing the collocation.
 *  The hierarchy used is decipted in the following
 *  figure.
 *
 *                    Top
 *                   /   \
 *               Left     Right
 *                   \   /
 *                   Bottom
 *
 *
 *  @author  Angelo Corsaro <corsaro@cs.wustl.edu>
 */
//=============================================================================

*/


module _Multiple
{

  interface Top
  {
    string top_quote ();

    oneway void shutdown ();
  };

  interface Left : Top
  {
    string left_quote ();
  };

  interface Right : Top
  {
    string right_quote ();
  };

  interface Bottom : Left, Right
  {
    string bottom_quote ();
  };

};
