/* $Id$ */
#include <datastream_common.h>
#include <dsui_types.h>
#include "kokyu_dsui_families.h"
counter_t DISP_TASK_COUNTERS[NUM_COUNTERS_DISP_TASK] = {
};
histogram_t DISP_TASK_HISTOGRAMS[NUM_HISTOGRAMS_DISP_TASK] = {
};
family_t DISP_TASK = {
	"DISP_TASK",
	NUM_EVENTS_DISP_TASK,
	NUM_COUNTERS_DISP_TASK,
	NUM_HISTOGRAMS_DISP_TASK,
	DISP_TASK_COUNTERS,
	DISP_TASK_HISTOGRAMS,
	0,
	0,
	0,
	0
};

counter_t DSRT_CV_DISPATCH_COUNTERS[NUM_COUNTERS_DSRT_CV_DISPATCH] = {
};
histogram_t DSRT_CV_DISPATCH_HISTOGRAMS[NUM_HISTOGRAMS_DSRT_CV_DISPATCH] = {
};
family_t DSRT_CV_DISPATCH = {
	"DSRT_CV_DISPATCH",
	NUM_EVENTS_DSRT_CV_DISPATCH,
	NUM_COUNTERS_DSRT_CV_DISPATCH,
	NUM_HISTOGRAMS_DSRT_CV_DISPATCH,
	DSRT_CV_DISPATCH_COUNTERS,
	DSRT_CV_DISPATCH_HISTOGRAMS,
	0,
	0,
	0,
	0
};

counter_t DSRT_DIRECT_DISPATCH_COUNTERS[NUM_COUNTERS_DSRT_DIRECT_DISPATCH] = {
};
histogram_t DSRT_DIRECT_DISPATCH_HISTOGRAMS[NUM_HISTOGRAMS_DSRT_DIRECT_DISPATCH] = {
};
family_t DSRT_DIRECT_DISPATCH = {
	"DSRT_DIRECT_DISPATCH",
	NUM_EVENTS_DSRT_DIRECT_DISPATCH,
	NUM_COUNTERS_DSRT_DIRECT_DISPATCH,
	NUM_HISTOGRAMS_DSRT_DIRECT_DISPATCH,
	DSRT_DIRECT_DISPATCH_COUNTERS,
	DSRT_DIRECT_DISPATCH_HISTOGRAMS,
	0,
	0,
	0,
	0
};

counter_t DISP_DEFERRER_COUNTERS[NUM_COUNTERS_DISP_DEFERRER] = {
};
histogram_t DISP_DEFERRER_HISTOGRAMS[NUM_HISTOGRAMS_DISP_DEFERRER] = {
};
family_t DISP_DEFERRER = {
	"DISP_DEFERRER",
	NUM_EVENTS_DISP_DEFERRER,
	NUM_COUNTERS_DISP_DEFERRER,
	NUM_HISTOGRAMS_DISP_DEFERRER,
	DISP_DEFERRER_COUNTERS,
	DISP_DEFERRER_HISTOGRAMS,
	0,
	0,
	0,
	0
};

counter_t DSRT_DISPATCH_IMPL_COUNTERS[NUM_COUNTERS_DSRT_DISPATCH_IMPL] = {
};
histogram_t DSRT_DISPATCH_IMPL_HISTOGRAMS[NUM_HISTOGRAMS_DSRT_DISPATCH_IMPL] = {
};
family_t DSRT_DISPATCH_IMPL = {
	"DSRT_DISPATCH_IMPL",
	NUM_EVENTS_DSRT_DISPATCH_IMPL,
	NUM_COUNTERS_DSRT_DISPATCH_IMPL,
	NUM_HISTOGRAMS_DSRT_DISPATCH_IMPL,
	DSRT_DISPATCH_IMPL_COUNTERS,
	DSRT_DISPATCH_IMPL_HISTOGRAMS,
	0,
	0,
	0,
	0
};

counter_t DSRT_DISPATCH_COUNTERS[NUM_COUNTERS_DSRT_DISPATCH] = {
};
histogram_t DSRT_DISPATCH_HISTOGRAMS[NUM_HISTOGRAMS_DSRT_DISPATCH] = {
};
family_t DSRT_DISPATCH = {
	"DSRT_DISPATCH",
	NUM_EVENTS_DSRT_DISPATCH,
	NUM_COUNTERS_DSRT_DISPATCH,
	NUM_HISTOGRAMS_DSRT_DISPATCH,
	DSRT_DISPATCH_COUNTERS,
	DSRT_DISPATCH_HISTOGRAMS,
	0,
	0,
	0,
	0
};

int kokyu_table_offset= 4;
family_t *kokyu_family_table[NUM_FAMILIES] = {




	&DSRT_DISPATCH,
	&DSRT_CV_DISPATCH,
	&DSRT_DIRECT_DISPATCH,
	&DISP_DEFERRER,
	&DISP_TASK,
	&DSRT_DISPATCH_IMPL,
};

