/* $Id$ */
#ifndef KOKYU_CONFIG_H
#define KOKYU_CONFIG_H

#define CONFIG_DSTREAM_DISP_TASK 1
#define CONFIG_DSTREAM_DSRT_CV_DISPATCH 1
#define CONFIG_DSTREAM_DSRT_DIRECT_DISPATCH 1
#define CONFIG_DSTREAM_DISP_DEFERRER 1
#define CONFIG_DSTREAM_DSRT_DISPATCH_IMPL 1
#define CONFIG_DSTREAM_DSRT_DISPATCH 1

#endif /* KOKYU_CONFIG_H */
