// $Id$

/**
 * @file Unkeyed_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef UNKEYED_TEST_CONNECTOR_IDL_
#define UNKEYED_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/Unkeyed_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

TYPED_MODULE( ::UnkeyedTest, ::UnkeyedTest_Seq, UnkeyedTest)

module Unkeyed_Test
{
  connector Unkeyed_Test_Connector : ::CCM_DDS::UnkeyedTest::DDS_MonoConnector
  {
  };
};

#endif /* Unkeyed_Test_CONNECTOR_IDL_ */
