// $Id$

#ifndef SIMPLE_MULTIPLEUSER_IDL
#define SIMPLE_MULTIPLEUSER_IDL

#include "SimpleCommon.idl"
#include "Components.idl"

module Simple
{
  component SimpleMultipleUser
  {
    uses multiple Trigger trig;
  };
  
  home SimpleMultipleUserHome manages SimpleMultipleUser
  {
  };
};

#endif /*SIMPLE_MULTIPLEUSER_IDL*/
