#ifndef RACE_COMMON_IDL
#define RACE_COMMON_IDL

#include "ciao/Deployment_Packaging_Data.idl"

module CIAO
{
  module RACE
    {
      typedef string RACE_Classification;
      typedef sequence <RACE_Classification> RACE_Classifications;

      struct FlowItem
      {
        string planner;
        RACE_Classification classification;
      };

      typedef sequence <FlowItem> PlannerFlow;

      enum Action
      {
        TEARDOWN,
        DEPLOY,
        AUTO_TEARDOWN,
        REPLAN_TEARDOWN,
        REPLAN_DEPLOY,
        REPLAN_AUTO_TEARDOWN
      };

      struct Plan_Action
      {
        Action command;
        Deployment::DeploymentPlan plan;
        Deployment::PackageConfiguration package;
      };

      typedef sequence<Plan_Action> Plan_Actions;

    };
};

#endif /* RACE_COMMON_IDL */
