#ifndef RACE_UTILS_IDL
#define RACE_UTILS_IDL

module CIAO
{
  module RACE
    {

      const long UNDEFINED_TIME_ENTRY = -1;

      struct TimeValue
      {
        // Seconds since Jan. 1, 1970
        long    sec;
        //and microseconds
        long    usec;
      };

      // A time window is a range between an earliest and latest time value.
      struct TimeWindow
      {
        // Beginning of time window.
        TimeValue earliest;

        // End of time window.
        TimeValue latest;
      };

      struct ExecutionRate
      {
        /// Minimum execution rate (in Hz).
        double minRate;

        /// Maximum execution rate (in Hz).
        double maxRate;

        /// Current execution rate (in Hz).
        double currRate;
      };
  };
};

#endif /* RACE_UTILS_IDL */
