#ifndef RACE_CONTROLLER_IDL
#define RACE_CONTROLLER_IDL

/**
 * @file Controller.idl
 *
 * @brief Controller Component of RACE.
 *
 * This file declares a Controller of the RACE framework.
 *
 * @author Nishanth Shankaran <nshankar@dre.vanderbilt.edu>
 */

#include <Components.idl>
#include "ciao/Deployment_Target_Data.idl"
#include "TargetManager/TargetManagerExt.idl"
#include "Interface.idl"
#include "Monitor/Central_Monitor/Monitor.idl"

/**
 * @module CIAO
 * @brief The CIAO module.
 */

module CIAO
{
  module RACE
  {

    struct component_info
    {
      string id;
      string node;
    };

    /**
     * @component Controller
     * @brief The Controller component of RACE.
     */

    component Controller supports Trigger
    {
      /// Obtain resource utilization infromation from the target manager.
      uses CIAO::TargetManagerExt target_mgr_ext;
      uses Deployment::TargetManager target_mgr;

      uses ::CIAO::RACE::Execution_Time_Monitor monitor;


      /// Facet to which the descrpters can be pushed.
      provides Descriptors descriptors;

      /// The sampling period of the controller.
      readonly attribute long sampling_period;
    };

    home Controller_Home manages Controller
    {
    };
  };
};
#endif /* RACE_CONTROLLER_IDL */
