// $Id$
/**
 * @file ICEventSink.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests implied idl features of event sinks
 */

#include <Components.idl>

module ImpliedEventSink
{
#if !defined (CCM_NOEVENT)
  eventtype foo_event
    {
    };
#endif
  component Foo
    {
#if !defined (CCM_NOEVENT)
      consumes foo_event c_foo;
#endif
    };
  /*
  interface test
    {
      ImpliedEventSink::FooEventConsumers::foo_eventConsumer test_a ();
    };
  */
};
