// $Id$

/**
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef DDS_THROUGHPUT_SENDER_IDL
#define DDS_THROUGHPUT_SENDER_IDL

#include "Connector/Throughput_Connector.idl"
#include "SecConnector/Throughput_Sec_Connector.idl"

module Throughput
{
  component Sender
  {
    port ThroughputTestConn::DDS_Write info_write;
    port ThroughputCommandConn::DDS_Write command_write;

    provides CCM_DDS::ConnectorStatusListener connector_status;

    attribute unsigned long start_load;
    attribute unsigned long incr_load;
    attribute unsigned long long max_load;
    attribute unsigned short recover_time;
    attribute unsigned short datalen; //minimal 24
    attribute unsigned short number_of_sub; //number of subscribers
  };
};

#endif
