// $Id$

/**
 * @file CFT_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef CONTENTFILTEREDTOPIC_TEST_CONNECTOR_IDL_
#define CONTENTFILTEREDTOPIC_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/CFT_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/CFT_Test_ConnectorE.idl"

module ::CCM_DDS::Typed < ::CFTTwoDimensionalTest, ::CFTTwoDimensionalTestSeq> CFTTwoDimensionalTestConn;
module ::CCM_DDS::Typed < ::CFTThreeDimensionalTest, ::CFTThreeDimensionalTestSeq> CFTThreeDimensionalTestConn;
#endif /* CONTENTFILTEREDTOPIC_TEST_CONNECTOR_IDL_ */
