// $Id$
/**
 * @file dds4ccm_PortStatusListener.idl
 */

#ifndef DDS4CCM_PORTSTATUSLISTNER_IDL3
#define DDS4CCM_PORTSTATUSLISTNER_IDL3

#include "connectors/dds4ccm/idl/dds4ccm_Base.idl"

#pragma ciao lem "connectors/dds4ccm/idl/dds4ccm_PortStatusListenerE.idl"

module CCM_DDS
{
  local interface PortStatusListener {
    void on_requested_deadline_missed(in DDS::DataReader the_reader,
                                      in DDS::RequestedDeadlineMissedStatus status);
    void on_sample_lost(in DDS::DataReader the_reader,
                        in DDS::SampleLostStatus status);
  };
};

#endif
