// $Id$

#if !defined (DEPLOYMENT_CONNECTION_IDL)
#define DEPLOYMENT_CONNECTION_IDL

#include "DAnCE/Deployment/Deployment_DeploymentPlan.idl"
#include <ciaosvcs/Events/CIAO_Events_Base/CIAO_Events.idl>

// *************** Packaging and Deployment ***************
module Deployment
{
  typedef sequence < Object > Endpoints;
  //typedef Object Endpoint;
  
  // @@changed
  // struct Connection
  //   {
  //     string name;
  //     Endpoints endpoint;
  //   };
  
  // CIAO's specific <Connection> type defition.
  // To avoid the connection info in the plan being passed to the
  // local node and to make the implementation not very cumbersome
  // I changed the connection struct to include some extra informations.
  struct Connection
  {
    string instanceName;
    string portName;
    CCMComponentPortKind kind;

    string endpointInstanceName; // CIAO specific extension
    string endpointPortName;     // CIAO specific extension

    // the endpoints member is change to endpoint.
    // Since we will not have more than 1 objref in there.
    Object endpoint;

    // A wrapper facade interface to provision different event
    // communication mechanisms, including RTEC, etc.
    CIAO::CIAO_Event_Service event_service;

    // The properties of this connection, particularly useful
    // to speicfy QoS properties of pub/sub service connections.
    Properties config;
  };

  typedef sequence < Connection > Connections;
};
#endif /* DEPLOYMENT_CONNECTION_IDL */
