// $Id$

#ifndef TARGETMANAGER_IDL
#define TARGETMANAGER_IDL

#include "DAnCE/Deployment/Deployment_TargetData.idl"
#include "DAnCE/Deployment/Deployment_DeploymentPlan.idl"
#include "DAnCE/Deployment/Deployment_ResourceCommitmentManager.idl"

module Deployment {
  enum DomainUpdateKind {
    Add,
    Delete,
    UpdateAll,
    UpdateDynamic
  };

  interface TargetManager {
    Domain getAllResources ();

    Domain getAvailableResources ();

    ResourceCommitmentManager createResourceCommitment (in ResourceAllocations resources)
      raises (ResourceCommitmentFailure);

    void destroyResourceCommitment (in ResourceCommitmentManager manager);

    void updateDomain ( in ::CORBA::StringSeq elements,
                        in Domain domainSubset,
                        in DomainUpdateKind updateKind);
  };
};

#endif /* TARGETMANAGER_IDL */
