// $Id$
#ifndef ACE_CONFIG_MACOSX_IPHONE_HARDWARE_H
#define ACE_CONFIG_MACOSX_IPHONE_HARDWARE_H

#define ACE_SIZEOF_LONG_DOUBLE 8

#include "ace/config-macosx-snowleopard.h"

#endif ACE_CONFIG_MACOSX_IPHONE_HARDWARE_H

