// $Id$

#include "ace/SOCK_SCTP_SEQPACK.h"

ACE_BEGIN_VERSIONED_NAMESPACE_DECL

ACE_SOCK_SCTP_SEQPACK::ACE_SOCK_SCTP_SEQPACK (void)
{
}

ACE_SOCK_SCTP_SEQPACK::~ACE_SOCK_SCTP_SEQPACK (void)
{
}
 
ACE_END_VERSIONED_NAMESPACE_DECL
