#
# Makefile for building RTCORBA tests
#

DIRS = \
	Banded_Connections \
	Client_Propagated \
	Client_Protocol \
	Collocation \
	Destroy_Thread_Pool \
	Explicit_Binding \
	Linear_Priority \
	MT_Client_Protocol_Priority \
	ORB_init \
	Persistent_IOR \
	Policies \
	Policy_Combinations \
	Private_Connection \
        Profile_And_Endpoint_Selection \
        RTMutex \
	Server_Declared \
	Server_Protocol \
	Thread_Pool

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
