
!include <$(ACE_ROOT)\include\makeinclude\make_flags.bor>

all:
        cd $(ACE_ROOT)\apps\Gateway\Gateway
        $(MAKE) -f Makefile.bor $(MAKE_FLAGS)
        cd $(ACE_ROOT)\apps\Gateway\Peer
        $(MAKE) -f Makefile.bor $(MAKE_FLAGS)

