/* $Id$ */
#ifndef KOKYU_CONFIG_H
#define KOKYU_CONFIG_H

#define CONFIG_DSTREAM_DSRT_DISPATCH
#define CONFIG_DSTREAM_DSRT_CV_DISPATCH
#define CONFIG_DSTREAM_DSRT_DIRECT_DISPATCH

#endif /* KOKYU_CONFIG_H */
