/* -*- C++ -*- */
// @(#)Notifier.idl	1.1	10/18/96


// ============================================================================
//
// = LIBRARY
//    EventComm
// 
// = FILENAME
//    Notifier.idl
//
// = DESCRIPTION 
//    This is the CORBA IDL interface for the Event Communication <Notifier>.
//
// = AUTHOR
//    Douglas C. Schmidt (schmidt@cs.wustl.edu)
// 
// ============================================================================

#ifndef _Notifier_iDL
#define _Notifier_iDL

#include "Notification.idl"
#include "Notification_Receiver.idl"

interface Notifier
  // = TITLE
  //   Defines the interface for a <Notifier> of events.
  //
  // = DESCRIPTION
{
  oneway void send_disconnect (in string reason);
  // Disconnect all the receivers, giving them the <reason>.

  oneway void send_notification (in Notification notification);
  // Send the <Notification> to all the consumers who
  // have subscribed and who match the filtering criteria.

  oneway void subscribe (in Notification_Receiver notification_receiver,
			 in string filtering_criteria);
  // Subscribe the <Notification_Receiver> to receive events that
  // match <filtering_criteria> applied by the <Notifier>.

 oneway void unsubscribe (in Notification_Receiver notification_receiver);
  // Unsubscribe the <Notification_Receiver>.
};

#endif /* _Notifier_iDL */
