
//=============================================================================
/**
 *  @file    anyunion.idl
 *
 *  $Id$
 *
 *  This file contains examples of IDL code that has
 *  caused problems in the past for the TAO IDL
 *  compiler. This test is to make sure the problems
 *  stay fixed.
 *
 *
 *  @author Jeff Parsons <parsons@cs.wustl.edu> and TAO users.
 */
//=============================================================================


// AnyUnion
enum AnyUnionEnum {
  ANYUNIONENUM2
};

union MyAnyUnion switch (AnyUnionEnum) {
  case ANYUNIONENUM2:
    any my_any;
};
