/**
 * @file CIAO_Properties.idl
 * @author William R. Otte
 * $Id$
 * Standardizes names of configvalues used by CIAO.
 */

#ifndef CIAO_PROPERTIES_IDL
#define CIAO_PROPERTIES_IDL

module CIAO
{
  module Deployment
  {
    const string SVNT_ENTRYPT = "edu.vanderbilt.dre.CIAO.ServantEntrypoint";
    const string SVNT_ARTIFACT = "edu.vanderbilt.dre.CIAO.ServantArtifact";
    const string EXEC_ARTIFACT = "edu.vanderbilt.dre.CIAO.ExecutorArtifact";
    const string COMPONENT_FACTORY = "component factory";
    const string HOME_FACTORY = "home factory";
    const string COMPONENT_HOME = "edu.vanderbilt.dre.CIAO.ComponentHomeId";
    const string CONTAINER_ID = "edu.vanderbilt.dre.CIAO.ContainerId";
    const string SERVER_UUID = "edu.vanderbilt.dre.CIAO.ServerUUID";
    const string SERVER_EXECUTABLE = "edu.vanderbilt.dre.CIAO.ComponentServer.Executable";
    const string SERVER_ARGUMENTS = "edu.vanderbilt.dre.CIAO.ComponentServer.Args";
    const string SERVER_TIMEOUT = "edu.vanderbilt.dre.CIAO.ServerTimeout";
    const string SERVER_MULTITHREAD = "edu.vanderbilt.dre.CIAO.Multithreaded";
    const string REGISTER_NAMING = "edu.vanderbilt.dre.CIAO.RegisterNaming";
    const string COMPONENTINSTALLATION_REF = "edu.vanderbilt.dre.CIAO.ComponentInstallation";
  };
};
#endif /* CIAO_PROPERTIES_IDL */
