// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Getter_Test_Connector.idl"
#include "Connector/Getter_Test_ConnectorE.idl"

#include "Base/Get_Invoker.idl"
#include "Base/Get_InvokerE.idl"

module Getter_Test
{
  component Receiver
  {
    port CCM_DDS::GetterTest::DDS_Get info_get;

    provides GetInvoker getter_invoke;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
  };
};

#endif
