// $Id$

/**
 * @file dds4ccm_ConnectorStatusListener.idl
 *
 */

#ifndef DDS4CCM_CONNECTORSTATUSLISTNER_IDL3
#define DDS4CCM_CONNECTORSTATUSLISTNER_IDL3

#include "connectors/dds4ccm/idl/dds4ccm_Base.idl"

#pragma ciao lem "connectors/dds4ccm/idl/dds4ccm_ConnectorStatusListenerE.idl"

module CCM_DDS
{
  local interface ConnectorStatusListener {
    // status that are relevant system-wide
    void on_inconsistent_topic(in DDS::Topic the_topic,
                               in DDS::InconsistentTopicStatus status);
    void on_requested_incompatible_qos(in DDS::DataReader the_reader,
                                       in DDS::RequestedIncompatibleQosStatus status);
    void on_sample_rejected(in DDS::DataReader the_reader,
                            in DDS::SampleRejectedStatus status);
    void on_offered_deadline_missed(in DDS::DataWriter the_writer,
                                    in DDS::OfferedDeadlineMissedStatus status);
    void on_offered_incompatible_qos(in DDS::DataWriter the_writer,
                                     in DDS::OfferedIncompatibleQosStatus status);
    void on_unexpected_status (in DDS::Entity the_entity,
                               in DDS::StatusKind status_kind);
  };
};

#endif
