// $Id$

/**
 * @file Connector1.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef SHARED_DP_CONNECTOR1_IDL_
#define SHARED_DP_CONNECTOR1_IDL_

#include  <Components.idl>
#include "Base/Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector1/Connector1E.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::SharedDPTest1, ::SharedDPTest1Seq> SharedDPTest1;
};

module SharedDP_Connector1
{
  connector Connector1 : ::CCM_DDS::SharedDPTest1::DDS_Event
  {
  };
};



#endif /* SHARED_DP_CONNECTOR1_IDL_ */
