// $Id$

#if !defined (AMI4CCM_IDL_H)
#define AMI4CCM_IDL_H

#include <Components.idl>

#pragma ciao lem "connectors/ami4ccm/ami4ccm/ami4ccmE.idl"

module CCM_AMI
{
  native UserExceptionBase;

  local interface ExceptionHolder
  {
    void raise_exception() raises (UserExceptionBase);
  };

  /// Base interface for the Callback model
  local interface ReplyHandler
  {
  };

  connector AMI_Base
  {
  };
  
  module Connector_T<interface T, interface AMI_T>
  {
    porttype AMI_Port
    {
      provides AMI_T sendc_run;
      uses T run;
    };
    
    connector The_Connector : AMI_Base
    {
      port AMI_Port The_Port;
    };
  };
};

#endif /* AMI4CCM_IDL_H */
