// $Id$

/**
 * @file HomeT_Base.idl
 * @author  Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef HOMET_BASE_IDL
#define HOMET_BASE_IDL

#pragma ndds typesupport "Base/HomeT_BaseSupport.h"
#pragma opendds typesupport "Base/HomeT_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "HomeTest"

struct HomeTest {
  string hello;
  short iterator;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<HomeTest> HomeTestSeq;
#endif

#endif
