/* -*- IDL -*- */
//=============================================================================
/**
 *  @file    FT_NamingReplication.idl
 *
 *  $Id$
 *
 *  This file is part of Fault Tolerant Naming Service in support of
 *  replication between redundant servers.
 *
 *  @author Kevin Stanley <stanleyk@ociweb.com>
 */
//=============================================================================

#ifndef _FT_NAMING_REPLICATION_IDL_
#define _FT_NAMING_REPLICATION_IDL_

#include <orbsvcs/CosNaming.idl>
#include <orbsvcs/FT_NamingManager.idl>

module FT_Naming
{

  typedef string GroupName;
  enum ChangeType { NEW, UPDATED, DELETED };

  exception NotAvailable
  {
  };

  /*
   * A structure that describes the updated element in a Naming Service
   */
  struct NamingContextUpdate
  {
    /// The name of context being updated
    string context_name;
    /// The type of change that is being reported
    ChangeType change_type;
  };

  struct ReplicaInfo
  {
    CosNaming::NamingContext root_context;
    FT::NamingManager naming_manager;
  };

  /*
   * A structure that describes the updated element within
   * an Object Group Manager
   */
  struct ObjectGroupUpdate
  {
    /// The type of change that is being reported
    ChangeType change_type;
    /// This is the name that is used to identify object group references.
    GroupName name;
  };

  interface ReplicationManager
  {
   /*
    * Register with a peer replica providing an object reference for
    * notification of updates.  Each replica will maintain their state
    * in a shared repository and the update notification indicates the
    * element that was changed.
    */
    ReplicaInfo register_replica (in ReplicationManager replica,
                                  in ReplicaInfo replica_info)
      raises (NotAvailable);

    oneway void notify_updated_object_group(in ObjectGroupUpdate group_info);

    oneway void notify_updated_context(in NamingContextUpdate context_info);
  };
};


#endif // _FT_NAMING_REPLICATION_IDL_
