// $Id$

#if !defined (ETCL_MACROS)
#define ETCL_MACROS

#define ETCL_PREFERENCE_CLASS ETCL_Preference
#define ETCL_BINARY_EXPR_CLASS ETCL_Binary_Expr
#define ETCL_UNARY_EXPR_CLASS ETCL_Unary_Expr
#define ETCL_EXIST_CLASS ETCL_Exist
#define ETCL_DEFAULT_CLASS ETCL_Default
#define ETCL_EVAL_CLASS ETCL_Eval
#define ETCL_DOT_CLASS ETCL_Dot
#define ETCL_COMPONENT_CLASS ETCL_Component
#define ETCL_SPECIAL_CLASS ETCL_Special
#define ETCL_COMPONENT_ARRAY_CLASS ETCL_Component_Array
#define ETCL_COMPONENT_ASSOC_CLASS ETCL_Component_Assoc
#define ETCL_COMPONENT_POS_CLASS ETCL_Component_Pos
#define ETCL_UNION_POS_CLASS ETCL_Union_Pos
#define ETCL_UNION_VALUE_CLASS ETCL_Union_Value

#define ETCL_PARSER_EXPORT_MACRO ACE_ETCL_Parser_Export
#define BEGIN_VERSIONED_NAMESPACE_MACRO ACE_BEGIN_VERSIONED_NAMESPACE_DECL
#define END_VERSIONED_NAMESPACE_MACRO ACE_END_VERSIONED_NAMESPACE_DECL

#endif // ETCL_MACROS

