// $Id$
#ifndef DOMAINAPPLICATION_IDL
#define DOMAINAPPLICATION_IDL

#include "Deployment.idl"
#include "NodeApplicationManager.idl"

module Deployment {
  interface DomainApplication : Application
  {
  };
  
  typedef sequence < DomainApplication > DomainApplications;
};

#endif /* DOMAINAPPLICATION_IDL */
