// $Id$

#ifndef OFM_CONNECTOR_IDL
#define OFM_CONNECTOR_IDL

#include <Components.idl>
#include <ccm_dds.idl>

#include "OFM_Base.idl"

#pragma ciao lem "OFM_ConnectorE.idl"

module ::CCM_DDS::Typed < ::Topic1, ::Topic1Seq> Topic1Connector;
module ::CCM_DDS::Typed < ::Topic2, ::Topic2Seq> Topic2Connector;
module ::CCM_DDS::Typed < ::Topic3, ::Topic3Seq> Topic3Connector;

#endif
