// -*- IDL -*-

//=============================================================================
/**
 * @file Test.idl
 *
 * $Id$
 *
 * "Test" IDL interface for the DLL_ORB test.
 *
 * @author Ossama Othman <ossama@uci.edu>
 */
//=============================================================================

/**
 * @class Test
 *
 * @brief Simple interface that supplies an operation to invoke.
 */
interface Test
{

  // Simple two-way operation to invoke so that the ORB transport
  // internals are excercised.
  void invoke_me ();

  // Shutdown the server-side ORB.
  oneway void shutdown ();

};
