// $Id$

/**
 * @file LatencyTT_TestSec_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef LATENCYTT_TESTSEC_CONNECTOR_IDL_
#define LATENCYTT_TESTSEC_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/LatencyTT_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "SecConnector/LatencyTT_TestSec_ConnectorE.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::LatencyTTTestSec, ::LatencyTTTestSec_Seq> LatencyTTTestSec;
};

module LatencyTT_Test
{
  connector LatencyTT_TestSec_Connector : ::CCM_DDS::LatencyTTTestSec::DDS_Event
  {
  };
};

#endif /* LatencyTT_Test_CONNECTOR_IDL_ */
