// $Id$
#ifndef RACE_PLANNER_IDL
#define RACE_PLANNER_IDL

#include <Components.idl>
#include "../Interface/Planner_I.idl"
#include "../../common/RACE_common.idl"

module CIAO
{
  
  module RACE
  {
    component Planner
    {
      provides Planner_I planner_i;
      attribute string name;
      attribute RACE_Classification type;
    };
  };
  
};

#endif /* RACE_PLANNER_IDL */
