// -*- IDL -*-
// $Id$

#include "ImR_Activator.idl"

module ImplementationRepository
{
  interface Locator : Administration
  {
    /// returns a token that can be used (along with activator name) to
    /// unregister the activator.
    long register_activator (in string name, in Activator act);

    /// You must pass in the token returned from register_activator.
    void unregister_activator (in string name, in long token);

    /// The ImR_Activator calls this method to notify death of child
    /// process that it had started.
    void notify_child_death (in string name);
  };
};

