// $Id$

/**
 * @file LNE_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef LISTEN_NOT_ENABLED_TEST_BASE_IDL
#define LISTEN_NOT_ENABLED_TEST_BASE_IDL

#pragma rti typesupport "Base/LNE_Test_BaseSupport.h"

struct ListenNotEnabledTest {
  string key; //@key
  long iteration;
};

typedef sequence<ListenNotEnabledTest> ListenNotEnabledTest_Seq;

#endif
