// $Id$
/**
 * @file Inheritance.idl
 * @author Will Otte <wotte@dre.vanderbilt.edu>
 *
 * Tests the compilation of Home inheritance.
 */

#include <Components.idl>

module HomeInheritance
{
  interface foo_interface
    {
    };

  component Foo supports foo_interface
    {
    };

  home FooHome manages Foo
    {
    };

  component Bar
    {
    };

  home BarHome : FooHome manages Bar
    {
    };

};
