// $Id$

/**
 * @file Component2.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef COMPONENT2_IDL_
#define COMPONENT2_IDL_

#include "Base/PartialShutdown.idl"

module PartialShutdown
{
  component Component2
  {
    uses Writer write_to_comp_1;
    uses Writer write_to_comp_3;

    uses Reader read_from_comp_1;
    uses Reader read_from_comp_3;

    provides Writer comp_2_writer;

    provides Reader comp_2_reader;
  };
};

#endif /* COMPONENT2_IDL_ */
