//$Id$:
/**
 * @file Receiver.idl
 *
 * @author Tao Lu <lu@dre.vanderbilt.edu>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "../Hello_Base/Hello_Base.idl"

module Hello
{
  component Receiver
  {
    uses message read_message;
    
    // Not use in test, just used to test 'uses multiple'.
    uses multiple message gather_messages;
    
    consumes timeout click_in;
  };

  home ReceiverHome manages Receiver
  {
  };

};
#endif /*RECEIVER_IDL*/
