// $Id$

#ifndef SIMPLE_FAILURE_IDL
#define SIMPLE_FAILURE_IDL

#include "Components.idl"

module Simple
{
  enum FailureType {
    NO_FAILURE,
    AT_STARTUP,
    AT_ACTIVATE,
    AT_PASSIVATE,
    AT_REMOVE
  };

  component SimpleFailure
  {
    attribute FailureType type_attr;
  };

  home SimpleFailureHome manages SimpleFailure
  {
  };
};

#endif /*SIMPLE_ATTRIBUTE_IDL*/
