// $Id$

/**
 * @file Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef CONNECTOR_IDL_
#define CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>
#include "Hello/HelloGoodbye.idl"
#include "Goodbye/HelloGoodbye.idl"


#pragma ciao lem "Connector/ConnectorE.idl"
#pragma ndds typesupport "Hello/HelloGoodbyeSupport.h"
#pragma ndds typesupport "Goodbye/HelloGoodbyeSupport.h"
#pragma opendds typesupport "Hello/HelloGoodbyeTypeSupportImpl.h"
#pragma opendds typesupport "Goodbye/HelloGoodbyeTypeSupportImpl.h"

module Hello
{
  // Hello connector
  module ::CCM_DDS::Typed < HelloGoodbye, HelloGoodbyeSeq> HelloConnector;
};

module Goodbye
{
  // Goodbye connector
  module ::CCM_DDS::Typed < HelloGoodbye, HelloGoodbyeSeq> GoodbyeConnector;
};

module HelloGoodbye
{
  // Hello connector
  module ::CCM_DDS::Typed < ::Hello::HelloGoodbye, ::Hello::HelloGoodbyeSeq> HelloConnector;

  // Goodbye connector
  module ::CCM_DDS::Typed < ::Goodbye::HelloGoodbye, ::Goodbye::HelloGoodbyeSeq> GoodbyeConnector;
};

// Hello connector
module ::CCM_DDS::Typed < ::Hello::HelloGoodbye, ::Hello::HelloGoodbyeSeq> HelloConnector;

// Goodbye connector
module ::CCM_DDS::Typed < ::Goodbye::HelloGoodbye, ::Goodbye::HelloGoodbyeSeq> GoodbyeConnector;

#endif /* CONNECTOR_IDL_ */
