// $Id$

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "Hello_Base/Hello_Base.idl"
#include "Hello_Base/HelloE.idl"
#include "Hello_Base/Hello_BaseE.idl"

module Hello
{
  component Sender
  {
    /// For asynch invocation. @@implied
    uses Hello::AMI_MyFoo       run_asynch_my_foo;

    /// For synchronous invocation
    uses Hello::MyFoo         run_my_foo;
  };
};

#endif
