// $Id$
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl MANAGEMENTWORKINSTRUCTIONS_SVNT
// ------------------------------
#ifndef MANAGEMENTWORKINSTRUCTIONS_SVNT_EXPORT_H
#define MANAGEMENTWORKINSTRUCTIONS_SVNT_EXPORT_H

#include "ace/config-all.h"

#if !defined (MANAGEMENTWORKINSTRUCTIONS_SVNT_HAS_DLL)
#  define MANAGEMENTWORKINSTRUCTIONS_SVNT_HAS_DLL 1
#endif /* ! MANAGEMENTWORKINSTRUCTIONS_SVNT_HAS_DLL */

#if defined (MANAGEMENTWORKINSTRUCTIONS_SVNT_HAS_DLL) && (MANAGEMENTWORKINSTRUCTIONS_SVNT_HAS_DLL == 1)
#  if defined (MANAGEMENTWORKINSTRUCTIONS_SVNT_BUILD_DLL)
#    define MANAGEMENTWORKINSTRUCTIONS_SVNT_Export ACE_Proper_Export_Flag
#    define MANAGEMENTWORKINSTRUCTIONS_SVNT_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define MANAGEMENTWORKINSTRUCTIONS_SVNT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* MANAGEMENTWORKINSTRUCTIONS_SVNT_BUILD_DLL */
#    define MANAGEMENTWORKINSTRUCTIONS_SVNT_Export ACE_Proper_Import_Flag
#    define MANAGEMENTWORKINSTRUCTIONS_SVNT_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define MANAGEMENTWORKINSTRUCTIONS_SVNT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* MANAGEMENTWORKINSTRUCTIONS_SVNT_BUILD_DLL */
#else /* MANAGEMENTWORKINSTRUCTIONS_SVNT_HAS_DLL == 1 */
#  define MANAGEMENTWORKINSTRUCTIONS_SVNT_Export
#  define MANAGEMENTWORKINSTRUCTIONS_SVNT_SINGLETON_DECLARATION(T)
#  define MANAGEMENTWORKINSTRUCTIONS_SVNT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* MANAGEMENTWORKINSTRUCTIONS_SVNT_HAS_DLL == 1 */

// Set MANAGEMENTWORKINSTRUCTIONS_SVNT_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (MANAGEMENTWORKINSTRUCTIONS_SVNT_NTRACE)
#  if (ACE_NTRACE == 1)
#    define MANAGEMENTWORKINSTRUCTIONS_SVNT_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define MANAGEMENTWORKINSTRUCTIONS_SVNT_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !MANAGEMENTWORKINSTRUCTIONS_SVNT_NTRACE */

#if (MANAGEMENTWORKINSTRUCTIONS_SVNT_NTRACE == 1)
#  define MANAGEMENTWORKINSTRUCTIONS_SVNT_TRACE(X)
#else /* (MANAGEMENTWORKINSTRUCTIONS_SVNT_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define MANAGEMENTWORKINSTRUCTIONS_SVNT_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (MANAGEMENTWORKINSTRUCTIONS_SVNT_NTRACE == 1) */

#endif /* MANAGEMENTWORKINSTRUCTIONS_SVNT_EXPORT_H */

// End of auto generated file.
