//$Id$
interface Roundtrip
{
    /// A simple method to measure roundtrip delays
    /**
     * The operation simply returns its argument, this is used in AMI
     * and deferred synchronous tests to measure the roundtrip delay
     * without the need for a different reply handler for each
     * request.
     */
  unsigned long long test_method (in unsigned long long send_time);

};
