// -*- IDL -*-

//=============================================================================
/**
 * @file test.idl
 *
 * $Id$
 *
 * "test" IDL interface for the Codec test.
 *
 * @author Ossama Othman <ossama@uci.edu>
 */
//=============================================================================

module Foo
{

  struct Bar
  {
    string A;
    long B;
    string C;
  };

};
