// $Id$

/**
 * @file
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/SL_Disabled_Connector.idl"

module SL_Disabled
{
  component Receiver
  {
    port SL_DisabledConnector::DDS_StateListen info_out;
  };
};

#endif
