// $Id$
/// Compliant with OMG 06-04-01 Section 6.10.2.1

#if !defined (CCM_HOMECONFIGURATION_IDL)
#define CCM_HOMECONFIGURATION_IDL

#include "ccm/CCM_Configurator.idl"
#include "ccm/CCM_StandardConfigurator.idl"
#include "ccm/CCM_Home.idl"

module Components
{
  typeprefix Components "omg.org";

  interface HomeConfiguration : CCMHome
  {
#if !defined (CCM_LW)
    void set_configurator (in Configurator cfg);
#endif
    void set_configuration_values (in ConfigValues config);
#if !defined (CCM_LW)
    void complete_component_configuration (in boolean b);
    void disable_home_configuration();
#endif
  };
};
#endif /* CCM_HOMECONFIGURATOR_IDL */
