// $Id$
/// Compliant with OMG 06-04-01 Section 6.7.6

#if !defined (CCM_HOME_IDL)
#define CCM_HOME_IDL

#if !defined (CCM_LW)
#include "tao/IFR_Client/IFR_Base.pidl"
#endif

#include "ccm/CCM_Exceptions.idl"

module Components
{
  typeprefix Components "omg.org";

#if !defined (CCM_LW)
  exception DuplicateKeyValue {};
  exception InvalidKey {};
  exception UnknownKeyValue {};
#endif

  interface CCMObject;

  interface CCMHome
  {
#if !defined (CCM_LW)
    CORBA::IRObject get_component_def ();
#endif
#if !defined (CCM_LW)
    CORBA::IRObject get_home_def ();
#endif
    void remove_component (in CCMObject comp)
      raises (RemoveFailure);
  };
};

#endif /* CCM_HOME_IDL */
