// $Id$

#ifndef INTERINOUT_T_RECEIVER_IDL
#define INTERINOUT_T_RECEIVER_IDL

#include <Components.idl>

#include "Base/InterInOutT.idl"

module InterInOutT
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
