# Makefile for building the parser

NAME = ACEXML_XML_Svc_Conf_Parser

OBJFILES = \
        $(OBJDIR)\Svcconf.obj \
        $(OBJDIR)\Svcconf_Handler.obj

CFLAGS = \
        $(ACE_CFLAGS) \
        $(ACE_XML_CFLAGS)

CPPDIR = .;..

LIBFILES = \
        $(ACE_LIB) \
        $(ACE_XML_LIB)
# WE need both -lACEXML and -lACEXML_Parser here

!include <$(ACE_ROOT)\include\makeinclude\build_core_library.bor>
