/* This file contains OMG IDL from  CORBA V2.0, July 1995.
*/


#ifndef __CONV_FRAME_IDL
#define __CONV_FRAME_IDL

#pragma prefix "omg.org"

module CONV_FRAME 
{
        // CodeSet Component of IOR Multi-Component Profile:

	typedef unsigned long CodeSetId;

	struct CodeSetComponent 
	{
		CodeSetId			native_code_set;
		sequence<CodeSetId>		conversion_code_sets;
	};

	struct CodeSetComponentInfo 
	{
		CodeSetComponent ForCharData;
		CodeSetComponent ForWcharData;
	};

	// GIOP Code Set Service Context:

	struct CodeSetContext {
		CodeSetId char_data;
		CodeSetId wchar_data;
	};
};

#endif
