//File: CosTypedEventComm.idl
//Part of the Event Service

#ifndef _COS_TYPED_EVENT_COMM_IDL_
#define _COS_TYPED_EVENT_COMM_IDL_

#include <CosEventComm.idl>

#pragma prefix "omg.org"

module CosTypedEventComm {

   interface TypedPushConsumer : CosEventComm::PushConsumer {
      Object get_typed_consumer();
   };

   interface TypedPullSupplier : CosEventComm::PullSupplier {     
      Object get_typed_supplier();
   };
};

#endif /* ifndef _COS_TYPED_EVENT_COMM_IDL_ */
