
#ifndef _TIME_BASE_IDL
#define _TIME_BASE_IDL
#pragma prefix "omg.org"

#include <orb.idl>

module TimeBase 
{
		
#ifdef NOLONGLONG
    struct ulonglong {
	unsigned long low;
	unsigned long high;
    };
    typedef ulonglong TimeT;
#else
    typedef unsigned long long TimeT;
#endif
		
    typedef TimeT              InaccuracyT;
    typedef short              TdfT;
		
    struct UtcT {
	TimeT            time;    // 8 octets
	unsigned long    inacclo; // 4 octets
	unsigned short   inacchi; // 4 octets
	TdfT             tdf;     // 2 octets
	// total 16 octets
    };
		
    struct IntervalT {
	TimeT            lower_bound;
	TimeT            upper_bound;
    };

};
#endif /* _TIME_BASE_IDL */
