// $Id$
/**
 * @file EventSource.idl
 * @author Will Otte <wotte@dre.vanderblit.edu>
 */

#include <Components.idl>

module PublishesEmits
{
  eventtype foo_event
    {
    };

  component Foo
    {
      publishes foo_event p_foo;
    };

  component Bar
    {
      emits foo_event foo;
    };
};
