// -*- IDL -*-

//=============================================================================
/**
 * @file test.idl
 *
 * Simple IDL file
 *
 * @author Johnny Willemsen  <jwillemsen@remedy.nl>
 */
//=============================================================================

module TestModule
{

  interface test
  {
  };
};
