// $Id$

#ifndef HELLO_RECEIVER_BASE_IDL
#define HELLO_RECEIVER_BASE_IDL

#include "dds4ccm/idl/dds4ccm_Base.idl3"
#include "dds4ccm/idl/dds4ccm_BaseE.idl"
#include "dds4ccm/idl/dds4ccm_ListenerControl.idl3"
#include "dds4ccm/idl/dds4ccm_ListenerControlE.idl"
#include "dds4ccm/idl/dds4ccm_PortStatusListener.idl3"
#include "dds4ccm/idl/dds4ccm_PortStatusListenerE.idl"

module CCM_DDS
{
    interface string_Reader
    {
      typedef sequence<string> stringSeq;
      
      void read_all (out stringSeq instances, out ReadInfoSeq infos)
        raises (InternalError);
      
      void read_all_history (out stringSeq instances, out ReadInfoSeq infos)
        raises (InternalError);
      
      void read_one (inout string an_instance, out ReadInfo info)
        raises (NonExistent,
                InternalError);
      
      void read_one_history (in string an_instance,
                             out stringSeq instances, out ReadInfoSeq infos)
        raises (NonExistent,
                InternalError);
      
      attribute QueryFilter filter
        setraises (BadParameter);      
    };

  interface string_RawListener
  {
    void on_data (in string an_instance, in ReadInfo info);
  };
};

#endif