// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include "Connector/Hello_Connector.idl"
#include "Connector/Hello_ConnectorE.idl"

module Hello
{
  component Receiver
  {
    port CCM_DDS::Hello::DDS_Listen info_out;

    attribute string name;
    attribute unsigned long expected_samples;
  };
};

/*
For future use: IDL3 plus
#include <dds4ccm/idl/dds4ccm_Connector_Base.idl3p>
#include <dds4ccm/idl/dds4ccm_Port_RawListen.idl3p>

module Hello
{
  component Receiver
  {
    port CCM_DDS::DDS_RawListen <DDSHello> info;
  };
};
*/
#endif
