// $Id$

/**
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef WL_RESETTOPIC_SENDER_IDL
#define WL_RESETTOPIC_SENDER_IDL

#include "Connector/WL_ResetTopic_Connector.idl"

module WL_ResetTopic
{
  interface ChangeTopicInterface
  {
    void set_new_topic (in string topic_name);
  };

  component Sender supports ChangeTopicInterface
  {
    port WL_ResetTopicTestConnector::DDS_Write  info_write;

    attribute unsigned short iterations;
    attribute unsigned short keys;
  };
};

#endif
