//
// $Id$
//

/// A simple module to avoid namespace pollution
module Test
{
  /// Use a timestamp to measure the roundtrip delay
  typedef unsigned long long Timestamp;

  /// Measure roundtrip delay
  interface Roundtrip
  {
    /// A simple method to measure roundtrip delays
    /**
     * The operation simply returns its argument, this is used in AMI
     * and deferred synchronous tests to measure the roundtrip delay
     * without the need for a different reply handler for each
     * request.
     */
    Timestamp test_method (in Timestamp send_time);

    /// Shutdown the ORB
    void shutdown ();
  };
};
