#----------------------------------------------------------------------------
#       GNU Makefile
#----------------------------------------------------------------------------

MAKEFILE        = Makefile.Kokyu
DEPENDENCY_FILE = .depend.Makefile.Kokyu
LIB_UNCHECKED   = libKokyu.a
SHLIB_UNCHECKED = libKokyu.$(SOEXT)



FILES = \
  Dispatcher_Impl \
  Kokyu \
  Default_Dispatcher_Impl \
  Dispatcher_Task \
  Kokyu_defs

LIB   = $(LIB_UNCHECKED)
SHLIB = $(SHLIB_UNCHECKED)

#----------------------------------------------------------------------------
#       Include macros and targets
#----------------------------------------------------------------------------
include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
LSRC   = $(addsuffix .cpp, $(FILES))
ACELIB = -lACE

include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.lib.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU

CPPFLAGS     += -I..
LDFLAGS      += -L../ace

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------
# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
