//$Id$

#ifndef TSEC_CHECKPOINT_IDL
#define TSEC_CHECKPOINT_IDL

#include "../interfaces/ENW.idl"


module ENW
{
  component TSEC_CheckPoint supports ISessionService
  {
    provides ISessionService sessionService;

    consumes  ET_LifeToken lifeTokenIn;
    publishes ET_LifeToken lifeTokenOut;

  };

  home TSEC_CheckPointHome manages TSEC_CheckPoint
  {
    factory new_TSEC_CheckPoint( in string   Version );
  };
};


#endif // TSEC_CHECKPOINT_IDL
