
//=============================================================================
/**
 *  @file    ami_ccm.idl
 *
 *  $Id$
 *
 *  IDL description of the AMI Test interface
 *
 */
//=============================================================================



module A
  {
    exception InternalError {
      long id;
      string error;
    };

    interface AMI_CCM
      {
        void asynch_foo (in string hello, out string answer)
          raises (InternalError);

        oneway void shutdown ();
      };
  };
