// $Id$

/**
 * @file SL_ManyByMany_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef SL_MANYBYMANY_CONNECTOR_IDL_
#define SL_MANYBYMANY_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/SL_ManyByMany_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/SL_ManyByMany_ConnectorE.idl"

module SL_ManyByMany
{
  module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> SLManyByManyConnector;
};

#endif /* SL_ManyByMany_CONNECTOR_IDL_ */
