// $Id$

/**
 * @file LNE_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef LISTEN_NOT_ENABLED_TEST_CONNECTOR_IDL_
#define LISTEN_NOT_ENABLED_TEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/LNE_Test_Base.idl"

#pragma ciao lem "Connector/LNE_Test_ConnectorE.idl"

module LNE_Test
{
  module ::CCM_DDS::Typed < ::ListenNotEnabledTest, ::ListenNotEnabledTestSeq> ListenNotEnabledTestConnector;
};

#endif /* LNE_Test_CONNECTOR_IDL_ */
