/** 
 * $Id$
 * 
 * @file DAnCE_Properties.idl
 * @author William R. Otte <wotte@dre.vanderbilt.edu>
 *
 * Codifies properties used to configure the deployment engine.
 */

module DAnCE
{
  // Home Configuration Properties
  /// Describes the entrypoint for the home executor. Property value is string.
  const string HOME_FACTORY = "home factory";
  
  // Component Configuration Properties
  /// Describes the entrypoint for the component executor. Property value is string.
  const string COMPONENT_FACTORY = "component factory";
  /// Indicates that the component instance should be deployed using specified home ID.
  /// Property value is string.
  const string EXPLICIT_HOME = "edu.vanderbilt.dre.DAnCE.ExplicitHome";
  
  const string SERVER_EXECUTABLE = "edu.vanderbilt.dre.DAnCE.ServerExecutable";
  
  const string IMPL_TYPE = "edu.vanderbilt.dre.DAnCE.ImplementationType";

  // Instance (i.e., Home or Component) Properties
  /// Indicates that the instance object reference should be registered in the 
  /// Instance naming context using a specified name.  Property value is string.
  const string REGISTER_NAMING = "edu.vanderbilt.dre.DAnCE.RegisterNaming";
  /// Indicates that the instance object reference should be printed to a specifid
  /// file.  Property value is string.
  const string INSTANCE_IOR_FILE = "edu.vanderbilt.dre.DAnCE.InstanceIOR";
  // const string REGISTER_PORT_NAMING = "edu.vanderbilt.dre.DAnCE.RegisterPortNaming";

  // Node Infrastructure Configuration
  /// Indicates that the NodeManager is running as a standalone entity. 
  const string STANDALONE_NM = "edu.vanderbilt.dre.DAnCE.StandaloneNM";
  /// Indicates the naming context for domain objects, which includes infrastructure
  /// and redirection. 
  const string DOMAIN_NC = "edu.vanderbilt.dre.DAnCE.DomainNC";
  /// Indicates the naming context used for instance objects.  
  const string INSTANCE_NC = "edu.vanderbilt.dre.DAnCE.InstanceNC";
  

};

