// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 *
 * by-hand idl3 translation of sender components.
 */

#ifndef DDS_UPDATER_SENDER_IDL
#define DDS_UPDATER_SENDER_IDL

#include "Connector/Updater_Connector.idl"

module Updater
{
  component Sender
  {
     port UpdaterConnector::DDS_Update test_topic_update;
  };
};

#endif
