// $Id$

/*
We've added a comment to the effect that this file does not contain the following
directives:
#include "tao/PI/PI.pidl"
#include "tao/PortableServer/PortableServer.pidl"
#include "tao/ObjRefTemplate/ObjectReferenceTemplate.pidl"
#include "tao/Compression/Compression.pidl"
#include "tao/Monitor/Monitor.pidl"
*/

#undef FOO
#ifdef FOO
// We've ifdef'd these directives out because we don't want to include them right now
// either because that would be wrong too.
#include "tao/PI_Server/PI_Server.pidl"
#include "tao/CodecFactory/IOP_Codec.pidl"
#include "tao/RTCORBA/RTCORBA.pidl"
#include "tao/RTPortableServer/RTPortableServer.pidl"
#include "tao/RTScheduling/RTScheduler.pidl"
#endif

// We *are* including these files instead because that's the right thing to do

#include "tao/PortableServer/PortableServer_include.pidl"
#include "tao/ObjRefTemplate/ObjectReferenceTemplate_include.pidl"
#include "tao/Compression/Compression_include.pidl"
#include "tao/PI_Server/PI_Server_include.pidl"
#include "tao/RTPortableServer/RTPortableServer_include.pidl"
#include "tao/PI/PI_include.pidl"
#include "tao/RTScheduling/RTScheduler_include.pidl"
#include "tao/Monitor/Monitor_include.pidl"
#include "tao/CodecFactory/IOP_Codec_include.pidl"
#include "tao/RTCORBA/RTCORBA_include.pidl"

