/**
 * @@ This is just a temporary file. CIAO doesn't use the security
 * service in its implementation but just using this local
 * interface below from the real security service pulls in
 * 250Kb of footprint
 *
 * $Id$
 */

#if !defined (CIAO_SECURITY_IDL)
#define CIAO_SECURITY_IDL

#if !defined (CCM_LW)

#pragma prefix "omg.org"

module SecurityLevel2 {

# pragma version SecurityLevel2 1.8

  local interface Credentials
  {
  };
};

#endif

#endif /* CIAO_SECURITY_IDL */
