// $Id$

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "Base/Hello.idl"

#pragma ciao ami4ccm receptacle "Hello::Sender::run_my_foo"

module Hello
{
  component Sender
  {
    /// For synchronous invocation
    uses MyFoo run_my_foo;
  };
};

#endif
