//$Id$:

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "../Hello_Base/Hello_Base.idl"

module Hello
{
  component Receiver
  {
    uses ReadMessage read_message;
    consumes TimeOut click_in;

    attribute short iterations;
  };

};
#endif /*RECEIVER_IDL*/
