// $Id$

/**
 *  @file Administrator.idl
 *
 *  @author Don Busch <busch_d@ociweb.com>
 */

#ifndef ADMINISTRATOR_IDL
#define ADMINISTRATOR_IDL

#include <Components.idl>
#include "Runnable.idl"
#include "Publication.idl"

component Administrator {
  uses multiple Runnable runnables;
  uses multiple Publication content;
};

home AdministratorHome manages Administrator {};

#endif

