// $Id$

/**
 * @file VT_Valuetype_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef VT_VALUETYPE_CONNECTOR_IDL_
#define VT_VALUETYPE_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/VTopic_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Conn_Valuetype/VT_Valuetype_ConnectorE.idl"

module VTopic
{
  module ::CCM_DDS::Typed < ::TopicValuetype, ::TopicValuetypeSeq> TopicValuetypeConnector;
};

#endif /* VT_VALUETYPE_CONNECTOR_IDL_ */
