// $Id$

#ifndef AMI_IDL
#define AMI_IDL

#include <Components.idl>

#include "Hello_Base/Hello_Base.idl"
#include "Hello_Base/Hello_BaseE.idl"
#include "Hello_Base/HelloE.idl"

#define connector component

module Hello
{
  connector AMI_Receiver
  {
    /// Provides the interface for Sender
    provides Hello::AMI_MyFoo perform_asynch_my_foo;

    /// Uses the interface of the Receiver ('server')
    uses Hello::MyFoo my_foo_receiver;
  };
};


#endif
