// $Id$

#ifndef AMI_IDL
#define AMI_IDL

#include <Components.idl>

#include "Hello_Base/Hello_Base.idl"
#include "Hello_Base/Hello_BaseE.idl"
#include "Hello_Base/HelloE.idl"

module Hello_AMI
{
  component AMI
  {
    //provides the interface for Sender
    provides CCM_AMI::AMI_MyFoo perform_asynch_my_foo;

    //uses the interface of the Receiver ('server')
    uses Hello::MyFoo my_foo_receiver;

    //uses the callback interface of the sender
    uses CCM_AMI::AMI_MyFooCallback callback_my_foo;
  };

  home AMIHome manages AMI
  {
  };
};


#endif
