// $Id$

/**
 * @@ Compile this file with:
 *
 *     tao_idl -I ../.. \
 *          -Wb,export_macro=CIAO_Export \
 *          -Wb,export_include=CIAO_export.h \
 *          -Wb,pre_include="ace/pre.h" \
 *          -Wb,post_include="ace/post.h" \
 *          CCM_Deployment.idl
 */

//#define CIAO_HAS_IMPORT_KEYWORD

#if !defined (CCM_DEPLOYMENT_IDL)
#define CCM_DEPLOYMENT_IDL

#include "CCM_Component.idl"
#include "../Property.idl"

// *************** Packaging and Deployment ***************

module Components
{
  // Typeprefix Components "omg.org";
  // OMG threw these things away, didn't it.

  //@@ I have decided to keep this ::Component::Deployment
  //module to keep it apart from ::Deployment. --Tao
  module Deployment
  {
    typedef string UUID;
    typedef string Location;

    enum AssemblyState
    {
      INACTIVE,
      INSERVICE
    };

    exception UnknownImplId {};
    exception InvalidLocation {};
    exception InstallationFailure
    {
      FailureReason reason;
    };

    exception InvalidAssembly {};
    interface Container;        // Forward decl.
    typedef sequence<Container> Containers;

    //@@ Is this exception still necessary?
    //   I would like to keep it since it's more accurate on
    //   describing the situation. --Tao
    exception ImplEntryPointNotFound {};

    interface Container
    {
      readonly attribute ::Deployment::Properties con_properties;

      //@@ We know that Dployment::NodeApplication will be returned,
      //   however to avoid the size of the shared object of CIAO_Server.
      //   we return a Object.
      Object get_node_application ();

      //@@ The properties will contain
      //1 dll/so name of the exec
      //2 entry point of the exec
      //3 dll/so name of the svnt
      //4 entry point of the svnt
      //5 Poosible other configuration for container/home/component
      //Note:: We have to decide later how container/home/component could be configured.
      //       These properties could be passed in here or at higher level
      //       according to the plan(@ NodeApplicationManager/NodeApplication?)
      //
      //                                                   --Tao
      CCMHome install_home (in ::Deployment::Properties properties)
        raises (UnknownImplId,
                ImplEntryPointNotFound,
                InstallationFailure,
                InvalidConfiguration);

      void remove_home (in CCMHome href)
        raises (RemoveFailure);

      CCMHomes get_homes ();
      void remove ()
        raises (RemoveFailure);

    };

  };
};
#endif /* CCM_DEPLOYMENT_IDL */
