// $Id$

/**
 * @file Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef BASE_IDL
#define BASE_IDL

#pragma rti typesupport "Base/BaseSupport.h"

struct SharedDPTest {
  string key;
  long iteration;
};
typedef sequence<SharedDPTest> SharedDPTest_Seq;

#endif
