// $Id$

/**
 * @file   psat_type.idl
 */

#ifndef PSAT_TYPE_IDL
#define PSAT_TYPE_IDL

#pragma ndds typesupport "psat_typeSupport.h"
#pragma opendds typesupport "psat_typeTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "TestTopic"
#pragma DCPS_DATA_KEY "TestTopic key"

struct TestTopic {
  string key; //@key
  long x;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<TestTopic> TestTopicSeq;
#endif

#endif
