// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/LatencyTT_Test_Connector.idl"

module LatencyTT_Test
{
  component Receiver
  {
    port LatencyTTTestConn::DDS_Listen info_listen;
    port LatencyTTTestConn::DDS_Write write_ping;
  };
};

#endif
