 
import "oaidl.idl";
import "ocidl.idl";

#include "DecoratorConfig.h"

#define MAKE_STR(PAR) #PAR
#define PATH3(X,Y) MAKE_STR(X##Y)
#define PATH2(X,Y) PATH3(X,Y)
#define PATH(NAME) PATH2(GME_INTERFACES_BASE,NAME)

#include PATH(/InterfaceColl.h)
#include PATH(/meta.idl)
#include PATH(/mga.idl)
#include PATH(/gme.idl)
#include PATH(/MgaDecorator.idl)


[
	uuid(TYPELIB_UUID),
	version(1.0),
	helpstring("TYPELIB_NAME")
]
library DecoratorLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(COCLASS_UUID),
		helpstring(COCLASS_NAME)
	]
	coclass Decorator
	{
		[default] interface IMgaDecorator;
		interface IMgaVersionInfo;
	};

};
