// $Id$

#include "concrete_classes.h"
#include "ace/Auto_Ptr.h"

ACE_RCSID(IFR_Service, tmplinst, "$Id$")

#if defined (ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION)

template class ACE_Node<CORBA::DefinitionKind>;
template class ACE_Unbounded_Queue<CORBA::DefinitionKind>;
template class ACE_Unbounded_Queue_Iterator<CORBA::DefinitionKind>;
template class ACE_Node<ACE_Configuration_Section_Key>;
template class ACE_Unbounded_Queue<ACE_Configuration_Section_Key>;
template class ACE_Unbounded_Queue_Iterator<ACE_Configuration_Section_Key>;

template class POA_CORBA_Repository_tie<TAO_Repository_i>;
template class POA_IR::ComponentRepository_tie<TAO_ComponentRepository_i>;
template class POA_CORBA_PrimitiveDef_tie<TAO_PrimitiveDef_i>;
template class POA_CORBA_StringDef_tie<TAO_StringDef_i>;
template class POA_CORBA_WstringDef_tie<TAO_WstringDef_i>;
template class POA_CORBA_SequenceDef_tie<TAO_SequenceDef_i>;
template class POA_CORBA_ArrayDef_tie<TAO_ArrayDef_i>;
template class POA_CORBA_FixedDef_tie<TAO_FixedDef_i>;
template class POA_CORBA_EnumDef_tie<TAO_EnumDef_i>;
template class POA_CORBA_AliasDef_tie<TAO_AliasDef_i>;
template class POA_CORBA_NativeDef_tie<TAO_NativeDef_i>;
template class POA_CORBA_ValueBoxDef_tie<TAO_ValueBoxDef_i>;
template class POA_CORBA_UnionDef_tie<TAO_UnionDef_i>;
template class POA_CORBA_StructDef_tie<TAO_StructDef_i>;
template class POA_IR::ConsumesDef_tie<TAO_ConsumesDef_i>;
template class POA_IR::PublishesDef_tie<TAO_PublishesDef_i>;
template class POA_IR::EmitsDef_tie<TAO_EmitsDef_i>;
template class POA_IR::PrimaryKeyDef_tie<TAO_PrimaryKeyDef_i>;
template class POA_IR::ProvidesDef_tie<TAO_ProvidesDef_i>;
template class POA_IR::UsesDef_tie<TAO_UsesDef_i>;
template class POA_CORBA_ValueMemberDef_tie<TAO_ValueMemberDef_i>;
template class POA_IR::FactoryDef_tie<TAO_FactoryDef_i>;
template class POA_IR::FinderDef_tie<TAO_FinderDef_i>;
template class POA_CORBA_AttributeDef_tie<TAO_AttributeDef_i>;
template class POA_CORBA_ConstantDef_tie<TAO_ConstantDef_i>;
template class POA_IR::ComponentDef_tie<TAO_ComponentDef_i>;
template class POA_IR::HomeDef_tie<TAO_HomeDef_i>;
template class POA_CORBA_ValueDef_tie<TAO_ValueDef_i>;
template class POA_CORBA_ExceptionDef_tie<TAO_ExceptionDef_i>;
template class POA_CORBA_ModuleDef_tie<TAO_ModuleDef_i>;
template class POA_CORBA_OperationDef_tie<TAO_OperationDef_i>;
template class POA_CORBA_InterfaceDef_tie<TAO_InterfaceDef_i>;
template class POA_CORBA_AbstractInterfaceDef_tie<TAO_AbstractInterfaceDef_i>;
template class POA_CORBA_LocalInterfaceDef_tie<TAO_LocalInterfaceDef_i>;

template class auto_ptr<TAO_Repository_i>;
template class ACE_Auto_Basic_Ptr<TAO_Repository_i>;
template class auto_ptr<TAO_ComponentRepository_i>;
template class ACE_Auto_Basic_Ptr<TAO_ComponentRepository_i>;
template class auto_ptr<TAO_PrimitiveDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_PrimitiveDef_i>;
template class auto_ptr<TAO_StringDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_StringDef_i>;
template class auto_ptr<TAO_WstringDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_WstringDef_i>;
template class auto_ptr<TAO_SequenceDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_SequenceDef_i>;
template class auto_ptr<TAO_ArrayDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ArrayDef_i>;
template class auto_ptr<TAO_FixedDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_FixedDef_i>;
template class auto_ptr<TAO_EnumDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_EnumDef_i>;
template class auto_ptr<TAO_AliasDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_AliasDef_i>;
template class auto_ptr<TAO_NativeDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_NativeDef_i>;
template class auto_ptr<TAO_ValueBoxDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ValueBoxDef_i>;
template class auto_ptr<TAO_UnionDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_UnionDef_i>;
template class auto_ptr<TAO_StructDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_StructDef_i>;
template class auto_ptr<TAO_ConsumesDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ConsumesDef_i>;
template class auto_ptr<TAO_PublishesDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_PublishesDef_i>;
template class auto_ptr<TAO_EmitsDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_EmitsDef_i>;
template class auto_ptr<TAO_PrimaryKeyDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_PrimaryKeyDef_i>;
template class auto_ptr<TAO_ProvidesDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ProvidesDef_i>;
template class auto_ptr<TAO_UsesDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_UsesDef_i>;
template class auto_ptr<TAO_ValueMemberDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ValueMemberDef_i>;
template class auto_ptr<TAO_FactoryDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_FactoryDef_i>;
template class auto_ptr<TAO_FinderDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_FinderDef_i>;
template class auto_ptr<TAO_AttributeDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_AttributeDef_i>;
template class auto_ptr<TAO_ConstantDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ConstantDef_i>;
template class auto_ptr<TAO_ComponentDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ComponentDef_i>;
template class auto_ptr<TAO_HomeDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_HomeDef_i>;
template class auto_ptr<TAO_ValueDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ValueDef_i>;
template class auto_ptr<TAO_ExceptionDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ExceptionDef_i>;
template class auto_ptr<TAO_ModuleDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_ModuleDef_i>;
template class auto_ptr<TAO_OperationDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_OperationDef_i>;
template class auto_ptr<TAO_InterfaceDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_InterfaceDef_i>;
template class auto_ptr<TAO_AbstractInterfaceDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_AbstractInterfaceDef_i>;
template class auto_ptr<TAO_LocalInterfaceDef_i>;
template class ACE_Auto_Basic_Ptr<TAO_LocalInterfaceDef_i>;
template class auto_ptr<TAO_Container_i>;
template class ACE_Auto_Basic_Ptr<TAO_Container_i>;
template class auto_ptr<TAO_Contained_i>;
template class ACE_Auto_Basic_Ptr<TAO_Contained_i>;
template class auto_ptr<TAO_IDLType_i>;
template class ACE_Auto_Basic_Ptr<TAO_IDLType_i>;

template class ACE_Auto_Basic_Ptr<char>;

#elif defined (ACE_HAS_TEMPLATE_INSTANTIATION_PRAGMA)

#pragma instantiate ACE_Node<CORBA::DefinitionKind>
#pragma instantiate ACE_Unbounded_Queue<CORBA::DefinitionKind>
#pragma instantiate ACE_Unbounded_Queue_Iterator<CORBA::DefinitionKind>
#pragma instantiate ACE_Node<ACE_Configuration_Section_Key>
#pragma instantiate ACE_Unbounded_Queue<ACE_Configuration_Section_Key>
#pragma instantiate ACE_Unbounded_Queue_Iterator<ACE_Configuration_Section_Key>

#pragma instantiate POA_CORBA_Repository_tie<TAO_Repository_i>
#pragma instantiate POA_IR::ComponentRepository_tie<TAO_ComponentRepository_i>
#pragma instantiate POA_CORBA_PrimitiveDef_tie<TAO_PrimitiveDef_i>
#pragma instantiate POA_CORBA_StringDef_tie<TAO_StringDef_i>
#pragma instantiate POA_CORBA_WstringDef_tie<TAO_WstringDef_i>
#pragma instantiate POA_CORBA_SequenceDef_tie<TAO_SequenceDef_i>
#pragma instantiate POA_CORBA_ArrayDef_tie<TAO_ArrayDef_i>
#pragma instantiate POA_CORBA_FixedDef_tie<TAO_FixedDef_i>
#pragma instantiate POA_CORBA_EnumDef_tie<TAO_EnumDef_i>
#pragma instantiate POA_CORBA_AliasDef_tie<TAO_AliasDef_i>
#pragma instantiate POA_CORBA_NativeDef_tie<TAO_NativeDef_i>
#pragma instantiate POA_CORBA_ValueBoxDef_tie<TAO_ValueBoxDef_i>
#pragma instantiate POA_CORBA_UnionDef_tie<TAO_UnionDef_i>
#pragma instantiate POA_CORBA_StructDef_tie<TAO_StructDef_i>
#pragma instantiate POA_IR::ConsumesDef_tie<TAO_ConsumesDef_i>
#pragma instantiate POA_IR::PublishesDef_tie<TAO_PublishesDef_i>
#pragma instantiate POA_IR::EmitsDef_tie<TAO_EmitsDef_i>
#pragma instantiate POA_IR::PrimaryKeyDef_tie<TAO_PrimaryKeyDef_i>
#pragma instantiate POA_IR::ProvidesDef_tie<TAO_ProvidesDef_i>
#pragma instantiate POA_IR::UsesDef_tie<TAO_UsesDef_i>
#pragma instantiate POA_CORBA_ValueMemberDef_tie<TAO_ValueMemberDef_i>
#pragma instantiate POA_IR::FactoryDef_tie<TAO_FactoryDef_i>
#pragma instantiate POA_IR::FinderDef_tie<TAO_FinderDef_i>
#pragma instantiate POA_CORBA_AttributeDef_tie<TAO_AttributeDef_i>
#pragma instantiate POA_CORBA_ConstantDef_tie<TAO_ConstantDef_i>
#pragma instantiate POA_IR::ComponentDef_tie<TAO_ComponentDef_i>
#pragma instantiate POA_IR::HomeDef_tie<TAO_HomeDef_i>
#pragma instantiate POA_CORBA_ValueDef_tie<TAO_ValueDef_i>
#pragma instantiate POA_CORBA_ExceptionDef_tie<TAO_ExceptionDef_i>
#pragma instantiate POA_CORBA_ModuleDef_tie<TAO_ModuleDef_i>
#pragma instantiate POA_CORBA_OperationDef_tie<TAO_OperationDef_i>
#pragma instantiate POA_CORBA_InterfaceDef_tie<TAO_>
#pragma instantiate POA_CORBA_AbstractInterfaceDef_tie<TAO_AbstractInterfaceDef_i>
#pragma instantiate POA_CORBA_LocalInterfaceDef_tie<TAO_LocalInterfaceDef_i>

#pragma instantiate auto_ptr<TAO_Repository_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_Repository_i>
#pragma instantiate auto_ptr<TAO_ComponentRepository_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ComponentRepository_i>
#pragma instantiate auto_ptr<TAO_PrimitiveDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_PrimitiveDef_i>
#pragma instantiate auto_ptr<TAO_StringDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_StringDef_i>
#pragma instantiate auto_ptr<TAO_WstringDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_WstringDef_i>
#pragma instantiate auto_ptr<TAO_SequenceDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_SequenceDef_i>
#pragma instantiate auto_ptr<TAO_ArrayDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ArrayDef_i>
#pragma instantiate auto_ptr<TAO_FixedDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_FixedDef_i>
#pragma instantiate auto_ptr<TAO_EnumDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_EnumDef_i>
#pragma instantiate auto_ptr<TAO_AliasDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_AliasDef_i>
#pragma instantiate auto_ptr<TAO_NativeDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_NativeDef_i>
#pragma instantiate auto_ptr<TAO_ValueBoxDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ValueBoxDef_i>
#pragma instantiate auto_ptr<TAO_UnionDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_UnionDef_i>
#pragma instantiate auto_ptr<TAO_StructDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_StructDef_i>
#pragma instantiate auto_ptr<TAO_ConsumesDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ConsumesDef_i>
#pragma instantiate auto_ptr<TAO_PublishesDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_PublishesDef_i>
#pragma instantiate auto_ptr<TAO_EmitsDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_EmitsDef_i>
#pragma instantiate auto_ptr<TAO_PrimaryKeyDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_PrimaryKeyDef_i>
#pragma instantiate auto_ptr<TAO_ProvidesDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ProvidesDef_i>
#pragma instantiate auto_ptr<TAO_UsesDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_UsesDef_i>
#pragma instantiate auto_ptr<TAO_ValueMemberDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ValueMemberDef_i>
#pragma instantiate auto_ptr<TAO_FactoryDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_FactoryDef_i>
#pragma instantiate auto_ptr<TAO_FinderDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_FinderDef_i>
#pragma instantiate auto_ptr<TAO_AttributeDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_AttributeDef_i>
#pragma instantiate auto_ptr<TAO_ConstantDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ConstantDef_i>
#pragma instantiate auto_ptr<TAO_ComponentDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ComponentDef_i>
#pragma instantiate auto_ptr<TAO_HomeDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_HomeDef_i>
#pragma instantiate auto_ptr<TAO_ValueDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ValueDef_i>
#pragma instantiate auto_ptr<TAO_ExceptionDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ExceptionDef_i>
#pragma instantiate auto_ptr<TAO_ModuleDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_ModuleDef_i>
#pragma instantiate auto_ptr<TAO_OperationDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_OperationDef_i>
#pragma instantiate auto_ptr<TAO_InterfaceDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_InterfaceDef_i>
#pragma instantiate auto_ptr<TAO_AbstractInterfaceDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_AbstractInterfaceDef_i>
#pragma instantiate auto_ptr<TAO_LocalInterfaceDef_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_LocalInterfaceDef_i>
#pragma instantiate auto_ptr<TAO_Container_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_Container_i>
#pragma instantiate auto_ptr<TAO_Contained_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_Contained_i>
#pragma instantiate auto_ptr<TAO_IDLType_i>
#pragma instantiate ACE_Auto_Basic_Ptr<TAO_IDLType_i>

#pragma instantiate ACE_Auto_Basic_Ptr<char>

#endif /* ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION */
