// $Id$

/**
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef DDS_SL_MANYBYMANY_SENDER_IDL
#define DDS_SL_MANYBYMANY_SENDER_IDL

#include "Connector/SL_ManyByMany_Connector.idl"

module SL_ManyByMany
{
  component Sender
  {
     port ::SL_ManyByMany::SLManyByManyConnector::DDS_Update test_topic_update;
     provides CCM_DDS::ConnectorStatusListener test_topic_connector_status;
  };
};

#endif
