// $Id$

/**
 * @file OneFile_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef ONEFILE_CONNECTOR_IDL_
#define ONEFILE_CONNECTOR_IDL_

#if defined __TAO_IDL
#include <ccm_dds.idl>
#endif

#include "OneFile_Base.idl"

#pragma ndds typesupport "OneFile_BaseSupport.h"
#pragma ciao lem "OneFile_ConnectorE.idl"

module OneFile_Connector
{
  module ::CCM_DDS::Typed < OneFileTopic, OneFileTopicSeq> OneFileConnector;
};

module ::CCM_DDS::Typed < OneFileTopic, OneFileTopicSeq> OneFileConnector;

#endif /* ONEFILE_CONNECTOR_IDL_ */
