// $Id$

/**
 * @file ConnectorStatusListener_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef CONNECTORSTATUSLISTENER_TESTSEC_CONNECTOR_IDL_
#define CONNECTORSTATUSLISTENER_TESTSEC_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/ConnectorStatusListener_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

TYPED_MODULE( ::TestSecondTopic, ::TestSecondTopic_Seq, TestSecondTopic)

module ConnectorStatusListener_Test
{
  connector ConnectorStatusListener_TestSec_Connector : ::CCM_DDS::TestSecondTopic::DDS_Event
  {
  };

};



#endif /* ConnectorStatusListener_CONNECTOR_IDL_ */
