//$Id$
#ifndef RACE_INTERACTIVE_INPUT_ADAPTER_IDL
#define RACE_INTERACTIVE_INPUT_ADAPTER_IDL

#include <Components.idl>
#include "../Base/Input_Adapter.idl"

module CIAO
{
  module RACE
  {
    component Interactive_Input_Adapter : Input_Adapter
    {
    };
    
    home Interactive_Input_Adapter_Home manages Interactive_Input_Adapter
    {
    };
  };
};

#endif /* RACE_INTERACTIVE_INPUT_ADAPTER_IDL */
