// $Id$

/**
 * @file NonChangeable_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef NONCHANGABLE_CONNECTOR_IDL_
#define NONCHANGABLE_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/NonChangeable_Base.idl"

#pragma ciao lem "Connector/NonChangeable_ConnectorE.idl"

module NonChangeable
{
  module ::CCM_DDS::Typed
    < ::NonChangeableTest, ::NonChangeableTestSeq>
    NonChangeableTestConnector;
};

#endif /* NonChangeable_CONNECTOR_IDL_ */
