// $Id$

interface Test
{
  // = TITLE
  //   @@ Kirthika, please fill in here.
  //
  // = DESCRIPTION
  //   @@ Kirthika, please fill in here.

  exception Oops 
    {
      string reason;
    };

  short method (in short boo) raises (Oops);

  oneway void shutdown ();
};
