/* -*- C++ -*- $Id$ */

// messenger.idl

interface Messenger
{
  boolean send_message ( in    string user_name,
                          in    string subject,
                          inout string message );

  void shutdown ( in string user_name );
};
