/* -*- C++ -*- */
// $Id$

interface Receiver
{
  // = TITLE
  //    The Receiver interface is implemented by the simple chat
  //    clients.The interface functions are called by the chat server.

  void message (in string msg);
  // Displays the message in the client application.

  oneway void shutdown ();
  // Called by the chat server before it goes away.
};
