// $Id$

/**
 * @file Controller.idl
 *
 * Definition of an Controller component that triggers a worker
 * connecting to it to do some work.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */

#ifndef CONTROLLER_IDL
#define CONTROLLER_IDL

#include "../Priority_Test.idl"

module Priority_Test
{
  component Controller supports Op_Mode
    {
      uses Common_Ops worker;
    };

  home ControllerHome manages Controller
  {
  };
};

#endif /* CONTROLLER_IDL */
