// $Id$

// Either of these sets will work, but only the last one
// demonstrates the original tao_idl problem.

//#define MyString string
//typedef MyString ArrayOfString[15];

//typedef string MyString;
//typedef string ArrayOfString[15];

typedef string MyString;
typedef MyString ArrayOfString[15];

interface SimpleStrings
{
  void get_strings(out ArrayOfString strings);
};
