// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/CSL_USTest_Connector.idl"

module CSL_USTest
{
  component Receiver
  {
    port CSL_US_Connector::DDS_Listen info_out;
    port CSL_US_Connector::DDS_Read info_read;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
   };
};

#endif
