// $Id$

/**
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef DDS_LISTEN_MANY_BY_MANY_TEST_SENDER_IDL
#define DDS_LISTEN_MANY_BY_MANY_TEST_SENDER_IDL

#include "Connector/LMBM_Test_Connector.idl"

module LMBM_Test
{
  component Sender
  {
    port ListenManyByManyTestConnector::DDS_Write info_write;
    provides CCM_DDS::ConnectorStatusListener info_write_connector_status;

    attribute unsigned short keys;
    attribute unsigned short iterations;
  };
};

#endif
