// $Id$

/**
 * @@ Compile this file with:
 *
 *     tao_idl -Gv -I ../.. -I ../../orbsvcs/orbsvcs \
 *          -Wb,export_macro=CIAO_Export \
 *          -Wb,export_include=CIAO_export.h \
 *          -Wb,pre_include="ace/pre.h" \
 *          -Wb,post_include="ace/post.h" \
 *          CCM_Component.idl
 */

#if !defined (CCM_HOMECONFIGURATION_IDL)
#define CCM_HOMECONFIGURATION_IDL

#include "ccm/CCM_Configurator.idl"
#include "ccm/CCM_StandardConfigurator.idl"
#include "ccm/CCM_Home.idl"

module Components
{
  typeprefix Components "omg.org";

  interface HomeConfiguration : CCMHome
  {
    void set_configurator (in Configurator cfg);
    void set_configuration_values (in ConfigValues config);
    void complete_component_configuration (in boolean b);
    void disable_home_configuration();
  };
};
#endif /* CCM_HOMECONFIGURATOR_IDL */
