// $Id$

/**
 * @file State_MemLeakDetection_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef STATE_MEMLEAKDETECTION_TEST_BASE_IDL
#define STATE_MEMLEAKDETECTION_TEST_BASE_IDL

#pragma ndds typesupport "Base/State_MemLeakDetection_Test_BaseSupport.h"
#pragma opendds typesupport "Base/State_MemLeakDetection_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "State_MemLeakDetectionTest"
#pragma DCPS_DATA_KEY "State_MemLeakDetectionTest key"

struct State_MemLeakDetectionTest {
  string key; //@key
  long iteration;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<State_MemLeakDetectionTest> State_MemLeakDetectionTestSeq;
#endif

#endif
