// $Id$

/**
 * @file
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Latency_Test_Connector.idl"

module Latency_Test
{
  component Receiver
  {
    port CCM_DDS::LatencyTest::DDS_Listen info_listen;
    port CCM_DDS::LatencyTest::DDS_Write write_ping;
  };
};

#endif
