//$Id$:
/**
 *  @file Hello.idl
 *  Definition of common interfaces used by the Hello example
 *
 *  @auther Tao Lu <lu@dre.vanderbilt.edu>
 */

#ifndef HELLO_IDL
#define HELLO_IDL

#include <Components.idl>


module Hello
{
  interface message
  {
    string get_message();
  };

  eventtype timeout
  {
  };

};

#endif /* HELLO_IDL */
