// $Id$

/**
 * @file
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/CSL_DeadlineTest_Connector.idl"

module CSL_DeadlineTest
{
  component Receiver
  {
    port CSLDeadlineConnector::DDS_Listen info_out;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
   };
};

#endif
