// $Id$

#if !defined (CCM_SESSIONCONTEXT_IDL)
#define CCM_SESSIONCONTEXT_IDL

#include "ccm/CCM_Context.idl"

module Components
{
  typeprefix Components "omg.org";

  local interface SessionContext : CCMContext
  {
    Object get_CCM_object()
      raises (IllegalState);
  };
};
#endif /* CCM_SESSIONCONTEXT_IDL */
