// $Id$

/**
 * @file VT_Seq_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef VT_SEQ_CONNECTOR_IDL_
#define VT_SEQ_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/VTopic_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "VT_Seq_ConnectorE.idl"

TYPED_MODULE( ::TopicSeq, ::TopicSeq_Seq, TopicSeq)

module VTopic
{
  connector VT_Seq_Connector : ::CCM_DDS::TopicSeq::DDS_Event
  {
  };
};

#endif /* VTopic_CONNECTOR_IDL_ */
