// $Id$

/**
 * @file Keyed_Test_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 *
 * by-hand translation of the idl3p.
 */

#ifndef KEYED_TEST_CONNECTOR_IDL_
#define KEYED_TEST_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/Keyed_Test_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

TYPED_MODULE( ::KeyedTest, ::KeyedTest_Seq, KeyedTest)

module Keyed_Test
{
  connector Keyed_Test_Connector : ::CCM_DDS::KeyedTest::DDS_MonoConnector
  {
  };
};

#endif /* Keyed_Test_CONNECTOR_IDL_ */
