//=============================================================================
/**
 *  @file    Triangle_Test.idl
 *
 *  $Id$
 *
 *  An example of how nested upcalls work/fail?
 *
 *
 *  @author Michael Kircher
 */
//=============================================================================



interface Initiator {

  oneway void foo_object_B ();

};

interface Object_A {

  void foo (in Initiator theInitiator);

  oneway void finish ();

  oneway void shutdown ();

};

interface Object_B {

  void foo (in Object_A theObject_A);

  oneway void shutdown ();

};
