// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Event_Connection_Test_Connector.idl"

module Event_Connection_Test
{
  component Receiver
  {
    port Event_ConnectionConnector::DDS_Listen  info_listen;
    port Event_ConnectionConnector::DDS_Get     info_get;
    provides CCM_DDS::ConnectorStatusListener status_listener;
  };
};

#endif
