// $Id$

#include "CCM_Container.idl"


module CIAO
{
  local interface Swap_Exec : ::Components::EnterpriseComponent
  {
    Components::EnterpriseComponent incarnate ();
    Components::EnterpriseComponent etherealize ();
  };
};
