// $Id$
#include <Components.idl>
#include "BMClosedED.idl"

module BasicSP
{
  local interface CCM_ReadData : ReadData
  {
  };

};

module BasicSP
{
  local interface CCM_BMClosedED : ::Components::EnterpriseComponent
  {
    ::BasicSP::CCM_ReadData get_dataout ();
    void push_in_avail (in ::BasicSP::DataAvailable ev);
  };

  local interface CCM_BMClosedED_Context  : ::Components::SessionContext
  {
    ::BasicSP::ReadData get_connection_datain ();
    void push_out_avail (in ::BasicSP::DataAvailable ev);
  };

  local interface CCM_BMClosedEDHomeExplicit : ::Components::HomeExecutorBase
  {
  };

  local interface CCM_BMClosedEDHomeImplicit
  {
    ::Components::EnterpriseComponent create () raises (::Components::CCMException);
  };

  local interface CCM_BMClosedEDHome : CCM_BMClosedEDHomeExplicit, CCM_BMClosedEDHomeImplicit
  {
  };

};

module BMClosedED_Impl
{
  local interface _Context : ::BasicSP::CCM_BMClosedED_Context, ::Components::SessionContext
  {
  };

};

