// $Id$

#ifndef HELLO_RECEIVER_CONNECTOR
#define HELLO_RECEIVER_CONNECTOR


#include <Components.idl>


#include "Hello_Receiver_Base.idl"
#include "Hello_Receiver_BaseE.idl"
#include "dds4ccm/idl/dds_rtf2_dcpsE.idl"

module Hello_DDS
{
  component Hello_receiver_Connector
  {
    provides CCM_DDS::string_Reader receiver_data;
    provides CCM_DDS::ListenerControl receiver_control;
    uses CCM_DDS::string_RawListener receiver_listener;
    provides DDS::DataReader receiver_dds_entity;
    uses CCM_DDS::PortStatusListener receiver_status;
  };

  home ReceiverConnectorHome manages Hello_receiver_Connector
  {
  };
};

#endif
