// $Id$

#ifndef DEPLOYMENT_IDL
#define DEPLOYMENT_IDL

module Deployment {
  exception InvalidProperty {
    string name;
    string reason;
  };

  exception InvalidNodeExecParameter {
    string name;
    string reason;
  };

  exception InvalidComponentExecParameter {
    string name;
    string reason;
  };

  exception NoSuchName {
  };

  exception LastConfiguration {
  };

  exception InvalidReference {
  };
  //@! in DOCGroup added 1 additional exception and one structure
};

#endif /* DEPLOYMENT_IDL */

