// $Id$

#include "../common/DiffServ.idl"

module DiffServ
{
  interface Sender_Controller
  {
    void start (in unsigned long iterations, 
                in short priority);

    void shutdown ();
  };

  component Sender supports Sender_Controller
  {
    uses test reader;
  };

  home SenderHome manages Sender
  {
  };
};
