// $Id$

interface test
{
  void start_test (in long session_id,
       in string protocol,
       in unsigned long invocation_rate,
       in unsigned long message_size,
       in unsigned long iterations);

  void end_test ();

  oneway void oneway_sync ();

  void twoway_sync ();

  void shutdown ();

  typedef sequence<octet> octets;

  oneway void oneway_method (in long session_id,
           in unsigned long iteration,
           in octets payload);

  void twoway_method (inout long session_id,
          inout unsigned long iteration,
          inout octets payload);
};
