// $Id$

/**
 * @file SetConnectorAttribute_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef SETCONNECTORATTRIBUTE_CONNECTOR_IDL_
#define SETCONNECTORATTRIBUTE_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/SetConnectorAttribute_Base.idl"

#pragma ciao lem "Connector/SetConnectorAttribute_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/SetConnectorAttribute_BaseTypeSupport.idl"
#endif

module SetConnectorAttribute
{
  module ::CCM_DDS::Typed
    < ::SetConnectorAttributeTest, ::SetConnectorAttributeTestSeq>
    SetConnectorAttributeTestConnector;
};

#endif /* SetConnectorAttribute_CONNECTOR_IDL_ */
