// $Id$

/**
 * @file TL_ResetTopic_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef TL_RESETTOPIC_BASE_IDL
#define TL_RESETTOPIC_BASE_IDL

#pragma ndds typesupport "Base/TL_ResetTopic_BaseSupport.h"
#pragma opendds typesupport "Base/TL_ResetTopic_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "TL_ResetTopicTest"
#pragma DCPS_DATA_KEY "TL_ResetTopicTest key"

struct TL_ResetTopicTest {
  string key; //@key
  long iteration;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<TL_ResetTopicTest> TL_ResetTopicTestSeq;
#endif

#endif
