// $Id$

/**
 * @file NodeManagerDaemon.idl
 *
 * @brief Controling interface for managing and controling CIAO daemon.
 */

#include "DAnCE/Deployment/Deployment_NodeManager.idl"
#include "DAnCE/Deployment/Deployment_NodeApplicationManager.idl"

module CIAO
{
  /**
   * @brief CIAO daemon process control program.
   *
   * @@The Inheritage might cause binary code bloating but
   * it's an easy way of combining features. In the future we could
   * move this definition into Deployment.idl.
   */
  interface NodeManagerDaemon : Deployment::NodeManager
  {
    // Canonical name of this daemon
    readonly attribute string name;

    // Shutdown the daemon process.
    oneway void shutdown ();

    /// RACE specific extension.
    /// Modify the priority of a node application process.
    long set_priority (in string plan_id,
                       in string cid,
                       in ::Deployment::Sched_Params nm_params);
  };
};
