// $Id$

/**
 * @file State_Connection_Test_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef STATE_CONNECTION_TEST_BASE_IDL
#define STATE_CONNECTION_TEST_BASE_IDL

#pragma ndds typesupport "Base/State_Connection_Test_BaseSupport.h"
#pragma opendds typesupport "Base/State_Connection_Test_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "State_ConnectionTest"
#pragma DCPS_DATA_KEY "State_ConnectionTest key"

struct State_ConnectionTest {
  string key; //@key
  long iteration;
};

typedef sequence<State_ConnectionTest> State_ConnectionTestSeq;

#endif
