#----------------------------------------------------------------------------
#       $Id$
#
#       Touches the executable if any of the libraries have changed
#----------------------------------------------------------------------------

ifndef TAO_ROOT
  TAO_ROOT = $(ACE_ROOT)/TAO
endif # ! TAO_ROOT

#----------------------------------------------------------------------------
#       Include macros
#----------------------------------------------------------------------------

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU

#----------------------------------------------------------------------------
#       Define local rules and targets
#---------------------------------------------------------------------------

all: tao_idl

ifeq ($(static_libs_only),)
  override static_libs_only=0
endif

ifeq ($(static_libs_only),0)

tao_idl: libTAO_IDL_FE_DLL.$(SOEXT) libTAO_IDL_BE_DLL.$(SOEXT)
	touch tao_idl$(EXEEXT);

libTAO_IDL_FE_DLL.$(SOEXT):

libTAO_IDL_BE_DLL.$(SOEXT):

else # static_libs_only == 1

tao_idl: libTAO_IDL_FE_DLL.a libTAO_IDL_BE_DLL.a
	touch tao_idl$(EXEEXT);

libTAO_IDL_FE_DLL.a:

libTAO_IDL_BE_DLL.a:

endif # static_libs_only

depend idl_stubs clean realclean:
