// -*- IDL -*-

//=============================================================================
/**
 * @file TX_Object.idl
 *
 * $Id$
 *
 * IDL for the SSLIOP Big_Request test.
 *
 * @author Andrew Finnell
 * @author Ossama Othman <ossama@uci.edu>
 */
//=============================================================================


typedef sequence<octet> DataSeq;

interface TX_Object
{

  void send (in DataSeq data);
  void recv (out DataSeq data);

  oneway void shutdown ();

};
