// $Id$

/**
 * @file OneFile_Base.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef ONEFILE_BASE_IDL_
#define ONEFILE_BASE_IDL_

#pragma ndds typesupport "OneFile_BaseSupport.h"
#pragma opendds typesupport "OneFile_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "OneFileTopic"
#pragma DCPS_DATA_KEY "OneFileTopic hello"

struct OneFileTopic {
  string hello; //@key
  long iteration;
};
#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<OneFileTopic> OneFileTopicSeq;
#endif

#endif /* ONEFILE_BASE_IDL_ */
