/**
 * @file DomainEvents.idl
 * @brief Contains Events in the Domain
 *
 * @author Nilabja R <nilabjar@dre.vanderbilt.edu>
 */

#ifndef DOMAIN_CHANGE_IDL
#define DOMAIN_CHANGE_IDL

#include "ciao/Deployment_TargetData.idl"
#include "ciao/TargetManager.idl"
#include "ciao/CCM_Event.idl"

module CIAO
{
    eventtype Domain_Changed_Event
    {
      public ::Deployment::Domain changes;
      public ::Deployment::DomainUpdateKind change_kind;
    };
};

#endif
