/**
 * @file CIAO_CS_Client.idl
 * @author William R. Otte <wotte@dre.vanderbilt.edu>
 *
 * A couple CIAO-specific extensions to the component server client
 * interfaces.
 */

#ifndef CIAO_COMPONENTSERVER_IDL_
#define CIAO_COMPONENTSERVER_IDL_

#include <ccm/ComponentServer/CCM_ComponentServer_Client.idl>

module CIAO
{
  module Deployment
  {
      interface ServerActivator : ::Components::Deployment::ServerActivator
      {
	/// Used by spawned component servers to notify the server
	/// activator of their object reference and retrieve
	/// configuration information.
	void component_server_callback (in ::Components::Deployment::ComponentServer serverref,
					in string server_UUID,
					out ::Components::ConfigValues config);
        
        void configuration_complete (in string server_UUID);
      };
  };
};


#endif

      
