// $Id$

/**
 * @file Updater_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef UPDATER_BASE_IDL
#define UPDATER_BASE_IDL

#pragma ndds typesupport "Base/Updater_BaseSupport.h"
#pragma opendds typesupport "Base/Updater_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "TestTopic"
#pragma DCPS_DATA_KEY "TestTopic key"

struct TestTopic {
  string key; //@key
  long x;
};

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<TestTopic> TestTopicSeq;
#endif

#endif
