// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/RG_LateBinding_Connector.idl"
#include "Base/Reader_Starter.idl"

module RG_LateBinding
{
  component Receiver
  {
    port RG_LateBindingTestConnector::DDS_Get info_get;
    port RG_LateBindingTestConnector::DDS_Read info_read;

    provides ReaderStarter start_reading;
  };
};

#endif
