/**
 * @file Test.idl
 *
 * $Id$
 *
 */

module Test
{
   typedef string<10> MyString;
   typedef MyString OtherString;

   interface Foo
   {
      void op1( in MyString s );
      void op2( in OtherString s );
   };
};

