
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl TESTER_COMPONENT_EXEC
// ------------------------------
#ifndef TESTER_COMPONENT_EXEC_EXPORT_H
#define TESTER_COMPONENT_EXEC_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (TESTER_COMPONENT_EXEC_HAS_DLL)
#  define TESTER_COMPONENT_EXEC_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TESTER_COMPONENT_EXEC_HAS_DLL */

#if !defined (TESTER_COMPONENT_EXEC_HAS_DLL)
#  define TESTER_COMPONENT_EXEC_HAS_DLL 1
#endif /* ! TESTER_COMPONENT_EXEC_HAS_DLL */

#if defined (TESTER_COMPONENT_EXEC_HAS_DLL) && (TESTER_COMPONENT_EXEC_HAS_DLL == 1)
#  if defined (TESTER_COMPONENT_EXEC_BUILD_DLL)
#    define TESTER_COMPONENT_EXEC_Export ACE_Proper_Export_Flag
#    define TESTER_COMPONENT_EXEC_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TESTER_COMPONENT_EXEC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TESTER_COMPONENT_EXEC_BUILD_DLL */
#    define TESTER_COMPONENT_EXEC_Export ACE_Proper_Import_Flag
#    define TESTER_COMPONENT_EXEC_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TESTER_COMPONENT_EXEC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TESTER_COMPONENT_EXEC_BUILD_DLL */
#else /* TESTER_COMPONENT_EXEC_HAS_DLL == 1 */
#  define TESTER_COMPONENT_EXEC_Export
#  define TESTER_COMPONENT_EXEC_SINGLETON_DECLARATION(T)
#  define TESTER_COMPONENT_EXEC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TESTER_COMPONENT_EXEC_HAS_DLL == 1 */

// Set TESTER_COMPONENT_EXEC_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (TESTER_COMPONENT_EXEC_NTRACE)
#  if (ACE_NTRACE == 1)
#    define TESTER_COMPONENT_EXEC_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define TESTER_COMPONENT_EXEC_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !TESTER_COMPONENT_EXEC_NTRACE */

#if (TESTER_COMPONENT_EXEC_NTRACE == 1)
#  define TESTER_COMPONENT_EXEC_TRACE(X)
#else /* (TESTER_COMPONENT_EXEC_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define TESTER_COMPONENT_EXEC_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (TESTER_COMPONENT_EXEC_NTRACE == 1) */

#endif /* TESTER_COMPONENT_EXEC_EXPORT_H */

// End of auto generated file.
