#----------------------------------------------------------------------------
#       $Id$
#
#       Makefile for the ACE network services
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
#       Local macros
#----------------------------------------------------------------------------

INFO  = README

# Always decend into the dirs to cleanup, and let those Makefiles decide
# whether or not to build anything.
DIRS  = lib \
        clients \
	servers

#----------------------------------------------------------------------------
#       Include macros and targets
#----------------------------------------------------------------------------

include $(ACE_ROOT)/include/makeinclude/all_in_one.GNU
# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.



# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
