// $Id$

/**
 * @file WL_ResetTopic_Base.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef WL_RESETTOPIC_BASE_IDL
#define WL_RESETTOPIC_BASE_IDL

#pragma ndds typesupport "Base/WL_ResetTopic_BaseSupport.h"

#pragma DCPS_DATA_TYPE "WL_ResetTopicTest"
#pragma DCPS_DATA_KEY "WL_ResetTopicTest key"

struct WL_ResetTopicTest {
  string key; //@key
  long iteration;
};

typedef sequence<WL_ResetTopicTest> WL_ResetTopicTestSeq;

#endif
