// $Id$

/**
 * @@ Compile this file with:
 *
 *     tao_idl -Gv -I ../.. -I ../../orbsvcs/orbsvcs \
 *          -Wb,export_macro=CIAO_Export \
 *          -Wb,export_include=CIAO_export.h \
 *          -Wb,pre_include="ace/pre.h" \
 *          -Wb,post_include="ace/post.h" \
 *          CCM_Container.idl
 */

#if !defined (CCM_CCMEXCEPTION_IDL)
#define CCM_CCMEXCEPTION_IDL

module Components
{
  typeprefix Components "omg.org";

  enum CCMExceptionReason
  {
    SYSTEM_ERROR,
    CREATE_ERROR,
    REMOVE_ERROR,
    DUPLICATE_KEY,
    FIND_ERROR,
    OBJECT_NOT_FOUND,
    NO_SUCH_ENTITY,
    QOS_ERROR,
    REGISTRATION_ERROR,
    SERVICE_INSTALLATION_ERROR
  };

  exception CCMException
  {
    CCMExceptionReason reason;
  };
};
#endif /* CCM_CCMEXCEPTION_IDL */
