// $Id$

/**
 * @file Deployment_Events.idl
 *
 * @brief A collection of IDL data types for CIAO pub/sub services deployment.
 *
 * @author Gan Deng
 */

#if !defined (CIAO_DEPLOYMENT_EVENT_SERVICES_IDL)
#define CIAO_DEPLOYMENT_EVENT_SERVICES_IDL

module CIAO
{
  module DAnCE
  {
    /// CIAO specific extension to describe pub/sub services in the deployment
    enum EventServiceType
    {
      EC,
      RTEC,
      NOTIFY,
      RTNOTIFY
    };

    /// Each element in the EventSourceSet denotes a event source id
    typedef string EventSourceId;

    typedef sequence<EventSourceId> EventSourceSet;

    /// Event Filters
    enum FilterType
    {
      CONJUNCTION,
      DISJUNCTION,
      LOGICAL_AND,
      NEGATE
    };

    struct EventFilter
    {
      string name;
      FilterType type;
      EventSourceSet sources;
    };

    typedef sequence < EventFilter > EventFilters;

    /// CIAO specific extension to describe pub/sub services in the deployment
    struct EventServiceDeploymentDescription
    {
      string name;
      string node;
      EventServiceType type;
      string svc_cfg_file;

      EventFilters filters;
    };

    typedef sequence < EventServiceDeploymentDescription >
      EventServiceDeploymentDescriptions;
  };
};

#endif /* CIAO_DEPLOYMENT_EVENT_SERVICES_IDL */
