/**
 * @@ This is just a temporary file. CIAO doesn't sue the IFR
 * service in its implementation so we're using the dummy
 * interface below
 *
 * $Id$
 */

#if !defined (CIAO_IFR_BASE_IDL)
#define CIAO_IFR_BASE_IDL

module CORBA
{
  typeprefix CORBA "omg.org";

  interface IRObject
  {
  };
};

#endif /* CIAO_IFR_BASE_IDL */
