// $Id$

#ifndef TARGET_DATA_IDL
#define TARGET_DATA_IDL

module Deployment {

  exception PlanError {
    string name;
    string reason;
  };

  exception ResourceNotAvailable {
    string name;
    string resourceType;
    string propertyName;
    string elementName;
    string resourceName;
  };
};

#endif /* TARGET_DATA_IDL */
