//=============================================================================
/**
 *  @file    Triangle_Test.idl
 *
 *  $Id$
 *
 *  An example of how nested upcalls work/fail?
 *
 *
 *  @author Michael Kircher
 */
//=============================================================================




interface Object_A {

  long foo (in long time);

};

interface MT_Object;

interface MT_Object
{
  long yadda (in long hop_count, in MT_Object partner);
};
