// $Id$
#ifndef NODEMANAGER_IDL
#define NODEMANAGER_IDL

#include "Deployment.idl"

module Deployment {

  interface NodeApplicationManager;

  interface NodeManager {
    void joinDomain (in Domain ciao_domain,
                     in TargetManager manager,
                     in Logger log);

    void leaveDomain ();

    NodeApplicationManager preparePlan (in DeploymentPlan plan)
      raises (StartError, PlanError);

    void destroyManager (in NodeApplicationManager appManager)
      raises (StopError, InvalidReference);

    /// CIAO specific extension
    /// Destroy the NAM and all the associated NAs with this child_plan
    /// We can guarantee that the input DeploymentPlan is valid, since it
    /// is fetched from the cached DeploymentPlan of DAM, which has been
    /// validated before.
    void destroyPlan (in DeploymentPlan plan)
      raises (StopError);

    /// CIAO specific extension
    /// Get all the shared components installed in this node
    ComponentPlans get_shared_components ();
  };
};

#endif /* NODEMANAGER_IDL */
