// ========================================================================
// $Id$
// 
// = LIBRARY
//    orbsvcs
// 
// = FILENAME
//    Sequences.idl
//
// = AUTHOR
//    Seth Widoff <sbw1@cs.wustl.edu>
// ========================================================================

// Used for extracting simple sequences from anys.

module TAO_Sequences
{
  typedef sequence<short> ShortSeq;
  typedef sequence<unsigned short> UShortSeq;
  typedef sequence<long> LongSeq;
  typedef sequence<unsigned long> ULongSeq;
  typedef sequence<boolean> BooleanSeq;
  typedef sequence<float> FloatSeq;
  typedef sequence<double> DoubleSeq;
  typedef sequence<string> StringSeq;
};
