// $Id$

#ifndef DANCE_ARTIFACT_INSTALLATION_IDL
#define DANCE_ARTIFACT_INSTALLATION_IDL

#include "DAnCE/Deployment/Deployment_DeploymentPlan.idl"
#include "DAnCE/Deployment/Deployment_PlanError.idl"

module DAnCE
{
  interface ArtifactInstallation
  {
    void initialize ()
      raises (::Deployment::PlanError);

    void clear ()
      raises (::Deployment::PlanError);

    /// Acts as a front end to the ArtifactInstallationHandlers
    /// that were installed at object creation. Each InstallationHandler
    /// is capable of handling a single URI type;
    void install (in string plan_uuid,
                  in ::Deployment::ArtifactDeploymentDescription artifact)
      raises (::Deployment::PlanError);

    void remove (in string plan_uuid,
                 in string artifact_name)
      raises (::Deployment::PlanError);

    void remove_all (in string plan_uuid)
      raises (::Deployment::PlanError);

    /// Used by component/locality server to query location of a given artifact
    string get_artifact_location (in string uuid,
                                  in string artifact_name);
  };
};

#endif /* DANCE_ARTIFACT_INSTALLATION_IDL */
