// $Id$

/**
 * @file Writer_Connector.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef WRITER_CONNECTOR_IDL_
#define WRITER_CONNECTOR_IDL_

#include  <Components.idl>
#include "Base/Writer_Base.idl"
#include "connectors/dds4ccm/idl/ccm_dds.idl"

#pragma ciao lem "Connector/Writer_ConnectorE.idl"

module CCM_DDS
{
  module ::CCM_DDS::Typed < ::WriterTest, ::WriterTestSeq> WriterTest;
};

module Writer
{
  connector Writer_Connector : ::CCM_DDS::WriterTest::DDS_Event
  {
  };
};

#endif /* Writer_CONNECTOR_IDL_ */
