
//=============================================================================
/**
 *  @file    Web_Server.idl
 *
 *  $Id$
 *
 *   IDL schema definition for Web server interface.
 *
 *
 *  @author  Priyanka Gontla <pgontla@ece.uci.edu>
 */
//=============================================================================


module Web_Server
{
  interface Iterator_Factory
  {
  };

};
