// $Id$

/**
 * @file Listen_Invoker.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef LISTEN_INVOKER_IDL
#define LISTEN_INVOKER_IDL

interface ListenInvoker
{
  void start_not_enabled ();
  void start_listen_one_by_one (in unsigned short keys,
                                in unsigned long iteration);
  void start_listen_many_by_many (in unsigned short keys,
                                  in unsigned long iteration);
};

#endif /* SAMPLE_INFO_IDL */
