// $Id$

#ifndef DDS4CCM_CONNECTOR_IDL
#define DDS4CCM_CONNECTOR_IDL

#include <Components.idl>
#include "connectors/dds4ccm/idl/dds4ccm_Base.idl"
#include "connectors/dds4ccm/idl/dds4ccm_ConnectorStatusListener.idl"

#pragma ciao lem "connectors/dds4ccm/idl/dds4ccm_ConnectorE.idl"

module CCM_DDS
{
  connector DDS_Base {
    uses ConnectorStatusListener error_listener;
    attribute DDS::DomainId_t domain_id
      setraises (NonChangeable);
    attribute string qos_profile
      setraises (NonChangeable);
  };
  connector DDS_TopicBase : DDS_Base {
    attribute string topic_name
      setraises (NonChangeable);
    attribute DDS::StringSeq key_fields
      setraises (NonChangeable);
  };
};

#endif
