// $Id$

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "Hello_Base/Hello_Base.idl"
#include "Hello_Base/HelloE.idl"
#include "Hello_Base/Hello_BaseE.idl"

module Hello_AMI
{
  component Sender
  {
    // for asynch invocation. @@implied
    uses Hello_AMI::AMI_MyFoo       run_asynch_my_foo;

    // for synchronous invocation
    uses Hello::MyFoo         run_my_foo;
  };

  home SenderHome manages Sender
  {
  };
};

#endif
