// $Id$

#ifndef COLLACATED_BASE_
#define COLLACATED_BASE_

#pragma ndds typesupport "Base/Collocated_BaseSupport.h"
#pragma opendds typesupport "Base/Collocated_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "CoPubSub::Test_msg"

module CoPubSub {
  struct Test_msg {
    string hello;
    long msgId;
  };

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence <Test_msg> Test_msgSeq;
#endif
};


#endif // COLLACATED_BASE_

