// $Id$

/**
 * @file ExecutionManagerDaemon.idl
 *
 * @brief Simple interface to control the ExecutionManager. This
 * interface currently provides an additional method called shutdown
 * to terminate the process cleanly.
 */

#include "DAnCE/Deployment/Deployment_ExecutionManager.idl"

module DAnCE
{
  /**
   * @brief CIAO Execution Manager Program
   *
   * This feature addition is added using inheritance mechanism currently
   */
  interface ExecutionManagerDaemon : Deployment::ExecutionManager
  {
    // Shutdown the daemon process.
    oneway void shutdown ();
  };
};
