// -*- IDL -*-

//=============================================================================
/**
 * @file Foo.idl
 *
 * $Id$
 *
 * IDL for the Null_Cipher test.
 *
 * @author Ossama Othman <ossama@uci.edu>
 */
//=============================================================================

interface Foo
{
    /// Shutdown the server.
    void shutdown ();

};
