//$Id$
#ifndef RACE_PLANNER_MANAGER_I_IDL
#define RACE_PLANNER_MANAGER_I_IDL

#ifndef INCLUDED_DEPLOYMENT_DATA
#define INCLUDED_DEPLOYMENT_DATA
#include "DAnCE/Deployment/Deployment_DeploymentPlan.idl"
#endif

#include "../../common/RACE_common.idl"

module CIAO
{
  module RACE
  {
    interface Planner_Manager_I
    {
      void execute_planners (in Deployment::DeploymentPlan plan,
                             in PlannerFlow flow);
    };
  };
};

#endif /* RACE_PLANNER_MANAGER_I_IDL */
