// $Id$
/// Compliant with OMG 06-04-01 Section 6.8

#if !defined (CCM_HOMEFINDER_IDL)
#define CCM_HOMEFINDER_IDL

#include "tao/orb_types.pidl"

#if !defined (CCM_LW)

module Components
{
  typeprefix Components "omg.org";

  exception HomeNotFound {};

  interface CCMHome;

  interface HomeFinder
  {
    CCMHome find_home_by_component_type (in CORBA::RepositoryId comp_repid)
      raises (HomeNotFound);

    CCMHome find_home_by_home_type (in CORBA::RepositoryId home_repid)
      raises (HomeNotFound);

    CCMHome find_home_by_name (in string home_name)
      raises (HomeNotFound);
  };
};
#endif

#endif /* CCM_HOMEFINDER_IDL */
