// $Id$

module Stock
{
  exception Invalid_Stock {};
  exception Invalid_Quoter {};

  interface Quoter
  {
    // = TITLE
    //   Access Stock information.

    long get_quote (in string stock_name) 
      raises (Invalid_Stock, Invalid_Quoter);
    // Returns the current stock value or throws and exception.

    void destroy ();
    // Destroy a Quoter session and release resources.
  };
  
  interface Quoter_Factory 
  {
    // = TITLE
    //   Manage the lifecycle of a Quoter object.
    Quoter create_quoter (in string name)
      raises (Invalid_Quoter);
    // Returns a new Quoter selected by name e.g., "Dow Jones,"
    // "Reuters,", etc
  };
};
