// $Id$

/**
 * @file HelloGoodbye.idl
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef GOODBYE_IDL_
#define GOODBYE_IDL_

#pragma ndds typesupport "Goodbye/HelloGoodbyeSupport.h"
#pragma opendds typesupport "Goodbye/HelloGoodbyeTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "Goodbye::HelloGoodbye"
#pragma DCPS_DATA_KEY "Goodbye::HelloGoodbye goodbye"

module Goodbye
{
  struct HelloGoodbye {
    string goodbye;  //@key
    long iteration;
  };
  #if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence<HelloGoodbye> HelloGoodbyeSeq;
#endif
};

#endif /* GOODBYE_IDL_ */
