// $Id$

#ifndef DEPLOYMENT_INVALIDNODEEXECPARAMETER_IDL
#define DEPLOYMENT_INVALIDNODEEXECPARAMETER_IDL

module Deployment {
  exception InvalidNodeExecParameter {
    string name;
    string reason;
  };
};

#endif
