#
# Makefile for building the DynAny test
#

NAME = basic_test

TAO_IDL = $(CORE_BINDIR)\tao_idl -g $(CORE_BINDIR)\gperf.exe -I..\.. -Ge 1

OBJFILES = \
	$(OBJDIR)\da_testsC.obj \
	$(OBJDIR)\da_testsS.obj \
	$(OBJDIR)\data.obj \
	$(OBJDIR)\driver.obj \
	$(OBJDIR)\test_dynany.obj \
	$(OBJDIR)\test_dynarray.obj \
	$(OBJDIR)\test_dynenum.obj \
	$(OBJDIR)\test_dynsequence.obj \
	$(OBJDIR)\test_dynstruct.obj \
	$(OBJDIR)\test_dynunion.obj \
	$(OBJDIR)\test_wrapper.obj

CFLAGS = $(ACE_CFLAGS) $(TAO_CFLAGS)

LIBFILES = $(ACE_LIB) $(TAO_LIB)

CPPDIR = .

IDLDIR = .

!include <$(ACE_ROOT)\include\makeinclude\build_exe.bor>

#
# IDL Build rules
#

$(IDLDIR)\da_testsC.cpp $(IDLDIR)\da_testsS.cpp: $(IDLDIR)\da_tests.idl
	$(TAO_IDL) $**
