// $Id$

/**
 * @file dds4ccm_DataListenerControl.idl
 *
 */

#ifndef DDS4CCM_LISTENERCONTROL_IDL3
#define DDS4CCM_LISTENERCONTROL_IDL3

#include "connectors/dds4ccm/idl/dds4ccm_Base.idl"

#pragma ciao lem "connectors/dds4ccm/idl/dds4ccm_DataListenerControlE.idl"

module CCM_DDS
{
  local interface DataListenerControl {
    attribute ListenerMode mode;
    attribute DataNumber_t max_delivered_data;
  };
};

#endif
