// $Id$
#ifndef RACE_INTERACTIVE_INPUT_ADAPTER_IDL
#define RACE_INTERACTIVE_INPUT_ADAPTER_IDL

#include <Components.idl>
#include "RACE/Input_Adapters/Base/Input_Adapter_Base.idl"
#include "RACE/common/RACE_common.idl"

module CIAO
{
  module RACE
  {
    module Input_Adapter
    {
      interface Admin
      {
        /// "Schedule" a plan for future deployment.
        boolean add_plan (in string filename, out UUID ID);

        /// Remove a plan that was scheduled for deployment. Raises
        /// UnknownID.
        boolean delete_plan (in UUID ID)
          raises (UnknownID);

        /// Deploy the plan right away.
        boolean deploy_plan (in string filename, out UUID ID);

        /// Deploy a plan that was previously scheduled via
        /// add_plan. Raises UnknownID.
        boolean deploy_plan_with_id (in UUID ID)
          raises (UnknownID);

        /// Modify a previously scheduled/deployed plan. Raises UnknownID.
        boolean modify_plan (in string filename, in UUID ID)
          raises (UnknownID);

        /// Teardown a plan. Raises UnknownID.
        boolean tear_down_plan (in UUID ID)
          raises (UnknownID);

        /// Start the controller.
        boolean start_controller ();

        /// Stop the controller.
        boolean stop_controller ();
      };

      component Interactive_IA_Component : Input_Adapter_Base
      {
        provides Admin admin;
      };

      home Interactive_IA_Component_Home manages Interactive_IA_Component
      {
      };
    };
  };

};


#endif /* RACE_INTERACTIVE_INPUT_ADAPTER_IDL */
