//
// $Id$
//

module Test
{
  /// An interface to communicate and shutdown a process
  interface Ping_Service
  {
    /// Just a void function contact the server
    void ping ();

    /// Shutdown the server
    oneway void shutdown ();
  };
};
