#include "orbsvcs/orbsvcs/LWFT/ReplicatedApplication.idl"

module DeCoRAM
{
  interface Worker : ReplicatedApplication
  {
    void run_task (in double execution_time,
                   in boolean ignore);

    void run_method (in unsigned long prime_number,
                 in unsigned long kill);

    void stop ();
  };
};
