// $Id$

/**
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef COMPONENT_IDL
#define COMPONENT_IDL

#include  <Components.idl>

interface ParseErrorTest {
  void do_something ();
};

module ParseError_Test
{
  component ParseErrorTestComponent
  {
    provides ParseErrorTest to_do;
    uses ParseErrorTest do_to;
    attribute unsigned long test;
  };
};

#endif
