// $Id$

/**
 * @file CSL_QoSTest_Connector.idl
 * @author Marijke Hengstmengel <mhengstmengel@remedy.nl>
 */

#ifndef CSL_QOSTEST_CONNECTOR_IDL_
#define CSL_QOSTEST_CONNECTOR_IDL_

#include <Components.idl>
#include <ccm_dds.idl>

#include "Base/CSL_QoSTest_Base.idl"

#pragma ciao lem "Connector/CSL_QoSTest_ConnectorE.idl"

#if (CIAO_DDS4CCM_OPENDDS==1)
# include "Base/CSL_QoSTest_BaseTypeSupport.idl"
#endif

module ::CCM_DDS::Typed < ::TestTopic, ::TestTopicSeq> CSLQoSConnector;

#endif /* CSL_QoSTest_CONNECTOR_IDL_ */
