// $Id$

/**
 * @file dds4ccm_StateListenerControl.idl
 */

#ifndef DDS4CCM_STATELISTENERCONTROL_IDL
#define DDS4CCM_STATELISTENERCONTROL_IDL

#include "connectors/dds4ccm/idl/dds4ccm_DataListenerControl.idl"

#pragma ciao lem "connectors/dds4ccm/idl/dds4ccm_StateListenerControlE.idl"

module CCM_DDS
{
  local interface StateListenerControl : DataListenerControl {
    attribute boolean is_filter_interpreted;
  };
};

#endif
