// $Id$

#ifndef CONNECTORSTATUSLISTENER_TEST_BASE_IDL
#define CONNECTORSTATUSLISTENER_TEST_BASE_IDL

#pragma ndds typesupport "Base/ConnectorStatusListener_Test_BaseSupport.h"

struct TestTopic {
  string key; //@key
  long x;
};

typedef sequence<TestTopic> TestTopicSeq;

struct TestSecondTopic {
  string key; //@key
  long x;
  long y;
};

typedef sequence<TestSecondTopic> TestSecondTopicSeq;

#endif
