// $Id$

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "../Hello_Base/Hello_Base.idl"

module Hello_AMI
{
  component Receiver
  {
    //provides 
    provides CCM_AMI::MyFoo do_asynch_foo;
  };

  home ReceiverHome manages Receiver
  {
  };
};
#endif
