// $Id$

/**
 * @file RateGen.idl
 *
 * Definition of the RateGen (a rate generator) component.
 *
 * @author Nanbor Wang <nanbor@cs.wustl.edu>
 */

#include "../HUDisplay.idl"

module HUDisplay
{

  component RateGen supports opmode
    {
      publishes tick Pulse;
    };
};
