// $Id$

#ifndef DEPLOYMENT_DOMAINAPPLICATION_IDL
#define DEPLOYMENT_DOMAINAPPLICATION_IDL

#include "DAnCE/Deployment/Deployment_Application.idl"

module Deployment
{
  interface DomainApplication :
    Application
  {
  };
};


#endif //DEPLOYMENT_DOMAINAPPLICATION_IDL
