// $Id$

/**
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef ON_INCONSISTENT_TOPIC_TEST_SENDER_IDL
#define ON_INCONSISTENT_TOPIC_TEST_SENDER_IDL

#include "SenderConnector/OIT_Sender_Connector.idl"

module OIT_Test
{
  component Sender
  {
    port OIT_Sender_TopicConnector::DDS_Write topic_write;
    provides CCM_DDS::ConnectorStatusListener connector_status;
  };
};

#endif
