// $Id$

/**
 * @file
 * @author Marcel Smit <msmit@remedy.nl>
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/Writer_Connector.idl"
#include "Connector/Writer_ConnectorE.idl"

module Writer
{
  component Receiver
  {
    port CCM_DDS::WriterTest::DDS_Listen info_out;
  };
};

#endif
