// $Id$

module CCM_AMI
{
  typedef long Cookie;

  exception InternalError {
      long id;
      string error;
  };

  // Sender/Receiver interface
  interface AMI_foo
    {
      long asynch_foo (in string in_str, out string answer)
        raises (InternalError);
    };

  // callback interface from AMI-component to Sender component
  interface AMI_foo_callback
    {
      void foo_callback_handler (in Cookie ck, in long result, in string answer);
      void foo_callback_excep (in Cookie ck, in string callback_exception);
    };

  // AMI component. Sender calls AMI-component and AMI-component calls Receiver
  // using the AMI_foo interface.
  interface AMI_ami_foo
    {
      Cookie sendc_asynch_foo (in string in_str);
    };
};
