// -*- IDL -*-

//=============================================================================
/**
 * @file Hasher.idl
 *
 * $Id$
 *
 * @author Ossama Othman <ossama@uci.edu>
 */
//=============================================================================

interface Hasher
{
  /// Perform a simple hashing operation on the input string <str> and
  /// return the hash value.
  unsigned long hash_string (in string str);

  /// Shutdown the ORB.
  //oneway void shutdown ();
};
