/* $Id$ */
#ifndef DT_ONEWAY_CONFIG_H
#define DT_ONEWAY_CONFIG_H

#define CONFIG_DSTREAM_MAIN_GROUP
#define CONFIG_DSTREAM_WORKER_GROUP
#define CONFIG_DSTREAM_TEST_ONE

#endif /* DT_ONEWAY_CONFIG_H */
