// -*- C++ -*-
//
// $Id$

/**
 * NOTE: This file is hand crafted to remove the CCM_DataWriter element and add the dds_rtf2_dcpeE.idl include.
 */

#ifndef _CIAO_HELLO_SENDER_CONNECTORE_IDL_
#define _CIAO_HELLO_SENDER_CONNECTORE_IDL_

#include "ccm/CCM_Container.idl"
#include "Hello_Sender_Connector.idl"
#include "dds4ccm/idl/dds_rtf2_dcpsE.idl"

module CCM_DDS
{
  local interface CCM_string_Writer : ::CCM_DDS::string_Writer
  {
  };
};

module Hello_DDS
{
  local interface CCM_Hello_sender_Connector
    : ::Components::EnterpriseComponent
  {
    ::CCM_DDS::CCM_string_Writer get_sender_data ();
    ::DDS::CCM_DataWriter get_sender_dds_entity ();
  };
  
  local interface CCM_Hello_sender_Connector_Context
    : ::Components::SessionContext
  {
  };
};

module CIAO_Hello_DDS_Hello_sender_Connector_Impl
{
  typedef ::Hello_DDS::CCM_Hello_sender_Connector_Context Hello_sender_Connector_Exec_Context;
  
  local interface Hello_sender_Connector_Exec
    : ::Hello_DDS::CCM_Hello_sender_Connector,
      ::Components::SessionComponent
  {
  };
};

module Hello_DDS
{
  local interface CCM_SenderConnectorHomeImplicit
  {
    ::Components::EnterpriseComponent create ()
      raises ( ::Components::CCMException);
  };
  
  local interface CCM_SenderConnectorHomeExplicit
    : ::Components::HomeExecutorBase
  {
  };
  
  local interface CCM_SenderConnectorHome
    : CCM_SenderConnectorHomeExplicit,
      CCM_SenderConnectorHomeImplicit
  {
  };
};

module CIAO_Hello_DDS_Hello_sender_Connector_Impl
{
  local interface SenderConnectorHome_Exec
    : ::Hello_DDS::CCM_SenderConnectorHome
  {
  };
};

#endif /* ifndef */

