#ifndef SA_POP_COMPONENT_IDL
#define SA_POP_COMPONENT_IDL

#include <Components.idl>
#include "common/OpString.idl"
#include "common/Goal.idl"
#include "Data_Base/Data_Base.idl"

module CIAO
{
  module RACE
  {
    module SA_POP
    {
      interface Planning
      {
        /// Initialize SA-POP with a task network and task map.
        boolean init (in string task_net_file, in string task_map_file);

        /// Plan for a goal.
        boolean generate_opstring (in GoalStructure goal, out OperationalString opstring);
      };

      component SA_POP_Component
      {
        provides Planning plan;

        uses CIAO::RACE::Data_Base::Query DB;
      };

      home SA_POP_Component_Home manages SA_POP_Component
      {
      };
    };
  };
};

#endif /* SA_POP_COMPONENT_IDL */
